feat: 権限設定]の画面を追加
kufu/smarthr-design-system pull request #1040
Opened 2023-12-20 11:57 UTC by kgsi

## 課題・背景

## やったこと

-

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2023-12-21 09:21 UTC, versionfive commented on content/articles/products/design-patterns/admin-screen.mdx
> +  * 表示は通常`{姓} {名}<{メールアドレス}>`となりますが、メールアドレスがの登録がない場合は`{姓} {名}`、姓名の登録がない場合は`{メールアドレス}`とします。
```suggestion
* **1. アカウント名**
  * [B-2. アカウントの選択](#h4-4)で設定したアカウント名を表示します。
  * 表示は通常`{姓} {名}<{メールアドレス}>`となりますが、メールアドレスの登録がない場合は`{姓} {名}`、姓名の登録がない場合は`{メールアドレス}`とします。
```
キャプチャの列名（Th）は「アカウント」だけど、「アカウント名」が正しいですかね？

2023-12-22 06:39 UTC, o-kwr approved these changes
わかりやすくてLGTM🫶

2023-12-24 23:06 UTC, uknmr requested changes
大盛りになってしまった🙏

2023-12-24 23:06 UTC, uknmr commented on content/articles/products/design-patterns/admin-screen.mdx
> +操作の権限が上記の2つのみの場合は、[RadioButtonPanel](/products/components/radio-button-panel/)を使ってください。
Q: 2つの場合というよりは「n個以内」と書けそう? 3個の場合などもありそう。

2023-12-24 23:06 UTC, uknmr commented on content/articles/products/design-patterns/admin-screen.mdx
> +このケースでは[SingleComboBox](/products/components/combo-box/)、または[Select](/products/components/select/)の利用を検討してください。
- 冗長な表現を修正
- 突然のカタカナを日本語化
- 利用検討ではなく使用と言い切り

```suggestion
**「カスタム権限」**として、操作の権限をユーザーが増やせるプロダクトもあります。この場合は[SingleComboBox](/products/components/combo-box/)や[Select](/products/components/select/)を使ってください。
```

2023-12-24 23:06 UTC, uknmr commented on content/articles/products/design-patterns/admin-screen.mdx
> +#### B-3. 操作の権限
```suggestion
#### 3. 操作の権限
```

2023-12-24 23:06 UTC, uknmr commented on content/articles/products/design-patterns/admin-screen.mdx
> +#### B-2. アカウントの選択
```suggestion
#### 2. アカウントの選択
```

2023-12-24 23:06 UTC, uknmr commented on content/articles/products/design-patterns/admin-screen.mdx
> +#### B-4.  独自のオブジェクト設定
```suggestion
#### 4.  独自のオブジェクト設定
```

2023-12-24 23:06 UTC, uknmr commented on content/articles/products/design-patterns/admin-screen.mdx
> +機能ごとに設定が異なるため、現状は特にルールや決まったパターンを設けません。
画面の言葉ではなく、他と表現をあわせて修正提案。

```suggestion
独自の権限設定がある場合に表示します。用途に依って設定が異なるため、ルールやパターンは定めません。
```

2023-12-25 00:56 UTC, kgsi commented on content/articles/products/design-patterns/admin-screen.mdx
> +* [年末調整](https://smarthr.jp/function/nc/)
@uknmr これは第三者から見てどんなサービスかわかりたいケースがある...想定でリンクは付与してました！

2023-12-25 00:56 UTC, kgsi commented on content/articles/products/design-patterns/admin-screen.mdx
> +![](./images/admin-screen/admin-screen-admin1.png)
@uknmr 画像直上に入れたいテキストと同じものがある場合、同じテキストをalt内に入れると冗長だと思うんですが、この場合ってどんなテキストが適切ですかね？

2023-12-25 00:56 UTC, kgsi commented on content/articles/products/design-patterns/admin-screen.mdx
> +![](./images/admin-screen/admin-screen-admin2.png)
@uknmr これも同じく

2023-12-25 00:56 UTC, kgsi commented on content/articles/products/design-patterns/admin-screen.mdx
> +TabBarのタイトルは左から`アカウント一覧`、`{独自オブジェクト}`とします。
@uknmr 念のためですがこのルールに従う的な意味合いですか？
https://smarthr.design/products/contents/app-writing/#h2-8

2023-12-25 00:56 UTC, kgsi commented on content/articles/products/design-patterns/admin-screen.mdx
> +[SingleComboBox](/products/components/combo-box/)の`dropdownHelpMessage`は検索できる項目次第ですが、通常は`{検索対象名1}、{検索対象名2}で検索できます。`とします。
@uknmr  `コンボボックスパネル`って唐突感があるので、ComboBoxのパネルでどうですか？（不意なカタカナ用語

2023-12-25 00:57 UTC, uknmr commented on content/articles/products/design-patterns/admin-screen.mdx
> +* [年末調整](https://smarthr.jp/function/nc/)
理解〜。意図を把握したので閉じます!

2023-12-25 01:07 UTC, uknmr commented on content/articles/products/design-patterns/admin-screen.mdx
> +![](./images/admin-screen/admin-screen-admin1.png)
領域ごとに赤枠で囲んでることが伝えたいことなのかな、と思いました。その伝えたいことを alt で表したい。

2023-12-25 01:07 UTC, uknmr commented on content/articles/products/design-patterns/admin-screen.mdx
> +TabBarのタイトルは左から`アカウント一覧`、`{独自オブジェクト}`とします。
テキストのガイドラインがあるのは知らなかったですが、一覧であることは自明なため「一覧」を明示する必要はないように見えました。

2023-12-25 01:07 UTC, uknmr commented on content/articles/products/design-patterns/admin-screen.mdx
> +[SingleComboBox](/products/components/combo-box/)の`dropdownHelpMessage`は検索できる項目次第ですが、通常は`{検索対象名1}、{検索対象名2}で検索できます。`とします。
PlanC ですが Authoring Pracitce にならってリストボックスと呼ぶのはどうかしら。
https://www.w3.org/WAI/ARIA/apg/patterns/combobox/
（全体認識を揃えてからの方が良さそうであれば、ComboBoxパネルで gogo〜）

2023-12-25 01:08 UTC, tosiiu reviewed
全体的にLGTMです！
1点だけコメント入れてます！

2023-12-25 01:16 UTC, kgsi commented on content/articles/products/design-patterns/admin-screen.mdx
> +`{機能名}を利用する権限を設定します。詳しくは、{ヘルプへのリンク}を参照してください。`
これでいく

2023-12-25 01:35 UTC, wentzzz commented on content/articles/products/design-patterns/admin-screen.mdx
> +![](./images/admin-screen/admin-screen-admin1-dialog.png)
スクリーンショットの数字が1,3,3になっていました。

2023-12-25 01:37 UTC, wentzzz commented on content/articles/products/design-patterns/admin-screen.mdx
> +![](./images/admin-screen/admin-screen-admin1-dialog.png)
スクリーンショットの数字が1,3,3になっていました。

2023-12-25 03:30 UTC, kgsi commented on content/articles/products/design-patterns/admin-screen.mdx
> +SmartHRのアカウントを選択します。[SingleComboBox](/products/components/combo-box/)を使ってください。
@uknmr いいねしたけど、まとめて追加パターンって別な気がしました。その場合ラベルも検討しないといけない気もするのですが、一旦補足程度に書いておきます（細かいパターンにできるほどパターンがまとまっていない認識

2023-12-25 03:33 UTC, kgsi commented on content/articles/products/design-patterns/admin-screen.mdx
> +[SingleComboBox](/products/components/combo-box/)の`dropdownHelpMessage`は検索できる項目次第ですが、通常は`{検索対象名1}、{検索対象名2}で検索できます。`とします。
一旦`ComboBoxのパネル`としておきましたー

2023-12-25 03:35 UTC, kgsi commented on content/articles/products/design-patterns/admin-screen.mdx
> +操作の権限が上記の2つのみの場合は、[RadioButtonPanel](/products/components/radio-button-panel/)を使ってください。
@uknmr 今今そのパターンが無いので（3つパターン）、「2つ以内」としておきます！

2023-12-25 03:51 UTC, tosiiu submitted a review, later dismissed
LGTMです！

2023-12-25 03:59 UTC, wentzzz reviewed
1点誤字を見つけました:pray:

2023-12-25 03:59 UTC, wentzzz commented on content/articles/products/design-patterns/permissions-settings.mdx
> +- [文書配布](https://smarthr.jp/function/distribution/)
```suggestion
- [文書配付](https://smarthr.jp/function/distribution/)
```

2023-12-25 05:55 UTC, uknmr commented on content/articles/products/design-patterns/admin-screen.mdx
> +操作の権限が上記の2つのみの場合は、[RadioButtonPanel](/products/components/radio-button-panel/)を使ってください。
理解
ング

2023-12-25 06:11 UTC, uknmr reviewed
よさそう〜! 👏 
細かいところだけコメントしてます。

2023-12-25 06:11 UTC, uknmr commented on content/articles/products/design-patterns/permissions-settings.mdx
> +アカウントのみを扱う場合のセクションタイトルは`アカウント一覧`、オブジェクトの追加ボタンラベルは`追加`としてください。
Figma に合わせると

```suggestion
アカウントのみを扱う場合のセクションタイトルは`アカウント`、オブジェクトの追加ボタンラベルは`追加`としてください。
```

2023-12-25 06:11 UTC, uknmr commented on content/articles/products/design-patterns/permissions-settings.mdx
> +一覧の[アカウントを追加]、または[(アカウントを)編集]ボタンを押したときに[ActionDialog](/products/components/dialog/#h3-1)で表示します。
```suggestion
一覧の[（アカウントを）追加]、または[（アカウントを）編集]ボタンを押したときに[ActionDialog](/products/components/dialog/#h3-1)で表示します。  
```

2023-12-25 06:11 UTC, uknmr commented on content/articles/products/design-patterns/permissions-settings.mdx
> +![スクリーンショット:1〜4とグルーピングされた赤枠がスクリーンショット上に表示、強調されている。タイトルが1、アカウントの選択が2、操作の権限が3、独自の権限設定が4でグルーピングされている。](./images/permissions-settings/permissions-settings2-dialog.png)
何かをミスって画像が展開されていなさそう。

2023-12-25 06:11 UTC, uknmr commented on content/articles/products/design-patterns/permissions-settings.mdx
> +## B.アカウントの詳細
残ってた

```suggestion
## アカウントの詳細
```

2023-12-25 06:14 UTC, uknmr commented on content/articles/products/design-patterns/admin-screen.mdx
> +SmartHRのアカウントを選択します。[SingleComboBox](/products/components/combo-box/)を使ってください。
人事評価など「アカウントの選択」を MultiCombobox で実装してるプロダクトが多い気もします。

2023-12-25 06:25 UTC, kgsi commented on content/articles/products/design-patterns/permissions-settings.mdx
> +![スクリーンショット:1〜4とグルーピングされた赤枠がスクリーンショット上に表示、強調されている。タイトルが1、アカウントの選択が2、操作の権限が3、独自の権限設定が4でグルーピングされている。](./images/permissions-settings/permissions-settings2-dialog.png)
@uknmr 直しました！

2023-12-25 06:31 UTC, uknmr approved these changes
LGTM~~~~~~~~~~~~~!!!!!!!!!!!

2023-12-25 06:33 UTC, kgsi commented on content/articles/products/design-patterns/permissions-settings.mdx
> +- [文書配布](https://smarthr.jp/function/distribution/)
@wentzzz こちら修正しました！

2023-12-25 06:33 UTC, merged