WIP 限られた資格のユーザのウェブ利用に関連する問題点と解決策のページを作った
kufu/smarthr-design-system pull request #1051
Opened 2023-12-26 08:21 UTC by im36-123

## 課題・背景

## やったこと

-

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2023-12-26 08:22 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +
@maiha2 書きます

2023-12-26 11:44 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +
書きました。 [db71d87](https://github.com/kufu/smarthr-design-system/pull/1051/commits/db71d87d873bc141bc9d5e2723dcf30200399e53)

2023-12-27 23:33 UTC, maiha2 requested changes
* 数字(1-1とか)を消しました。なくて大丈夫そう
* 困難→難しいに統一
* 要素→UIに統一
など

2023-12-28 02:57 UTC, im36-123 commented on content/articles/accessibility/low-vision.mdx
> +title: '限られた視覚のユーザーのウェブ利用に関連する問題点と解決策'
>「問題」だと、捉え方によって「ユーザーに問題がある」にも見えるおそれが有ると思った。

その懸念結構ありうる気がするので `利用時の課題` が良さそうですね

2023-12-28 03:02 UTC, im36-123 commented on content/articles/accessibility/low-vision.mdx
> +弱視・ロービジョンのユーザーは、画面上の色を見やすい組み合わせに変更したり、色を反転するOSの設定や機能を利用することがあります。設定や機能の仕様により、ウェブページのUIは任意の色の組み合わせで表示されます。
```suggestion
弱視・ロービジョンのユーザーは、画面上の色を見やすい組み合わせに変更したり、色を反転するOSの設定や機能を利用したりします。設定や機能の仕様により、ウェブページのUIは任意の色の組み合わせで表示されます。
```

「~たり」ときたら「〜たり」と続いてほしいので修正しました。ついでに「こと」というのも冗長なので削除しています

2023-12-28 03:09 UTC, im36-123 commented on content/articles/accessibility/low-vision.mdx
> +            ページの主要な導線にUIを配置する。ページの上部と下部を行ったり来たりするような設計にしない。たとえば、フォームの入力完了ボタンがページの上部にあるような設計になっていると複数のフォームを入力した後に再度ページを上までスクロールしボタンを押さなければならない。（1-5）
めちゃめちゃわかりやすい、いい表現〜〜〜

2023-12-28 03:33 UTC, maiha2 requested changes

2023-12-28 03:33 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +
```suggestion
```

2023-12-28 03:33 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +### 画面拡大について
```suggestion
### 画面拡大
```

「について」が繰り返されて邪魔だった

2023-12-28 03:33 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +### 色反転機能について
```suggestion
### 色反転機能
```

2023-12-28 03:33 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +### スクリーンリーダーについて
```suggestion
### スクリーンリーダー
```

2023-12-28 03:33 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +弱視・ロービジョンのユーザーは、画面上の色を見やすい組み合わせに変更したり、色を反転するOSの設定や機能を利用したりします。設定や機能の仕様により、ウェブページのUIは任意の色の組み合わせで表示されます。
```suggestion
弱視・ロービジョンのユーザーは、画面上の色を見やすい組み合わせに変更したり、色を反転するOSの設定や機能を利用することがあります。設定や機能の仕様により、ウェブページのUIは任意の色の組み合わせで表示されます。
```

2023-12-28 03:33 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +弱視・ロービジョンのユーザーは、拡大鏡や色反転機能と併せて、スクリーンリーダーを利用することがあります。残存視力や視野を利用して、画面を見るユーザーの場合は、見えにくい・見えない情報を得るための補助として、スクリーンリーダーの読み上げを利用します。
```suggestion
弱視・ロービジョンのユーザーは、拡大鏡や色反転機能と併せて、スクリーンリーダーを利用することがあります。残存視力や視野で画面を見るユーザーの場合、見えにくい・見えない情報を得るための補助として、スクリーンリーダーの読み上げを利用します。
```

2023-12-28 03:33 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +          <li>システムカラーを活用して色指定をする(参考: <a href="https://drafts.csswg.org/css-color/#css-system-colors">CSS Color Module Level 4 - System Colors</a>)</li>
```suggestion
          <li>色だけで情報を提示しない。 </li>
          <li>システムカラーを活用して色指定をする。(参考: <a href="https://drafts.csswg.org/css-color/#css-system-colors">CSS Color Module Level 4 - System Colors</a>)</li>
```

解決案列はみんな文末「。」ついているので、つけた

2023-12-28 03:33 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +
h1としてページタイトルが自動挿入されるので、不要

2023-12-28 03:37 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +                リンクテキストをクリックした際に画面の変化に気づけず、ページに遷移したことに気付けない。
```suggestion
                リンクテキストをクリックした際に画面の変化を捉えられず、ページに遷移したことに気づけない。
```

2023-12-28 03:44 UTC, tosiiu commented on content/articles/accessibility/low-vision.mdx
> +                リンクテキストをクリックした際に画面の変化に気づけず、ページに遷移したことに気付けない。
```suggestion
                リンクテキストをクリックした際に画面全体の変化を捉えられず、別のページに遷移したことに気づけない。
```
「別の」を付けたほうが分かりやすそうなので追加しました

2023-12-28 03:45 UTC, tosiiu commented on content/articles/accessibility/low-vision.mdx
> +                拡大時、表示中の狭い範囲の外に表示される通知バナーなどに気づけない。
```suggestion
                表示中の狭い範囲の外に表示される通知バナーなどに気づけない。
```
拡大時の話であることは自明なので省略できそう

2023-12-28 03:46 UTC, tosiiu commented on content/articles/accessibility/low-vision.mdx
> +          <li>高いコントラスト比を確保する</li>
```suggestion
          <li>高いコントラスト比を確保する。</li>
```
ここも句点付けたい

2023-12-28 03:46 UTC, tosiiu commented on content/articles/accessibility/low-vision.mdx
> +            正確なポイント操作や、ドラッグアンドドロップが必須の場合、キーボード操作による代替手段を提供する。
```suggestion
            正確なポインタ操作や、ドラッグアンドドロップが必須の場合、キーボード操作による代替手段を提供する。
```

2023-12-28 03:48 UTC, tosiiu commented on content/articles/accessibility/low-vision.mdx
> +            操作後のページ遷移を推測できるリンクテキストや、スタイル(下線付きテキストなど)を設定する。
```suggestion
            操作後のページ遷移を推測できるリンクテキスト（下線付きテキストなど）を設定する。
```
（下線付きテキストなど）リンクテキストのスタイルの説明だと思うので変更しました

2023-12-28 03:52 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +            関連するUIをできるだけ近くに配置する。たとえば、タブUIの切り替えボタンとタブパネルを近くに配置することでボタン操作によるパネルの変化に気付きやすくなる。
```suggestion
            関連するUIをできるだけ近くに配置する。たとえば、タブUIの切り替えボタンとタブパネルを近くに配置することでボタン操作によるパネルの変化に気づきやすくなる。
```

気付くは「気づく」で統一しようか

2023-12-28 03:52 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +            背景色の違いによって提示された領域の区切りに気付けない。
```suggestion
            背景色の違いによって提示された領域の区切りに気づけない。
```

2023-12-28 03:53 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +          <li>高いコントラスト比を確保する</li>
一個漏れてた！ありがとうございます！

2023-12-28 03:53 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +            正確なポイント操作や、ドラッグアンドドロップが必須の場合、キーボード操作による代替手段を提供する。
誤字！あざす！

2023-12-28 03:54 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +            操作後のページ遷移を推測できるリンクテキストや、スタイル(下線付きテキストなど)を設定する。
@tosiiu あー、前者は「テキストの内容」についてで、後者がスタイルのつもりでした！！

2023-12-28 03:55 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +            操作後のページ遷移を推測できるリンクテキストや、スタイル(下線付きテキストなど)を設定する。
> 操作後のページ遷移を推測できるテキストや、スタイル(下線付きテキストなど)を設定する。

でいいかな？

2023-12-28 03:57 UTC, tosiiu commented on content/articles/accessibility/low-vision.mdx
> +            操作後のページ遷移を推測できるリンクテキストや、スタイル(下線付きテキストなど)を設定する。
なるほど！理解です！
目的語があった方が分かりやすいと思ったのでこんなのどうでしょうか？

```suggestion
            操作後のページ遷移を推測できるリンクテキストや、スタイル(下線付きテキストなど)をリンクに設定する。
```

2023-12-28 04:00 UTC, maiha2 commented on content/articles/accessibility/low-vision.mdx
> +            操作後のページ遷移を推測できるリンクテキストや、スタイル(下線付きテキストなど)を設定する。
リンクが2回でてくるので、最後のだけ残して
```suggestion
            操作後のページ遷移を推測できるテキストや、スタイル(下線付きテキストなど)をリンクに設定する。
```
はどうでしょうか！前半「リンクテキスト」のほうがいいですかね？　@tosiiu

2023-12-28 05:31 UTC, tosiiu commented on content/articles/accessibility/low-vision.mdx
> +            操作後のページ遷移を推測できるリンクテキストや、スタイル(下線付きテキストなど)を設定する。
良さそうです！！

2023-12-28 05:49 UTC, tosiiu approved these changes
WIPとしてLGTMです！

2023-12-28 06:22 UTC, maiha2 approved these changes

2023-12-28 06:25 UTC, merged