#1300 ステップ式の操作画面のタイトルの書き方
kufu/smarthr-design-system pull request #1053
Opened 2023-12-27 03:38 UTC by aguringo

## 課題・背景

- https://github.com/kufu/smarthr-design-system-issues/issues/1300

## やったこと

-

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-01-10 05:30 UTC, versionfive reviewed
全体的にSuggestionしました。

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +3. 画面遷移エリア（[ダイアログ](#h3-3)・[ページ]/products/design-patterns/wizard/#h3-8)）
```suggestion
1. タイトルエリア（[ダイアログ](#h3-1)・[ページ](#h3-6)）
2. 操作エリア（[ダイアログ](#h3-2)・[ページ](#h3-7)）
3. 画面遷移エリア（[ダイアログ](#h3-3)・[ページ](#h3-8)）
```

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +複数ステップのモードのダイアログ・ページに共通する構成要素は次の通りです。
```suggestion
複数ステップのダイアログやページに共通する構成要素は次の通りです。
```

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +- [ボタンやテキストリンクでは、助詞は「を」を使用する](../../../products/contents/app-writing/#h2-4)
タイトルエリアの説明欄なので少し違うような？

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> + `従業員のhoge情報を一括登録`、`書き出し`
タイトルエリアの説明欄なので少し違うような？

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +![スクリーンショット: アクションダイアログの最初の画面](./images/wizard/wizard-dialog-1st.png)
```suggestion
[ActionDialog](/products/components/dialog/#h3-1)を使用し、操作に必要なコンポーネントは[余白の取り方](/products/design-patterns/spacing-layout-pattern/)に従って配置します。  

1. タイトルエリア
2. 操作エリア
3. 画面遷移エリア

![スクリーンショット: アクションダイアログの最初の画面](./images/wizard/wizard-dialog-1st.png)
```
説明と画像の間に、画像の1〜3の名前を示したいです。

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +### レイアウト
```suggestion
## ダイアログの構成
```
このセクション自体はレイアウト指定というよりも構成を示していると思いました。

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +### レイアウト
```suggestion
## Bottom fixed Areaを伴うページの構成
```

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +![スクリーンショット: アクションダイアログの最後の画面](./images/wizard/wizard-page-action.png)
```suggestion
[BottomFixedArea](/products/components/bottom-fixed-area/)を使用し、操作に必要なコンポーネントは[余白の取り方](/products/design-patterns/spacing-layout-pattern/)に従って配置します。

1. タイトルエリア
2. 操作エリア
3. 画面遷移エリア

![スクリーンショット: アクションダイアログの最後の画面](./images/wizard/wizard-page-action.png)
```
説明と画像の間に、画像の1〜3の名前を示したいです。

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +それぞれのステップごとの操作を見出しで伝えたい場合、`ScreenTitle`は複数ステップの操作の画面タイトルのパターンに合わせる必要はありません。ただし、一貫したモードであることがわかるように、`subBlockText`を使って複数ステップの操作画面タイトルのパターンを表示します。
```suggestion
それぞれのステップごとの操作を見出しで伝えたい場合、画面タイトル（`screenTitle`）は複数ステップの操作の画面タイトルのパターンに合わせる必要はありません。ただし、同じモードであることがわかるように、サブ・ブロックタイトル（`subBlockTitle`）を使って複数ステップの操作画面タイトルのパターンを表示します。
```
"画面タイトル"という言葉が被ってしまったのですが、「複数ステップの操作の画面タイトルのパターン」がなにかわかりませんでした。

subBlockText 👉 subBlockTitle

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +[Heading](/products/components/heading/)を使用し、`screenTitle`を使用します。
```suggestion
[Heading](/products/components/heading/)を使用し、画面タイトル（`screenTitle`）を使用します。
```
screenTitleはvariant名なので、[種類の名前](https://smarthr.design/products/components/heading/#h2-1)を加えました。

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +**見出しと操作テキストを表示しているパターン**
```suggestion
`複数ステップの操作画面`の見出しと説明テキストを含むエリアです。

- A. 見出し
- B. 説明テキスト

**見出しと操作テキストを表示しているパターン**
```

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +`登録する従業員の選択`
```suggestion
- サブ・ブロックタイトル：一連の操作の共通タイトル  
`従業員のhoge情報の一括登録（1/4）`
- 画面タイトル：このページでやることを表したタイトル  
`登録する従業員の選択`
```

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +[Bottom fixed Area](/products/components/bottom-fixed-area/)を使用します。
```suggestion
[BottomFixedArea](/products/components/bottom-fixed-area/)を使用します。
```
「BottomFixedArea」で一つの用語です。

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +#### Bottom fixed Areaのディスクリプション
```suggestion
#### BottomFixedAreaの説明テキスト
```

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +この画面のPrimaryButtonを押すことを促す説明を書きます。
```suggestion
この画面のPrimaryボタンを押すことを促す説明を書きます。
```

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +#### Bottom fixed Areaのボタンテキスト
```suggestion
#### BottomFixedAreaのボタンテキスト
```

2024-01-10 05:30 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +- 前の画面に移動する：`戻る`
```suggestion
Primaryボタンでは、次のステップに移動するか、複数ステップの操作のアクションを伝えます。
- 次の画面に移動する：`次へ`
- 最終画面のアクションテキスト：`登録`、`書き出し`など

Secondaryボタンでは、前のステップに移動できることを伝えます。
- 前の画面に移動する：`戻る`
```

2024-01-10 05:45 UTC, aguringo commented on content/articles/products/design-patterns/wizard.mdx
> +画面間の動線は一方通行ではなく、前のステップにも移動できるようにリンクを設けます。加えて、途中で操作をキャンセルできるようにします。
@versionfive 
> 「BottomFixedAreaを伴うページ」を以降は「ページ」と表記している場所がありますが、同じものと捉えられるかなぁ

これちょっと悩んだんですよね…
でも「BottomFixedAreaを伴うページ」って毎回書くには長くてくどいよなぁと思ってしまい。

2024-01-10 05:51 UTC, aguringo commented on content/articles/products/design-patterns/wizard.mdx
> +それぞれのステップごとの操作を見出しで伝えたい場合、`ScreenTitle`は複数ステップの操作の画面タイトルのパターンに合わせる必要はありません。ただし、一貫したモードであることがわかるように、`subBlockText`を使って複数ステップの操作画面タイトルのパターンを表示します。
@versionfive 

> 、「複数ステップの操作の画面タイトルのパターン」がなにかわかりませんでした。

伝わりづらいの、わかります。ちょっと考えます〜

2024-01-10 05:53 UTC, aguringo commented on content/articles/products/design-patterns/wizard.mdx
> +### レイアウト
🦀

2024-01-10 05:53 UTC, aguringo commented on content/articles/products/design-patterns/wizard.mdx
> +複数ステップのモードのダイアログ・ページに共通する構成要素は次の通りです。
@versionfive 
ですね。
コミット取り込んだ状態で見直してみます〜

2024-01-10 07:28 UTC, aguringo commented on content/articles/products/design-patterns/wizard.mdx
> +- [ボタンやテキストリンクでは、助詞は「を」を使用する](../../../products/contents/app-writing/#h2-4)
@versionfive 

ダイアログタイトルとその手前のアクションテキストは揃えようねってことを伝えたいんですけど、どこに書くのが適当ですかね…

dialogコンポーネントのコードには両方書くじゃないですか。だから、一緒に書いておきたいんですよね。

```
<Button>
ボタンのテキスト
</Button>
<ActionDialog title="タイトル".......>
  <hoge>
 </hoge>
</ActionDialog>
```

つか、こっちに書けば良いのかなぁ…
https://smarthr.design/products/components/dialog/#h2-3

2024-01-10 07:54 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +画面間の動線は一方通行ではなく、前のステップにも移動できるようにリンクを設けます。加えて、途中で操作をキャンセルできるようにします。
>毎回書くには長くてくどい

わかる。
「モーダルダイアログ（ActionDialog）、モーダルページ（BottomFixedAreaを伴うページ）」と書くとかでしょうか…

2024-01-10 07:55 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +- [ボタンやテキストリンクでは、助詞は「を」を使用する](../../../products/contents/app-writing/#h2-4)
そうですね、場所としてはButtonかDialogにある方が適当な気がします

2024-01-10 08:04 UTC, versionfive reviewed
🙏

2024-01-10 08:04 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +[「よくあるテーブル」](/products/design-patterns/smarthr-table/)や[FormControl](/products/components/form-control/)などを使用して、ステップごとの操作するためのエリアです。
```suggestion
[よくあるテーブル](/products/design-patterns/smarthr-table/)や[FormControl](/products/components/form-control/)などを使用して、ステップごとの操作するためのエリアです。
```
直し忘れ…このカッコ外さないとですね。

2024-01-10 08:10 UTC, aguringo commented on content/articles/products/design-patterns/wizard.mdx
> +画面間の動線は一方通行ではなく、前のステップにも移動できるようにリンクを設けます。加えて、途中で操作をキャンセルできるようにします。
@versionfive 

なるほど！　先に命名しちゃうのか。いいアイディアですね。

2024-01-10 12:29 UTC, uknmr requested changes
デザインパターン内のパターンが崩れてきてるので揃えた方が良さそうです。
（「種類」の中でダイアログと BottomFixedArea と Stepper などをまず並べると他に沿うかも?）

2024-01-10 12:29 UTC, uknmr commented on content/articles/products/design-patterns/wizard.mdx
> +2. 操作エリア
操作エリア? ダイアログボディ? ボディ? 入力エリア?

2024-01-10 12:29 UTC, uknmr commented on content/articles/products/design-patterns/wizard.mdx
> +`複数ステップの操作画面`の見出しを表示するエリアです。
エリアって普段言わないからこの辺りでムズムズしてきちゃった。外国籍の名前に見えてくる

2024-01-10 12:29 UTC, uknmr commented on content/articles/products/design-patterns/wizard.mdx
> +基本的に、`{オブジェクト名}の{操作名}（1/n）`という表記します。
```suggestion
### 1. タイトルエリア

基本的に、見出しには`{オブジェクト名}の{操作名}（1/n）`と書きます。
```

2024-01-10 12:29 UTC, uknmr commented on content/articles/products/design-patterns/wizard.mdx
> +あわせて、[Dialog](https://smarthr.design/products/components/dialog/#h2-3)のライティングパターンも参照してください。
「の」の話は Dialog の方にあればよさそう。

```suggestion

あわせて、[Dialog](https://smarthr.design/products/components/dialog/#h2-3)のライティングパターンも参照してください。
```

2024-01-10 12:29 UTC, uknmr commented on content/articles/products/design-patterns/wizard.mdx
> +### 2. 操作エリア
「複数ステップの操作」で特段変わることはないので、丸っといらない気がした。

2024-01-10 12:29 UTC, uknmr commented on content/articles/products/design-patterns/wizard.mdx
> +- 最後の画面のアクションボタン：一連の操作の最終目的の操作名（`登録`、`書き出し`など）
画か実装が見たくなりそう。順番も定義したい。

```suggestion
<!-- textlint-enable -->
ボタンラベルは、以下のように表示します。
- 次の画面に移動する：`次へ`
- 前の画面に移動する：`戻る`
- 操作を取りやめる：`キャンセル`
- 最後の画面のアクションボタン：一連の操作の最終目的の操作名（`登録`、`書き出し`など）
```

2024-01-10 12:29 UTC, uknmr commented on content/articles/products/design-patterns/wizard.mdx
> +3. 画面遷移エリア
どちらかというとこっちが操作エリア感ある。フッターでもよさそう。

2024-01-10 12:29 UTC, uknmr commented on content/articles/products/design-patterns/wizard.mdx
> +3. 画面遷移エリア
特に Dialog と揃える必要はない気がした。

```suggestion
1. タイトルエリア
2. 入力エリア
3. BottomFixedArea
```

2024-01-10 12:29 UTC, uknmr commented on content/articles/products/design-patterns/wizard.mdx
> +それぞれのステップごとの操作を見出しで伝えたい場合、画面タイトル（`screenTitle`）はライティングパターンに合わせる必要はありません。ただし、同じモードであることがわかるように、サブ・ブロックタイトル（`subBlockTitle`）を使って複数ステップの操作画面タイトルのライティングパターンに合わせたテキストを表示します。
ここの読み取り難度が高そうです! 画面の例がすべてサブ・ブロック付きになってるからかも?

2024-01-11 03:05 UTC, versionfive commented on content/articles/products/design-patterns/wizard.mdx
> +### ライティング
ライティングにおける基本的な考え方があるなら、個別にセクションつくっていい構成になっているはずですね。
https://smarthr.design/products/design-patterns/#h3-2

ただ、たしかに現状書いてあることだけをみると、タイトルまわりのことが主なので、そっちのライティングパターンに移動しても違和感はないかなと思いました◎

2024-01-11 07:37 UTC, drivesketch commented on content/articles/products/design-patterns/wizard.mdx
> +- 基本的には[ActionDialog](#h2-2)を使用します。ただし、フォームなどの要素が多い場合は、[BottomFixedAreaを伴うページ](#h2-3)を使用して、**モーダル（一連の操作）であることを明示**します。
```suggestion
- 基本的には[ActionDialog](../components/dialog/#h3-1)を使用します。ただし、フォームなどの要素が多い場合はActionDialogではなくページを使用し、[BottomFixedArea](../components/bottom-fixed-area/)を伴うことで**モーダル（一連の操作）であることを明示**します。詳しくは、[ダイアログの構成](#h2-1)、[BottomFixedAreaを伴うページの構成](#h2-2)を参照してください。
```

このサジェストもあんまりイケてない気がするんですが、

- ActionDialogやBFAのComponentへの言及と、当ページ内で解説しているそれぞれの構成パターンへの言及は分ける方が良いのではないか
- 「モーダルであることを明示」しているのは「BFA（を伴うこと）」であって「（BFAを伴う）ページ」ではない

という方向性の意見です。

2024-01-11 07:47 UTC, drivesketch commented on content/articles/products/design-patterns/images/wizard/wizard-page-action.png
> 画面上部の「戻る」リンクがBFAと重複しているため、必要かどうか気になる

これ講座中に気になったのを思い出しました（自分の班では、戻るリンクがあるからという理由でキャンセルボタンをつけなかった）

「前ステップに戻るのか、モードから離脱するのか」の混乱もあるので、上部の戻るリンクはトリの方が良い気がしてきました。

2024-01-12 01:19 UTC, aguringo commented on content/articles/products/design-patterns/images/wizard/wizard-page-action.png
> SubBlockTitle・ScreenTitleの余白が広く、タイトルエリアのグルーピングが弱く見える

タイトルエリアの余白、確かに！でした。ここ調整しますね。

> 画面上部の「戻る」リンクがBFAと重複しているため、必要かどうか気になる

こっちは、Slackのスレで会話進みそうなので、そちらで進め方決めましょう。

2024-11-07 01:37 UTC, drivesketch commented
引き継いで改めて書き直すのでいったんcloseします。

2024-11-07 01:37 UTC, closed without merging