「ヘルプページレビューの手引き」を更新
kufu/smarthr-design-system pull request #1061
Opened 2024-01-09 00:54 UTC by INABAshina

## 課題・背景
https://github.com/kufu/smarthr-design-system-issues/issues/1314

## やったこと
- Zendesk時代の記述を修正

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-01-12 02:07 UTC, aguringo requested changes

2024-01-12 02:07 UTC, aguringo commented on content/articles/products/contents/help-center/review.mdx
> +| 8 | 画像（img）タグ内の属性に過不足がないか | altが空になっているか、不適切な画像名になっていないかなど。 | 参考：[キャプチャ・加工のルール](https://smarthr-inc.docbase.io/posts/1836257) |
```suggestion
| 8 | 画像のaltは適切な説明が入っているか | altが空になっているか、不適切な画像名になっていないかなど。 | 参考：[[本文と代替テキストのガイドライン](/image/#h2-1) |
```

Altのガイドラインがヘルプセンターガイドラインの中にあるので、そちらに変えたほうが良いと思いました。
（path間違ってたらごめんなさい）

2024-01-19 09:45 UTC, aguringo approved these changes

2024-01-19 09:52 UTC, 8chari approved these changes
ありがたう〜！LGTM！！！

2024-01-23 00:16 UTC, merged