ヘッダーのガイドラインを更新
kufu/smarthr-design-system pull request #1098
Opened 2024-03-15 10:15 UTC by wentzzz

## 課題・背景

## やったこと
- グローバルヘッダーのガイドラインを更新
- アプリナビゲーションのガイドラインを追加

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-04-17 02:52 UTC, uknmr approved these changes
後半、流し見になってしまいましたが LGTM!
ほぼ IMO なので無視して大丈夫です!!!

2024-04-17 02:52 UTC, uknmr commented on content/articles/products/design-patterns/contents-in-header.mdx
> +- B. [アプリナビゲーション（下）](#h2-1)
IMO: ちょっと面倒だけど、以下のように書くと意図通りかも?

```html
<ol type="A">
  <li>ほげ</li>
  <li>ふが</li>
</ol>
```

2024-04-17 02:52 UTC, uknmr commented on content/articles/products/design-patterns/contents-in-header.mdx
> +構成要素は次のとおりです。
IMO: 冗長に見えました

```suggestion
```

2024-04-17 02:52 UTC, uknmr commented on content/articles/products/design-patterns/contents-in-header.mdx
> +構成要素の必須項目以外は任意の要素です。機能によって使用有無を判断してください。
IMO: 基本必須で、任意のものに記しをつける方針の方がいいかも? と思いました。

以降の各見出しにも「（任意）」とあった方が、「あぁ、これは無視して大丈夫なやつだな」というのが理解しやすそう。

2024-04-17 02:52 UTC, uknmr commented on content/articles/products/design-patterns/contents-in-header.mdx
> +［WIP］
IMO: 企業アカウント選択が古（いにしえ）のものであることも触れたそう。

2024-04-17 02:52 UTC, uknmr commented on content/articles/products/design-patterns/contents-in-header.mdx
> +ただし、ユーザーがプロダクト上で日本語以外を表示設定している場合は、対応する言語のヘルプセンターへ移動します。
Q: これは開発側での意識が必要そう?（なんとなく勝手にリダイレクトされるのかと思ってました）

2024-04-17 02:52 UTC, uknmr commented on content/articles/products/design-patterns/contents-in-header.mdx
> +アプリナビゲーションは、アクセスしている機能に応じたアプリケーション内のページや設定などへの横断的なアクセスを提供します。
IMO: 少し伝わりにくく感じたので、提案してみました!

```suggestion
アプリナビゲーションは、アクセスしている機能内のページや設定など、機能に閉じた横断的なアクセスを提供します。アプリナビゲーションから多機能に移動はできません。
```

2024-04-17 03:23 UTC, aguringo reviewed
まだ正式に整理できてないけれど、アプリと機能の再定義中だったり、ちょっと先の話を踏まえてコメントしてます。

2024-04-17 03:23 UTC, aguringo commented on content/articles/products/design-patterns/contents-in-header.mdx
>  グローバルヘッダーは、システム設定・通知・機能間の移動などのシステム全体の機能への横断的なアクセスを提供します。
「システム」でいいのかが気になりました。

あと、「機能」は基本機能内にも複数機能を内包しているのが現状なので、
`アプリケーションへの横断的なアクセス`
の方が自然かなと思いました。（この辺の定義を今、検討中です〜）

2024-04-17 03:23 UTC, aguringo commented on content/articles/products/design-patterns/contents-in-header.mdx
> +ユーザーが利用できるSmartHR内の他の機能へ移動するためのボタンです。
```suggestion
ユーザーが利用できるSmartHR内の他のアプリケーションへ移動するためのボタンです。  
```
上述と同じ理由

2024-04-17 03:23 UTC, aguringo commented on content/articles/products/design-patterns/contents-in-header.mdx
> +原則として、他の機能とあわせて横断的に利用するユースケースが想定される場合に配置します。
```suggestion
原則として、他のアプリケーションとあわせて横断的に利用するユースケースが想定される場合に配置します。
```
アプリでも良いかも

2024-04-17 03:23 UTC, aguringo commented on content/articles/products/design-patterns/contents-in-header.mdx
> +アプリナビゲーションは、アクセスしている機能に応じたアプリケーション内のページや設定などへの横断的なアクセスを提供します。
```suggestion
アプリナビゲーションは、アクセスしているアプリケーション内のページや設定など、アプリケーションに閉じた横断的なアクセスを提供します。
```

ここも「機能」と「アプリケーション」の使い分けでのサジェスト

2024-04-17 03:23 UTC, aguringo commented on content/articles/products/design-patterns/contents-in-header.mdx
> +構成要素の必須項目以外は任意の要素です。機能によって使用有無を判断してください。
ここの機能は、「アプリケーションで提供している機能」とも捉えられるので、ママでよさそう

2024-04-17 03:23 UTC, aguringo commented on content/articles/products/design-patterns/contents-in-header.mdx
> +現在アクセスしている機能のリリースノートを確認するためのボタンです。
```suggestion
現在アクセスしているアプリケーションのリリースノートを確認するためのボタンです。  
```

2024-04-17 03:23 UTC, aguringo commented on content/articles/products/design-patterns/contents-in-header.mdx
> +リリースノートボタンを押すと、最新5件分の日付を含むリリースノートへのリンクと、対応する機能のリリースノートの一覧画面へ移動するリンクが表示されます。
```suggestion
リリースノートボタンを押すと、最新5件分の日付を含むリリースノートへのリンクと、対応するアプリケーションのリリースノートの一覧画面へ移動するリンクが表示されます。  
```

2024-04-17 03:23 UTC, aguringo commented on content/articles/products/design-patterns/contents-in-header.mdx
> +SmartHR基本機能の従業員情報や共通設定に登録されているデータを、現在アクセスしている機能のデータベースへ能動的に同期するためのボタンです。
ここなのですが、kagamiではEDPデータも同じボタンで同期タイミングを制御する予定なので、現時点ではOKでも早々に実態と変わってしまいそう。

@tosiiu どう思いますか？

2024-04-17 04:41 UTC, wentzzz commented on content/articles/products/design-patterns/contents-in-header.mdx
>  グローバルヘッダーは、システム設定・通知・機能間の移動などのシステム全体の機能への横断的なアクセスを提供します。
確かに。

2024-04-17 04:41 UTC, tosiiu commented on content/articles/products/design-patterns/contents-in-header.mdx
> +SmartHR基本機能の従業員情報や共通設定に登録されているデータを、現在アクセスしている機能のデータベースへ能動的に同期するためのボタンです。
今後EDPデータをこのボタンで同期するアプリが登場する可能性は大いにある（kagamiは例外的な振る舞いではない）ので、基本機能に限定しない書き方にするのが良さそうと思いました！

あまり良い書き方が思いつかないですが、こんなイメージです。
```suggestion
現在アクセスしている機能で必要なSmartHR基本機能や他機能に登録されているデータを、現在アクセスしている機能のデータベースへ能動的に同期するためのボタンです。  
```

2024-04-17 04:44 UTC, versionfive commented on content/articles/products/design-patterns/contents-in-header.mdx
> +原則として、他の機能とあわせて横断的に利用するユースケースが想定される場合に配置します。
ホームでも「アプリ」なのでアプリに一票

2024-04-17 04:58 UTC, wentzzz commented on content/articles/products/design-patterns/contents-in-header.mdx
> +構成要素の必須項目以外は任意の要素です。機能によって使用有無を判断してください。
なるほど

2024-04-17 05:44 UTC, versionfive reviewed
コメントやSuggestしました〜

2024-04-17 05:44 UTC, versionfive commented on content/articles/products/design-patterns/contents-in-header.mdx
> +対応するコンポーネントは[`Header`](/products/components/header/)です。
```suggestion
対応するコンポーネントは[Header](/products/components/header/)です。
```
（全部揃えられてないけど）コンポーネント名はCodeにしないようにしたい

2024-04-17 05:44 UTC, versionfive commented on content/articles/products/design-patterns/contents-in-header.mdx
> +
```suggestion
```
ないならとってもよさそう。あるいは、実態はHeaderがレイアウト持ってくれてるので、そういう記載でもいいのかもしれない

2024-04-17 05:44 UTC, versionfive commented on content/articles/products/design-patterns/contents-in-header.mdx
> +対応するコンポーネントは[`AppNavi`](/products/components/app-navi/)です。
```suggestion
対応するコンポーネントは[AppNavi](/products/components/app-navi/)です。
```

2024-04-17 05:44 UTC, versionfive commented on content/articles/products/design-patterns/contents-in-header.mdx
> +要素間の余白は以下のとおりです。詳細は[余白の取り方](/products/design-patterns/spacing-layout-pattern/)を参照してください。
実態としてはAppNaviで余白などのレイアウトは持ってくれると思いました。（デザイナーが余白を考慮する必要はないはず？）

2024-04-17 05:44 UTC, versionfive commented on content/articles/products/design-patterns/contents-in-header.mdx
> +［WIP］
アカウント名の表記方法、ルールほしいみありますね

2024-04-17 05:44 UTC, versionfive commented on content/articles/products/design-patterns/contents-in-header.mdx
>  移動先は、SmartHR基本機能のトップページです。
```suggestion
移動先は、SmartHRのホーム（`/`）です。
```
https://smarthr.design/products/contents/idiomatic-usage/usage/#recYNynP9kXNRdD0T-0

2024-04-17 06:40 UTC, wentzzz commented on content/articles/products/design-patterns/contents-in-header.mdx
> +要素間の余白は以下のとおりです。詳細は[余白の取り方](/products/design-patterns/spacing-layout-pattern/)を参照してください。
グローバルヘッダーの方も消したので、こちらもコンポーネントで担保されるはずなので消しちゃいます。

2024-04-17 06:56 UTC, wentzzz commented on content/articles/products/design-patterns/contents-in-header.mdx
>  グローバルヘッダーは、システム設定・通知・機能間の移動などのシステム全体の機能への横断的なアクセスを提供します。
システムからアプリに変更しました。

2024-04-17 07:04 UTC, wentzzz commented on content/articles/products/design-patterns/contents-in-header.mdx
> +構成要素の必須項目以外は任意の要素です。機能によって使用有無を判断してください。
任意を表記する方式に変更しました。

2024-04-17 07:04 UTC, wentzzz commented on content/articles/products/design-patterns/contents-in-header.mdx
> +［WIP］
追々で！

2024-04-17 07:20 UTC, uknmr commented on content/articles/products/design-patterns/contents-in-header.mdx
> +構成要素の必須項目以外は任意の要素です。機能によって使用有無を判断してください。
任意が明らかになったので、一文なくても大丈夫そう。

```suggestion
```

2024-04-17 07:22 UTC, uknmr commented on content/articles/products/design-patterns/contents-in-header.mdx
> +#### A-2. 企業アカウント切替ボタン
こっちにも欲しい!

```suggestion
#### A-2. 企業アカウント切替ボタン（任意）
```

2024-04-17 07:22 UTC, uknmr commented on content/articles/products/design-patterns/contents-in-header.mdx
> +#### A-4. アプリランチャー
```suggestion
#### A-4. アプリランチャー（任意）
```

2024-04-17 07:22 UTC, uknmr commented on content/articles/products/design-patterns/contents-in-header.mdx
> +#### A-5. ユーザーアカウントボタン
```suggestion
#### A-5. ユーザーアカウントボタン（任意）
```

2024-04-17 07:47 UTC, uknmr approved these changes
LGTM~

2024-04-17 07:58 UTC, versionfive requested changes
おそらく何かの移行時に漏れているのだと思うのですが、画像を格納するフォルダ名ですが、mdxファイル名と一致してほしいです :pray:

上に戻るリンクのように「contents-in-header」フォルダをつくるのがよさそうです。

2024-04-18 06:03 UTC, versionfive approved these changes
:arigatau: LGTM!

2024-04-18 06:32 UTC, aguringo approved these changes

2024-04-18 06:33 UTC, merged