「リリースノートの書き方」の修正・分割
kufu/smarthr-design-system pull request #1107
Opened 2024-03-28 08:26 UTC by kawakichi-desu

## 課題・背景

- [テクニカルライティング講座_リリースノート編](https://docs.google.com/presentation/d/1K3gksN_PQ8b9RvL4dbe5ETmmDQfk_oG3lLuVqEm88Fs/edit#slide=id.g2b95c15b3fc_0_78)が爆誕したため、ガイドラインへの適用・リライトが必要
- 上記と合わせて、リリースノートのガイドラインの課題を解消したい
  - 1ページに含まれる情報がモリモリで、必要な内容を探しづらい
  - 具体例が少なかったり、作成の流れに沿ってガイドラインを参照しづらかったりする
  - 書き方のページで言及していない表記ルールも守ってほしいが、あまり意識されていない
    - ライティングスタイル、用字用語、UIテキスト
    

## やったこと

- リリースノートの書き方を2つに分割
  - before：リリースノートの書き方
  - after：リリースノートの目的、リリースノートの書き方
- リリースノートの書き方に、スライドの内容を適用した
- 作成者の作成の流れに沿って構成を変更
  - 一番大事にしないといけないこと👉各カテゴリに何を書くか👉具体的に見出しや本文など要素別に何を書くかを、順番に参照できるようにした

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-04-02 02:21 UTC, aguringo requested changes
![image](https://github.com/kufu/smarthr-design-system/assets/44823946/5ee14287-669b-496e-b949-00570d94bbad)

リリースノートに関する記述のページが分割されたので、［ヘルプセンター］配下のコンテンツの並び順に違和感が出ましたね。

並びを変えることも考えたんですが、スクショとレビューのガイドラインはリリースノートにも適用できる部分があるので、これらのページも改善したいです〜

- ヘルプセンター
  - ヘルプページの構成
  - ヘルプページの書き方
  - 概要の書き方
  - 操作手順の書き方
  - 仕様の一覧の書き方
  - エラーメッセージごとの対応方法の書き方
  - よくある質問の書き方
  - リリースノートの目的
  - リリースノートの書き方
  - ヘルプセンターで使用する画像要素
  - コンテンツレビューの手引き

2024-04-03 02:40 UTC, aguringo requested changes
@kawakichi-desu 

細かくサジェストしました。
意図がわからなかったところは質問してください！

2024-04-03 02:40 UTC, aguringo commented on content/articles/products/contents/help-center/releasenotes.mdx
> +リリースノートでは「※」の注釈は使いません。専門的な言葉は使わず、平易な言葉でわかりやすく書くことを意識しましょう。
```suggestion
開発者にとっては当たり前でも、ユーザーにとっては不慣れな表現は伝わりません。一般的な言葉で書くことを意識しましょう。
```

少し具体的な書き方にしました。

>  リリースノートでは「※」の注釈は使いません。
これは、書き方のルールなので考え方を述べているここでは不適切な内容なので削除したいです。

2024-04-03 02:40 UTC, aguringo commented on content/articles/products/contents/help-center/releasenotes.mdx
> +変更点については、どの画面のことなのか、どの操作に関係するのかを具体的に書きます。
> 記載します。
> 伝えます。
> 書きます。

ってのが気になるので、

```suggestion
使い勝手の向上を目的としたアップデートについて記載します。  

変更点について、「画面」と「操作」を具体的に明示しながら説明します。  
また、変更内容に加えて、これまで使用時に生じていた不便など、アップデートの背景も説明します。  
```

2024-04-03 02:40 UTC, aguringo commented on content/articles/products/contents/help-center/releasenotes.mdx
> +また、アップデートに伴って必要な操作がある場合や、アプリケーションの挙動に影響を与える場合には必ず明記します。
```suggestion
アップデートに伴って必要な操作がある場合や、アプリケーションの挙動に影響を与える場合には必ず明記します。   
```

また、が続くので

2024-04-03 02:40 UTC, aguringo commented on content/articles/products/contents/help-center/releasenotes.mdx
> +どの画面、どのユーザーインターフェースで、どのようなアクセシビリティ対応が追加されたかを具体的に書きます。
```suggestion
アクセシビリティ向上につながる対応について記載します。  

どの画面、UIで、どのようなアクセシビリティ対応が追加されたかを具体的に書きます。  
```

2024-04-03 02:40 UTC, aguringo commented on content/articles/products/contents/help-center/releasenotes.mdx
> +どの画面、どのユーザーインターフェースで、どのような変更をしたかを具体的に書きます。
```suggestion
どの画面、UIで、どのような変更をしたかを具体的に書きます。  
```

2024-04-03 03:08 UTC, 8chari commented on content/articles/products/contents/help-center/review.mdx
> +※2024年1月時点では、ヘルプページに限り、UXライターが書いた記事であっても、他のUXライターによるレビューを実施しています。
```suggestion
※2024年1月時点では、ヘルプページに限り、UXライターが書いたコンテンツであっても、他のUXライターによるレビューを実施しています。
```

2024-04-03 03:10 UTC, 8chari commented on content/articles/products/contents/help-center/releasenotes.mdx
> +## ユーザーの立場に立って、「できるようになった」こと、「できなくなった」ことを伝える
```suggestion
## ユーザーの立場で、できるようになったこと、できなくなったことを伝える
```
好みかもですが、括弧がなくてもよいかなと思いました。

2024-04-03 03:14 UTC, 8chari commented on content/articles/products/contents/help-center/releasenotes.mdx
> +不具合修正のカテゴリのみ、見出しは不要です。重要度が高い内容を強調して伝えたい場合は、見出しを立てても構いません。
```suggestion
不具合の修正について記載します。

どの画面、UIで発生していた不具合が修正されたかを具体的に書きます。  

不具合修正が複数あるときは、箇条書きで記載します。  
基本的に見出しは不要です。重要度が高い修正を伝えたい場合は、見出しを立てても構いません。 
```
細かいですが、aguriさん案に追加する形で下記をsuggestしました。
`不具合修正のカテゴリのみ、`→`基本的に`
- 不具合修正に関することであることは自明なため
- すぐ後ろで「見出しを立ててもいいよ〜」と言っており、「あれ、不要なんじゃないの？」と違和感があったため

2024-04-03 03:21 UTC, 8chari commented on content/articles/products/contents/help-center/review.mdx
>  ### レビュイー
```suggestion
### レビュイー（レビューを依頼する人）
```
マージして、この下の`#### レビューを依頼する`は取ってしまってよいと思いましたが、どうでしょう？

2024-04-03 03:21 UTC, 8chari commented on content/articles/products/contents/help-center/review.mdx
>  #### レビューする
```suggestion
### レビュアー（レビューする人）
```

2024-04-03 03:23 UTC, 8chari commented on content/articles/products/contents/help-center/review.mdx
> +新機能をはじめ、以下のヘルプページは関係者レビューによる確認をする場合があります。
```suggestion
新機能をはじめ、以下のヘルプページは関係者レビューを実施する場合があります。
```
このほうがすっきりしそうです。

2024-04-03 03:25 UTC, 8chari requested changes
@kawakichi-desu 大盛更新ありがとうございます！表現まわりでいくつかコメントを入れました🙏

2024-04-03 04:07 UTC, kawakichi-desu commented on content/articles/products/contents/help-center/review.mdx
> +description: 'SmartHRヘルプセンターに掲載するコンテンツのレビューに関する考え方をまとめています。'
デザインとあわせて「コンテンツレビュー」にします！

2024-04-03 04:13 UTC, kawakichi-desu commented on content/articles/products/contents/help-center/releasenotes-purpose.mdx
> +- UI/UXの改善や、データ処理の高速化などが含まれます。
あああ……ぐうの音も出ません…!!🙇‍♀
リライトにあたって[hanicaの社内向けリリースノートの書き方](https://smarthr-inc.docbase.io/posts/1496955)から内容を引っ張ったままにしていました🙇‍♀この機会に引用元資料も修正しました🙏

2024-04-03 04:16 UTC, kawakichi-desu commented on content/articles/products/contents/help-center/releasenotes.mdx
> +## ユーザーの立場に立って、「できるようになった」こと、「できなくなった」ことを伝える
aguri-san案を踏まえて検討してくださった、snow-san案を反映します🙌

2024-04-03 04:21 UTC, kawakichi-desu commented on content/articles/products/contents/help-center/releasenotes.mdx
> +ユーザー目線とは、コード追加・修正によって生じるアプリケーションの挙動ではなく、ユーザーにとって、何が実現されたか/何ができなくなったかです。
🦀…！そっとご提案をいただいていますが、記述記号は全角が推奨でしたね😫 取り込みます！

2024-04-03 04:27 UTC, kawakichi-desu commented on content/articles/products/contents/help-center/releasenotes.mdx
> +リリースノートでは「※」の注釈は使いません。専門的な言葉は使わず、平易な言葉でわかりやすく書くことを意識しましょう。
この記載は「ここだけ妙に具体的になるけど言いたい〜〜」と思って、違和感がありつつも突っ込んだ内容でした🌀
考え方に落としつつ、具体的な内容の案内に変えていただいてありがとうございます！！

2024-04-03 04:34 UTC, kawakichi-desu commented on content/articles/products/contents/help-center/review.mdx
> +※2024年1月時点では、ヘルプページに限り、UXライターが書いた記事であっても、他のUXライターによるレビューを実施しています。
あああ、記事という言葉はどこにも出てこないですね😫ありがとうございます！

2024-04-03 04:36 UTC, kawakichi-desu commented on content/articles/products/contents/help-center/review.mdx
>  ### レビュイー
🦀 🦀 スッキリしますね！反映します🙌

2024-04-03 04:47 UTC, kawakichi-desu commented on content/articles/products/contents/help-center/review.mdx
> +| 8 | 画像名や画像のaltは適切な説明が入っているか | 不適切な画像名になっていないか、altが空になっていないかなど。  参考：[本文と代替テキストのガイドライン](/image/#h2-1) |
```suggestion
| 8 | 画像名や画像のaltは適切か | 不適切な画像名になっていないか、altが空になっていないかなど。  参考：[本文と代替テキストのガイドライン](/image/#h2-1) |
```
画像名が「適切な説明」にかかってしまうので調整しようと思います！良さげでしょうか？

2024-04-03 04:55 UTC, kawakichi-desu commented on content/articles/products/contents/help-center/review.mdx
>  #### レビューを依頼する
```suggestion
```

2024-04-03 06:52 UTC, kawakichi-desu commented on content/articles/products/contents/help-center/image.mdx
> +  - 例：hoge画面で［ダウンロード］を押します。
申し送り：画面名には［］をつけなくなったので修正しています

2024-04-03 06:52 UTC, kawakichi-desu commented on content/articles/products/contents/help-center/image.mdx
> +また、「[関連する情報は近くに配置する](../basic-rule/#h4-4)」にしたがって、スクリーンショットと対応する説明文を近くに配置すると、意図が伝わりやすくなります。
申し送り：リンク先の名称と合わせました

2024-04-03 06:58 UTC, kawakichi-desu commented on content/articles/products/contents/help-center/releasenotes.mdx
> +事前に機能の廃止をお知らせしていた、ヘルプセンターの[アップデート](https://smarthr.jp/update)の記事へのリンクを設置します。
申し送り：サビサにはアップデートというコンテンツがなくなっていたので変更しています。
![image](https://github.com/kufu/smarthr-design-system/assets/65280580/d09a37f4-a185-498b-b175-6328b28b4aa4)

2024-04-03 07:09 UTC, 8chari submitted a review, later dismissed
ありがとうございます :tada:
[![LGTMeow](https://lgtm-images.lgtmeow.com/2022/05/03/14/e9c9e48f-e243-483a-a4ac-c7090efc50fe.webp)](https://lgtmeow.com)

2024-04-03 08:17 UTC, aguringo requested changes
@kawakichi-desu もう一声！

2024-04-03 08:17 UTC, aguringo commented on content/articles/products/contents/help-center/releasenotes.mdx
> +また、プレスリリースや[アップデート](https://smarthr.jp/update)の記事、ヘルプページがある場合は、リンクを設置します。
```suggestion
また、プレスリリースやお知らせの記事、ヘルプページがある場合は、リンクを設置します。
```

2024-04-03 08:17 UTC, aguringo commented on content/articles/products/contents/help-center/releasenotes.mdx
> +事前に機能の廃止をお知らせしていた、ヘルプセンターの[アップデート](https://smarthr.jp/update)の記事へのリンクを設置します。
```suggestion
事前に機能の廃止を告知していた、お知らせの記事へのリンクを設置します。  
```

サブドメはヘルプセンターなのですが、入り口はサビサなのと、表示した画面のセクション名が「お知らせ」（URL 
だと、https://support.smarthr.jp/ja/info/）だったので、「お知らせ」にしています。
また、リンクはこの場合は不要なので削除しました。（上の方の行も同じく）

2024-04-03 08:43 UTC, kawakichi-desu commented on content/articles/products/contents/help-center/releasenotes.mdx
> +事前に機能の廃止をお知らせしていた、ヘルプセンターの[アップデート](https://smarthr.jp/update)の記事へのリンクを設置します。
🦀 ありがとうございます！

2024-04-04 00:34 UTC, kawakichi-desu commented on content/articles/products/contents/help-center/review.mdx
> +| 8 | 画像名や画像のaltは適切な説明が入っているか | 不適切な画像名になっていないか、altが空になっていないかなど。  参考：[本文と代替テキストのガイドライン](/image/#h2-1) |
あぐりさん、訂正ありがとうございます🙏

2024-04-04 00:45 UTC, aguringo submitted a review, later dismissed

2024-04-04 09:09 UTC, kawakichi-desu commented on content/articles/products/contents/help-center/releasenotes.mdx
> +どの画面、UIで、どのような変更をしたかを具体的に書きます。
```suggestion
どの画面、UIで、どのような変更をしたかを具体的に書きます。  
見出しを立てるかどうかは任意です。
```
@aguringo 「その他の変更」カテゴリについては見出しがあったりなかったりするようで、判断に迷う場面を見かけたので追記しました🙏

2024-04-10 08:44 UTC, aguringo commented on content/articles/products/contents/help-center/review.mdx
> +| 8 | 画像名や画像のaltは適切か | 不適切な画像名になっていないか、altが空になっていないかなど。参考：[本文と代替テキストのガイドライン](./image/#h2-1) |
```suggestion
| 8 | 画像名や画像のaltは適切か | 不適切な画像名になっていないか、altが空になっていないかなど。参考：[本文と代替テキストのガイドライン](../image/#h2-1) |
```

2024-04-10 08:45 UTC, aguringo approved these changes

2024-04-10 08:48 UTC, merged