デザインパターンとStorybookのコードを共通化
kufu/smarthr-design-system pull request #112
Opened 2022-06-09 08:39 UTC by yuw27b

## 課題・背景
https://github.com/kufu/smarthr-design-system-issues/issues/971

## やったこと
1. `SelectCompanyAccount.stories.tsx`に直接コンポーネントのコードを書かず、デザインパターンと共通の`SelectCompanyAccount.tsx`からimportするように変更
    - 末尾の`render(<SelectCompanyAccount />)`があるとStorybookではエラーになるので、このファイルからは`render()`部分を削除
    -  メインのコンポーネントである`const SelectCompanyAccount = ...`がexportされていないので、`export`を追加。
2. 上記の変更で、デザインパターンページのほうが正常に動かなくなるので、`CodeBlock.tsx`も変更する。
    -  `transformCode()`内で、追加した`export`を削除する（`import`を削除するコードと並べてあります）。
    - `renderingComponent`というpropsを追加し、コンポーネントが指定されていたらコードの末尾に`render(<ComponentName />)` を追加するように変更
3. `DesignPatternCodeBlock.tsx`で、上記の`renderingComponent`を指定するように変更。

また、コードを共通化するにあたって、`SelectCompanyAccount`コンポーネントで使われていた`PrimaryButton`コンポーネントが非推奨になっていたので、`Button`+`variabt="primary"`に変更しています（Storybookのコードはそうなっていたので、そちらに合わせたような感じです）。

## やらなかったこと
デザインパターンページのLive editorに表示されるコードでは、`export`の削除はしていないので、`import`同様にエディタ内に表示されています。動作に影響はないかと思いますが、削除したほうが良ければこちらも削除するようにします。
![スクリーンショット 2022-06-09 17 31 28](https://user-images.githubusercontent.com/7822534/172802402-653271f1-62ae-4e4b-9d2c-23937cdbc751.png)

## 動作確認

## キャプチャ
見た目の変更は（上記のコードを除き）ありません。

2022-06-10 01:51 UTC, uknmr requested changes
ありがとうございます!
動作よさそうでした!!

いくつか imo なコメント入れています:pray:

2022-06-10 01:51 UTC, uknmr commented on src/components/article/CodeBlock/CodeBlock.tsx
> +  const code = renderingComponent ? children.trim() + `\nrender(<${renderingComponent} />)` : children.trim()
imo： 意図的でなければテンプレートリテラルの中に入れてしまいたい

```suggestion
  const code = renderingComponent ? `${children.trim()}\nrender(<${renderingComponent} />)` : children.trim()
```

2022-06-10 02:36 UTC, tomof commented on content/articles/products/design-patterns/DesignPatternCodeBlock.tsx
@uknmr 最初、stringにしていたのですが`Components[componentName]`のところで型エラーになってしまったため、このようにしました。型エラーが発生しなければ、自分的にもanyを使わずに型エラーが出ないように出来れば、stringにしたいところなのですが…。

2022-06-10 02:45 UTC, tomof commented on content/articles/products/design-patterns/components/SelectCompanyAccount.tsx
>  import React, { useState } from 'react'
ありがとうございます。この辺りの構成悩ましかったのですよね。

content/articles/products/design-patterns/components/index.ts の対象コンポーネント読み込みパスを調整するだけで大丈夫そうですね。

2022-06-10 02:47 UTC, tomof commented on src/components/article/CodeBlock/CodeBlock.tsx
> +  const code = renderingComponent ? children.trim() + `\nrender(<${renderingComponent} />)` : children.trim()
ここも、https://github.com/kufu/smarthr-design-system/pull/112/files#r894087096 と同様にコメントあると良いかもですね。tsxファイルをStorybookとreact-liveのプレビューとソースコード表示をよしなに両立するための複雑さをこの辺に押し込めているので。

2022-06-10 02:48 UTC, tomof reviewed
@uknmr さんの指摘事項を対応してもらえれば良さそうですー🙆‍♂️

2022-06-10 05:06 UTC, uknmr commented on content/articles/products/design-patterns/DesignPatternCodeBlock.tsx
なるほど!!!

2022-06-10 06:00 UTC, yuw27b commented
@uknmr @tomof レビューありがとうございました！

`componentName`のtype問題以外は反映しています。（←は私も`string`にできないかと思ったんですが、typeエラーになるのでひとまずそのままにしてしまいました。今後、コンポーネント増えるでしょうし、上手いやり方がないか考えますー）

2022-06-10 08:36 UTC, uknmr approved these changes
LGTM :tada:

2022-06-13 00:57 UTC, tomof approved these changes
LGTM！

2022-06-13 00:57 UTC, merged