モーダルなUIの基準
kufu/smarthr-design-system pull request #1126
Opened 2024-04-15 21:03 UTC by drivesketch

一旦文字だけ書いた。これから画像を作成して入れます。

## 課題・背景

## やったこと

-

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-04-17 15:47 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui.mdx
> +モーダルなUIのガイドラインとパターンをまとめています。
タイトル以上の情報がないのでも少し書き下したいな〜

2024-04-18 01:48 UTC, versionfive reviewed
全体的に読みやすく内容も理解しやすかったです！
主に「こういうときにつかうとよい」という主張で書くようなコメントをしています。

ファイル構成ですが、ファイル移動に強い、以下がよいと思います。（ほかも整理したい…）

- /components/modai-ui/
  - index.mdx
  - images/

2024-04-18 01:57 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui.mdx
> +モーダルなUIのガイドラインとパターンをまとめています。
確かに。もうちょっと何か足します。

2024-04-18 01:59 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui.mdx
> +モーダルなUIの主なパターンを挙げます。
箇条書きで目次っぽいのを載せます

2024-04-18 02:09 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui.mdx
> +このため、原則としてはプロダクトの中心的な画面はモードレスであるように設計し、モーダルなUIはそれが特に有効である場面において限定的に提供することが推奨されます。
特に有効である場面的なものがうまく言語化出来なかったんですよねー汗
この後ろに箇条書きで何らか「おすすめの局面」を書く方向を考えます

2024-04-18 02:14 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui.mdx
> +MessageDialogはユーザーの操作に対するフィードバックとして使用できます。ただし、モーダルな操作フィードバックはユーザーの操作を強制的に中断させるため、使用は慎重に検討します。詳しくは操作フィードバック（作成中）を参照してください。
いったん「非推奨」と書きます。操作フィードバックができた際にまた変えるかもしれません。

2024-04-18 02:18 UTC, ouji-miyahara commented on content/articles/products/design-patterns/modal-ui.mdx
> +モーダルなUIのガイドラインとパターンをまとめています。
v5さんが指摘されていた内容と同様で、特に内容がなかったので削ってもよいと思いました。
また、他のページでは「〜〜について定義しています」と記載されているのに、このページだえ「〜〜をまとめています」と違う言い回しになっていることも気になりました

2024-04-18 02:20 UTC, ouji-miyahara commented on content/articles/products/design-patterns/modal-ui.mdx
> +一方で、モーダルなUIには以下のような面でユーザビリティを低下させることがあります。
デメリットの方ばかりが強調されており、ここまで読んで使わないほうが安全なのではという気持ちになりました。
利用する上でのメリットも、デメリットと同じ体裁でフェアに記載したほうが良いと思います。

2024-04-18 02:21 UTC, ouji-miyahara commented on content/articles/products/design-patterns/modal-ui.mdx
> +- タスクの途中で別のタスクをしたくなった際には、「モードから抜け出す」という余計な一手間が必要
> 余計な一手間が必要

モードを抜け出すことは必要があってしていることだと思うので、「余計な〜」とそこまでネガティブに書く必要があるのか疑問になりました

2024-04-18 02:23 UTC, ouji-miyahara commented on content/articles/products/design-patterns/modal-ui.mdx
> +モーダルダイアログの表示中、ダイアログの外側の領域はスクリム（幕）で隠されています。ダイアログを閉じるか、このモードの目的であるタスクを完了するまで、ダイアログ外の操作はできません。
> ダイアログの外側の領域は

ダイアログのメンタルモデルは画面の1枚手前のレイヤーにスクリムとダイアログコンポーネントが来ている演出になっているはずなので、ダイアログの外側ではなく「裏側」や「後ろ」のほうが適切に思いました

2024-04-18 02:25 UTC, ouji-miyahara commented on content/articles/products/design-patterns/modal-ui.mdx
> +
これは一般的なモーダルなUIの話しをしているのか、SmartHR UIのダイアログコンポーネントの話しをしているのかわからなくなりました。

一般的なモーダルなUIの話しをするのであれば、タイトルも「現在のモードのタイトル」といったようにモーダルなUI特有の固有名にしてあげるのが良いかなと思います

2024-04-18 02:28 UTC, ouji-miyahara commented on content/articles/products/design-patterns/modal-ui.mdx
> +モーダルなUIにおいては、「必須の入力要素が空欄になっている」などの理由でタスクを完了する条件が満たされていない場合であっても、原則として**完了ボタンは無効化せず、ユーザーに完了ボタンを押させた上で、エラーを返す**ようにします。
完了ボタンを押したフィードバックとしてエラーメッセージを出してあげるのであれば、完了ボタンの近くにエラーメッセージを出すパターンでないと理解が難しいと思いました。

2024-04-18 02:33 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui.mdx
> +/>
nitsですが、画像にスクロールバーがでているのは意図的…？

2024-04-18 02:36 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui.mdx
> +/>
ミスです！直します！
（前段でモーダルページとの対比をするにあたって入れてました）

2024-04-18 04:43 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui.mdx
> +モーダルなUIにおいては、「必須の入力要素が空欄になっている」などの理由でタスクを完了する条件が満たされていない場合であっても、原則として**完了ボタンは無効化せず、ユーザーに完了ボタンを押させた上で、エラーを返す**ようにします。
ダイアログのエラー表示の基準が固まっていないので、レビュー会に持ち込みます。

2024-04-18 04:44 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui.mdx
> +一方で、モーダルなUIには以下のような面でユーザビリティを低下させることがあります。
メリデメ両方をフラットに記載するのを試みます！

2024-04-18 04:49 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui.mdx
> +ページ全体を使ったモードの場合、[BottomFixedArea](../../components/bottom-fixed-area/)を使用してボタンを配置します。また、タスクを中断して元のページに戻る操作は「キャンセル」ボタンが担うため、[上に戻るリンク](../upward-navigation/)は配置しません。
先に進んでいた「複数ステップ操作」の方がBFAを例にかかれていたので引っ張られてしまっていましたが、そういえばFloatAreaの方が新しいんですよね。BFA以外の例もありうるような書き方に変えます。

2024-04-18 08:44 UTC, o-kwr reviewed
各所大まかに気になったところはouji sanやv5 sanが指摘しているので割愛しますが、全体として良いかと思いました！LGTM

加えて、私の中でもまだうまく言語化はできておらず恐縮なのですが、モーダルなUIの中で特にActionDialogを使うことを推奨する場合はどういうときなのかがあるとだいぶ実用的なページとして活用できるイメージが湧きました！

2024-04-23 04:23 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +[WIP]
hanicaの従業員更新や予約のような、ページ内にPrimaryボタンが置かれているようなパターンは「ページ全体を使ったモード」ともまた別のものとして分類したほうが良いと思ったので、見出しだけ用意してWIPとしました。

2024-04-23 04:24 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +- 長く複雑な一連の操作
このあたりを大幅に書き換えたので見ていただきたいです。

2024-04-23 09:34 UTC, wentzzz approved these changes
全体的にLGTMです！コメントは参考までにみていただければ！

2024-04-23 09:34 UTC, wentzzz commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +MessageDialogはユーザーの操作に対するフィードバックとして使用できます。ただし、モーダルな操作フィードバックはユーザーの操作を強制的に中断させるため、原則として推奨されません。詳しくは操作フィードバック（WIP）を参照してください。
IMO: WIPなのであれば、後から追記でもよさそうな気がしました

2024-04-23 09:34 UTC, wentzzz commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +モードのなかで提供したいUIのレイアウトが、モードレスなUIと近い場合、ページの一部を使ったモードを検討します。
この一文だけだと何のことか分かりづらかったですが、後述の例があったので分かりました。

「モードレスなUIと近い」が距離を指すのか、意匠の類似性を指すのかが少し分かりづらいと思いました。

2024-04-23 09:34 UTC, wentzzz commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +詳しくは複数ステップの操作（WIP）を参照してください。
IMO: 見出しが「複数ステップの操作」であるのに、リンク先が「複数ステップの操作（WIP）」になっているのに違和感があります。こちらもできてから追記でよさそうに思いました。

2024-04-23 09:34 UTC, wentzzz commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +ページ全体を使ったモードの場合、原則的に[BottomFixedArea](/products/components/bottom-fixed-area/)を使用してボタンを配置します。ただし、モードに入らないサイドバーがあるなど、BottomFixedAreaが不適切なときは、[FloatArea](/products/components/float-area/)を使用します。
IMO: ぱっと見で何のことか分かりづらかったので、補足の具体例として[共通設定のアクションビュー](https://smarthr.design/products/design-patterns-core-features/main-admin/#h2-3)を置いてもよさそうに思いました。

2024-04-23 09:34 UTC, wentzzz commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +### アクセシビリティ
IMO: 「アクセシビリティ」自体はエラーに対してのみ言及する概念ではないため、エラー状態の配下に「アクセシビリティ」というタイトルがあることに少し違和感がありました。

2024-04-23 09:34 UTC, wentzzz commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +### 参考文献
```suggestion
## 参考文献
```

IMO: こちらも同様です。おそらくエラーに対してかかっている参考文献だからだと思いますが、全体にもかかっていると思うので見出しレベルを上げてもよさそうです。

2024-04-23 09:34 UTC, wentzzz commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +［WIP］
一言だけでも説明があったほうがよさそうに思いました。

2024-04-24 01:24 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +モードのなかで提供したいUIのレイアウトが、モードレスなUIと近い場合、ページの一部を使ったモードを検討します。
`近い` → `似た` に変更しました。

2024-04-24 02:09 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +MessageDialogはユーザーの操作に対するフィードバックとして使用できます。ただし、モーダルな操作フィードバックはユーザーの操作を強制的に中断させるため、原則として推奨されません。詳しくは操作フィードバック（WIP）を参照してください。
あとから追記します

2024-04-24 02:19 UTC, versionfive reviewed
コメントしましたー

2024-04-24 02:19 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +また、タスクを中断して元のページに戻る操作は［キャンセル］ボタンが担うため、[上に戻るリンク](../upward-navigation/)は配置しません。
```suggestion
また、タスクを中断して元のページに戻る操作は［キャンセル］ボタンが担うため、[上に戻るリンク](/products/design-patterns/upward-navigation/)は配置しません。
```

2024-04-24 02:19 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +import imageUrlDont from './images/modal-ui_actiondialog_accessibility_disabled.png';
[IMO] 直接いれちゃってもいいような？

2024-04-24 02:19 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +モード、モーダル、モードレスの概念と、SmartHRにおけるモーダルなUIのパターンを定義しています。
```suggestion
モード、モーダル、モードレスの概念と、SmartHRプロダクトにおけるモーダルなUIのパターンを定義しています。
```
一応範囲を

2024-04-24 02:19 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +description: 'モード、モーダル、モードレスの概念と、SmartHRにおけるモーダルなUIのパターンを定義しています。'
```suggestion
description: 'モード、モーダル、モードレスの概念と、SmartHRプロダクトにおけるモーダルなUIのパターンを定義しています。'
```

2024-04-24 02:19 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +![ページ全体を使ったモード](./images/modal-ui_fullpage.png)
```suggestion
表示したい情報が多い以下のような場合には、ページ全体を使ったモードを検討します。

- ダイアログのファーストビュー以外にも重要な情報が存在し、気づきづらい場合
- ダイアログにするとスクロール（特に横スクロール）が多く発生する場合

![ページ全体を使ったモード](./images/modal-ui_fullpage.png)
```
同じことを繰り返していったので提案。
また、例にあるUIだと、モーダルダイアログと同じ内容だから差が視覚的にわからなかったです（なやましい）。具体的なケースを持ってきたほうがいいのかもしれません。

2024-04-24 02:29 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +### 複数ステップの操作
たしかに。複数ステップ操作の方のページ書いたらそこと合わせて調整します。

2024-04-24 02:30 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +### 複数ステップの操作
いったん「ステップを複数に分けたモード」でいってみる

2024-04-24 02:33 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +![ページ全体を使ったモード](./images/modal-ui_fullpage.png)
提案ありがとうございます。適用しました！

あと、ダイアログの方の内容を削り、スクロールなしにしてみます。

2024-04-24 02:34 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +- [複数ステップの操作](#h3-5)
説明足して、目次にも入れます

2024-04-24 02:41 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +order: 10
定例で話そうと思ってたんですが、順序は基準がある程度出揃ったタイミングで一気にいじるのがよさそうに思いました

2024-04-24 02:41 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +import imageUrlDont from './images/modal-ui_actiondialog_accessibility_disabled.png';
直接入れる方法が分からんかった… :sob:

2024-04-24 03:14 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +### アクセシビリティ
この案いただきます

2024-04-24 10:12 UTC, versionfive reviewed
細かいところをコメントしました。
恒常的なモードについてはslackで

2024-04-24 10:12 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +ページ全体を使ったモードの場合、原則的に[BottomFixedArea](/products/components/bottom-fixed-area/)を使用してボタンを配置します。ただし、モードに入らないサイドバーがあるなど、BottomFixedAreaが不適切なときは、[FloatArea](/products/components/float-area/)を使用します（例：[共通設定
```suggestion
ページ全体を使ったモードの場合、基本的に[BottomFixedArea](/products/components/bottom-fixed-area/)を使用してボタンを配置します。ただし、モードに入らないサイドバーがあるなど、BottomFixedAreaが不適切なときは、[FloatArea](/products/components/float-area/)を使用します（例：[共通設定のアクションビュー](/products/design-patterns-core-features/main-admin/)）。
```
BottomFixedAreaの採用は原則、ほどではない気がする（FloatAreaの採用も十分検討できるとおもう）
ちなみに「モードに入らないサイドバーがある」は部分的なモードとは違うんですかね？

2024-04-24 10:12 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +また、タスクを中断して元のページに戻る操作は［キャンセル］ボタンが担うため、原則として[上に戻るリンク](/products/design-patterns/upward-navigation/)は配置しません。
若干唐突感を感じました。配置的にはタイトル付近にあるものだからそちらに書くとよいかも

この節が結構雑多に書いてある印象ありますね。一部表とかで表現できるかも？

2024-04-24 10:12 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +- どの入力要素が、どんな理由で完了条件を満たしていないのかが伝わりにくい
Do&Don'tsより上に書いてあってほしいみ

2024-04-25 00:17 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +- オブジェクトの追加・編集
削除については「破壊的な処理を実行する前の確認」の方で言及してます。削除ダイアログにリンクするのはたしかにそうですね。修正します。

2024-05-02 05:21 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +ページ全体を使ったモードの場合、原則的に[BottomFixedArea](/products/components/bottom-fixed-area/)を使用してボタンを配置します。ただし、モードに入らないサイドバーがあるなど、BottomFixedAreaが不適切なときは、[FloatArea](/products/components/float-area/)を使用します（例：[共通設定
> 「モードに入らないサイドバーがある」は部分的なモードとは違うんですかね？

これは書いてて悩んだんですが、ヘッダーも含めナビゲーションは除外して、全画面扱いに分類しました。でも結果的には同じことにはなります。

2024-05-02 05:21 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +MessageDialogはユーザーの操作に対するフィードバックとして使用できます。ただし、モーダルな操作フィードバックはユーザーの操作を強制的に中断させるため、原則として推奨されません。
`明確な理由がない限り推奨されません。` にします

2024-05-02 05:48 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +- どの入力要素が、どんな理由で完了条件を満たしていないのかが伝わりにくい
順序入れ替えました！

2024-05-02 05:53 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +ページ全体を使ったモードの場合、原則的に[BottomFixedArea](/products/components/bottom-fixed-area/)を使用してボタンを配置します。ただし、モードに入らないサイドバーがあるなど、BottomFixedAreaが不適切なときは、[FloatArea](/products/components/float-area/)を使用します（例：[共通設定
ナビゲーション以外の箇所、たとえばコレクションの画面タイトルとかがある状態で並べ替えモードに入る、みたいなのを部分モードの典型例と捉えてます

2024-05-02 05:54 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +また、タスクを中断して元のページに戻る操作は［キャンセル］ボタンが担うため、原則として[上に戻るリンク](/products/design-patterns/upward-navigation/)は配置しません。
テーブル案もいまいちハマるのに出会えなかったので、小見出しで区切ってお茶を濁しました

2024-05-09 05:32 UTC, versionfive reviewed
あらためて全体をみてコメントしました

2024-05-09 05:32 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +  label="必須項目が空欄のまま完了ボタンを押すとエラーが返り、どの項目にどんな問題があるかが示される。"
[Comment] エラー状態の整理によってはUIのパターンが変わるかも

2024-05-09 05:32 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +また、タスクを中断して元のページに戻る操作は［キャンセル］ボタンが担います。そのため、基本的に[上に戻るリンク](/products/design-patterns/upward-navigation/)は配置しません。
[IMO] 結構大きな変更がしれっと書いてあるので、画像とかで示せるといいのかな。

2024-05-09 05:32 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +基本的に[BottomFixedArea](/products/components/bottom-fixed-area/)を使用してボタンを配置します。ただし、モードに入らないサイドバーがあるなど、BottomFixedAreaが不適切なときは、[FloatArea](/products/components/float-area/)を使用します（例：[共通設定のアクションビュー](/prod
「不適切」な判断基準がほしいな、と思いました。
画面全体を覆うべきではないとか、BottomFixedAreaだと圧迫感がある（言語化できてない…）とか…？

2024-05-09 05:32 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +タスクを中断するアクションのボタンラベルは［キャンセル］とします。
```suggestion
- タスクを完了してモードを終えるアクション
  - タスクを完了するアクションは[Primaryボタン](/products/components/button/#h3-1)を使います。
  - [削除ダイアログ](/products/design-patterns/delete-dialog/)など、危険なアクションの完了には[Dangerボタン](/products/components/button/#h3-3)を使います。
  - ボタンのラベルは、モードの目的であるタスクを完了するアクションであることがわかる動詞を用います。
- タスクを中断してモードから抜け出すアクション
  - タスクを中断するアクションのボタンラベルは［キャンセル］とします。
```
- 1, 2に依存することが並んでかいてあってので箇条書きにした
- Dangerボタンも使いうるので追記した
- Primaryボタンのリンクが誤ってたので直した

2024-05-09 05:32 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +モードレスなUIとしてダイアログを提供する場合は、[ModelessDialog](/products/components/dialog/#h3-3)を使用します。
```suggestion
なお、**モードレスなUI**としてダイアログを提供する場合は、[ModelessDialog](/products/components/dialog/#h3-3)を使用します。
```
[IMO] 文脈が異なるので接続詞をつけ、目がすべらないように強調してみました。

2024-05-09 05:32 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +### 参考文献
```suggestion
## 参考文献
```

2024-05-09 05:32 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +- 長く複雑な一連の操作
```suggestion
### モーダルなUIの使いどころ

SmartHRでは、プロダクトの中心的な画面はモードレスであるように設計しつつ、モードの提供が適切である場面ではモーダルなUIを使用しています。

モードの提供を検討する場面として、以下が挙げられます。

- オブジェクトの追加・編集
- オブジェクトの並べ替え
- データの取り込み・書き出し
- 破壊的な処理を実行する前の確認（[削除ダイアログ](/products/design-patterns/delete-dialog/)を参照）
- 長く複雑な一連の操作

一般的に、UIはなるべくモードレスであるように設計することが推奨されています。これは、モーダルなUIでは機能の全体像がわかりにくく、またユーザーが自由な手順で操作できないといった欠点があるためです。

一方で、特にSmartHRのような業務アプリケーションでは、あるデータの変更が広い範囲に影響を及ぼすことがあるため、ユーザーが操作をするたびに処理がモードレスに実行されるのは必ずしも望ましくありません。また、頻度が低いタスクや複雑な操作が必要なタスクの場合、手順を固定するなどして、ユーザーの操作の自由度を下げてでも安全性を高めることを優先することがあります。
```
[IMO] 最後までよまないと使いどころが把握できないので、先に使いどころを示してから説明するスタイルを提案してみます。

2024-05-09 05:55 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +  label="必須項目が空欄のまま完了ボタンを押すとエラーが返り、どの項目にどんな問題があるかが示される。"
これは承知してます！

2024-05-09 06:35 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +- 長く複雑な一連の操作
これ良いです！

2024-05-09 06:56 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +### 参考文献
ここは`## エラー状態のアクセシビリティ` にかかる参考文献なのでh3のママで

2024-05-09 07:24 UTC, versionfive commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +### 参考文献
テンプレでは最後にh2でまとめて出すように想定していました！（書くセクションにつくると、参考情報が最悪バラけてしまうため）
https://smarthr.design/operational-guideline/page-template/component-template/#h2-9

2024-05-10 01:35 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +### 参考文献
あーなるほど理解しました
今後他にも参考文献が出てきたときに、セクションごとに参考文献が分かれないほうがいいですね

2024-05-10 01:38 UTC, tosiiu reviewed
コメント2点しました！

2024-05-10 01:38 UTC, tosiiu commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +MessageDialogはユーザーの操作に対するフィードバックとして使用できます。ただし、モーダルな操作フィードバックはユーザーの操作を強制的に中断させるため、明確な理由がない限り推奨されません。
MessageDialogはユーザーの操作に対するフィードバックには不適切だと考えているので、あえてここでは記載しないか、もっと強い非推奨として書きたいと思いました（推奨されませんとあるものの、使用できますと書いてあるので弱い非推奨に見える）

また、個人的にはむしろ単に地のページ以上の情報をその場で一時的に表示する使い方の基準がほしいと思いました！

2024-05-10 07:30 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +MessageDialogはユーザーの操作に対するフィードバックとして使用できます。ただし、モーダルな操作フィードバックはユーザーの操作を強制的に中断させるため、明確な理由がない限り推奨されません。
> もっと強い非推奨として書きたい

理解しました。「こういう理由で操作フィードバックに使うのは非推奨です。NBとかを使ってください」という表記に変えます。事例画像も消します。

> 単に地のページ以上の情報をその場で一時的に表示する使い方（例：組織図の従業員詳細）

ありがとうございます。基準まで書けるか分かりませんが、言及を試みます。

2024-05-15 06:43 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +基本的に[BottomFixedArea](/products/components/bottom-fixed-area/)を使用してボタンを配置します。ただし、モードに入らないサイドバーがあるなど、BottomFixedAreaが不適切なときは、[FloatArea](/products/components/float-area/)を使用します（例：[共通設定のアクションビュー](/prod
BottomFixedAreaとFloatAreaのコンポーネント説明ページの方に書いて、こっちはあとから調整します。

2024-05-16 05:28 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +また、タスクを中断して元のページに戻る操作は［キャンセル］ボタンが担います。そのため、基本的に[上に戻るリンク](/products/design-patterns/upward-navigation/)は配置しません。
Don'tの画像を入れます

2024-05-16 05:47 UTC, drivesketch commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +MessageDialogはユーザーの操作に対するフィードバックとして使用できます。ただし、モーダルな操作フィードバックはユーザーの操作を強制的に中断させるため、明確な理由がない限り推奨されません。
ダイアログの方に書くことにしました

2024-05-17 01:33 UTC, tosiiu approved these changes
LGTM!

2024-05-17 02:10 UTC, versionfive submitted a review, later dismissed
LGTMです！！！！

2024-05-17 09:10 UTC, MasafumiKabe requested changes
一点だけ修正お願いします！その他はよさそう！

2024-05-17 09:10 UTC, MasafumiKabe commented on content/articles/products/design-patterns/modal-ui/index.mdx
> +- [複数ステップの操作](#h3-5)
実際の見出しと揃えたほうが良さそうです！（ほかが揃っているので尚更）
```suggestion
- [ステップを複数に分けたモード](#h3-5)
```

2024-05-20 05:02 UTC, MasafumiKabe approved these changes
LGTM! :arigatau:

2024-05-20 05:15 UTC, versionfive approved these changes

2024-05-20 05:16 UTC, drivesketch commented
@tosiiu 文言修正したのでノールックで再度approveいただけますと 🙏

2024-05-20 05:22 UTC, tosiiu approved these changes

2024-05-20 05:26 UTC, merged