StatusLabel no
kufu/smarthr-design-system pull request #1131
Opened 2024-04-17 02:55 UTC by oti

… を追加した

## 課題・背景

## やったこと

-

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-04-17 02:59 UTC, versionfive requested changes
テンプレートにある見出しの順序になるようにお願いしたいです〜
https://smarthr.design/operational-guideline/page-template/component-template/

2024-04-17 03:05 UTC, oti commented
@versionfive 見出し順を修正しました:bow:

2024-04-17 03:06 UTC, uknmr approved these changes
LGTM~

2024-04-17 07:53 UTC, versionfive approved these changes
LGTM!!

基準充足かの判断は @tosiiu さんにお任せします :pray:

2024-04-18 05:31 UTC, oremega approved these changes
LGTM

2024-04-22 09:34 UTC, tosiiu approved these changes
LGTMです！迷わず使えそうに思いました！
（種類（bold, type）の細かい判断は引き続き各プロダクトで行われそうですが厳密な基準化が難しい認識）

2024-04-22 09:35 UTC, merged