SegmentedControlの概要と使用上の注意を追加
kufu/smarthr-design-system pull request #1141
Opened 2024-04-22 08:27 UTC by o-kwr

## 課題・背景

基準充足！

## やったこと
- SegmentedControlの概要とどんなときに使うべきかを追加した

## やらなかったこと
- 

## 動作確認
Previewから確認お願いします！

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-04-22 08:48 UTC, versionfive reviewed
コメントしました！

2024-04-22 08:48 UTC, versionfive commented on content/articles/products/components/segmented-control.mdx
> +振る舞いとしては[RadioButton](/products/components/radio-button/)と同義とも言えますが、選択（状態の切り替え）によってビューに対して影響が発生することが特徴です。
概要文が大きく、読み切る必要があるので、この一文はRadioButtonとの使い分けになると思うので、使用上の注意に項目をつくってもよいのではと思いました。

2024-04-22 08:48 UTC, versionfive commented on content/articles/products/components/segmented-control.mdx
> +異なる状態の切り替えによって、扱うオブジェクトごとビューの関心が変わる場合はSegmentedControlではなく[TabBar](/products/components/tab-bar/)を用いるようにしてください。
このドキュメントはSegmentedControlの使い方を示すページなので、「こういうときに用いる」というスタンスで書けるならより適当かと思いました。

誤った使い方が多いから「このときは使わないで」を示す使い方もあると思いますが、SegmentedControlとTabBarに関しては「どっちを使うとよい？」という迷いが目立っている印象です。

2024-04-22 09:08 UTC, oti reviewed
SegmentControl を使うにふさわしい、同じオブジェクトの状態を切り替えるために用いることがスッとわかる具体例が欲しいと思いました！

2024-04-22 10:15 UTC, tosiiu reviewed
既出のコメントと同じく、近しいコンポーネントとの使い分けが迷うポイントだと思うので独立した章として[Switch](https://smarthr.design/products/components/switch/#h2-0)のように記載されているといいなと思いました！

2024-04-23 03:26 UTC, MasafumiKabe reviewed
既出のコメントと同じお気持ちです！
類似のコンポーネントとの違いなどについて割と序盤から言及しているので、まずは SegmentedContorol 単品について簡単に説明できていると良いと思いました！

2024-04-23 07:29 UTC, uknmr commented on content/articles/products/components/segmented-control.mdx
> +異なる状態の切り替えによって、扱うオブジェクトごとビューの関心が変わる場合はSegmentedControlではなく[TabBar](/products/components/tab-bar/)を用いるようにしてください。
SegmentedControl も TabBar も、なんだったら SideNav などをも包括したパターンの可能性もある?

2024-05-20 08:43 UTC, oti requested changes
いくつかコメントしました！

2024-05-20 08:43 UTC, oti commented on content/articles/products/components/segmented-control.mdx
> +
```suggestion
```tsx editable codeBlock
<SegmentedControl size="s" options={[
  { value: 'list view', content: 'リスト表示' },
  { value: 'map view', content: 'マップ表示' },
]} value="list view" />
```
```

ここに具体例を書くのはだめですか？

2024-05-20 08:43 UTC, oti commented on content/articles/products/components/segmented-control.mdx
> +Switchはオン・オフのどちらか1つの状態を表します。対する概念ではあるが、異なる状態を表す場合はSegmentedControlを使ってください。
このページの主体はSegmentedControlなので主従が逆だと思いました。

e.g）SegmentedControlは〜〜です。〜〜の場合はSwitchを使用してください。

2024-05-20 08:43 UTC, oti commented on content/articles/products/components/segmented-control.mdx
> +振る舞いとしては[RadioButton](/products/components/radio-button/)と同義とも言えますが、選択（状態の切り替え）によって即座にビューに対して影響が発生することが特徴です。絞り込み時にsubmitが発生する場合はRadioButtonの使用も検討してみてください。
うまく説明できているように感じなかったのと、「絞り込み時に」という言葉が急に出てきたのが引っかかりました。SegmentedControl か Tab か Switch か RadioButton かという話のなかに、絞り込みという認識はないように思います。言いたいことは「表示切替時に〜」なのかな？

2024-05-20 09:03 UTC, versionfive commented on content/articles/products/components/segmented-control.mdx
> +
ComponentStoryがそれを担っている認識

2024-05-20 09:25 UTC, versionfive reviewed
前提の確認をSlackでしておりますー

2024-05-20 09:25 UTC, versionfive commented on content/articles/products/components/segmented-control.mdx
> +ビューに対してフィルタリングしたり見え方を変えたいときに[TabBar](/products/components/tab-bar/)も用いることができますが、TabBarの場合はそれぞれのタブに内包されるオブジェクト自体が異なる場合に使うことが適しています。
```suggestion
ビューに対してフィルタリングしたり見え方を変えたいときに[TabBar](/products/components/tab-bar/)を使う場合がありますが、TabBarはそれぞれのタブに内包されるオブジェクト自体が異なる場合に使うことが適しています。

一方、SegmentedControlはそれぞれのセグメントに内包されるオブジェクトが同一である場合に使うことが適しています。
```
書きっぷりはこれでいいのかわかりませんが、SegmentedControlはどうだ、も書いてほしいです。

2024-05-21 02:02 UTC, tosiiu reviewed
切り替えの対象として「状態・フィルタリング・モード・見た目」が挙げられていますが、フィルタリングやモードの変化が何を示すのか明確に分かりませんでした...！何かしら説明があるとより分かりやすいと感じました

2024-06-07 08:39 UTC, o-kwr commented on content/articles/products/components/segmented-control.mdx
> +
おっしゃっている通りComponentStoryで示しているのでこれ以上は不要かなと思っています！

2024-06-07 10:44 UTC, versionfive requested changes
操作後の印象として、「オブジェクトが絞り込まれる（全体から一部が表示される）」というより「オブジェクトの一部が表示されたビューに切り替わる」ような結果になる気がしてきました。

また、mdxヘッダーのdescriptionが空なので埋めるようにお願いします。

2024-06-07 10:44 UTC, versionfive commented on content/articles/products/components/segmented-control.mdx
> +ビューに対してオブジェクトを絞り込んだり、見え方を変えたいときに[TabBar](/products/components/tab-bar/)も用いることができますが、SegmentedControlではTabBarと異なり、ビューに存在するオブジェクト自体を変更する場合には適していません。
```suggestion
SegmentedControlは、ビューに存在するオブジェクト自体を切り替える場合には適していません。

オブジェクト自体を切り替えて表示する場合は、[TabBar](/products/components/tab-bar/)を使用してください。
```
はじめにSegmentedControlは何に適しているのか、を先に知りたいと思いました。

2024-06-07 10:44 UTC, versionfive commented on content/articles/products/components/segmented-control.mdx
> +振る舞いとしては[RadioButton](/products/components/radio-button/)と同義とも言えますが、選択（状態の切り替え）によって即座にビューに対して影響が発生することが特徴です。表示切替時にsubmitが発生する場合はRadioButtonの使用も検討してみてください。
```suggestion
「複数の選択肢から1つを選ぶ」という振る舞いは[RadioButton](/products/components/radio-button/)と似ていますが、SegmentedControlは操作すると即座にビューに対して影響が発生することが特徴です。

選択操作後に「送信」や「保存」といった`submit`が発生する場合は、RadioButtonを使用してください。
```

https://github.com/kufu/smarthr-design-system/pull/1168 の書き方に合わせると良さそうです。

RadioButtonより：
```
#### ビューの切り替えを操作するUIとして使用しない

入力後に「送信」や「保存」といったtype属性が`submit`のボタンによって入力確定するフォーム画面などで使用してください。  
ラジオボタンは1クリックで選択肢ごとに異なる結果となるため、誤入力によって意図しない結果が反映されてしまう可能性あります。

コレクションなどでオブジェクトの表示方法を切り替える場合や、表示領域上`submit`のボタンの配置が難しい場合など、即時反映を前提とする箇所では[TabBar](/products/components/tab-bar/)や[SegmentedControl](/products/components/segmented-control/)、または[Switch](/products/components/switch/)を使用してください。
```

2024-06-07 10:44 UTC, versionfive commented on content/articles/products/components/segmented-control.mdx
> +2つ以上の異なる状態を切り替えるためのコンポーネントです。状態を切り替えることによって影響下のビューに対して作用し、主にオブジェクトを絞り込んだりビューの見え方を変化させます。
```suggestion
2つ以上の異なる状態を切り替えるためのコンポーネントです。主に影響下のビューの見え方を変えたり、オブジェクトの一部が表示されているビューに切り替えるために使います。
```
「2つ以上の異なる状態を切り替える」ことのなかに「オブジェクトを絞り込む」ことが入るイメージが繋がりませんでした。

こねくり回してしまった感があるのですが、一応提案を…

2024-06-10 01:44 UTC, tosiiu reviewed
v5-sanのコメントに同意です。
「ビューの切り替え」に、レイアウトの変更も表示項目の変更（絞り込み）も含まれていると解釈して整理しても良さそうと思いました。

2024-06-10 07:43 UTC, oti submitted a review, later dismissed
LGTM!

2024-06-10 07:51 UTC, tosiiu reviewed
一点コメントしましたが、大枠LGTMです！

2024-06-10 07:51 UTC, tosiiu commented on content/articles/products/components/segmented-control.mdx
> +2つ以上の異なる状態を切り替えるためのコンポーネントです。主に影響下のビューの見え方を変えたり、オブジェクトの一部が表示されたビューに切り替えるために使います。
```suggestion
2つ以上の異なる状態を切り替えるためのコンポーネントです。主にコレクションビュー/シングルビューのレイアウトや表示項目を切り替えるために使います。
```

これがベストかは分からないですが、対象とその変化をより明確に指し示すことが出来そうに思いました！

2024-06-10 07:58 UTC, MasafumiKabe submitted a review, later dismissed
yosasou~

2024-06-10 08:30 UTC, uknmr approved these changes
LGTM~
（「使用してください」と「使ってください」が揺れてるのはちょっと気になりました）

2024-06-10 08:30 UTC, uknmr commented on content/articles/products/components/segmented-control.mdx
> +</TabBar>
不要そう・名前不適切そう。

```suggestion
<TabBar>
    <TabItem id="object-1" selected>
    書類
    </TabItem>
    <TabItem id="object-2">
    承認経路
    </TabItem>
    <TabItem id="object-3">
    承認履歴
    </TabItem>
</TabBar>
```

2024-06-10 09:09 UTC, ytysym submitted a review, later dismissed
よさそうでした！

2024-06-10 10:19 UTC, versionfive commented on content/articles/products/components/segmented-control.mdx
> +</TabBar>
たしかに、TabBarのページではないので、ここになくてもよさそう

2024-06-14 06:24 UTC, tosiiu commented on content/articles/products/components/segmented-control.mdx
> +2つ以上の異なる状態を切り替えるためのコンポーネントです。主に影響下のビューの見え方を変えたり、オブジェクトの一部が表示されたビューに切り替えるために使います。
[#1141](https://github.com/kufu/smarthr-design-system/pull/1141)で分かりやすいニュアンスになっていたのでクローズします

2024-06-14 06:24 UTC, tosiiu approved these changes
LGTM!

2024-06-14 06:30 UTC, oti requested changes
解説全体的に良くなったと思います！

見出しを「どういうときに使う/使わない」側の表現に揃えてみました。2つずつ提案しています。

2024-06-14 06:30 UTC, oti commented on content/articles/products/components/segmented-control.mdx
> +### TabBar との違い
```suggestion
### オブジェクト自体を切り替える場合には使用しない
```

```suggestion
### オブジェクト自体を切り替える場合はTabBarを使用する
```

2024-06-14 06:30 UTC, oti commented on content/articles/products/components/segmented-control.mdx
> +### Switch との違い
```suggestion
### オン・オフを切り替える場合には使用しない
```

```suggestion
### オン・オフを切り替える場合にはSwitchを使用する
```

2024-06-14 06:30 UTC, oti commented on content/articles/products/components/segmented-control.mdx
> +### RadioButton との違い
```suggestion
### Submitが発生する操作の選択項目には使用しない
```

```suggestion
### Submitが発生する操作の選択項目にはRadioButtonを使用する
```

2024-06-14 06:30 UTC, oti commented on content/articles/products/components/segmented-control.mdx
> +SegmentedControlは異なる状態を切り替えるためのコンポーネントですが、オン・オフのどちらか1つの状態を表して切り替えるときは[Switch](/products/components/switch/)を使ってください。
```suggestion
SegmentedControlは異なる状態を切り替えるためのコンポーネントですが、オンとオフの2つの状態を切り替えるときは[Switch](/products/components/switch/)を使ってください。
```
[nits]なんとなく冗長に感じましたが、元のままでも良い気はしました。

2024-06-14 06:30 UTC, oti commented on content/articles/products/components/segmented-control.mdx
> +選択操作後に「送信」や「保存」といった`submit`が発生する場合は、RadioButtonを使ってください。
```suggestion
選択操作後に「送信」や「保存」といったSubmitが発生する場合は、RadioButtonを使ってください。
```
[IMO] ここでいうsubmitはコードではなく処理の名称なので、code にしなくてもよさそうに感じました。ｲﾓです。

2024-06-14 06:38 UTC, versionfive reviewed
使用上の注意の見出しについてはoti sanのコメントを反映後に確認しますが、さきに細かい点だけコメントしました

2024-06-14 06:38 UTC, versionfive commented on content/articles/products/components/segmented-control.mdx
> +選択操作後に「送信」や「保存」といった`submit`が発生する場合は、RadioButtonを使ってください。
```suggestion
選択操作後に、`送信`や`保存`といったtype属性が`submit`のボタンなどを押すことで入力内容を適用したい場合は、RadioButtonを使ってください。
```
https://github.com/kufu/smarthr-design-system/pull/1168 で検討されている表記とあわせてみました。

2024-06-14 09:08 UTC, ytysym approved these changes
otiさん、v5さんのコメントの部分が修正される前提で、ほかは気になるところなかったのでLGTMです！

2024-06-18 04:09 UTC, oti approved these changes
LGTM!

2024-06-18 04:18 UTC, MasafumiKabe approved these changes
改めて LGTM!

2024-06-18 04:37 UTC, versionfive approved these changes
LGTM!

2024-06-18 04:39 UTC, merged