InformationPanelに使用上の注意を追加する
kufu/smarthr-design-system pull request #1145
Opened 2024-04-23 07:56 UTC by oti

## 課題・背景

https://smarthr.atlassian.net/browse/SD-639

## やったこと
- `使用上の注意`セクションを追加
  - `短い一文で説明できるものに使用しない`セクションを追加
  - `重要な情報には開閉ボタンを表示しない`セクションを追加
  - `Baseのなかに直接配置しない`セクションを追加

https://deploy-preview-1145--smarthr-design-system.netlify.app/products/components/information-panel

見出しと内容のセットで使うことを強調し、短い一文にはResponseMessageとInformationPanelの使用を促す内容にしました。

頻出パターンとして議論に挙がっていた[削除ダイアログの注意事項](https://smarthr.design/products/design-patterns/delete-dialog/#h3-4)は、InformationPanelに機能追加してlayer,bgColor,roundedを受け取れるようにするアイデアもありましたが、実装が込み入っていそうだったので、一旦BaseColumnをつかったソリューションをcodeBlockで提示するにとどめました。

## やらなかったこと
- 

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-06-11 10:58 UTC, oti commented
[フィードバックがマージ寸前になった](https://github.com/kufu/smarthr-design-system/pull/1158)のでInformationPanelを加筆修正しました！

2024-06-11 11:08 UTC, versionfive reviewed
ひとまず書いてある使用上の注意についてコメントしました。
これで利用方法にこまらないか（充足するか）は @tosiiu にmm

2024-06-11 11:08 UTC, versionfive commented on content/articles/products/components/information-panel.mdx
> +フィードバックの内容が多いときや、常に表示しておく必要があるときはInformationPanelの使用を推奨します。
どのようなときに使うべきかがきになるので、「使用しない」よりも「使用する」方でタイトルがあるとよいなと思いました。

2024-06-11 11:08 UTC, versionfive commented on content/articles/products/components/information-panel.mdx
> +InformationPanelの[レイヤー順序](/products/design-tokens/z-index/#h2-1)は3です。レイヤー順序が2以下の要素の中、特に[Base](/products/components/base/)にInformationPanelを配置しないでください。
このときは何を推奨するのか気になりました。

NotificationBarとか、ResponseMessage on BaseColumnとかですかね？

2024-06-11 11:08 UTC, versionfive commented on content/articles/products/components/information-panel.mdx
> +どちらか一方だけの表示に使用しないでください。Baseと似たデザインでただ目立たせるためのような使い方は推奨しません。
タイトルのみの場合はNotificationBar[base="base"]でしょうか。

2024-06-11 11:47 UTC, oti commented on content/articles/products/components/information-panel.mdx
> +どちらか一方だけの表示に使用しないでください。Baseと似たデザインでただ目立たせるためのような使い方は推奨しません。
タイトルのみというのは有り得るのでしょうか？　内容のみなら `NotificationBar[base="base"]`でよさそうです。

2024-06-11 12:13 UTC, oti commented on content/articles/products/components/information-panel.mdx
> +Baseのなかで目立たせたい場合は、[BaseColumn](/products/components/base/base-column/)を使用すると良いでしょう。
@versionfive BaseColumn についての解説を追加しました。

2024-06-11 12:15 UTC, oti commented on content/articles/products/components/information-panel.mdx
> +
@versionfive 見出しを「〜使用する」の形に統一して解説を加筆修正しました。

前にあった「常に表示しておく必要が〜」は、InformationPanel だけの役割ではなく、NotificationBar や ResponsiveMessage でもできる（その他なんででもできる）ので文章丸ごとオミットしました。

2024-06-12 02:27 UTC, versionfive commented on content/articles/products/components/information-panel.mdx
> +Baseのなかで目立たせたい場合は、[BaseColumn](/products/components/base/base-column/)を使用すると良いでしょう。
イメージとしてはこういうUI（4️⃣）を想定していました。

![image](https://github.com/kufu/smarthr-design-system/assets/64398878/c2b50ac2-1c4e-46a4-a0f1-a7c98194376c)

結構毎回これをレイアウトするのもアレなので、`InformationPanel[base="BaseColumn"]`とかできると便利なのかな〜

2024-06-12 02:28 UTC, versionfive commented on content/articles/products/components/information-panel.mdx
> +
@oti 結果的に似たような注意事項が順不同に並んでいる感じなったのでちょっと整理したみありませんか…？

>- タイトルと内容のセットで使用する
>- 表示する内容が多い場合は開閉ボタンの表示を検討する
>- レイヤー順序に注意して配置する
>- 内容の多いフィードバック表示に使用する

2024-06-13 01:56 UTC, versionfive commented on content/articles/products/components/information-panel.mdx
> +どちらか一方だけの表示に使用しないでください。Baseと似たデザインでただ目立たせるためのような使い方は推奨しません。
すみません、「内容」ですね :+1:

2024-06-13 01:57 UTC, versionfive commented on content/articles/products/components/information-panel.mdx
> +Baseのなかで目立たせたい場合は、[BaseColumn](/products/components/base/base-column/)を使用すると良いでしょう。
>[BaseColumn](/products/components/base/base-column/)を使用すると良い

これだけだとちょっと判断しにくいかも、と思ったりしました。 @tosiiu

2024-06-13 01:57 UTC, versionfive requested changes
こちらの件で使用上の注意が散漫になっているので、整理してほしいです。
https://github.com/kufu/smarthr-design-system/pull/1145#discussion_r1635729664

2024-06-14 12:56 UTC, tosiiu commented on content/articles/products/components/information-panel.mdx
> +Baseのなかで目立たせたい場合は、[BaseColumn](/products/components/base/base-column/)を使用すると良いでしょう。
この流れを知っているので何となく伝えたいことは理解できますが、いきなり読むとBaseColumnの利用イメージは分からないなと私も思いました。

コンポーネント化してしまうか、一旦作例を示すかがあるとイメージ付くと思いました〜

2024-06-14 12:59 UTC, tosiiu commented on content/articles/products/components/information-panel.mdx
> +タイトルがないものや、「処理に成功しました」「処理に失敗しました」程度の短い文言をフィードバック表示する場合は、[ResponsiveMessage](/products/components/responsive-message/)や[NotificationBar[bold]](/products/components/notification-bar/)の使用を検討してください。
タイトルがある/ないというより、1~2文の短い文言で表現しきれるかが使い分けのポイントとして実際の思考に近いように個人的には思いました。

2024-06-14 12:59 UTC, tosiiu commented on content/articles/products/components/information-panel.mdx
> +どちらか一方だけの表示に使用しないでください。内容だけの場合は[NotificationBar[base="base"]](/products/components/notification-bar/)の検討してください。
タイトルがある/ないというより、1~2文の短い文言で表現しきれるかが使い分けのポイントとして実際の思考に近いように個人的には思いました。（hogeに失敗しました。fugaしてください。という感じでタイトル/内容の関係に近くても文が短ければNotificationBarを使う認識）

2024-06-18 15:01 UTC, oti commented on content/articles/products/components/information-panel.mdx
> +詳しい使い分けは[フィードバック - 同期的な処理が完了したとき](/products/design-patterns/feedback/#h3-6)を参照してください。
InformationPanel / ResponseMessage との使い分けはややざっくりとした説明にして、詳しい解説はフィードバックの基準にまかせている形にしました。

2024-06-18 15:03 UTC, oti commented on content/articles/products/components/information-panel.mdx
> +基本的に開閉ボタンを表示できるのは、閉じて隠されても操作に問題のない補足的な内容や、全文表示すると操作の妨げになるほど長大な内容のときのみです。
開閉ボタンは表示しないケースを主軸に、例外として表示するケースを解説する形にしました。

2024-06-18 15:05 UTC, oti commented on content/articles/products/components/information-panel.mdx
> +
頻出パターンとして議論に挙がっていた[削除ダイアログの注意事項](https://smarthr.design/products/design-patterns/delete-dialog/#h3-4)は、InformationPanelに機能追加してlayer,bgColor,roundedを受け取れるようにするアイデアもありましたが、コンポーネントの実装が込み入っていて速度ある対応が難しかったです。

なので、一旦BaseColumnをつかったソリューションをcodeBlockで提示するにとどめました。

2024-06-18 15:06 UTC, oti commented
@versionfive @tosiiu 構成を見直して本文も書き直しました！ 確認お願いいたします〜！

2024-06-19 01:57 UTC, versionfive reviewed
コメントしましたー

2024-06-19 01:57 UTC, versionfive commented on content/articles/products/components/information-panel.mdx
> +見出しと内容を必ずセットにして使用してください。また、見出しには必ずアイコンを表示します。
InformationPanelを使えばアイコンは必ずつくはずなので、この書きっぷりだと使う側がなにかしないといけないかと思うかも。

2024-06-19 01:57 UTC, versionfive commented on content/articles/products/components/information-panel.mdx
> +基本的に開閉ボタンを表示できるのは、閉じて隠されても操作に問題のない補足的な内容や、全文表示すると操作の妨げになるほど長大な内容のときのみです。
```suggestion
閉じて隠されても操作に問題のない内容や、全文表示したままだと操作の妨げになるほど長大な内容の場合には開閉ボタンを表示しましょう。
```
「選択肢として閉じれるようにもできるよ」程度の意図に調整してみました。

2024-06-19 01:57 UTC, versionfive commented on content/articles/products/components/information-panel.mdx
> +          </CheckBox>
```suggestion
```
実態としてこのようなパターンはないはず。
参考：https://deploy-preview-1145--smarthr-design-system.netlify.app/products/components/check-box/#h3-2

2024-06-19 01:57 UTC, versionfive commented on content/articles/products/components/information-panel.mdx
> +      </Heading>
Base自体の見出しはBaseの外（SectionTitle）で示すケースが多いと思います。

2024-06-19 07:58 UTC, oti commented on content/articles/products/components/information-panel.mdx
> +          </CheckBox>
削除ダイアログを想定してました。
<img width="774" alt="スクリーンショット 2024-06-19 16 57 33" src="https://github.com/kufu/smarthr-design-system/assets/710216/e4c6aab2-0aeb-4795-9f6f-1a644720d8c3">

とはいえChecBox的には例外のパターンなので、別の形にしたほうがいいですね。

2024-06-19 08:00 UTC, oti commented on content/articles/products/components/information-panel.mdx
> +      </Heading>
@versionfive Baseの見出しとBaseの本文をトルツメして、シンプルにBase > BaseColumn > ResponseMessage + Textだけの形で良さそうですかね？

2024-06-19 08:03 UTC, versionfive commented on content/articles/products/components/information-panel.mdx
> +      </Heading>
@oti それでいってみましょう！

2024-06-21 00:45 UTC, oti commented
@versionfive @tosiiu Suggestionを取り込んでcodeBlock部分を修正しました。確認お願いします！

2024-06-21 02:21 UTC, versionfive approved these changes
LGTM!!!

2024-06-21 02:44 UTC, drivesketch approved these changes
わかりやすかったです。LGTM。

2024-06-21 02:44 UTC, drivesketch commented on content/articles/products/components/information-panel.mdx
> +閉じて隠されても操作に問題のない内容や、全文表示したままだと操作の妨げになるほど長大な内容の場合には開閉ボタンを表示しましょう。
「togglable=false を明示してね（デフォルトはtrueなので）」的な内容があってもいいかも

2024-06-21 02:50 UTC, tosiiu approved these changes
細かい呟きだけコメントしましたが、LGTMです！

2024-06-21 02:50 UTC, tosiiu commented on content/articles/products/components/information-panel.mdx
> +[削除ダイアログの注意事項](/products/design-patterns/delete-dialog/#h3-4)など、Baseのなかで見出しと内容を目立たせたい場合は、[BaseColumn](/products/components/base/base-column/)を使用してください。見出し部分は[Heading[type="blockTitle"]](/products/com
この場合の見出しってResponseMessageで実装するべきですかね〜見た目的には完全に同一ですが、何かへのResponseではないのでやや意味合い的に逸れる気がするんですよね...
とはいえそれぞれ独自実装するとブレそうなので悩ましい...

2024-06-21 02:50 UTC, tosiiu commented on content/articles/products/components/information-panel.mdx
> +[削除ダイアログの注意事項](/products/design-patterns/delete-dialog/#h3-4)など、Baseのなかで見出しと内容を目立たせたい場合は、[BaseColumn](/products/components/base/base-column/)を使用してください。見出し部分は[Heading[type="blockTitle"]](/products/com
InformationPanel内の実装でもResponseMessage使ってたので一旦公開を妨げるレベルのコメントではないです！

2024-06-21 02:56 UTC, o-kwr approved these changes
普段悩むポイントが押さえられてて全体としてLGTMです！

2024-06-21 03:17 UTC, oti commented on content/articles/products/components/information-panel.mdx
> +[削除ダイアログの注意事項](/products/design-patterns/delete-dialog/#h3-4)など、Baseのなかで見出しと内容を目立たせたい場合は、[BaseColumn](/products/components/base/base-column/)を使用してください。見出し部分は[Heading[type="blockTitle"]](/products/com
> InformationPanel内の実装でもResponseMessage使ってた
そうなんですよね〜。デザインでもResponseなもの以外にも使いがちなので、名前が違ってる説はあると思います。

2024-06-21 03:33 UTC, merged