チェックボックスのガイドラインを追加
kufu/smarthr-design-system pull request #1146
Opened 2024-04-23 08:24 UTC by wentzzz

## 課題・背景

https://smarthr.atlassian.net/browse/SD-660

## やったこと
- checkboxの使用上の注意、状態、デザインパターンを追加

## やらなかったこと
- 

## 動作確認

- 

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-04-23 08:43 UTC, oti commented on content/articles/products/components/check-box/index.mdx
> +複数の選択肢から1つを選択する場合は、表示領域に余裕がある場合は原則として[RadioButton](/products/components/radio-button/)、項目数が多い場合や表示領域が狭い場合などは[Select](/products/components/select/)や[ComboBox](/products/components/combo-box/)の使用を検討してく
```suggestion
### 3つ以上の選択肢から複数選択する場合に使用する

チェックボックスは、3つ以上の選択肢から複数選択して入力する場合に使用します。

![スクリーンショット](/images/check-box1.png)

複数の選択肢から単一選択する場合は、表示領域に余裕がある場合は原則として[RadioButton](/products/components/radio-button/)、項目数が多い場合や表示領域が狭い場合などは[Select](/products/components/select/)や[ComboBox](/products/components/combo-box/)の使用を検討してください。
```

[IMO]数字がいっぱいならんで目が滑ったので、複数/単一 としてもいいかも？

2024-04-23 08:47 UTC, oti commented on content/articles/products/components/check-box/index.mdx
> +例外として、表示領域が限られるなどの理由がある場合は、チェックボックスや[Switch](/products/components/switch/)の使用を検討します。
削除ダイアログの「注意事項を確認しました」で”「ON/OFF」といった2択の切り替え入力に使用”してましたぁ〜 https://smarthr.design/products/design-patterns/delete-dialog/#h2-1

って思ったけど削除ダイアログの方はON/OFFというよりはtrue/falseだから、例外なのかな？

2024-04-23 08:50 UTC, uknmr commented on content/articles/products/components/check-box/index.mdx
> +チェックボックスは、3つ以上の選択肢から2つ以上を複数選択して入力する場合に使用します。
1つも有り得るので語弊がありそうです。

```suggestion
チェックボックスは、3つ以上の選択肢から1つ以上を複数選択して入力する場合に使用します。
```

2024-04-23 08:50 UTC, uknmr commented on content/articles/products/components/check-box/index.mdx
> +複数の選択肢から1つを選択する場合は、表示領域に余裕がある場合は原則として[RadioButton](/products/components/radio-button/)、項目数が多い場合や表示領域が狭い場合などは[Select](/products/components/select/)や[ComboBox](/products/components/combo-box/)の使用を検討してく
原則ではなさそう?

```suggestion
複数の選択肢から1つを選択する場合は、表示領域に余裕がある場合は[RadioButton](/products/components/radio-button/)、項目数が多い場合や表示領域が狭い場合などは[Select](/products/components/select/)や[ComboBox](/products/components/combo-box/)の使用を検討してください。
```

2024-04-23 09:32 UTC, versionfive commented on content/articles/products/components/check-box/index.mdx
> +例外として、表示領域が限られるなどの理由がある場合は、チェックボックスや[Switch](/products/components/switch/)の使用を検討します。
Switchは即時反映を前提とするので、submit前提のCheckboxを使うシーンでの代替にはあまりならない印象があります。

逆にその場合はoti sanが示しているように1項目だけのON/OFFに使う気がしており、基本的に使うべきではないものの、例外がありそうですね。

2024-04-23 09:32 UTC, versionfive commented on content/articles/products/components/check-box/index.mdx
> +よくあるテーブルで「表示/非表示」を切り替えたい場合など、表示領域上`submit`のボタンの配置が難しい場合は、[Switch](/products/components/switch/)を使用してください。
```suggestion
よくあるテーブルで「表示/非表示」の切り替える場合や、表示領域上`submit`のボタンの配置が難しい場合などの即時反映を前提とする箇所では、[Switch](/products/components/switch/)を使用してください。
```
「Switchは、submitボタンを置けない場合だけに使う」ように読み取れたので修正

2024-04-23 09:32 UTC, versionfive commented on content/articles/products/components/check-box/index.mdx
> +
```suggestion
```

2024-04-23 09:32 UTC, versionfive commented on content/articles/products/components/check-box/index.mdx
> +<Cluster gap="XS">
```suggestion
<Cluster gap={1}>
```
nitsですが

2024-04-23 09:32 UTC, versionfive commented on content/articles/products/components/check-box/index.mdx
> +複数の選択肢から1つを選択する場合は、表示領域に余裕がある場合は原則として[RadioButton](/products/components/radio-button/)、項目数が多い場合や表示領域が狭い場合などは[Select](/products/components/select/)や[ComboBox](/products/components/combo-box/)の使用を検討してく
原則、というか適所（こういう用途ならこのコンポーネント）がありそう

2024-04-23 09:39 UTC, wentzzz commented on content/articles/products/components/check-box/index.mdx
> +複数の選択肢から1つを選択する場合は、表示領域に余裕がある場合は原則として[RadioButton](/products/components/radio-button/)、項目数が多い場合や表示領域が狭い場合などは[Select](/products/components/select/)や[ComboBox](/products/components/combo-box/)の使用を検討してく
わかる

2024-04-23 09:42 UTC, wentzzz commented on content/articles/products/components/check-box/index.mdx
> +例外として、表示領域が限られるなどの理由がある場合は、チェックボックスや[Switch](/products/components/switch/)の使用を検討します。
>逆にその場合はoti sanが示しているように1項目だけのON/OFFに使う気がしており、基本的に使うべきではないものの、例外がありそうですね。

お二人がおっしゃる通りで「確認しました」「同意します」などが該当するものだと思っています。それをどう表現したものかと悩んでおりました。

2024-04-23 10:45 UTC, oti requested changes
追加でコメントしました！

2024-04-23 10:45 UTC, oti commented on content/articles/products/components/check-box/index.mdx
> +チェックボックスは、3つ以上の選択肢から1つ以上を複数選択して入力する場合に使用します。
```suggestion
### 選択肢が複数選択できる場合に使用する

チェックボックスは選択肢を複数選択できる場合に使用します。
```

複数選択しなければならないとは限らないので、「選択**できる**」でどうでしょう？

また、選択肢が2つなこともあると思うので、あえて数に言及しなくてもいいんじゃないかと思いました。

2024-04-23 10:45 UTC, oti commented on content/articles/products/components/check-box/index.mdx
> +複数の選択肢から1つを選択する場合は、表示領域に余裕がある場合は[RadioButton](/products/components/radio-button/)、項目数が多い場合や表示領域が狭い場合などは[Select](/products/components/select/)や[ComboBox](/products/components/combo-box/)の使用を検討してください。
```suggestion
複数の選択肢から単一選択しかできず、表示領域に余裕がある場合は原則として[RadioButton](/products/components/radio-button/)、選択肢が多い場合や表示領域が狭い場合などは[Select](/products/components/select/)や[ComboBox](/products/components/combo-box/)の使用を検討してください。
```

場合は場合はと続くのがちょっと気になったので、選択する数の表現も複数/単一として↑こんなふうにするのはどうでしょう？

2024-04-25 06:32 UTC, versionfive commented on content/articles/products/components/check-box/index.mdx
> +複数の選択肢から単一選択しかできず、表示領域に余裕がある場合は原則として[RadioButton](/products/components/radio-button/)、選択肢が多い場合や表示領域が狭い場合などは[Select](/products/components/select/)や[ComboBox](/products/components/combo-box/)の使用を検討してくだ
```suggestion
- 複数の選択肢から単一選択しかできず、表示領域に余裕がある場合は原則として[RadioButton](/products/components/radio-button/)を検討してください。
- 選択肢が多い場合や表示領域が狭い場合は、[Select](/products/components/select/)や[ComboBox](/products/components/combo-box/)を検討してください。

![スクリーンショット](/images/check-box1.png)
```
画像の上にリストで示せるとよいかも

2024-04-25 06:32 UTC, versionfive commented on content/articles/products/components/check-box/index.mdx
> +よくあるテーブルで「表示/非表示」の切り替える場合や、表示領域上`submit`のボタンの配置が難しい場合などの即時反映を前提とする箇所では、[Switch](/products/components/switch/)を使用してください。
```suggestion
よくあるテーブルで「表示/非表示」を切り替える場合や、表示領域上`submit`のボタンの配置が難しい場合など、即時反映を前提とする箇所では[Switch](/products/components/switch/)を使用してください。
```
私のsuggestionがtypoしてたかも :pray:

2024-04-25 06:32 UTC, versionfive commented on content/articles/products/components/check-box/index.mdx
> +[テーブル内の一括操作](/products/design-patterns/table-bulk-action/)など、複数のチェックボックスを「一括選択するチェックボックス」において、1つ以上選択された場合（選択状態と未選択状態が混ざっている場合）に「一括選択するチェックボックス」を混在選択状態（mixed=true）にします。
```suggestion
[テーブル内の一括操作](/products/design-patterns/table-bulk-action/)の「一括選択するチェックボックス」など、複数のチェックボックスの状態をまとめて示す必要があるチェックボックスにおいて、選択状態と未選択状態が混ざっている状態を示す場合には、混在選択状態（`mixed=true`）を採用します。
```

2024-04-25 06:32 UTC, versionfive commented on content/articles/products/components/check-box/index.mdx
> +設定画面など、複数の設定項目でチェックボックスを整列して表示する場合などは、[共通設定の操作権限項目](/products/design-patterns-core-features/access-control-setting-pattern/)のデザインパターンを参考にしてください。
```suggestion
設定画面によくある複数の設定項目でチェックボックスを整列して表示する場合などは、[共通設定の操作権限項目](/products/design-patterns-core-features/access-control-setting-pattern/)のデザインパターンを参考にしてください。
```
などなどしていた

2024-04-25 06:32 UTC, versionfive commented on content/articles/products/components/check-box/index.mdx
> +<ComponentPropsTable name="CheckBox" />
```suggestion
## Props

<ComponentPropsTable name="CheckBox" />
```

2024-04-26 01:55 UTC, MasafumiKabe approved these changes
よさそみです！

2024-04-26 08:01 UTC, versionfive approved these changes
LGTM！！

2024-04-26 09:55 UTC, tosiiu approved these changes
LGTM!迷わず使えそうに思いました！！

2024-04-26 10:19 UTC, oti approved these changes
LGTM!

2024-04-26 10:19 UTC, merged