フィードバックのデザインパターンを追加
kufu/smarthr-design-system pull request #1158
Opened 2024-05-14 08:38 UTC by tosiiu

## 課題・背景

操作に関するフィードバックの基準がなく、設計のブレが生じていたため

## やったこと
- デザインパターン配下にフィードバックページを追加

## やらなかったこと
- 

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-05-23 04:16 UTC, ytysym reviewed
いくつかコメント残しました！

2024-05-23 04:16 UTC, ytysym commented on content/articles/products/design-patterns/feedback.mdx
> +    - ユーザーが直前に操作していた要素の近くにsync状態の[ResponseMessage](/products/components/response-message/)を表示することを検討します。
ここも例があると、どういう場合かイメージしやすそうだと思いました！

2024-05-23 04:16 UTC, ytysym commented on content/articles/products/design-patterns/feedback.mdx
> +成功時にはsuccess状態で、失敗時にはerror状態でResponseMessage, NotificationBar, InformationPanelを表示します。
propsを表現する場合、`success`とか`type="success"`のような書き方をしているページを見かけたので、そっちに揃えてもいいかも？

2024-05-23 04:16 UTC, ytysym commented on content/articles/products/design-patterns/feedback.mdx
> +ページとその要素の読み込み時のフィードバックには、処理中のフィードバックと結果のフィードバック（失敗時）があります。まず、処理中であることを示し、読み込みに失敗したらその結果を表示します。成功時は、要素が表示されることでその結果が自明であるため、フィードバックのためのUIは表示しません。
「成功時は、〜〜」の部分は、####結果のフィードバックのセクションに入れてもよいかもと思いました。その方が、処理の実行時のセクションと書き方が揃うので。

2024-05-23 06:43 UTC, drivesketch requested changes
気になったところコメントしました。

2024-05-23 06:43 UTC, drivesketch commented on content/articles/products/design-patterns/feedback.mdx
> +#### 結果のフィードバック
ふと浮かんだ疑問なのですが、「処理がうまくできなかった」と「そもそも処理を受け付けない」って、同じ扱いでいいんでしょうか

たとえば、必須項目のあるモーダルダイアログとかで、必須を埋めずにサブミットすると「必須が埋められてないよ！」とエラーを返しますが、これを「処理結果」と呼ぶのに若干の違和感があります。（が、エラーメッセージを出す場所やコンポーネントは同じだしなあ、という思いもあり‥）

2024-05-23 06:43 UTC, drivesketch commented on content/articles/products/design-patterns/feedback.mdx
> +ここでは、フォーム関連コンテンツへの入力時のフィードバックについて説明します。フォーム関連コンテンツへ入力であっても、それが処理の実行を即時的に引き起こす場合は[処理の実行時](#h3-2)を参照してください。
「違うやつ」の説明から始まるので、わかりにいと感じました。
タイトルを工夫したり、あとの説明を改善したりして、この一文目をなくすか後ろに回したいです。

2024-05-23 06:43 UTC, drivesketch commented on content/articles/products/design-patterns/feedback.mdx
> +
全体的に、改段落（`<p>〜<p>`）ではなく改行（`<br>`）が多く使われているのが気になりました。

基本的に、意味が変わるなら段落を変える、そうでないなら改行もしない、の方が読みやすいと思います。

2024-05-23 06:43 UTC, drivesketch commented on content/articles/products/design-patterns/feedback.mdx
> +フォームの入力時には、主に入力内容が不正である場合のエラーメッセージを表示します。
「フロントだけで判定できるフォーマット不正や文字数超過の場合、submitを待たずにonblurでエラー出してね（出していいよ）」
みたいな内容を一文で言い切ってほしいと思いました
（代替案は浮かんでいないゴメン）

2024-05-23 06:43 UTC, drivesketch commented on content/articles/products/design-patterns/feedback.mdx
> +フォームの入力時には、主に入力内容が不正である場合のエラーメッセージを表示します。
雑ですが

```
ユーザーがフォームに入力した値が、期待されているフォーマットと明らかに異なる場合、フォームからフォーカスが外れたタイミングで、エラーである旨を伝えます。

たとえば以下のような場合。

- 日付が欲しいのに文字列が入ってる
- 許容されている文字数を超過している

エラーの表示は（中略）errorMessagesオプションを利用します。

[画像]

フォームの値が修正され、エラーが解消されたら、エラーの表示を止めます。
```

みたいなイメージ

2024-05-23 06:54 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +<!-- textlint-disable -->
「読み込み時」が"時"を"とき"とひらくルールに引っかかるので入れてます〜

2024-05-23 08:16 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +    - ButtonのLoadingオプションを利用します。
処理を開始していないが、Buttonをloading状態にすることってありますか？

2024-05-23 08:22 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +#### 結果のフィードバック
必須項目が埋まっているかどうかの判定も"処理"に含むと考えての記載でした！

2024-05-23 08:34 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +#### 結果のフィードバック
submitボタンで実行される各フォームが不正であるかの判定も処理の一部として捉えています。が、そもそもそのケースがこの基準のどこでもカバーできてないのでちょっと考えてみます！

（一度返信書いたのですが、的外れだったので再投稿しました🙏🏻）

2024-05-23 08:42 UTC, drivesketch commented on content/articles/products/design-patterns/feedback.mdx
> +    - ButtonのLoadingオプションを利用します。
一般的かどうかは自信ありませんが、うちのプロダクトで「ボタンが押された瞬間にloadingになる（サーバーサイドからの返答に関係なく）」という実装になっているのを見たことがあります。

2024-05-23 09:05 UTC, drivesketch commented on content/articles/products/design-patterns/feedback.mdx
> +    - ButtonのLoadingオプションを利用します。
あーでも
ユーザーに伝えたいメッセージは「そのまま待ってて」なので、処理中と同じグループで良い気がしてきました

2024-05-24 09:34 UTC, ysasaki10 reviewed
レビューコメントを追加しました！

2024-05-24 09:34 UTC, ysasaki10 commented on content/articles/products/design-patterns/feedback.mdx
> +### アクセシビリティ
現状だと「基本的な考え方」のセクション内で同じレベルで他の見出しがないので、アクセシビリティの見出しを付けてあげる必要があまり感じられなかったです

2024-05-24 09:34 UTC, ysasaki10 commented on content/articles/products/design-patterns/feedback.mdx
> +基本的に[FormControl](/products/components/form-control/)か[Fieldset](/products/components/fieldset/)のerrorMessagesオプションを利用して表示します。FormControlの場合はさらに入力要素にerror状態を付与します。
> FormControlの場合はさらに入力要素にerror状態を付与します。

ここ、なにを言ってるのかわからなかったです。

2024-05-24 09:34 UTC, ysasaki10 commented on content/articles/products/design-patterns/feedback.mdx
> +    - ユーザーが直前に操作していた要素の近くにsync状態の[ResponseMessage](/products/components/response-message/)を表示することを検討します。
同じく参考例の画像が欲しいと感じました。
全体的に文字文字しくて具体をイメージしずらいのでもっと画像で読者の認知の手助けをしてあげてほしいです。

2024-05-30 06:04 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +title: 'フィードバック'
仰る通りソフトウェアの文脈でフィードバックという言葉が使われる場面は他にもあると思います。
ただ、デザインシステムの汎用的なデザインパターンで「システムからユーザーへの状況の応答」以外の意味でフィードバックという語を用いることは少ないように思います。概要にもその記載があるので迷うこともなさそうです。
フィードバックでも実使用上あまり問題がないように思うのですがどうでしょう？

（これは個人的な考えですが、できるだけページタイトルはシンプルである方が良いと考えています）

2024-05-30 06:59 UTC, drivesketch commented on content/articles/products/design-patterns/feedback.mdx
> +title: 'フィードバック'
大丈夫な気がしてきたのでgogoです！

2024-06-03 02:58 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +ここでは、フォーム関連コンテンツへの入力時のフィードバックについて説明します。フォーム関連コンテンツへ入力であっても、それが処理の実行を即時的に引き起こす場合は[処理の実行時](#h3-2)を参照してください。
「ここでは」を省略しました！

MDNのHTML要素の分類を引用する形で「フォーム関連コンテンツ」としていましたが、フォームに対する入力とシンプルに捉え直して整理しました。

2024-06-03 03:00 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +成功時にはsuccess状態で、失敗時にはerror状態でResponseMessage, NotificationBar, InformationPanelを表示します。
「状態」を省くと文として違和感があったので、一旦コード表記にだけしています！より良い表現がもしあれば教えてください🙏🏻

2024-06-03 03:00 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +ページとその要素の読み込み時のフィードバックには、処理中のフィードバックと結果のフィードバック（失敗時）があります。まず、処理中であることを示し、読み込みに失敗したらその結果を表示します。成功時は、要素が表示されることでその結果が自明であるため、フィードバックのためのUIは表示しません。
取り入れました！

2024-06-03 03:01 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +フィードバックは、ユーザーが操作の結果を理解し、次の行動を判断するために重要です。ユーザーがシステムに何らかの操作をした際は受動的にその結果を認識できるよう、素早く画面上にフィードバックのためのUIを表示してください。
フィードバックとは何かの説明を入れてみました！

>「ユーザーが何か操作したら、コンピュータからなにか返答させてね、じゃないとユーザーが今どうなってるか分からず不安になっちゃうよ」

ここに関しては、「ユーザーがシステムに何らかの操作をした際は受動的にその結果を認識できるよう、素早く画面上にフィードバックのためのUIを表示してください。」がそれにあたると判断していますが解釈違うようであれば教えてください！

2024-06-03 03:02 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +    - ButtonのLoadingオプションを利用します。
「処理開始時〜処理中のフィードバック」と整理し直しました！

2024-06-03 03:03 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +#### 結果のフィードバック
見出し「フォームの入力時」を「フォームの入力・送信時」として、このケースがカバーできるよう整理し直しました！

2024-06-03 03:03 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +ここでは、フォーム関連コンテンツへの入力時のフィードバックについて説明します。フォーム関連コンテンツへ入力であっても、それが処理の実行を即時的に引き起こす場合は[処理の実行時](#h3-2)を参照してください。
MDNのHTML要素の分類を引用する形で「フォーム関連コンテンツ」としていましたが、フォームに対する入力とシンプルに捉え直して整理しました。

2024-06-03 03:03 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +
全体の改行を整理し直しました！

2024-06-03 03:05 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +フォームの入力時には、主に入力内容が不正である場合のエラーメッセージを表示します。
一文では言い切れていないものの、送信時のエラー表示タイミングと合わせて書いてみたので再度見ていただけると🙏🏻

2024-06-03 03:06 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +### アクセシビリティ
そもそもアクセシビリティに関する考慮点は「基本的な考え方」に含まれないと感じたので、見出しを独立させました！

2024-06-03 03:15 UTC, versionfive reviewed
Slackでコメントしています、というコメントです

2024-06-05 10:44 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +基本的に[FormControl](/products/components/form-control/)か[Fieldset](/products/components/fieldset/)のerrorMessagesオプションを利用して表示します。FormControlの場合はさらに入力要素にerror状態を付与します。
画像を追加し、「どの入力要素がエラーとなっているかを視覚的に見つけやすくするために、入力要素にも`error`状態を付加して意匠を変化させます。」という説明に変更しました。

2024-06-05 10:45 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +    - ユーザーが直前に操作していた要素の近くにsync状態の[ResponseMessage](/products/components/response-message/)を表示することを検討します。
全体に画像を追加しました。例として十分かやや心配なのでイメージがつくか見ていただきたいです。

2024-06-05 10:47 UTC, tosiiu commented
レビュー内容を反映しました。全体的に差分が出ているので再度見ていただけると🙏🏻

2024-06-05 10:51 UTC, tosiiu commented on content/articles/products/design-patterns/feedback.mdx
> +    - ユーザーが直前に操作していた要素の近くにsync状態の[ResponseMessage](/products/components/response-message/)を表示することを検討します。
@versionfive NotificationBarの位置について直接の言及はないのですが、一旦代表的な配置を画像にしています...！不足がありそうであればコメントください！

2024-06-05 21:03 UTC, drivesketch commented on content/articles/products/design-patterns/feedback.mdx
> +フィードバックは、ユーザーが操作の結果を理解し、次の行動を判断するために重要です。ユーザーがシステムに何らかの操作をした際は受動的にその結果を認識できるよう、素早く画面上にフィードバックのためのUIを表示してください。
とても分かりやすいと思います。
このセクションと合わせて、タイトルも「フィードバック」で十分に思いました。

2024-06-05 21:06 UTC, drivesketch commented on content/articles/products/design-patterns/feedback.mdx
> +#### 結果のフィードバック
構成分かりやすいです

2024-06-05 21:09 UTC, drivesketch commented on content/articles/products/design-patterns/feedback.mdx
> +フォームの入力時には、主に入力内容が不正である場合のエラーメッセージを表示します。
構成分かりやすいです

2024-06-06 01:56 UTC, drivesketch submitted a review, later dismissed
すごく読みやすく、分かりやすくなったと感じます。
細かい気になりをコメントしましたが、基本的にはLGTMです！

2024-06-06 01:56 UTC, drivesketch commented on content/articles/products/design-patterns/feedback/index.mdx
> +<!-- textlint-enable -->
Lintよけも兼ねて

```suggestion
1. フォームを入力・送信するとき
1. 処理を実行するとき
1. ページとその要素を読み込むとき
```

みたいにしても、言葉が平易になって良いかも

2024-06-06 01:56 UTC, drivesketch commented on content/articles/products/design-patterns/feedback/index.mdx
> +- 値が許容範囲外
```suggestion
- 入力必須の要素の値が空である
- データ型が異なる
- 許容範囲外の値が入力されている
```

語尾を揃えてもいいかも

2024-06-06 01:56 UTC, drivesketch commented on content/articles/products/design-patterns/feedback/index.mdx
> +    - ![スクリーンショット: Inputを持つFormControlを内包するActionDialog。ActionDialogのPrimaryボタンがloading状態で表示されている。](./images/button-loading.png)
多段階箇条書きの中に文と画像があるの、見づらく感じました。

見出しはh5までいけるので、見出しで区切るほうが良いかもしれません。

手元で適当に作った案
<img width="632" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/7392923/8ae3b434-3603-4ad3-852a-23b31c62f77a">

2024-06-06 01:56 UTC, drivesketch commented on content/articles/products/design-patterns/feedback/index.mdx
> +    - ![スクリーンショット: Inputを持つFormControlを内包するActionDialog。Inputの枠線は赤く表示され、Inputの上部に「タイトルが入力されていません。」というエラーメッセージが表示されたResponseMessageがある。](./images/form-control-error-on-blur.png)
うちのプロダクトで、必須チェックをonblurでやってるイメージがなくて、少し違和感がありました。
（でも、やる方針に変えるほうがいいのかな…？）

2024-06-07 03:18 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +<!-- textlint-enable -->
取り入れました！

2024-06-07 03:19 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +- 値が許容範囲外
suggestを取り入れました！

2024-06-07 03:19 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +    - ![スクリーンショット: Inputを持つFormControlを内包するActionDialog。ActionDialogのPrimaryボタンがloading状態で表示されている。](./images/button-loading.png)
fumiya-sanからのFB含めて階層構造を見直しました！

2024-06-07 03:22 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +    - ![スクリーンショット: Inputを持つFormControlを内包するActionDialog。Inputの枠線は赤く表示され、Inputの上部に「タイトルが入力されていません。」というエラーメッセージが表示されたResponseMessageがある。](./images/form-control-error-on-blur.png)
場合によってはやったほうが良さそうに思いました！

より適切な例があれば差し替えたいのですが何かありますかね？？

2024-06-07 03:27 UTC, drivesketch commented on content/articles/products/design-patterns/feedback/index.mdx
> +    - ![スクリーンショット: Inputを持つFormControlを内包するActionDialog。Inputの枠線は赤く表示され、Inputの上部に「タイトルが入力されていません。」というエラーメッセージが表示されたResponseMessageがある。](./images/form-control-error-on-blur.png)
うーん
文字数超過あたりですかね…？

2024-06-07 03:51 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +    - ![スクリーンショット: Inputを持つFormControlを内包するActionDialog。Inputの枠線は赤く表示され、Inputの上部に「タイトルが入力されていません。」というエラーメッセージが表示されたResponseMessageがある。](./images/form-control-error-on-blur.png)
確かに良さそうだったので変更してみました！

2024-06-07 09:55 UTC, ytysym commented on content/articles/products/design-patterns/feedback.mdx
> +成功時にはsuccess状態で、失敗時にはerror状態でResponseMessage, NotificationBar, InformationPanelを表示します。
コード表記でOKだと思います！

2024-06-07 11:14 UTC, versionfive reviewed
内容は別途議論されていると思うので、ひとまず書きっぷり目線でsuggetion入れています。

2024-06-07 11:14 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +## 状況に応じたパターン
```suggestion
## 種類
```
テンプレに合わせた

2024-06-07 11:14 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +
```suggestion
```
直接説明があれば良い気がしました。

2024-06-07 11:14 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +操作後に画面全体の切り替えが発生する場合など処理を実行したButtonの状態変化で伝えることが難しい場合は、`sync`状態の[NotificationBar](/products/components/notification-bar/)を表示します。
```suggestion
#### Buttonの状態変化で伝えることが難しい場合

操作後に画面全体の切り替えが発生する場合など、処理を実行したButtonの状態変化で伝えることが難しい場合は、`sync`状態の[NotificationBar](/products/components/notification-bar/)を表示します。
```

2024-06-07 11:14 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +
```suggestion
```

2024-06-07 11:14 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +操作後に画面全体の切り替えが発生する場合などユーザーが直前に操作していたButtonの近くに表示するのが難しい場合は、成功時には`success`状態、失敗時には`error`状態で[NotificationBar](/products/components/notification-bar/)を表示します。
```suggestion
#### Buttonの近くに表示するのが難しい場合

操作後に画面全体の切り替えが発生する場合など、ユーザーが直前に操作していたButtonの近くに表示することが難しい場合は、成功時には`success`状態、失敗時には`error`状態で[NotificationBar](/products/components/notification-bar/)を表示します。
```

2024-06-07 11:14 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +#### 記載する情報が多くResponseMessageやNotificationBarでは表示しきれない場合
```suggestion
#### 記載する情報が多い場合（ResponseMessageやNotificationBarで表示しきれない場合）
```

2024-06-07 11:14 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +#### 値が不正であることが入力時に判定できる場合
```suggestion
#### 入力時に値が不正であることを判定する場合
```

2024-06-07 11:14 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +#### 値が不正であることが入力時に判定できず、フォームの送信時に判定する場合
```suggestion
#### フォームの送信時に値が不正であることを判定する場合
```

2024-06-07 11:14 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +送信ボタンの押下後に、入力要素と送信ボタンに対してエラーメッセージを表示します。再度送信ボタンが押下された際に、エラーの原因が解消されていた場合はエラーメッセージの表示を止めます。
気づいたけど、NotificationBarは✗をだせば消せるけど、responseMessageだと何かのトリガーないとユーザーでは消せないですね。

2024-06-10 01:51 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +例：オブジェクトの新規インスタンスを作成すると、作成された新規インスタンスの詳細画面へ自動的に移動する場合, [Switch](/products/components/switch/)など、コンポーネント自体がその状態を示す場合
こちら別の表現に変わってるので確認いただけると！:pray:

2024-06-10 02:04 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +#### ユーザーが直前に操作していたButtonの近くに表示するのが難しい場合
たしかにですね〜！骨子段階では考慮してたのに抜けてました...
ちょっと変更してみます

2024-06-10 02:15 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +送信ボタンの押下後に、入力要素と送信ボタンに対してエラーメッセージを表示します。再度送信ボタンが押下された際に、エラーの原因が解消されていた場合はエラーメッセージの表示を止めます。
そうなんですよね〜
現時点で統一的な基準（消せないと困る場面・その代替案）を作るのやや難しそうに感じて言及できてません

2024-06-10 02:16 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +送信ボタンの押下後に、入力要素と送信ボタンに対してエラーメッセージを表示します。再度送信ボタンが押下された際に、エラーの原因が解消されていた場合はエラーメッセージの表示を止めます。
言及できないなら一旦

>再度送信ボタンが押下された際に、

をトルにしたらどうですかね？

2024-06-10 03:20 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +#### ユーザーが直前に操作していたButtonの近くに表示するのが難しい場合
@ytysym この構成で良いかやや悩みますが、変更してみました！

2024-06-10 03:20 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +送信ボタンの押下後に、入力要素と送信ボタンに対してエラーメッセージを表示します。再度送信ボタンが押下された際に、エラーの原因が解消されていた場合はエラーメッセージの表示を止めます。
良さそうだったので変更しました！

2024-06-10 06:32 UTC, versionfive reviewed
追加でコメントしましたmm

2024-06-10 06:32 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +1. ページ・要素の読み込みが完了したとき
```suggestion
- フォームを入力・送信するとき
- 同期処理を開始したとき
- 同期処理が完了したとき
- ページ・要素の読み込みを開始したとき
- ページ・要素の読み込みが完了したとき
```
順序リストにするなら、各見出しに番号の数字を出してほしいです

2024-06-10 06:32 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +ただし、以下のように操作結果が自明である場合は、フィードバックのためのUIを省略できます。
```suggestion
ただし、以下のように**操作結果が自明である場合は、フィードバックのためのUIを省略できます。**
```
これって省略すべき、したほうがいい、してもいい、だとどのくらいの推奨度でしょう？

2024-06-10 06:32 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +実行した[Button](/products/components/button/)を`loading`状態に変化させます。
例にあるActionDialogだと勝手にやってくれるかも？

2024-06-10 06:32 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +操作後に画面全体の切り替えが発生する場合など、ユーザーが直前に操作していたButtonの近くに表示することが難しい場合は、成功時には`success`状態、失敗時には`error`状態で[NotificationBar](/products/components/notification-bar/)を表示します。
例のNotificationBarでは`bold`になってるので、これは基準に含めたほうがいいのかな。それはNotificationBarの使い方にまかせますか？

2024-06-10 06:32 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +補足情報としてTextLinkやButtonを表示する場合は、成功時には`success`状態、失敗時には`error`状態で[NotificationBar](/products/components/notification-bar/)を表示します。
例のNotificationBarでは`bold`になってるので、これは基準に含めたほうがいいのかな。それはNotificationBarの使い方にまかせますか？

2024-06-10 06:32 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +要素が本来表示される場所に、`error`状態の[NotificationBar](/products/components/notification-bar/)を表示します。
例のNotificationBarではboldになってるので、これは基準に含めたほうがいいのかな。それはNotificationBarの使い方にまかせますか？

2024-06-10 07:39 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +実行した[Button](/products/components/button/)を`loading`状態に変化させます。
ActionDialogのpropsのresponseMessageに{ status: "processing"; }を渡さないといけなくないですか？
ただ、それは書かれてないので書いても良いかもですね

2024-06-10 08:00 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +1. ページ・要素の読み込みが完了したとき
順序付きリストである理由が特になかったので、変更取り込みました！

2024-06-10 08:01 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +操作後に画面全体の切り替えが発生する場合など、ユーザーが直前に操作していたButtonの近くに表示することが難しい場合は、成功時には`success`状態、失敗時には`error`状態で[NotificationBar](/products/components/notification-bar/)を表示します。
どこまで書くのかは難しいですが、概ねpropsについても言及しているページなので含めてみます。

2024-06-10 08:05 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +ただし、以下のように操作結果が自明である場合は、フィードバックのためのUIを省略できます。
以下の理由から「しても良い」の推奨度で書いているつもりです！

- 省略した方がいい場面はあるが、現時点では省略した方がその条件を明示的に示すアイデアが思いついていない
- 表示されても強い困りごとにはならないが、表示されないと困る場面はある

2024-06-10 09:17 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +実行した[Button](/products/components/button/)を`loading`状態に変化させます。
ですね！

2024-06-10 09:18 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +ただし、以下のように操作結果が自明である場合は、フィードバックのためのUIを省略できます。
>省略した方がいい場面はあるが

これを2点例示しているのだと思っていました。なので、この2点に該当する場合は少なくとも省略すべきなのかと読み取りました。

>表示されても強い困りごとにはならないが、表示されないと困る場面はある

これをよんで、「過度なフィードバック」のデメリットもあるな、と思いました。

2024-06-10 11:27 UTC, ysasaki10 submitted a review, later dismissed
LGTM!!

2024-06-10 22:07 UTC, drivesketch submitted a review, later dismissed
LGTMです！

2024-06-11 07:24 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +操作後に画面全体の切り替えが発生する場合など、ユーザーが直前に操作していたButtonの近くに表示することが難しい場合は、成功時には`success`状態、失敗時には`error`状態で[NotificationBar](/products/components/notification-bar/)を表示します。
追記しました！（この追記方法がベストかやや悩ましいのでより良い表現のアイデアあればください:pray:）

2024-06-11 07:24 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +補足情報としてTextLinkやButtonを表示する場合は、成功時には`success`状態、失敗時には`error`状態で[NotificationBar](/products/components/notification-bar/)を表示します。
追記しました！

2024-06-11 07:24 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +要素が本来表示される場所に、`error`状態の[NotificationBar](/products/components/notification-bar/)を表示します。
追記しました！

2024-06-11 07:24 UTC, tosiiu commented on content/articles/products/design-patterns/feedback/index.mdx
> +実行した[Button](/products/components/button/)を`loading`状態に変化させます。
追記しました！

2024-06-11 07:41 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +操作後に画面全体の切り替えが発生する場合など、ユーザーが直前に操作していたButtonの近くに表示することが難しい場合は、成功時には`success`状態、失敗時には`error`状態で[NotificationBar](/products/components/notification-bar/)を表示します。
一旦はよさそう、boldの基準についてはNotificationBarのほうに書いてあれば良いと思いました

2024-06-11 07:51 UTC, versionfive reviewed
細かいコメント2点だけ:pray: 
あと画像の粗さがちょっと気になりました

2024-06-11 07:51 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +ユーザーに操作の結果を伝えるUIのルールを定義します。
```suggestion
ユーザーに操作の結果を伝えるUIの基準を定義します。
```

2024-06-11 07:51 UTC, versionfive commented on content/articles/products/design-patterns/feedback/index.mdx
> +ただし、以下の例のように画面の変化から操作が成功していることが**明らかに理解できる場合のみ**フィードバックのためのUIは省略します。
```suggestion
#### フィードバックを省略できるケース
以下の例のように画面の変化から操作が成功していることが**明らかに理解できる場合のみ**フィードバックのためのUIは省略します。
```
今後参照したくなりそうなので見出しつけてみました。

2024-06-11 08:50 UTC, tosiiu commented
> 細かいコメント2点だけ:pray: あと画像の粗さがちょっと気になりました

画像を高解像度版に差し替えました！

2024-06-11 08:51 UTC, versionfive approved these changes
LGTM!!!

2024-06-11 08:53 UTC, ytysym commented on content/articles/products/design-patterns/feedback/index.mdx
> +例：オブジェクトの新規インスタンスを作成すると、作成された新規インスタンスの詳細画面へ自動的に移動する場合, [Switch](/products/components/switch/)など、コンポーネント自体がその状態を示す場合
冒頭に「省略できるケース」としてまとめた感じですね！よさそうです！

2024-06-11 08:54 UTC, ytysym commented on content/articles/products/design-patterns/feedback/index.mdx
> +#### ユーザーが直前に操作していたButtonの近くに表示するのが難しい場合
すぐしたに補足されていて分かると思うので、よさそうだと思いました！

2024-06-11 08:54 UTC, ytysym approved these changes
LGTMです！

2024-06-11 21:55 UTC, drivesketch approved these changes
LGTM!

2024-06-12 01:35 UTC, ysasaki10 approved these changes
LGTM!!

2024-06-12 01:35 UTC, merged