ErrorScreenの使用目的を追加した
kufu/smarthr-design-system pull request #1164
Opened 2024-05-21 07:38 UTC by oti

## 課題・背景

基準充足のため

## やったこと

ErrorScreenの使用目的を追加した。

## やらなかったこと
使用上の注意があるように思わなかった（序文の目的の反転が「使用しない」理由になりそう）のでセクションを追加していません。

## 動作確認

https://deploy-preview-1164--smarthr-design-system.netlify.app/products/components/error-screen/

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-05-21 07:50 UTC, tosiiu reviewed
現状一貫性が無いそれぞれのpropsの扱い方（logoを有効化する/しない, titleにHTTPステータスコードを入れる/入れない, childrenに渡すテキストの内容など）の基準がほしいと思いました！

2024-06-10 09:17 UTC, oti commented
@versionfive @tosiiu @ytysym @Qs-F おまたせしました！ 基本的なレイアウトと項目の解説を追加し、具体的なエラー別の内容を提示する構成にしてみました。確認お願いいたします！

2024-06-11 02:49 UTC, versionfive requested changes
書きっぷりでコメントしました。
各画面のメッセージについてはUXライターも踏まえて検討したいです。

2024-06-11 02:49 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +任意のロゴを指定してカスタマイズ可能です。
これは使用許諾もらい済みですかね？

2024-06-11 02:49 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +フォームのバリデーションエラーや連携APIの疎通エラーのような一時的なエラーには使用せず、[NotificationBar](/products/components/notification-bar/)や[ResponsiveMessage](/products/components/response-message/)、[InformationPanel](/products/compone
@tosiiu さんのフィードバックの基準と書きっぷりをあわせたいところですね。（ただのコメントです）

2024-06-11 02:49 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +なぜエラーが発生したのかがわかる文言にしてください。
```suggestion
なぜエラーが発生したのかがわかる文言を設定します。
```

2024-06-11 02:49 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +タイトルを補足する本文にしてください。
```suggestion
タイトルを補足する本文を設定できます。
```

2024-06-11 02:49 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +プロダクトのグランドルールとして、常にフッターを表示する必要があれば利用できます。
グランドルールとはなんでしょうか？

2024-06-11 02:49 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +### 存在しないページ（404エラー）
```suggestion
### 存在しないページにアクセスした場合（404 Not Foundエラー）
```
上のリストの表記に合わせつつ、HTTPレスポンスのステータスコードに合わせました

2024-06-11 02:49 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +### ページにアクセスする権限がない（Forbiddenエラー）
```suggestion
### ページにアクセスする権限がない場合（403 Forbiddenエラー）
```

2024-06-11 02:49 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +### 一定時間操作がなかった（Unauthorizedエラー）
```suggestion
### 一定時間操作がなかった場合（401 Unauthorizedエラー）
```

2024-06-11 02:49 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +また、必要であれば「5秒後に再ログインします。」などのメッセージの表示と実装も検討してください。
```suggestion
また、必要であれば「5秒後に再ログインします。」などのメッセージの表示と実装も検討してください。
```
これはログインできる機能があるんですかね？ログイン画面が表示されるイメージ？

2024-06-11 02:49 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +エラーになったときにユーザーの助けになるようなページへ誘導できる場合はリンクを表示してください。
これは実態としてはヘルプセンターになりますか？他の選択肢はあるのでしょうか？

2024-06-11 02:49 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +### サービスがメンテナンス中
```suggestion
### サービスがメンテナンス中の場合
```

2024-06-11 02:49 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +### 予期しないエラーが発生した（Unexpectedエラー）
```suggestion
### 予期しないエラーが発生した場合（Unexpectedエラー）
```
「Unexpectedエラー」というはHTTPステータスコードとは別？

2024-06-11 03:07 UTC, oti commented on content/articles/products/components/error-screen.mdx
> +任意のロゴを指定してカスタマイズ可能です。
使用許諾もらってません…！
https://github.com/kufu/smarthr-patterns/blob/main/patterns/ThemeProvider/ThemeProvider.stories.tsx#L119 にあったので利用可能と思っていましたが、よくよくみるとこの ThemeProvider をSDSで表示していないのですね…

2024-06-11 03:13 UTC, oti commented on content/articles/products/components/error-screen.mdx
> +プロダクトのグランドルールとして、常にフッターを表示する必要があれば利用できます。
単に「決まりごと」の意味でした。
それはそれとしてPR本文にも書いたのですが ErrorScreen でフッターを表示しているプロダクトがなかったので、ErrorScreenに`footer` propsが必要なのかどうかから個人的に疑問があります。

2024-06-11 03:16 UTC, oti commented on content/articles/products/components/error-screen.mdx
> +また、必要であれば「5秒後に再ログインします。」などのメッセージの表示と実装も検討してください。
プロダクトによって異なっていました。その場で再認証をかけているものもあれば、 `/login` にルーティングしているものもありました。

2024-06-11 03:18 UTC, oti commented on content/articles/products/components/error-screen.mdx
> +エラーになったときにユーザーの助けになるようなページへ誘導できる場合はリンクを表示してください。
どんなエラーかで必要なリンクが異なると思いました。
404であればトップページ、401であればログインページ、メンテナンス中であればヘルプセンターが考えられます。

2024-06-11 03:53 UTC, oti commented on content/articles/products/components/error-screen.mdx
> +### 予期しないエラーが発生した（Unexpectedエラー）
500エラーを「予期しないエラーが発生しました」としているプロダクトが多かったですが、一部、ステータスコードのswitch文やif文をすべて抜けたあとのエラーとして表示しているものもあり、500と言い切れなさそうでした。

2024-06-11 04:01 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +プロダクトのグランドルールとして、常にフッターを表示する必要があれば利用できます。
たしかに、いらないかもですね。リネームされる前のMessageScreen時代のとき、ログイン画面の実装にも使われる想定をしていたようなので、その時の名残な気がしますねぇ。

2024-06-11 04:03 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +### 予期しないエラーが発生した（Unexpectedエラー）
理解できました。「その他のunexpextedなエラー」という意図だということですね。

2024-06-11 06:38 UTC, tosiiu commented on content/articles/products/components/error-screen.mdx
> +具体体は<a href="#h2-2">エラー別の表示内容</a>に記述しています。
```suggestion
具体的には<a href="#h2-2">エラー別の表示内容</a>に記述しています。
```
typo？

2024-06-11 06:38 UTC, tosiiu commented on content/articles/products/components/error-screen.mdx
> +フォームのバリデーションエラーや連携APIの疎通エラーのような一時的なエラーには使用せず、[NotificationBar](/products/components/notification-bar/)や[ResponsiveMessage](/products/components/response-message/)、[InformationPanel](/products/compone
フィードバックが公開されたら、フィードバックへのリンク貼っても良さそう

2024-06-11 06:38 UTC, tosiiu commented on content/articles/products/components/error-screen.mdx
> +存在しないページはにアクセスした場合、ページが見つからないだけでなく移動や削除された可能性も表示し、トップページへ戻るリンクを提供してください。
トップページとは、各プロダクトのトップなのかSmartHRホームなのか分からなかったので記載ほしいです！

2024-06-11 07:00 UTC, oti commented on content/articles/products/components/error-screen.mdx
> +### 予期しないエラーが発生した（Unexpectedエラー）
そしたら、「その他のunexpectedなエラー」をまとめて扱えるパターンであることを説明しても良さそうですかね？

2024-06-11 08:37 UTC, oti commented on content/articles/products/components/error-screen.mdx
> +プロダクトのグランドルールとして、常にフッターを表示する必要があれば利用できます。
`### フッター` セクションとcodeBlockのfooter指定をトルツメしました。

2024-06-11 08:38 UTC, oti commented on content/articles/products/components/error-screen.mdx
> +具体体は<a href="#h2-2">エラー別の表示内容</a>に記述しています。
fix!

2024-06-11 08:39 UTC, oti commented on content/articles/products/components/error-screen.mdx
> +存在しないページはにアクセスした場合、ページが見つからないだけでなく移動や削除された可能性も表示し、トップページへ戻るリンクを提供してください。
SmartHRホームを指定しているプロダクトがなかった（利用シーンも思い浮かばず）ので、「プロダクトのトップページ」としました！

2024-06-11 08:41 UTC, oti commented on content/articles/products/components/error-screen.mdx
> +また、先述したエラー（存在しないページにアクセスした場合、ページにアクセスする権限がない場合、サービスがメンテナンス中の場合、一定時間操作がなかった場合）ではないその他のエラーをまとめて扱う場合にもこの表示内容を推奨します。
@versionfive https://github.com/kufu/smarthr-design-system/pull/1164#discussion_r1634305417 の件を↑のようにしてみました。

（）内が長くなってしまうのですが、（）内をトルツメして

> また、先述したエラーではないその他のエラーをまとめて扱う場合にもこの表示内容を推奨します。

だとちょっと説明が心もとないような気がしてます。

2024-06-11 08:49 UTC, tosiiu commented
コメント対応ありがとうございます〜〜！文言のfixを待って再度レビューします！

2024-06-11 08:49 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +また、先述したエラー（存在しないページにアクセスした場合、ページにアクセスする権限がない場合、サービスがメンテナンス中の場合、一定時間操作がなかった場合）ではないその他のエラーをまとめて扱う場合にもこの表示内容を推奨します。
@oti そうですね…プロダクトの状況がみえてないのでうまいこと言えないのですが、推奨度としては「この表示内容を使えます。」程度（活用できるよ！）かなぁとは思いました。

2024-06-11 08:56 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +任意のロゴを指定してカスタマイズ可能です。
ﾅﾙﾎﾄﾞ

2024-06-11 09:01 UTC, oti commented on content/articles/products/components/error-screen.mdx
> +また、先述したエラー（存在しないページにアクセスした場合、ページにアクセスする権限がない場合、サービスがメンテナンス中の場合、一定時間操作がなかった場合）ではないその他のエラーをまとめて扱う場合にもこの表示内容を推奨します。
やっぱり（）内が厳しかったので短めに修正しました:bow:

2024-06-12 09:52 UTC, INABAshina reviewed
細かいところも含めて提案とコメントを入れています🙏

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +    移動もしくは削除された可能性があります。
```suggestion
    指定のページは、一時的にアクセスできない状況にあるか、削除された可能性があります。
    <br />
   またはURLが間違っていないか確認してください。
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +    移動もしくは削除された可能性があります。
以下2点の懸念を踏まえて提案を入れています。
- リテラシー低い人だと「ページが移動した」の意味がわからないかなと思いました。
- URLが間違っている場合も考えられると思うのですが、ケースとして含めなくてよいでしょうか？

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +      label: 'トップページへ戻る',
```suggestion
      label: 'ホームへ戻る',
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +      label: 'トップページへ戻る',
用字用語と揃えたいです🙏
[アプリケーションで最初に表示される画面は「ホーム」と表現し、「トップ」「トップページ」の使用は控える](https://smarthr.design/products/contents/idiomatic-usage/usage/#recYNynP9kXNRdD0T-0)

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +      label: 'トップページへ戻る',
```suggestion
      label: 'ホームへ戻る',
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +      label: 'トップページへ戻る',
```suggestion
      label: 'ホームへ戻る',
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +ページにアクセスする権限がユーザーにない場合、プロダクトのトップページへ戻るリンクを提供し、必要に応じて管理者へ問い合わせるメッセージを表示してください。
```suggestion
ページにアクセスする権限がユーザーにない場合、プロダクトのホームへ戻るリンクを提供し、必要に応じて管理者へ問い合わせるメッセージを表示してください。
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +存在しないページはにアクセスした場合、ページが見つからないだけでなく移動や削除された可能性も表示し、プロダクトのトップページへ戻るリンクを提供してください。
```suggestion
存在しないページはにアクセスした場合、ページが見つからないだけでなく移動や削除された可能性も表示し、プロダクトのホームへ戻るリンクを提供してください。
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +    詳しくは管理者にお問い合わせください。
```suggestion
    詳しくは、管理者にお問い合わせください。
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +      いつも SmartHR をご利用いただきありがとうございます。
```suggestion
      いつもSmartHRをご利用いただき、ありがとうございます。
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +      いつも SmartHR をご利用いただきありがとうございます。
[数字と英単語の前後に半角スペースを挿入しない](https://deploy-preview-1164--smarthr-design-system.netlify.app/products/contents/writing-style/#h2-10)

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +      ただいまメンテナンスのため、一時サービスを停止しております。
```suggestion
      ただいまメンテナンスのため、一時的にサービスを停止しています。
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +      ご迷惑をおかけいたしますが、ご理解のほどよろしくお願いいたします。
```suggestion
      ご迷惑をおかけしますが、ご理解のほどよろしくお願いいたします。
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +      ご迷惑をおかけいたしますが、ご理解のほどよろしくお願いいたします。
敬語が冗長なのが気になり、提案を入れています。

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +      ただいまメンテナンスのため、一時サービスを停止しております。
正しい日本語として「一時停止」か「一時的に停止」としたく、後者で提案を入れています。

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +  title="一定時間操作がなかったためログアウトしました"
```suggestion
  title="一定の時間、操作がなかったためログアウトしました"
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +  title="お探しのページは見つかりませんでした"
```suggestion
  title="指定のページは見つかりませんでした"
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +  title="お探しのページは見つかりませんでした"
セッション切れと揃えて「指定のページ」でいいのではと思いました！

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +      指定のページにアクセスするには、再度ログインが必要です。
```suggestion
      一定の時間、操作がなかったため、自動でログアウトしました。
      <br />
      指定のページを表示するには、再度ログインしてください。
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +必要があればプロダクトのトップページへ戻るリンクを提供してください。
```suggestion
必要があればプロダクトのホームへ戻るリンクを提供してください。
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +  title="予期せぬエラーが発生しました"
```suggestion
  title="予期しないエラーが発生しました"
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +      時間をおいてもう一度おためしください。
```suggestion
      時間をおいて、やり直してください。
```

2024-06-12 09:52 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +      時間をおいてもう一度おためしください。
以前議論したことがあるので揃えたいなと思いました！
https://kufuinc.slack.com/archives/CJX59GJFR/p1713745814178409

2024-06-12 10:03 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +存在しないページはにアクセスした場合、ページが見つからないだけでなく移動や削除された可能性も表示し、プロダクトのトップページへ戻るリンクを提供してください。
URLが間違っている場合も考えられると思うのですが、ケースとして含めなくてよいでしょうか？含めるとしたらという想定で提案を入れてみました。

2024-06-12 10:09 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +ユーザーが一定時間操作しなかった場合、自動でログアウトしたメッセージとログインボタンを表示・実装し、この画面から再ログインができるようにしてください。
```suggestion
一定の時間、ユーザーが操作しなかった場合、自動でログアウトしたことがわかるメッセージとログインボタンを表示します。ログインボタンを押せば、再ログインできるようにしてください。
```

2024-06-12 10:09 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +ユーザーが一定時間操作しなかった場合、自動でログアウトしたメッセージとログインボタンを表示・実装し、この画面から再ログインができるようにしてください。
「この画面から再ログインができる」がログイン画面を表示できるという意味なのか、そのままログインできるのかがわかりませんでした。一旦、後者の意味だと想定して提案を入れています。

2024-06-12 10:10 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +また、先述したエラーではないその他のエラーをまとめて扱う場合にも、この表示内容を使用できます。
```suggestion
また、このページに記載されていないその他のエラーをまとめて扱う場合にも、以下の表示内容を使用できます。
```

2024-06-13 06:43 UTC, Qs-F commented on content/articles/products/components/error-screen.mdx
> +フォームのバリデーションエラーや連携APIの疎通エラーのような一時的なエラーの場合、[NotificationBar](/products/components/notification-bar/)や[ResponsiveMessage](/products/components/response-message/)、[InformationPanel](/products/components
```suggestion
フォームのバリデーションエラーや連携APIの疎通エラーのような一時的なエラーの場合、[NotificationBar](/products/components/notification-bar/)や[ResponseMessage](/products/components/response-message/)、[InformationPanel](/products/components/information-panel/)を使用を検討してください。
```

2024-06-13 06:43 UTC, Qs-F commented on content/articles/products/components/error-screen.mdx
> +### サービスがメンテナンス中の場合
他と揃えるなら通常メンテナンスにはHTTP レスポンスステータスコードの503 Service Unavailableが使われるので、以下でいかがでしょうか

```suggestion
### サービスがメンテナンス中の場合（503 Service Unavailableエラー）
```

2024-06-13 06:43 UTC, Qs-F commented on content/articles/products/components/error-screen.mdx
> +### 予期しないエラーが発生した場合（Unexpectedエラー）
他と揃えるなら通常メンテナンスにはHTTP レスポンスステータスコードの500 Internal Server Errorが使われるので、以下でいかがでしょうか

```suggestion
### 予期しないエラーが発生した場合（500 Internal Server Errorエラー）
```

2024-06-13 09:50 UTC, oti commented on content/articles/products/components/error-screen.mdx
> +ユーザーが一定時間操作しなかった場合、自動でログアウトしたメッセージとログインボタンを表示・実装し、この画面から再ログインができるようにしてください。
プロダクトによってログイン画面に遷移したり、その場で再認証できたりと、プロダクトによって実装がことなっていました。

それを踏まえても提案いただいた文言よさそうです！

2024-06-13 09:59 UTC, oti commented on content/articles/products/components/error-screen.mdx
> +### 予期しないエラーが発生した場合（Unexpectedエラー）
実装上は500に限らなそうだったんですが、
> また、このページに記載されていないその他のエラーをまとめて扱う場合にも、以下の表示内容を使用できます。
この一文を追加したので見出しの方にはステータスコードを書いてもよさそうですね！あざす！

2024-06-13 10:22 UTC, oti commented
@INABAshina 提案ありがとうございました！　どれも納得のものだったので取り込みました！

みなさま、改めてレビューをお願いいたします！ @Qs-F @tosiiu @versionfive

2024-06-13 12:53 UTC, INABAshina reviewed
1点だけ追加で提案とコメントを入れています🙏＞＜

2024-06-13 12:53 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +存在しないページはにアクセスした場合、ページが見つからないだけでなく移動や削除された可能性も表示し、プロダクトのホームへ戻るリンクを提供してください。
```suggestion
存在しないページはにアクセスした原因として、ページ自体が除された可能性やユーザーがURLを間違えている可能性を提示しましょう。プロダクトのホームへ戻るリンクも表示してください。
```

2024-06-13 12:53 UTC, INABAshina commented on content/articles/products/components/error-screen.mdx
> +存在しないページはにアクセスした場合、ページが見つからないだけでなく移動や削除された可能性も表示し、プロダクトのホームへ戻るリンクを提供してください。
メッセージを反映いただいたので、それにあわせて説明文も調整できたほうが良いかなと思いましたがいかがでしょう？

2024-06-14 03:05 UTC, Qs-F submitted a review, later dismissed
個人的には引っかかりポイントがなく、するっと理解できて良い気がしたのでLGTMです！

2024-06-14 07:43 UTC, versionfive reviewed
1点質問とSuggestionをいれております。文言が整ってありがたい…

2024-06-14 12:50 UTC, tosiiu reviewed
既出コメント以外LGTMです！

2024-06-15 02:30 UTC, oti commented on content/articles/products/components/error-screen.mdx
> +  <Text as="p" className="shr-text-center">
ありかどうかわかりません。というかナシである可能性を考えていませんでした……。
キメを教えてほしいです〜 @uknmr

2024-06-18 02:22 UTC, oti commented on content/articles/products/components/error-screen.mdx
> +  <Text as="p" className="shr-text-center">
今今は styled-components で書く、ということでtailwind cssでのクラス指定をトルツメしました！

2024-06-18 02:24 UTC, oti commented
@INABAshina @tosiiu @versionfive @Qs-F 対応漏れなどを作業したらapproveがdismissになっちゃいました。繰り返しで大変恐縮ですが再度確認をお願いいたします🙇

2024-06-18 03:35 UTC, oti commented
補足：SmartHR UI側でErrorScreenのレイアウトを修正する（上下左右の余白、中央揃え）

2024-06-18 04:04 UTC, versionfive reviewed
https://github.com/kufu/smarthr-design-system/pull/1164#issuecomment-2174918733
の前提を確認しました。
1点だけ、フィードバックが生まれたのでそちらにリンクを追加しました。

2024-06-18 04:04 UTC, versionfive commented on content/articles/products/components/error-screen.mdx
> +フォームのバリデーションエラーや連携APIの疎通エラーのような一時的なエラーの場合、[NotificationBar](/products/components/notification-bar/)や[ResponseMessage](/products/components/response-message/)、[InformationPanel](/products/components/i
```suggestion
フォームのバリデーションエラーや連携APIの疎通エラーのような一時的なエラーの場合、[NotificationBar](/products/components/notification-bar/)や[ResponseMessage](/products/components/response-message/)、[InformationPanel](/products/components/information-panel/)などを使用を検討します。詳細は[フィードバック](/products/design-patterns/feedback/)の基準を参照してください。
```
フィードバックに誘導

2024-06-18 04:20 UTC, oti commented
@versionfive フィードバックへの動線を追加しました！

2024-06-18 04:32 UTC, versionfive approved these changes
LGTM!!!明快になってすぐ使える基準が爆誕しましたね！

2024-06-18 04:56 UTC, Qs-F approved these changes
読みやすかったです！！ 👏

2024-06-18 06:17 UTC, tosiiu approved these changes
LGTM!

2024-06-18 07:07 UTC, merged