Inputのガイドラインを加筆
kufu/smarthr-design-system pull request #1172
Opened 2024-05-23 12:44 UTC by Qs-F

## 課題・背景

## やったこと
-

## やらなかったこと
- 

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-05-28 07:52 UTC, tosiiu reviewed
disabled / readOnlyの使用場面について、
submitで送信される/されないのは結果であって、使用の場面としては

- disabled: ユーザーが編集できる値だが、一時的または権限の問題で編集不可なとき
- readOnly: Inputの意匠を残しつつ表示したいが、当該画面でユーザーが編集出来る値ではないとき

と認識していました。
また、InputのreadOnlyはdefinitionListとの使い分け（≒Inputの意匠を残すか）に悩むのでそれについても言及がほしいです！

2024-06-03 01:58 UTC, versionfive reviewed
コメントしましたー

2024-06-03 01:58 UTC, versionfive commented on content/articles/products/components/input/index.mdx
> +## 使用上の注意
SearchInput, CurrencyInputとの使い分けも書いてあると親切かも

2024-06-03 01:58 UTC, versionfive commented on content/articles/products/components/input/index.mdx
> +テキストや数値などの情報を1行で入力するためのコンポーネントです。`input[type="text"]`や`input[type="number"]`などの代わりとして使用します。入力欄の前後にアイコンを入れられます。
アイコンをつけるつけないの基準が気になりました。
ちょうどysym sanがButtonのを更新してくださっていますが（https://github.com/kufu/smarthr-design-system/pull/1169 ）、Inputも基準があると助かりそうです。

2024-06-03 01:58 UTC, versionfive commented on content/articles/products/components/input/index.mdx
> +### 読み取り専用（readOnly）
uraさんのコメントに追加ですが、`Input[disabled]`で触らせたくないが入力要素があることを示しているケースもまだありそうなので（コ比NG）、その場合はreadOnlyで示すべきなパターンかと思いました。

2024-06-03 06:36 UTC, oti requested changes
v5さんとほとんど同じ意見でございました！

2024-06-03 06:39 UTC, Qs-F commented
📝 幅についての言及を増やす

2024-06-14 07:37 UTC, Qs-F commented on content/articles/products/components/input/index.mdx
> +<CurrencyInput
データ型がnumberじゃないのはあるが、基本金額入力には使うで良さそう

2024-06-14 07:42 UTC, Qs-F commented on content/articles/products/components/input/index.mdx
> +検索する語句を入力するためのコンポーネントです。
- Tooltipがだせるものと出せないものがあるってことと
- Tooltip出せるやつの用途 (レイアウトが限られてるときとか、SearchInputの内容を補足する時とか)

2024-06-14 07:43 UTC, Qs-F commented on content/articles/products/components/input/index.mdx
> +検索する語句を入力するためのコンポーネントです。
Tooltip出さなくていいようにする、出さないで使えるのが基本的には良さそうだよね〜ぐらいは会てもいいかも

2024-06-18 01:49 UTC, ayumizu approved these changes
LGTM

2024-06-18 01:57 UTC, Qs-F commented
自分へ: SearchInputのファイル消してね

2024-06-18 02:06 UTC, oti requested changes
気になったところコメントしました！

2024-06-18 03:02 UTC, versionfive reviewed
コメントしましたー

2024-06-18 03:02 UTC, versionfive commented on content/articles/products/components/input/index.mdx
> +#### 単位のテキストの設置判断基準
そうなんだ！
IMOですが実装例があると良さそうに思いました！

2024-06-18 03:28 UTC, Qs-F commented on content/articles/products/components/input/index.mdx
> +  </FormControl>
🦀
FaFilterは機能を想起させるので🔒アイコン(FaLock…的な)にさせてください！

2024-06-18 03:30 UTC, Qs-F commented on content/articles/products/components/input/index.mdx
> +  </FormControl>
そうなんですよね… 自分もこれ迷ったんですが、

- Inputと別で押させる何かを持ってきたくない (ここにbuttonを持ってきたくない) 
- Inputにフォーカスするだけで表示される何か

がほしくて、FaCircleXmarkだと消す操作を想起させるので困ってました、もう少し考えて別案持ってきます！

2024-06-18 03:31 UTC, Qs-F commented on content/articles/products/components/input/index.mdx
> +| 後方（`suffix`） | <Input suffix={<FaCaretDownIcon />} /> | [Combobox](/products/components/combo-box/)のようにフォーカスしたときに特定のUIが表示されるなど、操作を想起させるために使用します。 |
🦀 参考に整理します！

2024-06-18 03:35 UTC, Qs-F commented on content/articles/products/components/input/index.mdx
> +  </FormControl>
ですね… 同じことは感じてはいたのでsuffixのアイコン設定自体を非推奨にすることも視野にちょっと考えます！

https://github.com/kufu/smarthr-design-system/pull/1172#discussion_r1643698228

2024-06-18 03:38 UTC, versionfive commented on content/articles/products/components/input/index.mdx
> +  </FormControl>
- 単位をいれる
- インタラクティブな要素の時✖️ボタンをいれる

みたいなのはある？とか思ったりしました。

2024-06-18 03:52 UTC, Qs-F commented on content/articles/products/components/input/index.mdx
> +  </FormControl>
(単位についてはアイコンの下で言及しております！)
インタラクティブな要素を入れていいんだっけ… が少し気になってるので見てきます

2024-06-18 04:35 UTC, versionfive commented on content/articles/products/components/input/index.mdx
> +  </FormControl>
ごめんなさい、すでに書いてありました:pray:
https://deploy-preview-1172--smarthr-design-system.netlify.app/products/components/input/#h4-4

2024-06-18 07:42 UTC, Qs-F commented on content/articles/products/components/input/index.mdx
> +### SearchInput
なるほどです！Inputの含まれるformの検索ボタンを押すところまでが挙動としてこの削除ボタンに含まっているかどうか、ということですね！どうなんだろう… ちょっと別で聞いてみます！

2024-06-18 07:44 UTC, Qs-F commented on content/articles/products/components/input/index.mdx
> +#### 単位のテキストの設置判断基準
よくよく考えてみると一般的なアイコンについては支援技術の方でつけてくれるのでどっちかっていうとautocompleteつかってね、のほうが正しい気がしてきたので書き換えます！

2024-06-18 09:35 UTC, Qs-F commented on content/articles/products/components/input/index.mdx
> +- レイアウトの都合で入力内容の表示位置を揃えたい場合はアイコンをつけることが可能です。
🦀 ざっと探してない気がしたので丸ごと削りました！

2024-06-18 09:36 UTC, Qs-F commented on content/articles/products/components/input/index.mdx
> +表示領域が確保できない場合、`tooltipMessage`を使用して入力内容に対する説明を補足できます。
そもそもSearchInputがtooltipMessageがrequiredだったので使ってくださいに書き換えました！

2024-06-19 10:45 UTC, Qs-F commented on content/articles/products/components/input/index.mdx
> +### SearchInput
https://kufuinc.slack.com/archives/C018J0A6DCH/p1718763434509419 Slackでのやり取りの結論を追加

2024-06-20 01:30 UTC, tosiiu approved these changes
LGTM!
autocompleteへの言及あるの良いですね〜〜

2024-06-20 02:36 UTC, versionfive approved these changes
LGTM!!

2024-06-20 03:39 UTC, oti approved these changes
LGTM!

2024-06-20 04:49 UTC, merged