よくあるテーブルのガイドラインを更新
kufu/smarthr-design-system pull request #1179
Opened 2024-05-31 12:30 UTC by ayumizu

## やったこと
- 説明文がある場合のレイアウトを削除
- フルスクリーンレイアウトのパターンを追加
- スクロール時の挙動について追加
- TableReelについて追加
- EmptyStateのパターンを修正
- 「並べ替え」セクションを削除
- 画像の修正

## プレビュー

2024-06-03 03:08 UTC, versionfive reviewed
コメントしました。全体的によさそう！一部書いてる途中の状態がみられました。

2024-06-03 03:08 UTC, versionfive commented on content/articles/products/design-patterns/smarthr-table.mdx
> +やむを得ず横スクロールが生じる場合、後述の[TableReel]()を使用して主要な操作を見つけやすくしたり、[フルスクリーンレイアウト]()を使用して表示幅を広げたりできます。
```suggestion
やむを得ず横スクロールが生じる場合、後述の[TableReel](/products/components/table/)を使用して主要な操作を見つけやすくしたり、[フルスクリーンレイアウト](#h3-5)を使用して表示幅を広げたりできます。
```
TableReelは（イマはないけど）Tableの一部。フルスクリーンレイアウトはページ内リンクですかね。

2024-06-03 03:08 UTC, versionfive commented on content/articles/products/design-patterns/smarthr-table.mdx
> +一時操作エリアに置く機能が`テーブルのページ送り`のみの場合、Base外の下部にのみ配置します。このとき、Base内の上部のエリアは表示しないでください。
```suggestion
一時操作エリアに置く機能が`テーブルのページ送り`のみの場合、Base外の下部にのみ配置します。このとき、テーブルの左上に不要な余白が生まれるため、Base内の上部のエリアは表示しないでください。
```
上から理由を持ってきてあえて書きました。

2024-06-03 03:08 UTC, versionfive commented on content/articles/products/design-patterns/smarthr-table.mdx
> +テーブルを閲覧・操作することが主たる業務となりうるとき
途中？

2024-06-03 03:08 UTC, versionfive commented on content/articles/products/design-patterns/smarthr-table.mdx
> +また、縦にスクロールしたとき、ヘッダーを画面上部に固定します。
```suggestion
また、縦にスクロールしたとき、テーブルヘッダー（`thead`）を画面上部に固定します。
```

2024-06-03 03:08 UTC, versionfive commented on content/articles/products/design-patterns/smarthr-table.mdx
> +{TODO: 挙動がわかる資料}
これは埋めてリリース？一旦WIP？

2024-06-03 08:38 UTC, versionfive reviewed
前回から残っているコメント（以下）に加え、加筆部分に少しコメントしました！

https://github.com/kufu/smarthr-design-system/pull/1179/files#r1623736083
https://github.com/kufu/smarthr-design-system/pull/1179/files#r1623737392

2024-06-03 08:38 UTC, versionfive commented on content/articles/products/design-patterns/smarthr-table.mdx
> +横スクロールが生じるとき、重要な情報が隠れてしまうことを防ぐため、`TableReel`を用いて列を固定できます。
```suggestion
横スクロールが生じるとき、重要な情報が隠れてしまうことを防ぐため、[TableReel](/products/components/table/)を用いて列を固定できます。
```
TableReelはコンポーネントなので、該当のページにリンク（まだないけど）

2024-06-06 06:42 UTC, tosiiu reviewed
138行目
> オブジェクトを追加するためのボタンです。「{オブジェクト名}を追加」と表記します。
クリックすると、多くの場合、オブジェクトの追加ダイアログを表示します。

オブジェクト名は基本自明だと思うので、省略する方に倒しても良いかもと思いました！（[権限設定](https://smarthr.design/products/design-patterns/permissions-settings/)はそうしている）

2024-06-06 06:44 UTC, tosiiu reviewed
86行目
> ユーザーの視線導線に合わせ、基本的にオブジェクト名より右側に設置します。

実際には基本右端 or Reelで固定だと思うので、そのように書き換えても良さそうです！

2024-06-06 06:45 UTC, tosiiu reviewed
細かい2点コメントしましたが、その他は全体的に良さそうです！！迷わず設計できそうに思えました！

2024-06-06 07:19 UTC, oti requested changes
~先日話しに挙がっていた「一意のオブジェクト以外へのリンクは表示しない（［表示 →］ボタンなどで別列に表示する）」の話もほしいと思いました！~

![sample](https://github.com/kufu/smarthr-design-system/assets/710216/37d03044-519f-4326-a489-99eb6c065b76)

こちらわたしの勘違いでした！　ご放念ください :bow:

2024-06-07 04:46 UTC, versionfive commented
> 先日話しに挙がっていた「一意のオブジェクト以外へのリンクは表示しない（［表示 →］ボタンなどで別列に表示する）」の話もほしいと思いました！
> 
> ![sample](https://private-user-images.githubusercontent.com/710216/337161044-37d03044-519f-4326-a489-99eb6c065b76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzUxMjEsIm5iZiI6MTcxNzczNDgyMSwicGF0aCI6Ii83MTAyMTYvMzM3MTYxMDQ0LTM3ZDAzMDQ0LTUxOWYtNDMyNi1hNDg5LTk5ZWI2YzA2NWI3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QwNDMzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2RjODNjMWExZTE4MTk4MTllY2U4N2Y3M2FlOTljOTFmMTI2OTMzMTdmMmQwYmJhZWY3M2Q3ZDFlOGNhYjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._aKOEBCIr9UHTUAoB1QFPI2ajLxNNde8gtqV2__NaLQ)

@oti こんな話ありましたっけ…？かならずしもボタンにする必要はないかと思っています。
たとえば、文書配付のテーブルなどでも他のオブジェクトへのリンクがあり、妥当かとおもっています。

![image](https://github.com/kufu/smarthr-design-system/assets/64398878/c26630bf-9592-40dd-a648-b3db9dd4e108)

2024-06-10 08:52 UTC, ayumizu commented
@tosiiu 
> 138行目
> 
> > オブジェクトを追加するためのボタンです。「{オブジェクト名}を追加」と表記します。
> > クリックすると、多くの場合、オブジェクトの追加ダイアログを表示します。
> 
> オブジェクト名は基本自明だと思うので、省略する方に倒しても良いかもと思いました！（[権限設定](https://smarthr.design/products/design-patterns/permissions-settings/)はそうしている）

ここちょっとUXWにも相談したいかも〜と思ったので一旦このPRでは保留にさせてください！

2024-06-10 08:55 UTC, tosiiu submitted a review, later dismissed
LGTM!

2024-06-10 09:10 UTC, ayumizu commented on content/articles/products/design-patterns/smarthr-table.mdx
> +横スクロールが生じるとき、重要な情報が隠れてしまうことを防ぐため、`TableReel`を用いて列を固定できます。
- Tableのページに適切なリンク先がなかったので、一旦ページ内の「TableReel」セクションに飛ばす形にしました。
- TableReelセクションからは、Tableコンポーネントのページに飛べるようにしています。

2024-06-10 09:14 UTC, fumiko-KOSAKA commented on content/articles/products/design-patterns/smarthr-table.mdx
@ayumizu 
140行目の`クリックすると、CSVファイルを登録する一括操作ダイアログを表示するほか、` を
`クリックすると、CSVファイルを追加する一括操作ダイアログを表示するほか、` に修正お願いします！

2024-06-10 09:47 UTC, fumiko-KOSAKA approved these changes

2024-06-10 10:11 UTC, versionfive commented on content/articles/products/design-patterns/smarthr-table.mdx
>  SmartHRに頻出する、表形式で一覧表示するUIのパターンまとめています。
```suggestion
SmartHRに頻出する、表形式で一覧表示するUIのパターンをまとめています。
```
原初からのtypoだ…

2024-06-10 10:11 UTC, versionfive commented on content/articles/products/design-patterns/smarthr-table.mdx
> +</Cluster>
```suggestion
<Cluster gap={{ row: 0, column: 1 }}>
  <DoAndDont
    type="do"
    img={<StaticImage src={noTitleDo} alt="Do" />}
    label={<Text>画面タイトルとテーブルの間に余白ができない場合は省略できる</Text>}
    width="calc(50% - 8px)"
  />
  <DoAndDont
    type="dont"
    img={<StaticImage src={noTitleDont} alt="Dont" />}
    label={<Text>画面タイトルとテーブルの間にテーブル操作エリアがあり、テーブルの左上に不要な余白ができる</Text>}
    width="calc(50% - 8px)"
  />
</Cluster>
```
左右に並べたい場合

2024-06-10 11:32 UTC, ayumizu commented on content/articles/products/design-patterns/smarthr-table.mdx
> +</Cluster>
![image](https://github.com/kufu/smarthr-design-system/assets/99632029/03e8a41c-0b07-4876-a64a-288f02575de0)
やってみたんですが、やはり画像が小さすぎて分かりづらかったので、一旦こちらは対応しないことにします 🙏

2024-06-11 01:18 UTC, versionfive approved these changes
LGTM!!ありがとうございます!

2024-06-11 01:22 UTC, tosiiu approved these changes

2024-06-11 01:36 UTC, oti approved these changes
LGTM :clap:

2024-06-11 01:45 UTC, merged