[WIP] 「余白の取り方」のガイドラインを更新
kufu/smarthr-design-system pull request #1190
Opened 2024-06-12 06:07 UTC by MasafumiKabe

## 課題・背景

## やったこと
-

## やらなかったこと
- 

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-06-20 03:03 UTC, MasafumiKabe commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +ここで示す余白の基準は、必ず従わなければならないものではありません。例外的に基準から外れた余白を設定しても問題ありません。
こんな感じのことを言いたいのですが、いい感じの言い回しが思いつきません…

「例えばどういうときは基準から外れてもいいの？」などが言えたらよさそうだけど、その「どういうとき」が言語化できていません

2024-06-20 03:52 UTC, oremega commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +ここで示す余白の基準は、必ず従わなければならないものではありません。例外的に基準から外れた余白を設定しても問題ありません。
こういう場合に例外にしてよいですというより、「基準を逸脱した余白を取っているとき場合はその理由と効果を説明できるようにしておく」くらいに収めてもいいかも？

2024-06-20 05:04 UTC, versionfive commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +ここで示す余白の基準は、必ず従わなければならないものではありません。例外的に基準から外れた余白を設定しても問題ありません。
310 sanのスタンスよさそう。
「注意点」というセクションはテンプレにはないので、基本的な考え方に含めて良さそうだと思いました

2024-06-20 05:48 UTC, versionfive reviewed
全体的にとてもわかり易く、充実したと思いました！！

2024-06-20 05:48 UTC, versionfive commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +UI設計における余白とは、情報を整理するために設ける要素間のギャップのことを指します。
この1文は定義なので冒頭文に持ってきてほしいです。
https://smarthr.design/operational-guideline/page-template/design-patterns-template/#h2-0

2024-06-20 05:48 UTC, versionfive commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +![スクリーンショット:視線誘導の法則をもとに配置された画面内の要素](./images/spacing-layout-pattern/spacing-layout-pattern7.png)
視線誘導の方の画像もこれに差し替えたい
https://smarthr.design/products/design-patterns/visual-guidance/#h4-3

2024-06-20 05:48 UTC, versionfive commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +[視線誘導](/products/design-patterns/visual-guidance/#h3-1)のとおり、視線は大きいものから小さいものへ移動するため、余白は外側から内側に向かうにつれて狭くすることで、外側の要素から内側の要素に視線を誘導する効果を期待できます。
```suggestion
[視線誘導の「視線は大きいものから小さいものへ移動する」法則](/products/design-patterns/visual-guidance/#h3-1)のとおり、余白は外側から内側に向かうにつれて狭くすることで、外側の要素から内側の要素に視線を誘導する効果を期待できます。
```

2024-06-20 05:48 UTC, versionfive commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +余白の値は8の倍数を使用することが一般的ですが、SmartHRの製品設計においては[プリミティブトークン](/products/design-tokens/spacing/#h2-1)を使用します。
```suggestion
SmartHRの製品設計においては、**基準サイズの16pxを`1`**とした[プリミティブトークン](/products/design-tokens/spacing/#h2-1)を使用します。
```
- 一般的に8pxかはここで書く必要なさそう
- のちに唐突に`2（32px）`と出てくるけど、2がなにかちょっとわかりにくいのでここで`1`がなにかを伝えたい

2024-06-20 05:48 UTC, versionfive commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +- 水平方向に要素を配置する場合は[Cluster](/products/components/layout/cluster/)を使用し、`gap` propsにマージンを設定してください。
```suggestion
- 水平方向に要素を配置する場合は[Cluster](/products/components/layout/cluster/)や[Reel](/products/components/layout/reel/)を使用し、`gap` propsにマージンを設定してください。
```

2024-06-20 05:48 UTC, versionfive commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +#### アイコンやラベルなどの小さい要素間のマージン
前提として、基本的にはコンポーネントで確保されていることが多い（からそんなに気にしなくていい）、ということを伝えたいです。

2024-06-20 05:48 UTC, versionfive commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +  - [TextLink](/products/components/text-link/)に `prefix` や `suffix` propsを指定することで、この余白が自動的に適用されます。
箇条書きですが、全体的に読み取りにくいので、もう少し項目と説明に一貫性をもたせたリストにするか、表とかがいいのだろうか…

2024-06-20 05:48 UTC, versionfive commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +![スクリーンショット:代表的なダイアログ内レイアウトのマージン](./images/spacing-layout-pattern/spacing-layout-pattern2.png)
上の説明に対応するよう、画像内の余白の色を変えていると思いますが、説明を読みながら画像のどこに該当するか把握するのがちょっと大変でした。
レイアウトの説明で出てくるような番号を振ったりするとわかりやすいかも…？

2024-06-20 06:36 UTC, uknmr commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +余白の値は8の倍数を使用することが一般的ですが、SmartHRの製品設計においては[プリミティブトークン](/products/design-tokens/spacing/#h2-1)を使用します。
1 であり1文字分・標準文字サイズの1文字分、とも言えるから、1.5文字分などとも書けそう。

2024-06-21 02:23 UTC, MasafumiKabe commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +![スクリーンショット:視線誘導の法則をもとに配置された画面内の要素](./images/spacing-layout-pattern/spacing-layout-pattern7.png)
:sumi: [8190714](https://github.com/kufu/smarthr-design-system/pull/1190/commits/8190714804d14ebf24ca7dc7b3f5f3ef3432bcc9)

2024-06-21 02:38 UTC, drivesketch approved these changes
分かりやすく、読みやすかったです。欲しかったものでした。
いくつかIMOなsuggestion入れてますが、基本LGTMです。

2024-06-21 02:38 UTC, drivesketch commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
ファイル構成、後者のほうが良い（もし今後、全体構成に変更が入った際に、対応が楽）と思います。

```
design-patterns/
├ images/spacing-layout-pattern/
│  └（画像群）
└spacing-layout-pattern.mdx
```
↓↓↓
```
design-patterns/
└ spacing-layout-pattern/
  ├ index.mdx
  └ images/
    └ （画像群）
```

2024-06-21 02:38 UTC, drivesketch commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
パスも
`margin-padding` 
とかのほうがシンプルでいいかも（IMO）

2024-06-21 02:38 UTC, drivesketch commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +
```suggestion
## 考慮する法則
SmartHRの製品開発では、人間の認知に関する以下の法則を考慮して余白を設計します。

```

`余白に関する` は自明なので取ってよいかと。

2024-06-21 02:44 UTC, MasafumiKabe commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +UI設計における余白とは、情報を整理するために設ける要素間のギャップのことを指します。
移動しました！ [1fc06b1](https://github.com/kufu/smarthr-design-system/pull/1190/commits/1fc06b130d1ac719855d30cf91a18e2926c5d6cd)

2024-06-21 02:46 UTC, MasafumiKabe commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +ここで示す余白の基準は、必ず従わなければならないものではありません。例外的に基準から外れた余白を設定しても問題ありません。
よさそうなので取り入れました！ [14d6244](https://github.com/kufu/smarthr-design-system/pull/1190/commits/14d6244b6eea6f1e43a7ec8169ffe94dcafd7ba6)

2024-06-21 03:36 UTC, MasafumiKabe commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
よさそう！最後に対応します！

2024-06-21 09:12 UTC, versionfive commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +- 同じ意味階層となる要素同士は、ぞれぞれ同じ大きさのマージンを適用する。
階層が深くなったので、この下にToC的なリンクリストがあると便利そうと思いました。

2024-06-21 09:37 UTC, MasafumiKabe commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +- 同じ意味階層となる要素同士は、ぞれぞれ同じ大きさのマージンを適用する。
こんな感じで追加してみました！ [b4ccc73](https://github.com/kufu/smarthr-design-system/pull/1190/commits/b4ccc73e2cac8093c1e9964596e56853055ae3bd)

2024-06-21 09:44 UTC, versionfive commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +  - [アイコンやラベルなどの小さい要素間のマージン](/products/design-patterns/spacing-layout-pattern/#h5-4)
```suggestion
- 垂直方向のマージン
  - [代表的なページ内レイアウトのマージン](#h5-0)
  - [代表的なダイアログ内レイアウトのマージン](#h5-1)
  - [見出しとコンテンツのマージン](#h5-2)
  - [小さい要素間のマージン](#h5-3)
- 水平方向のマージン
  - [アイコンやラベルなどの小さい要素間のマージン](#h5-4)
```
ページ内リンクなのでアンカーだけでよさそう

2024-06-24 07:44 UTC, tosiiu commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +  - [BaseColumn](/products/components/base-column/)を使用することで、自動的に適用されます。
```suggestion
  - [BaseColumn](/products/components/base/base-column/)を使用することで、自動的に適用されます。
```

2024-06-24 07:44 UTC, tosiiu commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +  - [BaseColumn](/products/components/base-column/)を使用することで、自動的に適用されます。
```suggestion
  - [BaseColumn](/products/components/base/base-column/)を使用することで、自動的に適用されます。
```

2024-06-24 07:53 UTC, tosiiu reviewed
細かい点だけコメントしましたが、全体的にはLGTMです！分かりやすい〜〜
Slackでコメントされていた画像についても理解は出来ると思いました。ただ、画像に書かれたpx数から推察することしか出来なかったので何らか説明文と紐づけられるとより分かりやすいだろうと思いました！

2024-06-24 07:53 UTC, tosiiu commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +UI設計における余白とは、情報を整理するために設ける要素間のギャップのことを指します。
「要素間のギャップ」の意味がパッと分からなかったのでIMOですがsuggestです！
```suggestion
UI設計における余白とは、情報を整理するために設ける要素間の視覚的な距離のことを指します。  
```

2024-06-24 08:04 UTC, uknmr commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +- 画面内のメインコンテンツのパディング：`2（32px）`
nits: ここだけ「画面内の」と合ったが不要そう

```suggestion
- メインコンテンツのパディング：`2（32px）`
```

2024-06-25 02:40 UTC, oti requested changes
ALTにsuggestionをしました！

2024-06-25 02:40 UTC, oti commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +コンポーネント内で確保されているものが多いため、基本的に開発者が設定する必要はありません。
[IMO]CheckBoxやRadioButtonは単品のコンポーネントしかないのでそこは補足してあげると丁寧だと思います。

```suggestion
FormControl内のマージンはコンポーネントで確保されているため、基本的に開発者が設定する必要はありません。CheckBox同士とRadioButton同士のマージンはStackやClusterを使用してください。
```

2024-06-25 02:40 UTC, oti commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +![スクリーンショット:小さい要素間のマージン](./images/spacing-layout-pattern/spacing-layout-pattern4.png)
ここは0.5と1があるので、余白を色分けしたキャプチャの方が良いと思いました。その前提でALTもsuggestionしてます。

```suggestion
![スクリーンショット:小さい要素間のマージンの例。ブロックタイトルや要素同士の余白の大きさが色分けされて示されている。](./images/spacing-layout-pattern/spacing-layout-pattern4.png)
```

2024-06-25 02:40 UTC, oti commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +![スクリーンショット:アイコンやラベルなどの小さい要素間のマージン](./images/spacing-layout-pattern/spacing-layout-pattern9.png)
こちらも大きさごとに色分けされたキャプチャがいいと思います。

```suggestion
![スクリーンショット:アイコンやラベルなどの小さい要素間のマージン。インラインで配置される要素間の余白の大きさが色分けされて示されている。](./images/spacing-layout-pattern/spacing-layout-pattern9.png)
```

2024-06-25 02:40 UTC, oti commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +![スクリーンショット:代表的なページ内レイアウトのパディング](./images/spacing-layout-pattern/spacing-layout-pattern5.png)
```suggestion
![スクリーンショット:代表的なページ内レイアウトのパディングの例。コンテンツ内のパディングの大きさが色分けされて示されている。](./images/spacing-layout-pattern/spacing-layout-pattern5.png)
```

2024-06-25 02:40 UTC, oti commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +![スクリーンショット:代表的なダイアログ内レイアウトのパディング](./images/spacing-layout-pattern/spacing-layout-pattern6.png)
```suggestion
![スクリーンショット:代表的なダイアログ内レイアウトのパディングの例。コンテンツ内のパディングの大きさが色分けされて示されている。](./images/spacing-layout-pattern/spacing-layout-pattern6.png)
```

2024-06-25 08:20 UTC, uknmr commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
IMO: `/spacing` でよさそう（リダイレクトしないとだから変えなくてもよさそう

2024-06-25 08:23 UTC, oti requested changes
配置が難しいところもあると思いますが①②③のような数字は全部の画像にあって良いと思いました。

また、「小さい要素間のマージン」と「水平方向のマージン」の画像も、サイズごとに色が変わった画像になっていると全体が揃って見やすくなると思います！

2024-06-25 08:27 UTC, uknmr commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +ここでは、マージン（Margin）やパディング（Padding）などの余白のパターンをシーン別にまとめています。
nits: （元の言葉だけど）シーンに違和感あるし、シーン別でもないので消せそう。

```suggestion
ここでは、マージン（Margin）やパディング（Padding）などの余白のパターンをまとめています。
```

2024-06-25 08:39 UTC, uknmr reviewed
細かいのコメントしたけど無視でも大丈夫です!

2024-06-25 08:39 UTC, uknmr commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +適切な余白を設定することで、ユーザーの素早く、正しい情報の理解を助けることができます。
nits: することができる

```suggestion
適切な余白を設定することで、ユーザーの素早く、正しい情報の理解を助けられます。
```

2024-06-25 08:39 UTC, uknmr commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +開発者は[Layoutコンポーネント](/products/components/layout/)を使う場合や、コンポーネントを組み合わせて画面に配置する場合に、下記を参考に適切な余白を設定してください。
imo: 改行なくてもよさそう

```suggestion
UI設計において開発者は適切な余白について意識することが重要ですが、[SmartHR UIのコンポーネント](/products/components/)の中には、あらかじめ適切な余白が設定されており、余白の選定を意識することなく利用できるものがあります。[Layoutコンポーネント](/products/components/layout/)を使う場合や、コンポーネントを組み合わせて画面に配置する場合に、下記を参考に適切な余白を設定してください。
```

2024-06-25 08:39 UTC, uknmr commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +関連性の高い要素には小さな余白、関連性の低い要素には大きな余白を設定することで、情報のまとまりをユーザーに認識させることができます。
nits: することができるの書き換え

```suggestion
関連性の高い要素には小さな余白、関連性の低い要素には大きな余白を設定することで、ユーザーは情報のまとまりを認識できます。
```

2024-06-25 08:39 UTC, uknmr commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +SmartHRの製品設計においては、**基準サイズの16pxを`1`**とした[プリミティブトークン](/products/design-tokens/spacing/#h2-1)を使用します。
imo: あまり見かけない言葉だしトれそう

```suggestion
SmartHRにおいては、**基準サイズの16pxを`1`**とした[プリミティブトークン](/products/design-tokens/spacing/#h2-1)を使用します。
```

2024-06-25 08:39 UTC, uknmr commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +- 原則、要素に対して上方向に適用する。
imo: 賛否あるし、gap で指定することもあるので削ってよさそう

2024-06-25 10:47 UTC, MasafumiKabe commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +- 原則、要素に対して上方向に適用する。
🦀 なので削りました [e00ac9d](https://github.com/kufu/smarthr-design-system/pull/1190/commits/e00ac9db2bcf4f717433d3cbab800bc98323a233)

2024-06-25 10:49 UTC, MasafumiKabe commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
> +コンポーネント内で確保されているものが多いため、基本的に開発者が設定する必要はありません。
箇条書きの中に追記しました！

2024-06-25 11:01 UTC, MasafumiKabe commented on content/articles/products/design-patterns/spacing-layout-pattern.mdx
ファイル構成を変更しました！ [61a0a7e](https://github.com/kufu/smarthr-design-system/pull/1190/commits/61a0a7e057bef25b0cb4f692f1a8bc9fb8aa3cd9)

パスはuさんのおっしゃる通りリダイレクトを考慮する必要があるので、ここでは対応しないことにしました 🙇

2024-06-26 01:20 UTC, oti approved these changes
LGTM!

2024-06-26 01:34 UTC, wentzzz approved these changes
偉業

2024-06-26 01:53 UTC, versionfive approved these changes
1件nitsですが、LGTMですー

2024-06-26 01:53 UTC, versionfive commented on content/articles/products/design-patterns/spacing-layout-pattern/index.mdx
> +    - [Stack](/products/components/layout/stack/)を使用して余白を指定してください。
[nits]L122の方にはCluster使ってね、がないかも？

2024-06-26 01:57 UTC, MasafumiKabe commented on content/articles/products/design-patterns/spacing-layout-pattern/index.mdx
> +    - [Stack](/products/components/layout/stack/)を使用して余白を指定してください。
🦀 なので追記しました！ [ab2977e](https://github.com/kufu/smarthr-design-system/pull/1190/commits/ab2977e248323aa798f2f8fe13040e8f92f792c3)

2024-06-26 11:36 UTC, o-kwr approved these changes
LGTM！偉業！

2024-06-27 00:16 UTC, tosiiu approved these changes
LGTM!

2024-06-27 00:50 UTC, merged