TabBarの基準を追加
kufu/smarthr-design-system pull request #1199
Opened 2024-06-14 05:59 UTC by o-kwr

## 課題・背景

## やったこと
- TabBarの使い方・概要文を更新

## 動作確認

2024-06-14 06:26 UTC, tosiiu reviewed
下線を付けるか付けないか悩むことがあるので基準が欲しいです！

2024-06-14 06:40 UTC, versionfive reviewed
TabBarItem内に数字を出すケースがプロダクトで散見されているので、表示パターンを決めてくれるとうれしいなと思いました。

2024-06-14 08:46 UTC, oti requested changes
コメントしました！

2024-06-14 08:46 UTC, oti commented on content/articles/products/components/tab-bar.mdx
> +TabBarは扱うオブジェクトを問わず、ビューを切り替えるために使えるコンポーネントですが、特定のオブジェクトの異なる状態を切り替えて表示する場合[SegmentedControl](/products/components/segmented-control/)を使ってください。
「扱うオブジェクトを問わず、ビューを切り替えるため」に「特定のオブジェクトの異なる包帯を切り替えて表示する場合」が対応する説明になっていないと感じました。

また、「特定のオブジェクト」という表現は「とあるオブジェクト」くらいの重さで使っているように感じるので、であれもっと明確に「同じオブジェクトについて」と言い換えてしまってよいと思いました。

```suggestion
### 同じオブジェクトの状態を切り替えて表示する目的に使用しない

TabBarは異なるオブジェクトを切り替えるために使用してください。同じオブジェクトについて異なる状態を切り替えたい場合は[SegmentedControl](/products/components/segmented-control/)の使用を検討してください。
```

2024-06-18 04:16 UTC, oti requested changes
1点コメントしました！

2024-06-18 04:16 UTC, oti commented on content/articles/products/components/tab-bar.mdx
> +            <FaCircleExclamationIcon color="Danger" alt="エラーあり"/>
```suggestion
            <FaCircleExclamationIcon color="DANGER" alt="エラーあり"/>
```
color props の値は大文字っぽい

2024-06-19 11:34 UTC, uknmr approved these changes
gogo!

2024-06-21 05:41 UTC, ayumizu commented on content/articles/products/components/tab-bar.mdx
> +下線なし（bordered=false）のTabBarは、タブとしての認知がしにくくビューへの影響範囲が不明瞭なため、非推奨です。
使用上の注意に書いてもいいのかも

2024-06-21 05:45 UTC, ayumizu commented on content/articles/products/components/tab-bar.mdx
> +### 下線部の使い分け
セクション迷うのですが、使い分けと言うよりは基本「使う」一択だと思うので、使用上の注意にあっても良いのかな〜と思いました！

2024-06-21 07:28 UTC, oti requested changes
ayumizu さんと同意見でした！

2024-06-21 09:01 UTC, oti approved these changes
LGTM！

2024-06-21 09:02 UTC, versionfive approved these changes
順番だけ変えるSuggestionしましたがLGTMです

2024-06-21 09:02 UTC, versionfive commented on content/articles/products/components/tab-bar.mdx
> +![スクリーンショット: 下線なしのTabBar](./images/smarthr-tab-bar-bordered-minimum.png)
```suggestion
### 同じオブジェクトの異なる状態を切り替えて表示する目的に使用しない
TabBarは異なるオブジェクトやビューを切り替えるために使用してください。同じオブジェクトについて異なる状態を切り替えたい場合は[SegmentedControl](/products/components/segmented-control/)の使用を検討してください。

### 下線なし（`bordered=false`）のTabBarは非推奨
タブとして操作できるか認知がしにくく、ビューへの影響範囲が不明瞭なため、下線なしのTabBarは非推奨です。

### 下線によって影響範囲を明示する
TabBarは、下線によって影響するビューの範囲を明示して使用してください。

![スクリーンショット: 標準のTabBar](./images/smarthr-tab-bar-bordered-true.png)

下線が他のコンポーネントと競合する場合、最低限TabBarItemがある範囲までは下線が必要です。

![スクリーンショット: 下線なしのTabBar](./images/smarthr-tab-bar-bordered-minimum.png)
```

2024-06-21 09:08 UTC, tosiiu approved these changes
LGTM!

2024-06-21 09:28 UTC, merged