FilterDropdownの使い分けを追加
kufu/smarthr-design-system pull request #1217
Opened 2024-06-24 07:32 UTC by o-kwr

## 課題・背景
FilterDropdownの基準充足です。

## やったこと
- FilterDropdownの使い分けを追加
- 上位ページのDropdownに各コンポーネントの概要を追記

## 動作確認

2024-06-24 08:12 UTC, versionfive commented on content/articles/products/components/dropdown/index.mdx
> +表の並べ替え操作を統一するためのコンポーネントです。並べ替え項目と並び順を指定でき、ボタンラベルとアイコンで現在の並び順を表します。
PageIndexを使うと楽かもです。
https://github.com/kufu/smarthr-design-system/blob/main/content/articles/products/components/combo-box/index.mdx?plain=1#L10

2024-06-24 08:12 UTC, versionfive commented on content/articles/products/components/dropdown/filter-dropdown.mdx
> +絞り込みのロジックが複雑で、DropdownContentのパネルでは十分にエリアが確保できない場合、Dialogの使用を検討してください。
```suggestion
### 絞り込みのUIが複雑で、エリアを十分に確保できない場合はDialogを使用する
[よくあるテーブル](/products/design-patterns/smarthr-table/)やその他一覧画面で絞り込みを行なうとき、パネル内に[CheckBox](/products/components/check-box/)や[RadioButton](/products/components/radio-button/)、[DatePicker](/products/components/date-picker/)などを配置することでユースケースを達成できる場合はFilterDropdownを使用してください。
絞り込みのUIが複雑で、ドロップダウンパネルではエリアを十分に確保できない場合、Dialogの使用を検討してください。
```
SegmentedControlと合わせてみました。
また、ロジックの複雑さとエリアの確保は依存しきらないとおもったので、UIにしてみました。

2024-06-25 01:14 UTC, oti commented on content/articles/products/components/dropdown/filter-dropdown.mdx
> +絞り込みのロジックが複雑で、DropdownContentのパネルでは十分にエリアが確保できない場合、Dialogの使用を検討してください。
@versionfive [ASK] Dialogを使用する場合も、FilterDropdownのボタンから呼び出していいんでしょうか？

その場合はFaFilterアイコンをprefixにした［フィルター］ボタンだと思っていたので、であればその旨も示されていると良さそうです。

```suggestion
### FilterDropdownの使い分け
[よくあるテーブル](/products/design-patterns/smarthr-table/)やその他一覧画面で絞り込みを行なうとき、パネル内にCheckBoxやRadioButtonなどを配置することでユースケースを達成できる場合はFilterDropdownを使用してください。
絞り込みのロジックが複雑で、DropdownContentのパネルでは十分にエリアが確保できない場合、Dialogの使用を検討してください。その際、Dialogの呼び出しはFilterDropdownではなくフィルターボタンを使用してください。

```tsx editable codeBlock
<Button variant="text" prefix={<FaFilter />}>フィルター</Button>
```

```

2024-06-25 01:31 UTC, versionfive commented on content/articles/products/components/dropdown/filter-dropdown.mdx
> +絞り込みのロジックが複雑で、DropdownContentのパネルでは十分にエリアが確保できない場合、Dialogの使用を検討してください。
@oti たしかに、Dialogを呼ぶ場合はFilterDropdownのボタンから呼び出すのではなく、「フィルター」ボタンを想定していました！

2024-06-25 06:59 UTC, oti requested changes
2点コメントしました！

2024-06-25 06:59 UTC, oti commented on content/articles/products/components/dropdown/filter-dropdown.mdx
> +
Suggestionしておいてなんですが、「フィルターボタン」はデザインシステムのユビキタス言語ではないので、codeBlockか画像で示してあげないといけない気がしました。

2024-06-25 06:59 UTC, oti commented on content/articles/products/components/dropdown/filter-dropdown.mdx
> +絞り込みのUIが複雑で、ドロップダウンパネルではエリアを十分に確保できない場合、Dialogの使用を検討してください。その際、Dialogの呼び出しはFilterDropdownではなくフィルターボタンを使用してください。
デプロイを見ると改行がないので、「絞り込みUIが複雑で〜」の前で一行空けたいです。

2024-06-25 07:19 UTC, tosiiu reviewed
hasStatusTextを付ける/付けないの基準がほしいです！

2024-06-25 09:52 UTC, versionfive commented on content/articles/products/components/dropdown/index.mdx
> +<PageIndex path="/products/components/dropdown/" excludes={[]} heading="h2" />
```suggestion
<PageIndex path="/products/components/dropdown/" excludes={[]} heading="h3" />
```
importしてなくて表示されてなさそうですー
あと、h2に続く節なのでheadingはh3かと

2024-06-27 07:27 UTC, versionfive reviewed
コメントしました

2024-06-27 07:27 UTC, versionfive commented on content/articles/products/components/dropdown/filter-dropdown.mdx
> +絞り込みのUIが複雑で、ドロップダウンパネルではエリアを十分に確保できない場合、Dialogの使用を検討してください。その際、Dialogの呼び出しはFilterDropdownではなく`フィルターボタン`を使用してください。
```suggestion
絞り込みのUIが複雑で、ドロップダウンパネルではエリアを十分に確保できない場合、Dialogの使用を検討してください。その際、Dialogの呼び出しはFilterDropdownではなく「フィルター」ボタンを使用します。
```

2024-06-27 07:27 UTC, versionfive commented on content/articles/products/components/dropdown/filter-dropdown.mdx
> +* 「3件の雇用形態を選択中」といった絞り込み条件を表示して、DropdownContentを開かなくてもわかるようにする
```suggestion
### 絞り込み状態をわかりやすく明示する場合は「適用中」ラベルを表示する
FilterDropdownは絞り込み状態であることをアイコンの変化によって示しますが、より明示的に絞り込み状態を伝えたい場合は、`hasStatusText` propsを使用して「適用中」ラベルを表示することを検討します。
```
「適用中」のラベルは基本的に変えない前提の認識で提案してみます。

2024-06-27 07:30 UTC, o-kwr commented on content/articles/products/components/dropdown/filter-dropdown.mdx
> +* 「3件の雇用形態を選択中」といった絞り込み条件を表示して、DropdownContentを開かなくてもわかるようにする
そうしましょう！

2024-06-27 09:46 UTC, MasafumiKabe reviewed
内容的にはLGTMですが、スレで議論している hasStatusText の是非の結論が出てから approve します！

2024-06-27 10:10 UTC, oti requested changes
LGTMですが念の為のsuggestionしました！

2024-06-27 10:10 UTC, oti commented on content/articles/products/components/dropdown/filter-dropdown.mdx
> +`hasStatusText`Propsは絞り込みがされているときに「適用中」と表示するために使われますが、アイコンでの識別とaria-labelでのアクセシビリティの担保がされており、過剰なラベルとなるため非推奨です。
```suggestion
`hasStatusText` propsは絞り込みがされているときにボタンの横に「適用中」と表示するために使われますが、アイコンでの識別とaria-labelでのアクセシビリティの担保がされており、過剰なラベルとなるため非推奨です。
```

2024-06-27 10:19 UTC, MasafumiKabe commented on content/articles/products/components/dropdown/filter-dropdown.mdx
> +### `hasStatusText`は非推奨
逆に見づらくなるかもなので、囲わなくていいかも？
```suggestion
### hasStatusTextは非推奨
```

<img width="287" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/42249033/d8d0b57b-abf1-40b8-8faa-6d61fd0647aa">

2024-06-28 00:24 UTC, tosiiu approved these changes
LGTM!

2024-06-28 01:01 UTC, MasafumiKabe approved these changes
GOGO!

2024-06-28 01:07 UTC, versionfive commented on content/articles/products/components/dropdown/filter-dropdown.mdx
> +絞り込みのUIが複雑で、ドロップダウンパネルではエリアを十分に確保できない場合、Dialogの使用を検討してください。その際、Dialogの呼び出しはFilterDropdownではなく「フィルター」ボタンを使用します。
```suggestion
絞り込みのUIが複雑で、ドロップダウンパネルではエリアを十分に確保できない場合、[ActionDialog](/products/components/dialog/action-dialog/)の使用を検討してください。その際、ActionDialogの呼び出しはFilterDropdownではなく「フィルター」ボタンを使用します。
```
ActionDialogしかあり得なさそう

2024-06-28 01:08 UTC, o-kwr commented on content/articles/products/components/dropdown/filter-dropdown.mdx
> +絞り込みのUIが複雑で、ドロップダウンパネルではエリアを十分に確保できない場合、Dialogの使用を検討してください。その際、Dialogの呼び出しはFilterDropdownではなく「フィルター」ボタンを使用します。
よさそみ

2024-06-28 01:13 UTC, versionfive approved these changes

2024-06-28 01:13 UTC, versionfive commented on content/articles/products/components/dropdown/filter-dropdown.mdx
> +### 絞り込みのUIが複雑で、エリアを十分に確保できない場合はDialogを使用する
```suggestion
### 絞り込みのUIが複雑で、エリアを十分に確保できない場合はActionDialogを使用する
```

2024-06-28 01:15 UTC, oti requested changes
:pray:

2024-06-28 01:15 UTC, oti commented on content/articles/products/components/dropdown/filter-dropdown.mdx
> +</>
nitsで申し訳ないんですが空JSXで囲まなくても良さそうです。

```suggestion
<Button prefix={<FaFilterIcon />}>フィルター</Button>
```

2024-06-28 01:24 UTC, merged