SideNavの使用基準を追加
kufu/smarthr-design-system pull request #1219
Opened 2024-06-24 08:11 UTC by o-kwr

## 課題・背景
SideNavの基準充足。

## やったこと
- SideNavの定義と使い分けを追記した

## 動作確認

2024-06-24 08:43 UTC, oti requested changes
SideNav > TabBar とか、TabBar > SideNav の両パターンある気がしました。

どちらも同じレベルの粒度のオブジェクトが扱えて、縦並びか横並びかの違いが大きそうに思います。

他で言うと、SideNav > SideNav や TabBar > TabBar のように同じナビゲーションコンポーネントで入れ子にしない、というようなことが注意として言えそうです。

2024-06-25 09:57 UTC, versionfive commented on content/articles/products/components/side-nav.mdx
> +スタックするアイテム数が多いときの使用やナビゲーションとしての機能を持たせたいときに適していますが、そうでない場合はTabBarの使用も検討してみてください。
よさそう。
そういえば、Dialog内だとTabBarより使われがちだなーと思い出しました。

2024-06-25 09:57 UTC, versionfive commented on content/articles/products/components/side-nav.mdx
> +### 入れ子のように配置して使用しない
```suggestion
### 入れ子で使用しない
```

2024-06-25 09:57 UTC, versionfive commented on content/articles/products/components/side-nav.mdx
> +ビューを適切な単位で分割し、切り替えるためのコンポーネントです。主に項目設定のビューを切り替えるときに使います。
```suggestion
ビューを適切な単位で分割して縦方向に並べ、切り替えるためのコンポーネントです。項目設定のビューを切り替えるときなどに使います。
```
[Proposal]TabBarとの違い感をだしてみました

2024-06-25 09:57 UTC, versionfive commented on content/articles/products/components/side-nav.mdx
> +description: 'ビューを適切な単位で分割し、切り替えるためのコンポーネントです。'
```suggestion
description: 'ビューを適切な単位で分割して縦方向に並べ、切り替えるためのコンポーネントです。'
```

2024-06-26 02:09 UTC, uknmr commented on content/articles/products/components/side-nav.mdx
> +スタックするアイテム数が多いときの使用やナビゲーションとしての機能を持たせたいときに適していますが、そうでない場合はTabBarの使用も検討してみてください。
nits: 改行と日本語を手直し

```suggestion
SideNavは、異なるオブジェクトやビューを縦方向にスタックし、切り替えるためのコンポーネントです。スタックするアイテムが多いときやナビゲーション機能を持たせたいときに適していますが、そうでない場合はTabBarの使用を検討してください。
```

2024-06-26 02:09 UTC, uknmr commented on content/articles/products/components/side-nav.mdx
> +同様に、TabBar内のビューでさらにビューを分割したい場合はSideNavを使用してください。
nits: 改行と日本語を手直し

```suggestion
SideNavの影響範囲内にあるビュー中では、SideNavの使用を避けてください。SideNav内のビューを分割したい場合はTabBarを使用してください。また、TabBar内でビューを分割したい場合はSideNavを使用してください。
```

2024-06-27 00:42 UTC, tosiiu commented on content/articles/products/components/side-nav.mdx
> +スタックするアイテム数が多いときの使用やナビゲーションとしての機能を持たせたいときに適していますが、そうでない場合はTabBarの使用も検討してみてください。
結構読み手に判断を任せているので、TabBarとSideNavの明確な使い分けがあるなら知りたいな〜と思いました。
ただ、私もそれがなんなのかパッと基準化できる書き方が思いついていないので難しければ今の記載でgogoです！

2024-06-27 05:25 UTC, o-kwr commented on content/articles/products/components/side-nav.mdx
> +スタックするアイテム数が多いときの使用やナビゲーションとしての機能を持たせたいときに適していますが、そうでない場合はTabBarの使用も検討してみてください。
oti sanと話してる中では、用途としての明確な使い分けは実はそんなになくて、縦にスタックしたいのか横にスタックしたいのかの違いしかないのでは？となりました！

2024-06-27 05:47 UTC, uknmr commented on content/articles/products/components/side-nav.mdx
> +スタックするアイテム数が多いときの使用やナビゲーションとしての機能を持たせたいときに適していますが、そうでない場合はTabBarの使用も検討してみてください。
ユーザーが追加できるなど、アイテムの数が読めない場合は垂直方向にスタックする → SideNav
みたいな判断軸は提供できるかも?

2024-06-27 07:05 UTC, ytysym approved these changes
全体読んでみて、どういったときにSideNavを使えばいいかの指針になっていそうなので、LGMTです（些末なところだけ一点コメントしました）

2024-06-27 07:05 UTC, ytysym commented on content/articles/products/components/side-nav.mdx
> +SideNavの影響範囲内にあるビュー中では、SideNavの使用を避けてください。SideNav内のビューを分割したい場合はTabBarを使用してください。また、TabBar内でビューを分割したい場合はSideNavを使用してください。
```suggestion
SideNavの影響範囲内のビューでは、SideNavの使用を避けてください。SideNav内のビューを分割したい場合はTabBarを使用してください。また、TabBar内でビューを分割したい場合はSideNavを使用してください。
```
やや冗長な気がしたので、すっきりさせてみました。（内と中が重複していたと、以降の「内のビュー」とも対応させたい）

2024-06-27 07:15 UTC, versionfive approved these changes
ysym sanのコメントに同意でほかはLGTMですー

2024-06-27 07:40 UTC, uknmr approved these changes
GoGo!
（TabBar との使い分けは、言語化できた時に足せばよいじゃろ、の気持ち）

2024-06-27 08:03 UTC, tosiiu commented on content/articles/products/components/side-nav.mdx
> +スタックするアイテム数が多いときの使用やナビゲーションとしての機能を持たせたいときに適していますが、そうでない場合はTabBarの使用も検討してみてください。
> ユーザーが追加できるなど、アイテムの数が読めない場合は垂直方向にスタックする → SideNav
ありそう

2024-06-27 09:24 UTC, merged