Add defaultvalue
kufu/smarthr-design-system pull request #1227
Opened 2024-06-27 01:48 UTC by oremega

## 課題・背景

## やったこと
-

## やらなかったこと
- 

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-06-27 06:58 UTC, versionfive reviewed
コメントしました

2024-06-27 06:58 UTC, versionfive commented on content/articles/products/design-patterns/default_value.mdx
> +description: '画面を開いたときにあらかじめ入力、もしくは選択されている値をまとめています。'
```suggestion
description: '画面を開いたときにあらかじめ入力、もしくは選択されている値の基準をまとめています。'
```

2024-06-27 06:58 UTC, versionfive commented on content/articles/products/design-patterns/default_value.mdx
> +以下、デフォルト値についてまとめています。
```suggestion
```
まぁそうなので

2024-06-27 06:58 UTC, versionfive commented on content/articles/products/design-patterns/default_value.mdx
> +また、ユーザーが入力を間違えてもあとから変更可能な状態にしてください。
```suggestion

- デフォルト値を設定することでユーザーが意図しない入力や選択を強いられる場合には、**何も選択していない状態**を設定してください。
- ユーザーが入力を間違えてもあとから変更可能な状態にしてください。
```
>また、ユーザーが入力を間違えても

がどこにかかっているかわからなかったです。なんの入力を間違えている状況でしょうか？

2024-06-27 06:58 UTC, versionfive commented on content/articles/products/design-patterns/default_value.mdx
> +デフォルト値には以下のような値を設定してください。
```suggestion
デフォルト値を設定する場合は、以下のような値を検討してください。
```

2024-06-27 08:44 UTC, oremega commented on content/articles/products/design-patterns/default_value.mdx
> +また、ユーザーが入力を間違えてもあとから変更可能な状態にしてください。
かかってないので調整します。

2024-06-27 10:43 UTC, oremega commented on content/articles/products/design-patterns/default_value.mdx
> +また、ユーザーが入力を間違えてもあとから変更可能な状態にしてください。
箇条書きをそのまま取り込む

2024-06-28 07:57 UTC, uknmr commented on content/articles/products/components/check-box/index.mdx
> +- あらかじめ値を選択した状態で表示する場合は、[デフォルト値](/products/design-patterns/default_value/)を参照してください。
どんな時に「あらかじめ値を選択するのか」が知りたいことだったりしないかしら?
「あらかじめ選択した状態 = デフォルト」はそれはそう感があるので、デフォルト値ページに書いてあることと同じことが書いてあってもよさそう。
（ほかも同じ）

2024-06-28 07:57 UTC, uknmr commented on content/articles/products/design-patterns/default_value.mdx
> +主にこれらのコンポーネントでデフォルト値を設定できます。
特にコンポーネントページ側で記述がなくても列挙して良いと思いました。

```suggestion
以下のコンポーネントでデフォルト値を設定できます。
```

2024-06-28 07:57 UTC, versionfive requested changes

2024-06-28 07:57 UTC, versionfive commented on content/articles/products/components/check-box/index.mdx
> +- あらかじめ値を選択した状態で表示する場合は、[デフォルト値](/products/design-patterns/default_value/)を参照してください。
上にも「状態」がいるのでまとめてほしいです

<img width="283" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/64398878/171fa1d2-c980-4553-8746-b98b7d7f7513">

2024-06-28 07:57 UTC, versionfive commented on content/articles/products/components/radio-button/index.mdx
> +- 値を選択してない状態で表示する場合は、「未選択」を選択肢に追加してください。
テンプレートに合わせた位置に移動してほしいです。

<img width="273" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/64398878/ab730d46-2f9d-4959-8cae-db3efe0960e9">

2024-06-28 07:57 UTC, versionfive commented on content/articles/products/components/input/index.mdx
> +- 新規作成画面などで、Inputをオブジェクト名の入力欄として使用する際に、自動的にオブジェクト名を決められる場合は `yyyy/mm/dd + オブジェクト名` のようにデフォルト値を設定することを推奨します。
上にも「状態」があるのでまとめてください。

<img width="290" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/64398878/12b480b5-ab0d-4d16-b02a-5c8eb8a77055">

2024-06-28 08:01 UTC, MasafumiKabe reviewed
細かいですがこっちのほうがいいかも

2024-06-28 08:01 UTC, MasafumiKabe commented on content/articles/products/components/radio-button/index.mdx
> +- 値を選択してない状態で表示する場合は、「未選択」を選択肢に追加してください。
```suggestion
- 値を選択していない状態で表示する場合は、「未選択」を選択肢に追加してください。
```

2024-06-28 08:01 UTC, MasafumiKabe commented on content/articles/products/components/select.mdx
> +- 値を選択してない状態で表示する場合は、「未選択」を選択肢に追加してください。
```suggestion
- 値を選択していない状態で表示する場合は、「未選択」を選択肢に追加してください。
```

2024-06-28 08:05 UTC, oremega commented on content/articles/products/components/check-box/index.mdx
> +- あらかじめ値を選択した状態で表示する場合は、[デフォルト値](/products/design-patterns/default_value/)を参照してください。
あー、気づいてなかった。。。。。。

2024-06-28 08:33 UTC, oremega commented on content/articles/products/components/check-box/index.mdx
> +- あらかじめ値を選択した状態で表示する場合は、[デフォルト値](/products/design-patterns/default_value/)を参照してください。
@uknmr なるほど、1行目を以下の文章に差し替えてデフォルト値をリンクさせればいいと。

> 基本的にデフォルト値は設定せず、何も入力がない状態で表示します。
> ユーザーの入力作業が向上したり、ミスを減らせる場合にのみデフォルト値（リンク）を設定するようにします。
>

2024-06-28 10:05 UTC, versionfive commented on content/articles/products/components/input/index.mdx
> +- 新規作成画面などで、Inputをオブジェクト名の入力欄として使用する際に、自動的にオブジェクト名を決められる場合は `yyyy/mm/dd + オブジェクト名` のようにデフォルト値を設定することを推奨します。
```suggestion
何も入力されていない状態をデフォルトとしてください。

ユーザーの入力作業が向上したり、ミスを減らせる場合には[デフォルト値](/products/design-patterns/default_value/)を設定すること検討します。  
新規作成画面などで、Inputをオブジェクト名の入力欄として使用する際に、自動的にオブジェクト名を決められる場合は `yyyy/mm/dd + オブジェクト名` のようにデフォルト値を設定することを推奨します。
```

2024-06-28 10:09 UTC, tosiiu approved these changes
LGTM!

2024-06-28 10:16 UTC, versionfive approved these changes
LGTM!!お疲れさまでした!!

2024-06-28 10:18 UTC, oti approved these changes
LGTM!!!!

2024-06-28 10:18 UTC, merged