（再度）BottomFixedAreaとFloatAreaを更新
kufu/smarthr-design-system pull request #1343
Opened 2024-10-28 00:16 UTC by drivesketch

## 課題・背景

BottomFixedAreaとFloatAreaを更新しました。

- #1228 のときと方針が変わったので、1228は破棄して再作成しています。
- 「モーダルなUI」もあわせて更新が必要ですが、別途後追いでやります。モーダル〜との不整合は一旦無視してください。

## やったこと
- BottomFixedAreaを非推奨化
- FlotAreaの基準を、レイアウトを中心に大幅加筆

## やらなかったこと
- 

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-10-28 07:32 UTC, oti requested changes
気になったところコメントしました！

2024-10-28 07:32 UTC, oti commented on content/articles/products/components/bottom-fixed-area.mdx
> +    BottomFixedAreaは非推奨です。<a href="/products/components/float-area/">FloatArea</a>を使ってください。
```suggestion
    BottomFixedAreaは非推奨です。<a href="/products/components/float-area/">FloatArea</a>を使用してください。
```
細かいんですが、非推奨コンポーネントの代替を指定する文言は[「使用してください」が多勢](https://github.com/search?q=repo%3Akufu%2Fsmarthr-design-system%20%E3%81%AF%E9%9D%9E%E6%8E%A8%E5%A5%A8%E3%81%A7%E3%81%99%E3%80%82&type=code)のようでした。

2024-10-28 07:32 UTC, oti commented on content/articles/products/components/float-area/index.mdx
> +- FloatAreaの対象ではない領域が続く場合は、関連性が低いことを示せるように、`1.5（24px）` よりも広い余白（例：`2（32px）`）の余白を取ってください。
```suggestion
- FloatAreaの対象ではない領域が続く場合は、関連性が低いことを示せるように、`1.5（24px）` よりも広い余白（例：`2（32px）`）を取ってください。
```
「広い余白（略）の余白を〜」になっていたので一部トルツメですかね。

2024-10-28 07:32 UTC, oti commented on content/articles/products/components/float-area/index.mdx
> +- FloatAreaの対象ではない領域が続く場合は、関連性が低いことを示せるように、`1.5（24px）` よりも広い余白（例：`2（32px）`）の余白を取ってください。
別件の nits で、「最低32px、特別な理由がなければ 48px 」くらいの余白がほしいなとスクショを見ていて思いました。24px と 32px って意外と差が少ないなぁと…

2024-10-28 07:35 UTC, oti commented on content/articles/products/components/bottom-fixed-area.mdx
> +    BottomFixedAreaは非推奨です。<a href="/products/components/float-area/">FloatArea</a>を使ってください。
参考）
- [「使ってください」](https://github.com/search?q=repo%3Akufu%2Fsmarthr-design-system+%E4%BD%BF%E3%81%A3%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84&type=code)
- [「使用してください」](https://github.com/search?q=repo%3Akufu%2Fsmarthr-design-system+%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84&type=code)
- [「利用してください」](https://github.com/search?q=repo%3Akufu%2Fsmarthr-design-system+%E5%88%A9%E7%94%A8%E3%81%97%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84&type=code)

2024-10-28 08:15 UTC, drivesketch commented on content/articles/products/components/bottom-fixed-area.mdx
> +    BottomFixedAreaは非推奨です。<a href="/products/components/float-area/">FloatArea</a>を使ってください。
和語に寄せるほうが良いという思想で意図的にやってます。ただ特に誰とも合意は取ってないですね。

2024-10-28 08:16 UTC, drivesketch commented on content/articles/products/components/float-area/index.mdx
> +- FloatAreaの対象ではない領域が続く場合は、関連性が低いことを示せるように、`1.5（24px）` よりも広い余白（例：`2（32px）`）の余白を取ってください。
シャドウのせいか、同じくらいに見えますよね。その言い方もらいます。

2024-10-28 08:26 UTC, drivesketch commented on content/articles/products/components/float-area/index.mdx
> +- FloatAreaの対象ではない領域が続く場合は、関連性が低いことを示せるように、`1.5（24px）` よりも広い余白（例：`2（32px）`）の余白を取ってください。
画像も更新しました。

2024-10-28 10:49 UTC, versionfive reviewed
ざっとコメントしました :pray:

2024-10-28 10:49 UTC, versionfive commented on content/articles/products/components/bottom-fixed-area.mdx
>  画面下部に固定で表示する操作パネルです。項目ごとに画面を分けた機能など、連続した入力を求める場合に使用します。
>項目ごとに画面を分けた機能

こちらの意味がパッとわからなかったです

2024-10-28 10:49 UTC, versionfive commented on content/articles/products/components/float-area/index.mdx
> +FloatAreaには、ページ全体、もしくはページの一部を対象としたボタンやテキストを置きます。**ページ内のどの部分が対象の領域なのかを視覚的に示す**ことを目指して、FloatAreaの幅や周囲の要素との[余白の取り方](/products/design-patterns/spacing-layout-pattern/)、[レイヤー順序](/products/design-tokens/z-
nitsですが、上の「主にモーダルなUIを作るために使います。」とこの段落は「使用上の注意」にしてもいいかもな、とおもったりしました。

2024-10-28 10:49 UTC, versionfive commented on content/articles/products/components/float-area/index.mdx
> +FloatAreaには、ページ全体、もしくはページの一部を対象としたボタンやテキストを置きます。**ページ内のどの部分が対象の領域なのかを視覚的に示す**ことを目指して、FloatAreaの幅や周囲の要素との[余白の取り方](/products/design-patterns/spacing-layout-pattern/)、[レイヤー順序](/products/design-tokens/z-
https://smarthr.design/products/design-tokens/z-index/#h2-2

にFloatAreaがない？

2024-10-28 10:49 UTC, versionfive commented on content/articles/products/components/float-area/index.mdx
> +### 基本的な考え方
「対象の領域」の考え方があるとうれしいかも、と思いました。（全体 or 一部）

2024-10-28 20:56 UTC, drivesketch commented on content/articles/products/components/bottom-fixed-area.mdx
>  画面下部に固定で表示する操作パネルです。項目ごとに画面を分けた機能など、連続した入力を求める場合に使用します。
たぶんウィザードのことですね。非推奨化したのでいずれページごと消すと思って特に中身は見てなかったんですが、直した方がいいですかね？

2024-10-28 20:57 UTC, drivesketch commented on content/articles/products/components/float-area/index.mdx
> +FloatAreaには、ページ全体、もしくはページの一部を対象としたボタンやテキストを置きます。**ページ内のどの部分が対象の領域なのかを視覚的に示す**ことを目指して、FloatAreaの幅や周囲の要素との[余白の取り方](/products/design-patterns/spacing-layout-pattern/)、[レイヤー順序](/products/design-tokens/z-
あ、そういえばないですね。これじゃ参照できない。UIのチャンネルにスレ立てて決めます。

2024-10-29 04:20 UTC, drivesketch commented on content/articles/products/components/float-area/index.mdx
> +FloatAreaには、ページ全体、もしくはページの一部を対象としたボタンやテキストを置きます。**ページ内のどの部分が対象の領域なのかを視覚的に示す**ことを目指して、FloatAreaの幅や周囲の要素との[余白の取り方](/products/design-patterns/spacing-layout-pattern/)、[レイヤー順序](/products/design-tokens/z-
↓で対応
https://github.com/kufu/smarthr-design-system/pull/1349
https://github.com/kufu/smarthr-ui/pull/5066

2024-10-29 05:03 UTC, drivesketch commented on content/articles/products/components/bottom-fixed-area.mdx
>  画面下部に固定で表示する操作パネルです。項目ごとに画面を分けた機能など、連続した入力を求める場合に使用します。
FloatAreaと合わせて「モーダルなUIを作るために使います」にしてみます。

2024-10-29 10:05 UTC, tosiiu reviewed
いくつかコメントを書きました！

2024-10-29 10:05 UTC, tosiiu commented on content/articles/products/components/float-area/index.mdx
> +#### スクロール固定解除後
FloatAreaの下部に更にコンテンツが続くパターンって今のところありますか？？
FloatArea操作の影響範囲が分かりづらかったり、コンテンツがFloatAreaに続くことが分かりづらいかもと思ったので妥当な実装例がなければ現時点で基準として掲載しなくてもいいかもと思いました！

2024-10-29 10:05 UTC, tosiiu commented on content/articles/products/components/float-area/index.mdx
> +FloatAreaには、ページ全体、もしくはページの一部を対象としたボタンやテキストを置きます。**ページ内のどの部分が対象の領域なのかを視覚的に示す**ことを目指して、FloatAreaの幅や周囲の要素との[余白の取り方](/products/design-patterns/spacing-layout-pattern/)、[レイヤー順序](/products/design-tokens/z-
ややnice to haveかつモーダルなUIで示されればそれで問題ないと思うのですが、通常のセクションに対して配置するような操作ボタンではなくなぜFloatAreaを使うのか/またいつ使うのかがざっくりでも知りたいかもと思いました！

2024-10-29 10:05 UTC, tosiiu commented on content/articles/products/components/bottom-fixed-area.mdx
> +description: '画面下部に固定で表示する操作パネルです。項目ごとに画面を分けた機能など、連続した入力を求める場合に使用します。FloatAreaで代替が可能になったため非推奨です。'
FloatAreaにメッセージ表示エリアが追加されることを見越しての表記と解釈して良さそうでしょうか？（異議はないのですが、現時点では代替不可だと思うので念の為確認）

2024-10-29 21:56 UTC, drivesketch commented on content/articles/products/components/float-area/index.mdx
> +#### スクロール固定解除後
たしかに。発生してからのほうがいいですね。消します。
sticky/fixedの言及は別コンテンツが続く件に関する前段説明として入れたので、ここを消すならsticky/fixedの話もあわせて消そうと思います。

2024-10-29 21:57 UTC, drivesketch commented on content/articles/products/components/float-area/index.mdx
> +### 基本的な考え方
全体・一部の両方を図示しようと思います

2024-10-30 04:35 UTC, drivesketch commented on content/articles/products/components/float-area/index.mdx
> +FloatAreaには、ページ全体、もしくはページの一部を対象としたボタンやテキストを置きます。**ページ内のどの部分が対象の領域なのかを視覚的に示す**ことを目指して、FloatAreaの幅や周囲の要素との[余白の取り方](/products/design-patterns/spacing-layout-pattern/)、[レイヤー順序](/products/design-tokens/z-
「この目的が満たされれば、具体的な配置はこの次に書く例と違ってもいいよ」みたいなことが言いたいんですが、なにか案ないですかね？

2024-10-30 04:37 UTC, drivesketch commented on content/articles/products/components/float-area/index.mdx
> +FloatAreaには、ページ全体、もしくはページの一部を対象としたボタンやテキストを置きます。**ページ内のどの部分が対象の領域なのかを視覚的に示す**ことを目指して、FloatAreaの幅や周囲の要素との[余白の取り方](/products/design-patterns/spacing-layout-pattern/)、[レイヤー順序](/products/design-tokens/z-
まだあまりまとまっていないのですが、モーダルUIの方に書く or モーダルUIを更新する際にこっちに書こうと思います。

2024-10-30 04:39 UTC, drivesketch commented on content/articles/products/components/bottom-fixed-area.mdx
> +description: '画面下部に固定で表示する操作パネルです。項目ごとに画面を分けた機能など、連続した入力を求める場合に使用します。FloatAreaで代替が可能になったため非推奨です。'
メッセージは地のページ方に書くほうがいいよね、という考えです。

2024-10-30 04:42 UTC, drivesketch commented on content/articles/products/components/bottom-fixed-area.mdx
> +description: '画面下部に固定で表示する操作パネルです。項目ごとに画面を分けた機能など、連続した入力を求める場合に使用します。FloatAreaで代替が可能になったため非推奨です。'
まあでも代替可能性には言及せず、単に「非推奨です、FAつかってね」だけのほうがよさそうですね。

2024-10-30 05:17 UTC, drivesketch commented on content/articles/products/components/float-area/index.mdx
> +FloatAreaには、ページ全体、もしくはページの一部を対象としたボタンやテキストを置きます。**ページ内のどの部分が対象の領域なのかを視覚的に示す**ことを目指して、FloatAreaの幅や周囲の要素との[余白の取り方](/products/design-patterns/spacing-layout-pattern/)、[レイヤー順序](/products/design-tokens/z-
すぐ下にDo/Don'tの図示を追加します

2024-10-30 05:47 UTC, uknmr commented on content/articles/products/components/bottom-fixed-area.mdx
> +    BottomFixedAreaは非推奨です。<a href="/products/components/float-area/">FloatArea</a>を使ってください。
私はサ変動詞を基本的にひらきたい派なので、和語に寄せるの賛成です🥳

2024-10-30 05:51 UTC, oti commented on content/articles/products/components/float-area/index.mdx
> +- FloatAreaの対象ではない領域が続く場合は、関連性が低いことを示せるように、`1.5（24px）` よりも広い余白（例：`2（32px）`）の余白を取ってください。
> FloatAreaの下部に更にコンテンツが続くパターンって今のところありますか？？（ura）
> たしかに。発生してからのほうがいいですね。消します。（so）

のやりとりで指摘箇所トルツメ担ったんだなという個人メモをジャストコメントします

2024-10-30 05:51 UTC, oti approved these changes
yosasou!

2024-10-30 05:52 UTC, drivesketch commented on content/articles/products/components/float-area/index.mdx
> +- FloatAreaの対象ではない領域が続く場合は、関連性が低いことを示せるように、`1.5（24px）` よりも広い余白（例：`2（32px）`）の余白を取ってください。
あ、書きそびれてました :bow:
はい、最終的にトルツメにしました。

2024-10-30 08:35 UTC, tosiiu commented on content/articles/products/components/bottom-fixed-area.mdx
> +description: '画面下部に固定で表示する操作パネルです。項目ごとに画面を分けた機能など、連続した入力を求める場合に使用します。FloatAreaで代替が可能になったため非推奨です。'
なるほどです〜必要性があれば何かしら声があがってくると思うので良さそうに思いました！

2024-10-30 08:38 UTC, tosiiu approved these changes
実際にモーダルなUIの中でどのように使うべきかはモーダルなUIに書かれると思うので、この2コンポーネントの記載としてはLGTMです！Do/Don'tの例が分かりやすい〜〜

2024-11-01 02:15 UTC, versionfive approved these changes
LGTM!! 
追加いただいたDo/Don'tがとてもわかりやすいですね！！

2024-11-01 02:15 UTC, merged