アイコンの有無と新規ウィンドウを開く判断基準を追加
kufu/smarthr-design-system pull request #1386
Opened 2024-11-15 10:00 UTC by oremega

## 課題・背景
以下2チケットに対応
- [TextLinkでアイコンを利用するかどうかの基準](https://smarthr.atlassian.net/browse/SD-887)
- [TextLinkを新しいタブで開くかどうかの基準](https://smarthr.atlassian.net/browse/SD-888)

## やったこと
- 同上

## やらなかったこと
- 

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2024-11-20 07:54 UTC, oremega commented on src/content/articles/products/components/text-link/index.mdx
> +##### 新規ウィンドウで開くテキストリンクを設定する判断基準
@versionfive 対応しました。判断基準は「新規ウィンドウで開くテキストリンク」のセクションに移動して、わけてた部分を削除。
各パターンでアイコンを設置していない方に指定しない旨を記載しました。

2024-11-21 04:39 UTC, versionfive reviewed
もう1点suggestしました

2024-11-21 04:39 UTC, versionfive commented on src/content/articles/products/components/text-link/index.mdx
> +新規ウィンドウで開くテキストリンクを設定する判断は、テキストリンクが設置されている画面で情報の入力や機能の設定作業を中断することで、作業効率が著しく落ちる場合に指定してください。
```suggestion
テキストリンクで別の画面に遷移することで、現在の画面での入力や作業が中断され作業効率が著しく落ちる場合には、新規ウィンドウ（新規タブ）でテキストリンクを開くことを検討します。

新規ウィンドウで開くテキストリンクには、**テキストの右側**に <FaUpRightFromSquareIcon alt="新規ウィンドウ" color="TEXT_LINK" /> アイコン（`FaUpRightFromSquareIcon`）を必ず配置します。リンク先がSmartHRの内部ページ、外部サイトに関わらず表示します。`アイコン付き（左）`（プレフィックス）は指定しないでください。
```
先に判断基準を書くようにしてみました。

2024-11-21 07:46 UTC, oremega commented on src/content/articles/products/components/text-link/index.mdx
> +新規ウィンドウで開くテキストリンクを設定する判断は、テキストリンクが設置されている画面で情報の入力や機能の設定作業を中断することで、作業効率が著しく落ちる場合に指定してください。
なるほど〜。そもそも使うかどうかになるのでこっちのほうがわかりやすいですね。

2024-11-21 07:47 UTC, versionfive approved these changes
LGTM!

2024-11-22 02:19 UTC, MasafumiKabe requested changes
1点コメントしましたが、それ以外は良さそうです！

2024-11-22 02:19 UTC, MasafumiKabe commented on src/content/articles/products/components/text-link/index.mdx
> +[ヘルプセンター](https://support.smarthr.jp/ja/)を開くテキストリンクには、**テキストの左側**に <FaCircleQuestionIcon alt="ヘルプセンター" color="TEXT_LINK" /> アイコン（`FaCircleQuestionIcon`）を配置することを推奨します。詳細は[ヘルプページへの動線](/products/design-
今回の変更内容ではないですが、ここのリンクが死んでいた（おそらくディレクトリ構成の変更の際に修正が漏れていた）ので修正したほうがよさそう！

```suggestion
[ヘルプセンター](https://support.smarthr.jp/ja/)を開くテキストリンクには、**テキストの左側**に <FaCircleQuestionIcon alt="ヘルプセンター" color="TEXT_LINK" /> アイコン（`FaCircleQuestionIcon`）を配置することを推奨します。詳細は[ヘルプページへの動線](/products/contents/ui-text/help-link/#h3-2)を参照してください。`アイコン付き（右）`（サフィックス）は指定しないでください。
```

2024-11-22 02:40 UTC, MasafumiKabe approved these changes
LGTM~

2024-11-22 07:27 UTC, drivesketch approved these changes
LGTM!

2024-11-25 07:43 UTC, merged