Radio Buttonに並び順の基準を追記
kufu/smarthr-design-system pull request #1451
Opened 2024-12-16 08:21 UTC by fujitha

## 課題・背景
https://smarthr.atlassian.net/browse/SD-893

## やったこと
- Radio Buttonに並び順の基準を追記して、共通設定の操作権限項目の「設定項目の並び順」のリンクを貼った

## やらなかったこと
- 

## 動作確認
- Previewでみてね。

## キャプチャ

|After|
 <img width="757" alt="Screenshot 2024-12-16 at 17 19 32" src="https://github.com/user-attachments/assets/259ce6cc-f78f-46ec-afbe-4c15da8cc122" />

2024-12-18 08:19 UTC, oremega reviewed
構成を変更したほうがいいかなと思いました。

2024-12-18 08:19 UTC, oremega commented on src/content/articles/products/components/radio-button/index.mdx
> +#### ラジオボタンの並び順
共通設定をメインとして書いてくれてますが、RadioButtonの扱い方として書くのがいいと思うので、RadioButtonをメインとして、共通設定の方にリンクしたほうがいいかなと思います。

2024-12-19 02:37 UTC, fujitha commented on src/content/articles/products/components/radio-button/index.mdx
> +#### ラジオボタンの並び順
確認ありがとうございます！
確かにRadio Buttonに記載したほうが良いと思うので修正します🙇🏽‍♀️

2024-12-19 06:36 UTC, fujitha commented on src/content/articles/products/components/radio-button/index.mdx
> +#### ラジオボタンの並び順
@oremega 
修正したのでお手漉きで確認お願いいたします🙇🏽‍♀️

2024-12-19 08:50 UTC, oremega approved these changes
良さそうです！

2024-12-20 02:21 UTC, tosiiu requested changes
smarthr-ui.cssをコミットに含めているの意図的じゃなければ外したほうが良さそうです！

2024-12-23 01:06 UTC, fujitha commented
@tosiiu 
確認ありがとうございます。
意図しないコミットだったので修正しましたので再度ご確認お願いいたします🙇🏽‍♀️

2024-12-23 01:11 UTC, tosiiu approved these changes
LGTM! 今回はRadioButtonが対象ですがCheckboxにもどうようの記載をしたいですね!

2024-12-23 02:33 UTC, merged