(WIP)リンクチェッカーを追加
kufu/smarthr-design-system pull request #167
Opened 2022-07-05 06:38 UTC by yuw27b

## 課題・背景
https://github.com/kufu/smarthr-design-system-issues/issues/954

## やったこと
`/content/articles/`以下の`.mdx`ファイル内にある、リンク・画像パスについて、存在しているかどうかを確認→なければエラーメッセージ出力するスクリプトを作成しました。

## やらなかったこと
外部サイトへのリンクは対象外です。

## 動作確認
`npx ts-node ./scripts/linkChecker.ts`

現状では以下のようなエラーを出力するはずです。
```
Missing link: /basics/colors#3 in /content/articles/basics/illustration/creation-guideline.mdx at L:49
Missing link: /basics/illustration/#h1 in /content/articles/basics/illustration/user-co-other.mdx at L:12
Missing image source: /images/contents-composition.png in /content/articles/concept/contents-composition.mdx at L:11
Missing link: /foundations in /content/articles/concept/contents-composition.mdx at L:19
Missing link: #ページ内リンク in /content/articles/operational-guideline/page-template/design-patterns-template.mdx at L:28
Missing link: #ページ内リンク in /content/articles/operational-guideline/page-template/design-patterns-template.mdx at L:29
Missing link: #ページ内リンク in /content/articles/operational-guideline/page-template/design-patterns-template.mdx at L:30
Missing link: /employees/operational-guideline in /content/articles/operational-guideline/release.mdx at L:13
Missing link: URL in /content/articles/products/contents/releasenotes-guide.mdx at L:188
Missing link: /products/overview/principles/ in /content/articles/products/contents/writing-principles.mdx at L:10
Missing link: /foundations/basic/logo/ in /content/articles/products/design-patterns/contents-in-header.mdx at L:37
Missing link: /employees/operational-guideline/page-template/design-guide-template/ in /content/articles/products/design-patterns/index.mdx at L:34
Found 12 missing links. Link check finished.
```
URLが変わってリダイレクトされているもの、テンプレート内のサンプルURLなども引っかかっているので、修正する・除外するなどすればもう少し減りそうです。

## キャプチャ
Webアプリケーション本体への影響はありません。

2022-07-07 00:53 UTC, yuw27b commented
現在エラー判定になっているものの詳細は以下です：

**リダイレクトがかかっているもの** 
（古いURLなのかもしれません）
Missing link: /products/overview/principles/ in /content/articles/products/contents/writing-principles.mdx at L:10
→ /products/principles/
Missing link: /foundations/basic/logo/ in /content/articles/products/design-patterns/contents-in-header.mdx at L:37
→ /basics/logos/
Missing link: /employees/operational-guideline/page-template/design-guide-template/ in /content/articles/products/design-patterns/index.mdx at L:34
→ /operational-guideline/page-template/design-patterns-template/
Missing link: /foundations in /content/articles/concept/contents-composition.mdx at L:19
→ /foundation/

**404になるもの**
Missing link: /employees/operational-guideline in /content/articles/operational-guideline/release.mdx at L:13
ただ、そもそもこのリンク部分はコメントアウトされているので、修正不要かもしれません。

**アンカー部分が該当しないもの**
Missing link: /basics/colors#3 in /content/articles/basics/illustration/creation-guideline.mdx at L:49
→　/basics/colors#3−3 が正解？
Missing link: /basics/illustration/#h1 in /content/articles/basics/illustration/user-co-other.mdx at L:12
→ /basics/illustration/#h2-0 が正解？

**リンクの記述例** （なので無視して良さそう）
Missing link: #ページ内リンク in /content/articles/operational-guideline/page-template/design-patterns-template.mdx at L:28
Missing link: #ページ内リンク in /content/articles/operational-guideline/page-template/design-patterns-template.mdx at L:29
Missing link: #ページ内リンク in /content/articles/operational-guideline/page-template/design-patterns-template.mdx at L:30
Missing link: URL in /content/articles/products/contents/releasenotes-guide.mdx at L:188

**画像のパス**
Missing image source: /images/contents-composition.png in /content/articles/concept/contents-composition.mdx at L:11
Gatsbyでビルドすると画像の階層は関係なくなるので、実際には画像の表示はできていますが、他は相対パスで記述しているようなので、`./images/contents-composition.png`にしても良いのかもしれません。
何か問題が起きているわけではないので、無視でも良いかとは思います。

2022-07-07 08:04 UTC, yuw27b commented
- リダイレクトされるURLはリダイレクト先のURLに変更しました
- `IGNORE_LIST`を追加し、"URL""ページ内リンク"などのサンプルテキストは除外しました

2022-07-08 07:12 UTC, tomof requested changes
@yuw27b 見ましたー。処理的には問題ないかと思いますー🙆‍♂️
変数名についての指摘させてもらいました。

あとcheck関数が長いので、

- 前半の対象のパス集め
- 後半のエラーチェック

をそれぞれを関数化して抜き出して、check関数内でその2つを順に実行するみたいな処理にできないですかね？

2022-07-08 07:12 UTC, tomof commented on scripts/linkChecker.ts
> +  const errorList: LinkItem[] = []
エラー = missing linkだと思うので、`missingLinkList`とかで良いんじゃないでしょうかー？

2022-07-08 07:25 UTC, yuw27b commented
@tomof ありがとうございます、使わせていただきました🙏
`existPathList`良さそうです！（リンク元とリンク先の区別が分かりづらいなと思っていたので）

2022-07-08 08:16 UTC, merged