Add icon guidelines
kufu/smarthr-design-system pull request #18
Opened 2022-04-20 10:14 UTC by omameoicy

## 課題・背景
- アイコンリニューアルに伴い、アイコン作成ガイドラインを掲載
  - デザイナーであれば誰でも統一感のあるアイコンの作成ができるように

## やったこと
- ガイドラインページの追加

## やらなかったこと
- アイコンページ自体の修正

## 動作確認

2022-04-26 12:06 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +title: ‘アイコン作成ガイドライン’
```suggestion
title: アイコン作成ガイドライン
```
不要な文字列はいってるようです

2022-04-26 12:06 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +title: ‘アイコン作成ガイドライン’
```suggestion
title: アイコン作成ガイドライン
```
不要な文字列はいってるようです

2022-04-26 12:07 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +## アイコンデータ
```suggestion
## デザインデータ
```

2022-04-26 12:07 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +## アイコンデータ
```suggestion
## デザインデータ
```

2022-04-26 12:09 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +## Font Awesomeのアイコン
```suggestion
## Font Awesomeをそのまま利用する場合
```

2022-04-26 12:09 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +## Font Awesomeのアイコン
```suggestion
## Font Awesomeをそのまま利用する場合
```

2022-04-26 12:09 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +- SmartHR Design Systemで配布しているため、ProやPro Maxプランのアイコンは使用しないでください。
```suggestion
```

2022-04-26 12:09 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +- SmartHR Design Systemで配布しているため、ProやPro Maxプランのアイコンは使用しないでください。
```suggestion
```

2022-04-26 12:10 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +※2022年4月時点のFont Awesome最新 ver 6.0.0
```suggestion
※2022年4月時点のFontAwesome最新 ver 6.0.0
```

2022-04-26 12:10 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +※2022年4月時点のFont Awesome最新 ver 6.0.0
```suggestion
※2022年4月時点のFontAwesome最新 ver 6.0.0
```

2022-04-26 12:11 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +## 独自作成をする際のガイドライン
```suggestion
## 新規作成する場合
```

2022-04-26 12:11 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +## 独自作成をする際のガイドライン
```suggestion
## 新規作成する場合
```

2022-04-26 12:13 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +Font Awesomeのアイコンと並んだときに違和感のないようにKeylineを作成しました。
```suggestion
マスターデータ内に、Font Awesomeのアイコンと並んだときに違和感のないようなKeylineを配置しています。
```

2022-04-26 12:13 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +Font Awesomeのアイコンと並んだときに違和感のないようにKeylineを作成しました。
```suggestion
マスターデータ内に、Font Awesomeのアイコンと並んだときに違和感のないようなKeylineを配置しています。
```

2022-04-26 12:14 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +    - FontAwesomeの**Regular**と**Solid**の関係を参考にして作成してください。
```suggestion
outlineアイコンを先に作成し、Font AwesomeのOutlineをベースに線の太さを調整してsolidアイコンを作成してください。  
Font Awesomeの**Regular**と**Solid**の関係を参考にして作成してください。
```
```suggestion
- outlineアイコンを先に作成し、Font AwesomeのOutlineをベースに線の太さを調整してsolidアイコンを作成してください。
    - FontAwesomeの**Regular**と**Solid**の関係を参考にして作成してください。
```

2022-04-26 12:14 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +    - FontAwesomeの**Regular**と**Solid**の関係を参考にして作成してください。
```suggestion
outlineアイコンを先に作成し、Font AwesomeのOutlineをベースに線の太さを調整してsolidアイコンを作成してください。  
Font Awesomeの**Regular**と**Solid**の関係を参考にして作成してください。
```
```suggestion
- outlineアイコンを先に作成し、Font AwesomeのOutlineをベースに線の太さを調整してsolidアイコンを作成してください。
    - FontAwesomeの**Regular**と**Solid**の関係を参考にして作成してください。
```

2022-04-26 12:14 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +- solidを作成する際はoutlineの線を残したまま塗りをつけるとサイズ感が変わらずに作成できます。
```suggestion
先にoutlineのアイコンを作成します。  
solidを作成する際はoutlineの線を残したまま塗りをつけるとサイズ感が変わらずに作成できます。
```
```suggestion
- 先にoutlineのアイコンを作成します。
- solidを作成する際はoutlineの線を残したまま塗りをつけるとサイズ感が変わらずに作成できます。
```

2022-04-26 12:14 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +- solidを作成する際はoutlineの線を残したまま塗りをつけるとサイズ感が変わらずに作成できます。
```suggestion
先にoutlineのアイコンを作成します。  
solidを作成する際はoutlineの線を残したまま塗りをつけるとサイズ感が変わらずに作成できます。
```
```suggestion
- 先にoutlineのアイコンを作成します。
- solidを作成する際はoutlineの線を残したまま塗りをつけるとサイズ感が変わらずに作成できます。
```

2022-04-26 12:16 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +- 社内Slack `#design_comm_依頼`
```suggestion
- 社内Slack: `#ext_design_system`  
- Twitter: https://twitter.com/SHRDesignSystem
```

2022-04-26 12:16 UTC, samemaru commented on content/articles/communication/icons/creation-guideline.mdx
> +- 社内Slack `#design_comm_依頼`
```suggestion
- 社内Slack: `#ext_design_system`  
- Twitter: https://twitter.com/SHRDesignSystem
```

2022-04-26 12:17 UTC, samemaru requested changes
いくつかsuggestしています。
不明点あればお知らせください〜！

2022-04-27 09:26 UTC, omameoicy commented
確認、修正ありがとうございます！！
特に不明点ありませんでした！🙏

2022-04-28 11:35 UTC, samemaru approved these changes
LGTM〜！

2022-05-09 07:34 UTC, merged