テーブル内の一括操作のページを追加
kufu/smarthr-design-system pull request #193
Opened 2022-07-20 11:40 UTC by wentzzz

## 課題・背景

## やったこと

- テーブル内の一括操作のページを追加
- デザインパターン（共通）内のorderを一部変更

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2022-07-21 01:26 UTC, uknmr commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +反対に、「オブジェクトを一括選択するチェックボックス」の選択状態を解除すると、「ワクワクチェック」適用下かどうかに関わらず、ページ上もPagination上もすべてのオブジェクトの選択状態を解除します。
👍 
これ文章で読むとわくわくチェック時と挙動が違っていいのか? って思うけどこれでよさそうよね〜
わくわくチェック状態でページ外の操作をした時はわくわくチェック状態を解除する、みたいな仕様だといいのかしら（実質そうなってはいる

2022-07-21 01:29 UTC, uknmr commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +「オブジェクトを一括選択するチェックボックスが混在選択状態」が未選択状態で、テーブル内のオブジェクトのうち1つ以上が個別選択された場合（選択状態と未選択状態が混ざっている場合）は、「オブジェクトを一括選択するチェックボックス」を`mixed`が`true`の混在選択状態にします。
mixed の時に押すとどうなるかを明記したいので「オブジェクトを一括選択するチェックボックスが未選択の状態」の説明と順序入れ替えるといいかも?

2022-07-21 02:37 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +「よくあるテーブル」で複数のオブジェクトに対して一括操作するUIのパターンです。
よくあるテーブルの該当記述もこのドキュメントに合わせて直しつつ、リンクできるといいですね
https://deploy-preview-193--smarthr-design-system.netlify.app/products/design-patterns/smarthr-table/#h5-5

2022-07-21 02:37 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +1. テーブル内オブジェクトの一括操作エリア
全体的に単語が長くて呼びにくいから`一括`なのか`まとめて`なのかの議論結果にもよりますが、「オブジェクト」とかは省略してシュッとしたいお気持ち…
（テーブルの一括操作エリア、まとめて操作エリア、とか…）

2022-07-21 02:37 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +##### ラベルの表示例
これは「ラベル」なのだろか…？

2022-07-21 02:37 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +| Pagination上のすべてが選択されている | `一覧の{オブジェクト名}{件数}件すべてを選択しています。` |
```suggestion
| テーブルのページ送り上のすべてが選択されている | `一覧の{オブジェクト名}{件数}件すべてを選択しています。` |
```
よくあるテーブルでは、Paginationは「テーブルのページ送り」と表記しています

2022-07-21 02:37 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +反対に、「オブジェクトを一括選択するチェックボックス」の選択状態を解除すると、「ワクワクチェック」適用下かどうかに関わらず、ページ上もPagination上もすべてのオブジェクトの選択状態を解除します。
「選択解除」を押したときと同じ挙動とする、って話としてまとめちゃったらどうですかね？

2022-07-21 02:37 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +![スクリーンショット: テーブル内オブジェクトの一括操作エリアのレイアウト](./images/collection/table-bulk-action10.png)
`BulkActionRow`はコンポーネントなので、この中のレイアウトは…と思いましたが、SmartHR UIとしては枠だけしかなく各自実装が必要なのであったほうがいいですね。ボタンが複数なときの余白も表現するとよさそうです。

2022-07-21 03:22 UTC, wentzzz commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +- アクションボタンとして、[Button](/products/components/button/)や、類似する操作をまとめたドロップダウンリストを配置できます。
デザインパターンにある「ドロップダウンボタン」の内容をComponentの方のDropdownButtonの方にまとめた方が良さそうな気配。

2022-07-21 04:03 UTC, uknmr commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +- アクションボタンとして、[Button](/products/components/button/)や、類似する操作をまとめたドロップダウンリストを配置できます。
そうなんですよ〜😂
デザインパターンから生まれたコンポーネントなのでパターンの方を消してコンポーネントにまとめるに賛成です。

2022-07-22 00:44 UTC, wentzzz commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +##### ラベルの表示例
状態によって動的に変化するテキストなので、「テキスト」ですかね？
ラベルを「一意の固定された意味を持つ値」と捉えると動的に変わるテキストをラベルとするのは適切ではないのかもですね。

2022-07-22 01:45 UTC, uknmr requested changes
再🙏

2022-07-22 01:45 UTC, uknmr commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +[「よくあるテーブル」](/products/design-patterns/smarthr-table/)で複数のオブジェクトに対して一括操作するUIのパターンです。
nits & imo 括弧不要そう?

```suggestion
[よくあるテーブル](/products/design-patterns/smarthr-table/)で複数のオブジェクトに対して一括操作するUIのパターンです。
```

2022-07-22 01:45 UTC, uknmr commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +以下に限らず、扱う機能やユースケースによって、データの追加・一括変更などに関わるアクションボタンを配置できます。
imo

```suggestion
**データの削除・一括変更**など、選択したオブジェクトを一括で操作するためのボタンです。
必要な操作に応じて、`BulkActionRow`内の一番右の要素として複数配置できます。

- [Button](/products/components/button/)や、類似する操作をまとめた[DropdownButton](/products/components/dropdown-button/)を配置できます。
- ユーザーが操作に迷わないように、配置するボタンは**最大3つを上限とします**。それ以上配置する必要がある場合は、[ドロップダウンボタン](/products/design-patterns/dropdown-button/)を使用することを検討しましょう。

![スクリーンショット: テーブル内の一括操作エリアの一括操作ボタン](./images/collection/table-bulk-action5.png)

##### 一括操作ボタンの例

ここに配置される典型的な一括操作ボタンの例は以下のとおりです。  
以下に限らず、データの追加・一括変更など、扱う機能やユースケースによって配置できます。
```

2022-07-22 02:48 UTC, versionfive commented on content/articles/products/design-patterns/smarthr-table.mdx
> +    - SmartHR UIではこのエリアを`BulkActionRow`と呼んでいます。
この記載は、ドキュメントがないときに必要最低限だけ書いただけなので、まとめて今回の「テーブル内の一括操作」にリンクすればいいかもです。

2022-07-22 02:48 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +テーブル内で選択されたオブジェクトに対して一括操作を配置するエリアです。
このエリアの表示・非表示ってどのようなパターンがありましたっけ。
常に表示する？チェックボックスを操作すると表示される？

2022-07-22 02:48 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +オブジェクトの選択状態にあわせた表示例は以下の通りです。
```suggestion
##### テキストのライティングパターン

オブジェクトの選択状態にあわせたライティングパターンは以下の通りです。
```
表示例というより、ライティングのパターンかなと

2022-07-22 02:48 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +わくわくチェックとは、テーブル上に表示される複数のオブジェクトをPaginationによって分割表示する際に、ページの枠を超えてすべてのオブジェクトを選択できる機能の通称です。
```suggestion
わくわくチェックとは、テーブル上に表示される複数のオブジェクトをページ送りによって分割表示する際に、ページの枠を超えてすべてのオブジェクトを選択できる機能の通称です。
```

2022-07-22 02:48 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +また、わくわくチェックの適用下でテーブルのページ送り上の遷移を行なった場合は、ユーザーに一貫した体験を提供する目的で**選択状態は維持せずにテーブルのページ送り上のすべてのオブジェクトの選択状態を解除する**挙動で統一します。
ここは流れ（わくわくチェックの動作）を説明していて、構成の説明とは少しずれていると思いました。
このセクションはわくわくチェックの説明だけにして、別途h2レベルで「わくわくチェックの動作」を作ってそちらに動作を説明するのはいかがでしょうか？

2022-07-22 02:48 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +以下に限らず、扱う機能やユースケースによって、データの追加・一括変更などに関わるアクションボタンを配置できます。
このライティングパターンは別PRで追加する感じですか？

2022-07-22 02:48 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +3. 個別選択するチェックボックス（必須）
```suggestion
1. 個別選択するチェックボックス（必須）
2. 一括選択するチェックボックス（必須）
3. テーブル内の一括操作エリア
    - [オブジェクト選択状態の表示](#h4-0)
    - [わくわくチェック](#h4-1)
    - [一括操作するボタン](#h4-2)
```
チェックボックスを操作した結果、「テーブル内の一括操作エリア」が表示されるので、説明として先にチェックボックスの説明があるとよいかなと思いました。

2022-07-22 06:48 UTC, aguringo reviewed
気になったところコメントしました〜

遅くなってゴメンナサイ。

2022-07-22 06:48 UTC, aguringo commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +わくわくチェックとは、テーブル上に表示される複数のオブジェクトをPaginationによって分割表示する際に、ページの枠を超えてすべてのオブジェクトを選択できる機能の通称です。
```suggestion
複数のオブジェクトをPaginationを用いた複数テーブルにまたがって表示する際に、ページの枠を超えてすべてのオブジェクトを選択できるUIを、わくわくチェックと呼んでいます。
```

2022-07-22 06:48 UTC, aguringo commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +流れとしては、テーブル上に表示されているオブジェクトを１つ以上選択したときに「一覧のすべてのオブジェクトを選択」というテキストリンクを表示し、これをクリックすることで**テーブルのページ送り上のすべてのオブジェクトを選択できる**ようにします。
```suggestion
すべてのオブジェクトを選択するには、テーブル上のオブジェクトを１つ以上選択したときに「一覧のすべてのオブジェクトを選択」というテキストリンクを表示し、これをクリックすると**テーブルのページ送り上のすべてのオブジェクトを選択できる**ようになります。
```

2022-07-22 08:57 UTC, wentzzz commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +テーブル内で選択されたオブジェクトに対して一括操作を配置するエリアです。
常に表示してるパターンありましたっけ？なければその旨を書いても良さそうですね。

2022-07-22 09:00 UTC, wentzzz commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +- 件数の単位は、オブジェクトの種類にあわせて「件」「名」「人」などを状況にあわせて使用してください。
良さそうに思います！

2022-07-25 01:31 UTC, 8chari commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +| テーブルのページ送り上のすべてが選択されている | `一覧の{オブジェクト名}{件数}件すべてを選択しています。` |
@aguringo 
遅くなりました:pray:
ここでは、選択するユーザーよりも、選択したことで生じる結果に焦点を当てた方がよいと思うので、受動態に揃えるのが良いと思いました。

```suggestion
| 未選択 | `{オブジェクト名}が選択されていません。` |
| 複数選択されている | `{件数}件の{オブジェクト名}が選択されています。` |
| 表示されているものすべてが選択されている | `このページの{オブジェクト名}{件数}件すべてが選択されています。` |
| テーブルのページ送り上のすべてが選択されている | `一覧の{オブジェクト名}{件数}件すべてが選択されています。` |
```

2022-07-26 01:05 UTC, 8chari requested changes
suggestionで1件コメント入れています:pray:

2022-07-28 00:37 UTC, wentzzz commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +- アクションボタンとして、[Button](/products/components/button/)や、類似する操作をまとめたドロップダウンリストを配置できます。
メモ：別PRで作業する

2022-07-28 00:41 UTC, wentzzz commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +1. テーブル内オブジェクトの一括操作エリア
「オブジェクト」は省略しました。よくあるテーブルで「エリア」表記を採用しているのでそちらにあわせてます。

2022-07-28 01:05 UTC, wentzzz commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +以下に限らず、扱う機能やユースケースによって、データの追加・一括変更などに関わるアクションボタンを配置できます。
「一括操作ボタンの例」は実質ライティングパターンなので、このPRではラベルだけあわせて内容の追記は別のPRで行います。

2022-07-29 09:55 UTC, versionfive requested changes
細かいですが、よくあるテーブルの表記に合わせたり、文章をなるべく簡潔にするSuggestionをしています。
文によって主語がユーザーだったり、UIだったりするのが気になりました。（Suggestionでは元の文の主語からはかえていません）

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +「よくあるテーブル」のなかで、複数のオブジェクトへの一括操作に関するUIは以下の要素で構成されます。
```suggestion
「よくあるテーブル」のなかで、複数オブジェクトへの一括操作に関するUIは、以下の要素で構成されます。  
```

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +「一括選択するチェックボックス」のデフォルトは未選択状態で、クリックするとテーブル内に表示されているオブジェクトがすべて選択状態となります。
```suggestion
デフォルトは未選択状態で、クリックするとテーブルに表示されているオブジェクトがすべて選択状態になります。
```
主語をユーザーにして「クリックすると〜になります」とするか、主語をシステム（UI）にして、「クリックされると〜にします」とするか悩ましい。（下の方は主語がUIになってたりする）

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +ページ上に表示されていないテーブルのページ送り上のオブジェクトは選択状態になりません。
```suggestion
表示しているページ外のオブジェクト（他のページのオブジェクト）は選択状態になりません。
```

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +「一括選択するチェックボックス」が未選択状態のときに、テーブル内のオブジェクトのうち1つ以上が個別選択された場合（選択状態と未選択状態が混ざっている場合）は、「一括選択するチェックボックス」を`mixed`が`true`の混在選択状態にします。
```suggestion
「一括選択するチェックボックス」が未選択状態のときに、テーブル内のオブジェクトが1つ以上選択された場合（選択状態と未選択状態が混ざっている場合）は、「一括選択するチェックボックス」を混在選択状態（`mixed=true`）にします。
```
ここは主語がUIになっている

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +「一括選択するチェックボックス」の選択状態を解除すると、「わくわくチェック」の「選択解除」と同様にテーブルのページ送り上も含めすべての選択状態を解除します。
```suggestion
「一括選択するチェックボックス」の選択状態を解除すると、[「わくわくチェック」の選択解除](#h3-4)と同様にテーブルのページ送り上も含めたすべての選択状態を解除します。  
```

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +`mixed`が`true`の混在選択状態で「一括選択するチェックボックス」をクリックした場合も同様に、すべての選択状態を解除します。
```suggestion
混在選択状態（`mixed=true`）で「一括選択するチェックボックス」をクリックした場合も同様に、すべての選択状態を解除します。
```

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +オブジェクトを選択した状態でテーブルのページ送りで遷移した場合は、選択状態は維持せずにテーブルのページ送り上のすべてのオブジェクトの選択状態を解除します。
```suggestion
テーブル内のオブジェクトを個別選択できるチェックボックスです。

ページ送りで他のページに遷移した場合は、選択状態は維持せずにすべてのオブジェクトの選択状態を解除します。
```

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +原則として、一括選択するチェックボックス、または個別選択するチェックボックスが1つ以上選択されている場合に表示します。
```suggestion
原則として、「一括選択するチェックボックス」または「個別選択するチェックボックス」が1つ以上選択されている場合に表示します。
```

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +##### テキストのライティングパターン
```suggestion
##### 選択状態のライティングパターン
```

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +複数のオブジェクトをページ送りを用いて複数テーブルにまたがって表示する際に、ページの枠を超えてすべてのオブジェクトを選択できるUIを、わくわくチェックと呼んでいます。
```suggestion
複数のページに分けてオブジェクトを表示する際に、ページの枠を超えてオブジェクトを選択できるUIを「*わくわくチェック*」と呼んでいます。  
```
よくあるテーブルの表記に合わせています。

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +必要な操作に応じて、`BulkActionRow`内の一番右の要素として複数配置できます。
```suggestion
#### 一括操作ボタン

データの削除・一括変更など、選択したオブジェクトを一括で操作するためのボタンです。
`BulkActionRow`内の要素として配置します。
```
複数とかは下のリストで基準が書いてあるから文をシュッとしています。

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +- ユーザーが操作に迷わないように、配置するボタンは**最大3つを上限とします**。それ以上配置する必要がある場合は、[ドロップダウンボタン](/products/design-patterns/dropdown-button/)を使用することを検討しましょう。
```suggestion
- ユーザーが操作に迷わないように、配置するボタンは**最大3つを上限とします**。それ以上配置する必要がある場合は、[ドロップダウンボタン](/products/design-patterns/dropdown-button/)のパータンを検討しましょう。
```

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +ここに配置される典型的な一括操作ボタンのライティングパターンは以下のとおりです。
```suggestion
一括操作ボタンの典型的なライティングパターンは以下のとおりです。  
```
ラベルのライティングパターンとしてまとめていますが、アクションの例として書いたほうがいい気がします。
イメージ：https://smarthr.design/products/design-patterns/smarthr-table/#h4-5

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +テーブル内オブジェクトの一括操作エリアの要素間の余白は以下のとおりです。
```suggestion
[テーブル内の一括操作エリア](#h3-2)の要素間の余白は以下のとおりです。
```

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +2. すべてのオブジェクトを選択解除
```suggestion
- すべてのオブジェクトを選択
- すべてのオブジェクトを選択解除
```

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +すべてのオブジェクトを選択するには、テーブル上のオブジェクトを１つ以上選択したときに「一覧のすべてのオブジェクトを選択」というテキストリンクを表示し、これをクリックすると**テーブルのページ送り上のすべてのオブジェクトを選択できる**ようになります。
```suggestion
オブジェクトを1つ以上選択したときに `一覧のすべてのオブジェクトを選択` というテキストリンクを表示し、**テーブルのページ送り上のすべてのオブジェクトを選択**できるようにします。
```

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +わくわくチェックの適用下では、ユーザー自身で元の状態に戻せるように「一覧のすべてのオブジェクトを選択」のテキストリンクを「選択解除」に置き換え、**テーブルのページ送り上のすべてのオブジェクトの選択状態を解除できる**ようにします。
```suggestion
わくわくチェックのオブジェクト選択中は、ユーザー自身で元の状態に戻せるように `一覧のすべてのオブジェクトを選択` のテキストリンクを `選択解除` に置き換え、**（ページ送りも含めた）すべてのオブジェクトの選択状態を解除**できるようにします。
```

2022-07-29 09:55 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +また、わくわくチェックの適用下でテーブルのページ送り上の遷移を行なった場合は、ユーザーに一貫した体験を提供する目的で**選択状態は維持せずにテーブルのページ送り上のすべてのオブジェクトの選択状態を解除する**挙動で統一します。
```suggestion
また、わくわくチェックのオブジェクト選択中に、ページ送りで他のページに遷移した場合は、**選択状態は維持せずにすべてのオブジェクトの選択状態を解除する**動作に統一します。
```
一貫したユーザー体験なんて無いのじゃ…

2022-08-01 10:11 UTC, wentzzz commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +「一括選択するチェックボックス」のデフォルトは未選択状態で、クリックするとテーブル内に表示されているオブジェクトがすべて選択状態となります。
なるほど。基本的にUIを主語とし、ユーザーを主語に置きたい場合は明記するようにしてみます！

2022-08-02 05:57 UTC, versionfive reviewed
細かいところあとちょっとだけ…！

2022-08-02 05:57 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +![スクリーンショット: テーブル内の一括操作エリアのわくわくチェック](./images/collection/table-bulk-action3.png)
```suggestion
```
リンク先で見ればいいかも？

2022-08-02 05:57 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +- ユーザーが操作に迷わないように、配置するボタンは**最大3つを上限とします**。それ以上配置する必要がある場合は、[ドロップダウンボタン](/products/design-patterns/dropdown-button/)のパターンを検討しましょう。
この表現だと4つ以上は認めないように読めますが、意図はあいますか？（あれ、申請は…？）

2022-08-02 05:57 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +わくわくチェックの動作パターンは次のとおりです。
```suggestion
`わくわくチェック` の動作パターンは次のとおりです。
```
よくあるテーブルの表記と合わせました。

2022-08-02 05:57 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +わくわくチェックのオブジェクト選択中は、ユーザー自身で元の状態に戻せるように `一覧のすべてのオブジェクトを選択` のテキストリンクを `選択解除` に置き換え、**（ページ送りも含めた）すべてのオブジェクトの選択状態を解除**できるようにします。
```suggestion
`わくわくチェック` のオブジェクト選択中は、ユーザー自身で元の状態に戻せるように `一覧のすべてのオブジェクトを選択` のテキストリンクを `選択解除` に置き換え、**（ページ送りも含めた）すべてのオブジェクトの選択状態を解除**できるようにします。
```

2022-08-02 05:57 UTC, versionfive commented on content/articles/products/design-patterns/table-bulk-action.mdx
> +また、わくわくチェックのオブジェクト選択中に、ページ送りによって他のページに遷移された場合は、**選択状態は維持せずにすべてのオブジェクトの選択状態を解除する**動作に統一します。
```suggestion
また、`わくわくチェック` のオブジェクト選択中に、ページ送りによって他のページに遷移された場合は、**選択状態は維持せずにすべてのオブジェクトの選択状態を解除する**動作に統一します。
```

2022-08-02 09:31 UTC, aguringo approved these changes
私からは、:lgtm: です　:arigatau:

2022-08-03 05:33 UTC, versionfive approved these changes
LGTM!

2022-08-03 06:13 UTC, 8chari approved these changes

2022-08-03 06:13 UTC, uknmr approved these changes

2022-08-03 06:15 UTC, aguringo approved these changes

2022-08-03 06:15 UTC, merged