複数のエラーをまとめたヘルプページのガイドラインを追加
kufu/smarthr-design-system pull request #227
Opened 2022-08-08 02:23 UTC by ibulog

## 課題・背景

複数のエラーをまとめたヘルプページのガイドラインがなかったため、追加

## やったこと

- 「よくある質問の書き方」に複数のエラーをまとめたヘルプページのガイドラインを追加

## 動作確認

- Previewでみてね。

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2022-08-08 06:28 UTC, 8chari commented on content/articles/products/contents/help-center/faq.mdx
> +文頭に `エラー` をつけ、エラーメッセージを`「　」`で囲みます。エラーメッセージが複数の文で構成されている場合は、最初の文を抜粋しても構いません。
私の記憶違いだったらごめんなさいなんですが、`：`はなしになったんでしたっけ？
```suggestion
文頭に `エラー：` をつけ、エラーメッセージを`「　」`で囲みます。エラーメッセージが複数の文で構成されている場合は、最初の文を抜粋しても構いません。
```

2022-08-08 06:38 UTC, 8chari requested changes
@ibulog 
対応ありがとうございます〜！
1件コメントしました:pray:

2022-08-09 01:33 UTC, ibulog commented
> 私の記憶違いだったらごめんなさいなんですが、`：`はなしになったんでしたっけ？
```suggestion
文頭に `エラー：` をつけ、エラーメッセージを`「　」`で囲みます。エラーメッセージが複数の文で構成されている場合は、最初の文を抜粋しても構いません。
``` 

はい、：はなしになりました！

2022-08-09 01:47 UTC, aguringo approved these changes
:LGTM::arigatau::gogo:

2022-08-09 01:55 UTC, 8chari approved these changes
👍 👍 👍 👍 👍

2022-08-09 01:57 UTC, merged