ヘルプセンターリンクの装飾アイコンの基準見直し
kufu/smarthr-design-system pull request #230
Opened 2022-08-08 06:52 UTC by versionfive

## 課題・背景

- https://github.com/kufu/smarthr-design-system-issues/issues/1030

## やったこと

- ヘルプセンターのテキストリンクのアイコンの使用基準を変更
  - https://smarthr.design/products/design-patterns/help-link/#h3-2
  - https://smarthr.design/products/components/icon/#h2-4
  - アイコンを使っている他のページの書き方を揃えた

## 動作確認
- Previewでみてね。

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2022-08-08 07:43 UTC, 8chari commented on content/articles/products/design-patterns/help-link.mdx
> +    - モードレスダイアログや新規ウィンドウ（新規タブ）など表示に関わらず、ヘルプセンターのリンクとして認知させたいときに採用可能です。
細かいのですが、「採用可能です」がちょっと堅いので、下記の表現がシンプルで良いかなと思いました。
```suggestion
    - モードレスダイアログや新規ウィンドウ（新規タブ）など表示に関わらず、ヘルプセンターのリンクとして認知させたいときに使います。
```

2022-08-08 07:53 UTC, aguringo reviewed
@versionfive いくつかSuggestionしました！

2022-08-08 07:53 UTC, aguringo commented on content/articles/products/components/icon.mdx
> +| 新規ウィンドウ（新規タブ）で開くテキストリンク | **テキストの後ろ**に <FaExternalLinkAltIcon visuallyHiddenText="新規ウィンドウ" color="TEXT_LINK" /> アイコン（`FaExternalLinkAltIcon`）を設置（必須） | リンク先がSmartHRの内部ページ、外部サイトに関わらず新規ウィンドウで開く場合は付与しま
```suggestion
| 新規ウィンドウで開くテキストリンク | **テキストの右側**に <FaExternalLinkAltIcon visuallyHiddenText="新規ウィンドウ" color="TEXT_LINK" /> アイコン（`FaExternalLinkAltIcon`）を配置（必須） | リンク先がSmartHRの内部ページ、外部サイトに関わらず新規ウィンドウ（新規タブ）で開く場合は表示します。 |
```

2022-08-08 07:53 UTC, aguringo commented on content/articles/products/components/icon.mdx
> +| [ヘルプセンター](https://knowledge.smarthr.jp/hc/ja)を開くテキストリンク | **テキストの前**に <FaQuestionCircleIcon visuallyHiddenText="ヘルプセンター" color="TEXT_LINK" /> アイコン（`FaQuestionCircleIcon`）を設置（推奨） | 詳細は[ヘルプページへの動線](/
```suggestion
| [ヘルプセンター](https://knowledge.smarthr.jp/hc/ja)を開くテキストリンク | **テキストの左側**に <FaQuestionCircleIcon visuallyHiddenText="ヘルプセンター" color="TEXT_LINK" /> アイコン（`FaQuestionCircleIcon`）を配置（推奨） | 詳細は[ヘルプページへの動線](/products/design-patterns/help-link/#h3-2)を参照してください。 |
```

2022-08-08 07:53 UTC, aguringo commented on content/articles/products/components/icon.mdx
> +| [ヘルプセンター](https://knowledge.smarthr.jp/hc/ja)を開くテキストリンク | **テキストの前**に <FaQuestionCircleIcon visuallyHiddenText="ヘルプセンター" color="TEXT_LINK" /> アイコン（`FaQuestionCircleIcon`）を設置（推奨） | 詳細は[ヘルプページへの動線](/
他の場所では、「テキストの右、左」ならびに、「配置」と表記しているので、揃えました。

2022-08-08 07:53 UTC, aguringo commented on content/articles/products/components/icon.mdx
> +| 新規ウィンドウ（新規タブ）で開くテキストリンク | **テキストの後ろ**に <FaExternalLinkAltIcon visuallyHiddenText="新規ウィンドウ" color="TEXT_LINK" /> アイコン（`FaExternalLinkAltIcon`）を設置（必須） | リンク先がSmartHRの内部ページ、外部サイトに関わらず新規ウィンドウで開く場合は付与しま
表中のラベル扱いのテキストの（　）は煩わしいので、説明の方で新規タブについても言及するように変更

2022-08-08 07:53 UTC, aguringo commented on content/articles/products/design-patterns/help-link.mdx
> +- 新規ウィンドウで開く場合は、[「新規ウィンドウ（新規タブ）で開くテキストリンク」の装飾](/products/components/icon/#h2-4)に準じて <FaExternalLinkAltIcon visuallyHiddenText="新規ウィンドウ" color="TEXT_LINK" /> アイコン（`FaExternalLinkAltIcon`）をテキストリンクの文末に配
```suggestion
- リンクを新規ウィンドウ（新規タブ）で開く場合は、[「新規ウィンドウで開くテキストリンク」の装飾](/products/components/icon/#h2-4)に準じて <FaExternalLinkAltIcon visuallyHiddenText="新規ウィンドウ" color="TEXT_LINK" /> アイコン（`FaExternalLinkAltIcon`）をテキストリンクの左側に配置します。（必須）
- ヘルプセンターへのリンクとして認知させたい場合には、<FaQuestionCircleIcon visuallyHiddenText="ヘルプセンター" color="TEXT_LINK" /> アイコン（`FaQuestionCircleIcon`）をテキストリンクの右側に配置できます。（推奨）
    - モードレスダイアログや新規ウィンドウなど表示に関わらず、使用できます。
```

2022-08-08 07:53 UTC, aguringo commented on content/articles/products/design-patterns/help-link.mdx
> +- 新規ウィンドウで開く場合は、[「新規ウィンドウ（新規タブ）で開くテキストリンク」の装飾](/products/components/icon/#h2-4)に準じて <FaExternalLinkAltIcon visuallyHiddenText="新規ウィンドウ" color="TEXT_LINK" /> アイコン（`FaExternalLinkAltIcon`）をテキストリンクの文末に配
- 必須のアイコンを先にしました。
- 説明が冗長だったのでリライトしています。
- （新規タブ）の説明は初出のみにしています。

2022-08-08 07:54 UTC, 8chari requested changes
ありがとうございます！
1件だけコメントしました:pray:

2022-08-08 08:19 UTC, versionfive commented on content/articles/products/design-patterns/help-link.mdx
> +- 新規ウィンドウで開く場合は、[「新規ウィンドウ（新規タブ）で開くテキストリンク」の装飾](/products/components/icon/#h2-4)に準じて <FaExternalLinkAltIcon visuallyHiddenText="新規ウィンドウ" color="TEXT_LINK" /> アイコン（`FaExternalLinkAltIcon`）をテキストリンクの文末に配
このドキュメントはヘルプセンターの導線に関する説明なので、そっちのアイコンを先にしていましたが認識合いますか？（むしろ新規ウィンドウの方は補足）

2022-08-08 08:26 UTC, aguringo commented on content/articles/products/design-patterns/help-link.mdx
> +- 新規ウィンドウで開く場合は、[「新規ウィンドウ（新規タブ）で開くテキストリンク」の装飾](/products/components/icon/#h2-4)に準じて <FaExternalLinkAltIcon visuallyHiddenText="新規ウィンドウ" color="TEXT_LINK" /> アイコン（`FaExternalLinkAltIcon`）をテキストリンクの文末に配
確かにヘルプへの導線のページですが、ここはアイコンに関するルールの見出し配下なので、必須アイコンの条件を先に示したほうが良いかなと思いました。

2022-08-08 08:28 UTC, versionfive commented on content/articles/products/design-patterns/help-link.mdx
> +- 新規ウィンドウで開く場合は、[「新規ウィンドウ（新規タブ）で開くテキストリンク」の装飾](/products/components/icon/#h2-4)に準じて <FaExternalLinkAltIcon visuallyHiddenText="新規ウィンドウ" color="TEXT_LINK" /> アイコン（`FaExternalLinkAltIcon`）をテキストリンクの文末に配
…という意図を出す感じで修正pushしていますので、確認くださいませ〜 @aguringo

2022-08-08 10:09 UTC, 8chari commented on content/articles/products/design-patterns/help-link.mdx
> +モードレスダイアログや新規ウィンドウなどの表示に関わらず使用できます。
- 左と右が逆になっています:pray:
- こまいですが、句点があった方が読みやすいです→「関わらず、」
```suggestion
ヘルプセンターのリンクであることを表すために、<FaQuestionCircleIcon visuallyHiddenText="ヘルプセンター" color="TEXT_LINK" /> アイコン（`FaQuestionCircleIcon`）をテキストリンクの左側に配置できます。（推奨）  
モードレスダイアログや新規ウィンドウなどの表示に関わらず、使用できます。
```

2022-08-08 10:09 UTC, 8chari commented on content/articles/products/design-patterns/help-link.mdx
> +- リンクを新規ウィンドウ（新規タブ）で開く場合は、[「新規ウィンドウで開くテキストリンク」の装飾](/products/components/icon/#h2-4)に準じて <FaExternalLinkAltIcon visuallyHiddenText="新規ウィンドウ" color="TEXT_LINK" /> アイコン（`FaExternalLinkAltIcon`）をテキストリンクの
こちらも逆になっています:pray:
```suggestion
- リンクを新規ウィンドウ（新規タブ）で開く場合は、[「新規ウィンドウで開くテキストリンク」の装飾](/products/components/icon/#h2-4)に準じて <FaExternalLinkAltIcon visuallyHiddenText="新規ウィンドウ" color="TEXT_LINK" /> アイコン（`FaExternalLinkAltIcon`）をテキストリンクの右側に配置してください。（必須）
```

2022-08-08 10:15 UTC, 8chari requested changes
@versionfive 
細かいのですが、大事なところなので2件コメントしています:pray:

2022-08-08 10:22 UTC, versionfive commented
@8chari わああああ、ほんまや！ありがとうございます🙏

2022-08-08 10:28 UTC, 8chari approved these changes
👍

2022-08-09 01:42 UTC, aguringo approved these changes
:arigatau::gogo:

2022-08-09 01:53 UTC, merged