MDXコンテンツ用のスタイルを調整
kufu/smarthr-design-system pull request #241
Opened 2022-08-16 07:12 UTC by yuw27b

## 課題・背景
https://github.com/kufu/smarthr-design-system-issues/issues/1026

## やったこと
`src/templates/article.tsx`内にMDXコンテンツ全体に適用されるCSSが定義されていますが、`td`の中の`p`や入れ子になった`ul`の子要素などに意図しない上マージンが効いているケースがあったため、CSSを修正しました。

具体的には、`td`内の`p`、`ul`、`ol`の先頭の要素（`:first-child`）と、入れ子になった`ul`または`ol`の子の先頭の要素について、`margin-block-start: 0;`を追加しました。

## 動作確認
/products/design-tokens/typography/#h3-3
/products/design-patterns/table-bulk-action/#h2-0
/products/contents/help-center/#h3-3
/products/contents/idiomatic-usage/data/

## キャプチャ

|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/184818223-c59d0f1f-7c54-40ae-9b58-464747e77705.png" width="350" alt> | <img src="https://user-images.githubusercontent.com/7822534/184818160-fd801d18-065c-4e8a-b3d7-fda413728833.png" width="350" alt> |
| <img src="https://user-images.githubusercontent.com/7822534/184818528-ba901e5f-eb92-43e5-8936-da7cd36a37e6.png" width="350" alt> | <img src="https://user-images.githubusercontent.com/7822534/184818470-fc95037e-1d2f-4c48-9fcf-3f30fec072fc.png" width="350" alt> |
| <img src="https://user-images.githubusercontent.com/7822534/184818939-d95a6588-38f4-40dd-9338-3b04272ecb25.png" width="350" alt> | <img src="https://user-images.githubusercontent.com/7822534/184818807-d87381d7-18e0-4e53-a5a6-7190655a98f1.png" width="350" alt> |

2022-08-17 00:29 UTC, tomof submitted a review, later dismissed
@yuw27b 良さそうです！LGTM🎉

2022-08-17 00:37 UTC, tomof commented
@versionfive 確認お願いします🙏

2022-08-18 07:20 UTC, versionfive requested changes
ここに当たってないみたいです。
https://deploy-preview-241--smarthr-design-system.netlify.app/products/design-patterns/help-link/#h3-0

2022-08-18 09:04 UTC, yuw27b commented
@versionfive ご指摘ありがとうございます、対応しました：
https://deploy-preview-241--smarthr-design-system.netlify.app/products/design-patterns/help-link/#h3-0

こちら、太字部分の`<strong>`タグがあるために、`ul ul:first-child`ではCSSが適用になっていませんでした。リストの入れ子の場合、
```
ul
  li
    ul（子リスト1つめ）
    ul（子リスト2つめ）
  li
  ...
```
のように子リストが並ぶことはあまりなさそうですし、並んだとしても、どちらも上マージンは不要かと思いますので、`first-child`をなくし、子（あるいは孫でも）になる`ul`・`ol`はすべて上マージンなしにしました。

2022-08-18 09:46 UTC, versionfive approved these changes

2022-08-18 09:46 UTC, merged