UIテキストとヘルプセンター／リリースノートでのボタンを囲う括弧の統一に伴う、ドキュメントの修正
kufu/smarthr-design-system pull request #262
Opened 2022-08-30 12:09 UTC by aguringo

## 課題・背景
https://github.com/kufu/smarthr-design-system-issues/issues/1047

## やったこと
- リリースノートガイドライン
　- テキストを修正
　- ライティングガイドへのリンクを修正
- ヘルプセンターガイドライン、ヘルプページの構成を修正
　- その他、リンクの追加や変更に追随できていなかった部分も併せて修正

## 動作確認
- Previewでみてね。

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2022-08-30 12:19 UTC, 8chari commented on content/articles/products/contents/help-center/help-page.mdx
> +また、表記ルールは、基本的にプロダクトデザインにおける[ライティングガイドライン](../writing-style/)、[用字用語](../idiomatic-usage/data/)、[UIテキスト](../app-writing/)に準拠します。
リンク先のタイトルに合わせると、ライティングスタイルが良さそうです。
```suggestion
また、表記ルールは、基本的にプロダクトデザインにおける[ライティングスタイル](../writing-style/)、[用字用語](../idiomatic-usage/data/)、[UIテキスト](../app-writing/)に準拠します。
```

2022-08-30 12:22 UTC, 8chari commented on content/articles/products/contents/help-center/index.mdx
> +ヘルプページのライティングは、基本的にプロダクトデザインにおける[ライティングガイドライン](../writing-style/)、[用字用語](../idiomatic-usage/data/)、[UIテキスト](../app-writing/)に準拠しますが、ユーザーのメンタルモデルに配慮して特例を設けているケースがあります。
```suggestion
ヘルプページのライティングは、基本的にプロダクトデザインにおける[ライティングスタイル](../writing-style/)、[用字用語](../idiomatic-usage/data/)、[UIテキスト](../app-writing/)に準拠しますが、ユーザーのメンタルモデルに配慮して特例を設けているケースがあります。  
```

2022-08-30 12:28 UTC, 8chari requested changes
@aguringo 2箇所だけsuggestでコメントしました。よろしくお願いします！

2022-08-31 01:21 UTC, aguringo commented
@8chari suggest、コミットしました！
確認お願いします🙏

2022-08-31 01:37 UTC, 8chari commented on content/articles/products/contents/help-center/index.mdx
> +ヘルプページのライティングは、基本的にプロダクトデザインにおける[ライティングスタイル](../writing-style/)、[用字用語](../idiomatic-usage/data/)、[UIテキスト](../app-writing/)に準拠しますが、ユーザーのメンタルモデルに配慮して特例を設けているケースがあります。
@aguringo 
あとからですみません！！飛び先が404エラーになっています🙏`help-center`の部分が不要だと思います。
products/contents/help-center/writing-style/
/products/contents/help-center/idiomatic-usage/data/
products/contents/help-center/app-writing/

2022-08-31 01:38 UTC, 8chari commented on content/articles/products/contents/help-center/help-page.mdx
> +また、表記ルールは、基本的にプロダクトデザインにおける[ライティングスタイル](../writing-style/)、[用字用語](../idiomatic-usage/data/)、[UIテキスト](../app-writing/)に準拠します。
@aguringo
あとからですみません！！飛び先が404エラーになっています🙏help-centerの部分が不要だと思います。
- products/contents/help-center/writing-style/
- /products/contents/help-center/idiomatic-usage/data/
- products/contents/help-center/app-writing/

2022-09-01 01:45 UTC, aguringo commented
> @aguringo リンクエラーがあったのでコメントしています🙇

https://github.com/kufu/smarthr-design-system/pull/262/commits/93cddeb03ea21117d790d7a8db6d4de65e571cf5
修正しました！

2022-09-01 02:44 UTC, 8chari approved these changes
👍 👍 👍 👍 👍

2022-09-01 02:44 UTC, merged