💬: ミッションを差し替え
kufu/smarthr-design-system pull request #277
Opened 2022-09-07 10:12 UTC by uknmr

プロダクト関連で使われている「社会の非合理を、ハックする」を「well-working 労働にまつわる社会課題をなくし、誰もがその人らしく働ける社会をつくる。」に差し替えた。

2022-09-07 10:29 UTC, versionfive approved these changes
LGTM!

2022-09-07 10:29 UTC, versionfive commented on content/articles/products/design-tokens/typography.mdx
> -      <Td><Sampletext size={'S'}>社会の非合理を、ハックする。</Sampletext></Td>
そういえば16px基準になったから段落テキストには`XS`も追加していいなーと気づきました。

2022-09-07 22:14 UTC, uknmr commented on content/articles/products/design-tokens/typography.mdx
> -      <Td><Sampletext size={'S'}>社会の非合理を、ハックする。</Sampletext></Td>
追加した 7ce62c3

2022-09-08 01:12 UTC, versionfive requested changes
nitsですが、段落テキストの説明文にある

>サイズ小の積極的な使用は避け、レイアウトの都合上、どうしようもない場合に使います。

これを
```
サイズ小とサイズ極小の積極的な使用は避け、レイアウトの都合上、どうしようもない場合に使います。
```
にしたほうがよいかもです。

2022-09-08 03:29 UTC, uknmr commented
修正しました! [832a4b2](https://github.com/kufu/smarthr-design-system/pull/277/commits/832a4b284af9096c2c327dfdf8d53dd194cfc5b0)

2022-09-08 04:44 UTC, versionfive approved these changes
LTGM!!

2022-09-08 04:44 UTC, merged