「伝わる文章の書き方」を「基本要素」に追加
kufu/smarthr-design-system pull request #339
Opened 2022-10-28 01:38 UTC by 8chari

「伝わる文章の書き方」を「基本要素」に追加しました。
冒頭の「対象」は別途アップデートします。

## 課題・背景
https://github.com/kufu/smarthr-design-system-issues/issues/1102

## やったこと
- 「伝わる文章の書き方」を「基本要素」に追加
- 「基本要素」内のorderを修正
  - イラストレーションを「6」→「5」に変更

## やらなかったこと
- 「対象」の更新
  - @aguringo さんにお願いしています。

## 動作確認
- Previewで確認お願いします。

2022-10-28 04:15 UTC, ibulog commented on content/articles/basics/text/index.mdx
> +読者の目線に立ち、コンテンツの目的に適した情報を取捨選択しましょう。
細いですが、「取捨選択」は「不要な情報を捨てる」ことも含まれるので、「コンテンツの目的に適した情報を」「取捨選択する」という使い方はしない方がいいかも？と思いました！
```suggestion
### コンテンツの目的に合わせて情報を取捨選択する
読者の目線に立ち、コンテンツの目的に合わせて情報を取捨選択しましょう。
```

2022-10-28 04:15 UTC, ibulog commented on content/articles/basics/text/index.mdx
> +**読者に与えたい印象**
```suggestion
**読者に与えたい印象**

```

2022-10-28 04:15 UTC, ibulog commented on content/articles/basics/text/index.mdx
> +意味の重複が無くなり、より簡潔で読みやすくなりました。
ここだけ「〜なりました」の形だったので、揃えた方がよさそうです。
```suggestion
意味の重複を無くし、より簡潔で読みやすくしています。
```

2022-10-28 04:15 UTC, ibulog commented on content/articles/basics/text/index.mdx
> +「権限がないと手続きを作成できない」と二重否定になっていることで、読者が「権限があると手続きを作成できる」と読みかえる必要が生じています。
反映はお任せしますが、「必要が生じる」ってあんまり見慣れない表現だな、と思いました。
```suggestion
「権限がないと手続きを作成できない」と二重否定になっていることで、読者が「権限があると手続きを作成できる」と読みかえる手間が生じています。
```

2022-10-28 04:15 UTC, ibulog commented on content/articles/basics/text/index.mdx
> +* 同じ言葉を繰り返して使うことで読みづらくなっていたり、稚拙な印象を与えていたりしていないか
意味のまとまり的に、読点を入れたいです！
```suggestion
* 同じ言葉を繰り返して使うことで、読みづらくなっていたり、稚拙な印象を与えていたりしていないか
```

2022-10-28 07:30 UTC, 8chari commented on content/articles/basics/text/index.mdx
> +* 「厚生年金保険」でインターネット検索をした人に、厚生年金保険の内容を伝えるための文章にも関わらず、厚生年金保険以外の話から始まっており、読者が「厚生年金保険」とは何かを把握するのに時間がかかる内容になっています。
@aguringo 
リライトありがとうございます🙏
ここだけ一文が長めなので、少し短くできると良さそうと思ったのですが、いかがでしょう？

```suggestion
* 厚生年金保険の内容を伝えるための文章にも関わらず、厚生年金保険以外の話から始まっており、「厚生年金保険」でインターネット検索をした人が「厚生年金保険」とは何かを把握するのに時間がかかる内容になっています。
```

2022-10-31 00:44 UTC, aguringo reviewed
私のチェックはOKですぅ〜

@samemaru @a50akiki @sayuriko @chihari 
コムデズに見てもらいたいです

2022-10-31 08:53 UTC, samemaru requested changes
すごい！待ってた〜！
いくつかコメントを入れましたので、ご確認よろしくお願いします！

2022-10-31 08:53 UTC, samemaru commented on content/articles/basics/text/index.mdx
> +どういう思考プロセスからどんな表現が生まれるのか、参考として実例を紹介しています。実際に読み比べ、SmartHRの社員として何かを伝えようとするときの、参考にしてください。
```suggestion
どういう思考プロセスからどんな表現が生まれるのか、参考として実例を紹介しています。実際に読み比べ、SmartHRの従業員として何かを伝えようとするときの、参考にしてください。
```
雇用形態は関係ないので、修正をお願いします！
デザインシステムではすべて「従業員」と表現しています。
https://smarthr.design/concept/about/#h2-0

2022-10-31 08:53 UTC, samemaru commented on content/articles/basics/text/index.mdx
> +`hogehogeのデータによると、○○業界は離職率が平均◯％で、決して低い数字ではありません。`
データの部分だけ`○○`ではなく `hogehoge` とルールが違うようですが、なにか意図がありますか？
`○○○○`や `△△` など、ほかの要素を合わせるといいかな、と思いました

2022-10-31 08:53 UTC, samemaru commented on content/articles/basics/text/index.mdx
> +`SmartHRの中だけでつくるのではなく、サードパーティへの提供を進めます。`
おそらくSmartHR Plus のようなプラットフォーム関連の一文だと思うのですが、一文だけではAfterでも意味がよくわかりませんでした。
（`SmartHRの中だけでつくる` ってどういう意味か想像つかない。なにをつくるんだろう？）
もうすこし情報を補足するなど、一文でも通じる内容になると嬉しいです。

2022-10-31 08:53 UTC, samemaru commented on content/articles/basics/text/index.mdx
> +`手続き > 住所変更手続きの［作成］権限がある場合、ホームにある［従業員の住所変更］または［住所変更の手続き］から住所変更手続きを作成できます。`
`手続き > ` 
これはヘルプセンターなどで出てくる、UI階層の表現ですかね？
私は、最初は意味がわからなくて戸惑いました。
ここは文章の書き方の実例なので、省いてもいいかなと思いました。

2022-10-31 10:05 UTC, aguringo commented
@8chari 
お願いしますぅ:pray:

2022-10-31 10:21 UTC, 8chari commented on content/articles/basics/text/index.mdx
> +`hogehogeのデータによると、○○業界は離職率が平均◯％で、決して低い数字ではありません。`
ありがとうございます🙏
特に意図はなかったため、`hogehoge`を`〇〇`に変更して、`△△業界`とします！

2022-10-31 10:29 UTC, 8chari commented on content/articles/basics/text/index.mdx
> +`SmartHRの中だけでつくるのではなく、サードパーティへの提供を進めます。`
ありがとうございます！
ここで伝えたいのは「情報の重複がないように書くことで簡潔な文章になる」ことなので、それが伝わりやすい別の例文に変えたいと思います🙏

2022-10-31 10:30 UTC, 8chari commented on content/articles/basics/text/index.mdx
> +`手続き > 住所変更手続きの［作成］権限がある場合、ホームにある［従業員の住所変更］または［住所変更の手続き］から住所変更手続きを作成できます。`
ありがとうございます！おっしゃるとおりなので、省きます🙏

2022-10-31 11:23 UTC, 8chari commented
@samemaru さんのコメント、反映しました！確認お願いします🙏

2022-10-31 12:46 UTC, uknmr requested changes
内容の前に HTML が気になってしまいました🤗
伝わる HTML にもしたい〜

2022-10-31 12:46 UTC, uknmr commented on content/articles/basics/text/index.mdx
> +**目的**
p > strong は意図的ですか?
h5 でよさそうに見えました。以降も同じ。

2022-10-31 12:46 UTC, uknmr commented on content/articles/basics/text/index.mdx
> +`日本の年金制度は、全国民に共通した基礎年金（国民年金）を基礎に、2階部分にあたる厚生年金、その上乗せ部分である企業年金の3階建ての体系となっています。では、企業年金とはどのようなものでしょうか。企業年金とは、企業が社員に対して年金を支給する仕組みのことです。企業年金には3種類の年金制度があり、その3つでいろいろと条件が違ってきます。詳しくは、後述します。`
`code` 扱いになってしまうので、意味的には `blockquote` かも。以降も同じ
https://developer.mozilla.org/ja/docs/Web/HTML/Element/blockquote

2022-10-31 12:46 UTC, uknmr commented on content/articles/basics/text/index.mdx
> +* 厚生年金保険の内容を伝えるための文章にも関わらず、厚生年金保険以外の話から始まっており、「厚生年金保険」でインターネット検索をした人が「厚生年金保険」とは何かを把握するのに時間がかかる内容になっています。
リストにしているのは意図的ですか?
通常の段落でよさそうに思いました!

2022-10-31 13:00 UTC, 8chari commented on content/articles/basics/text/index.mdx
> +**目的**
ありがとうございます🙏h5に変えて問題ないので変えます！

2022-10-31 13:05 UTC, 8chari commented on content/articles/basics/text/index.mdx
> +`日本の年金制度は、全国民に共通した基礎年金（国民年金）を基礎に、2階部分にあたる厚生年金、その上乗せ部分である企業年金の3階建ての体系となっています。では、企業年金とはどのようなものでしょうか。企業年金とは、企業が社員に対して年金を支給する仕組みのことです。企業年金には3種類の年金制度があり、その3つでいろいろと条件が違ってきます。詳しくは、後述します。`
試してみたんですが、どこまでが例文で、どこからが例文の解説なのかが少しわかりづらくなるかなと思っていて、`code`のままでいきたいな〜というお気持ちです。いかがでしょう…？

![image](https://user-images.githubusercontent.com/85212123/199014215-0cd7f8a8-ddf2-48fe-85e5-2367c7d2b739.png)

2022-10-31 13:06 UTC, 8chari commented on content/articles/basics/text/index.mdx
> +* 厚生年金保険の内容を伝えるための文章にも関わらず、厚生年金保険以外の話から始まっており、「厚生年金保険」でインターネット検索をした人が「厚生年金保険」とは何かを把握するのに時間がかかる内容になっています。
ここ、@aguringo さんに追加コミットで更新いただいた部分なので、aguriさんに確認お願いしたいです🙏🙏🙏

2022-10-31 13:18 UTC, uknmr commented on content/articles/basics/text/index.mdx
> +`日本の年金制度は、全国民に共通した基礎年金（国民年金）を基礎に、2階部分にあたる厚生年金、その上乗せ部分である企業年金の3階建ての体系となっています。では、企業年金とはどのようなものでしょうか。企業年金とは、企業が社員に対して年金を支給する仕組みのことです。企業年金には3種類の年金制度があり、その3つでいろいろと条件が違ってきます。詳しくは、後述します。`
> 通常、字下げを伴ってレンダリングされます
> https://developer.mozilla.org/ja/docs/Web/HTML/Element/blockquote

字下げがあるので十分違いがあるように感じました!
いずれにせよ装飾の問題なので `code` ではないと思います。

> コンピューターコードの短い断片の文字列であると識別できるような外見のコンテンツを表示します。
> https://developer.mozilla.org/ja/docs/Web/HTML/Element/code

2022-11-01 00:48 UTC, 8chari commented on content/articles/basics/text/index.mdx
> +`日本の年金制度は、全国民に共通した基礎年金（国民年金）を基礎に、2階部分にあたる厚生年金、その上乗せ部分である企業年金の3階建ての体系となっています。では、企業年金とはどのようなものでしょうか。企業年金とは、企業が社員に対して年金を支給する仕組みのことです。企業年金には3種類の年金制度があり、その3つでいろいろと条件が違ってきます。詳しくは、後述します。`
`code`ではない点、:crab:すぎるので、 `blockquote` に変更します！ありがとうございます〜🙏

2022-11-01 01:22 UTC, uknmr commented on content/articles/basics/text/index.mdx
> +`日本の年金制度は、全国民に共通した基礎年金（国民年金）を基礎に、2階部分にあたる厚生年金、その上乗せ部分である企業年金の3階建ての体系となっています。では、企業年金とはどのようなものでしょうか。企業年金とは、企業が社員に対して年金を支給する仕組みのことです。企業年金には3種類の年金制度があり、その3つでいろいろと条件が違ってきます。詳しくは、後述します。`
`blockquote` の装飾に難があれば、別チケットでやるのが良いと思います〜!

2022-11-01 04:30 UTC, samemaru requested changes
すみません、追加で1ヶ所提案です :pray:

2022-11-01 04:30 UTC, samemaru commented on content/articles/basics/text/index.mdx
> +* 「水のペットボトルのパッケージ」と、誰が読んでも同じものをイメージできる表現に言い換えています。
```suggestion
`パンフレット1枚でも、水のペットボトルのラベルでも、社内外のあらゆる制作物の細部までクオリティにこだわります。プロダクト以外でも「良さそう」と感じてもらい、信頼につなげることが役割だと思っています。`

* 「水のペットボトルのラベル」と、誰が読んでも同じものをイメージできる表現に言い換えています。
```
実際制作したメンバーに確認してきました！
こちらの表記でお願いします:pray:

2022-11-01 07:08 UTC, 8chari commented on content/articles/basics/text/index.mdx
> +* 「水のペットボトルのパッケージ」と、誰が読んでも同じものをイメージできる表現に言い換えています。
ありがとうございます🙇反映します！

2022-11-01 07:33 UTC, 8chari commented
@uknmr @aguringo @samemaru 
ありがとうございました！頂いたFBを反映して、再コミットしましたので、ご確認お願いします！

[こちら](https://github.com/kufu/smarthr-design-system/pull/339#discussion_r1009375086)、箇条書きが1つのものは通常の段落に変更しています！もし、違う〜〜等あれば、コメントください🙏

問題なければ、approveお願いします:bow:

2022-11-01 08:37 UTC, samemaru approved these changes
うお〜！LGTM〜！

2022-11-01 20:36 UTC, uknmr reviewed
チェックリスト見ながら「これ、なんでなんだっけ?」を実例に見に行きたくなったので、ナビゲーションやコンテンツの配置を見直すときに、チェックリストは別ページでもよさそうと思いました!

imo は箇条書きを段落にした2つ。他に合わせたくなってしまった😇

2022-11-01 20:36 UTC, uknmr commented on content/articles/basics/text/index.mdx
> +* 読者が知りたいキーワード「厚生年金保険」が冒頭にあることで、求めている記事だと読者が早い段階で認知でき、その後の説明を理解しやすくなります。
imo

```suggestion
「厚生年金保険」の定義を端的に述べたあとで、詳細を説明する流れです。  
また、読者が知りたいキーワード「厚生年金保険」が冒頭にあることで、求めている記事だと読者が早い段階で認知でき、その後の説明を理解しやすくなります。
```

2022-11-01 20:36 UTC, uknmr commented on content/articles/basics/text/index.mdx
> +* 主語と述語が曖昧になり、一読して理解しづらい内容になっています。
imo

```suggestion
「金額の内訳」と「決済」の2つの情報が一文で書かれています。  
また、主語と述語が曖昧になり、一読して理解しづらい内容になっています。
```

2022-11-02 00:28 UTC, uknmr approved these changes

2022-11-02 00:32 UTC, merged