仮置きのテキストを追加
kufu/smarthr-design-system pull request #358
Opened 2022-11-07 10:15 UTC by omameoicy

## 課題・背景
- 仮に入れるテキストが定義されていなかった。
  - それにより、コミュニケーションや調査に時間がかかっていた。
https://github.com/kufu/smarthr-design-system-issues/issues/1100

## やったこと
- 仮置きのテキストのページを追加
  - 住所
  - 固定電話番号
  - 携帯電話番号

## やらなかったこと
hoge

## 動作確認

## キャプチャ
<img width="1507" alt="仮置きのテキスト追加後" src="https://user-images.githubusercontent.com/101125529/200285191-8d6447d6-2bb1-449d-b2be-57764f3eedc6.png">

2022-11-21 11:58 UTC, 8chari commented on content/articles/communication/sample/text.mdx
> +- プロダクトの入力例が表示されているプレースホルダ
[‐er、‐or、‐arで終わる単語は「長音あり」、-yで終わる単語は「長音なし」とする（例外あり）](https://smarthr.design/products/contents/idiomatic-usage/usage/#recKk3i3NODrXp6D3-0)に従って、長音（ー）を付けました:pray:
```suggestion
- プロダクトの入力例が表示されているプレースホルダー
```

2022-11-21 11:59 UTC, 8chari commented on content/articles/communication/sample/text.mdx
> +| 固定電話番号 | **03-1234-5678** | 2つ以上掲載したい場合は、先頭を「03」にして、以降は0から9までの整数を順に記載してください（例: 03-2345-6789） |
細かいのですが、`：`を全角表記にしています:pray:
```suggestion
| 固定電話番号 | **03-1234-5678** | 2つ以上掲載したい場合は、先頭を「03」にして、以降は0から9までの整数を順に記載してください（例：03-2345-6789） |
```

2022-11-21 12:00 UTC, 8chari commented on content/articles/communication/sample/text.mdx
> +| 携帯電話番号 | **080-1234-5678** | 2つ以上掲載したい場合は、先頭を「080」にして、以降は0から9までの整数を順に記載してください（例: 080-2345-6789） |
```suggestion
| 携帯電話番号 | **080-1234-5678** | 2つ以上掲載したい場合は、先頭を「080」にして、以降は0から9までの整数を順に記載してください（例：080-2345-6789） |
```

2022-11-21 12:01 UTC, 8chari commented on content/articles/communication/sample/text.mdx
> +- 社内Slack　`#ext_design_system`
相談先の社内slackでいうと、`#design_system_相談`が良いのかなと思ったのですが、いかがでしょう？

2022-11-21 12:02 UTC, 8chari requested changes
細かい部分ばかりで恐縮ですが、コメントを入れました🙏よろしくおねがいします〜！

2022-11-22 01:31 UTC, omameoicy commented on content/articles/communication/sample/text.mdx
> +- 社内Slack　`#ext_design_system`
ありがとうございます！確かにサンプルテキストについて、コムデの依頼チャンネルから相談いただくより ``#design_system_相談``の方が相談がコムデだけに閉じなくてスムーズかもです！

@samemaru さんいかがでしょう？コミュニケーション領域の相談先は``#design_comm_依頼``に統一したいなどありますでしょうか👀

2022-11-22 07:38 UTC, samemaru commented on content/articles/communication/sample/text.mdx
> +- 社内Slack　`#ext_design_system`
あ、ほんとだ、そうですね！
 `#design_comm_依頼` がよさそうです〜！

2022-11-28 05:54 UTC, omameoicy commented on content/articles/communication/sample/text.mdx
> +- 社内Slack　`#ext_design_system`
お待たせです🙏フィードバック先を`#design_comm_依頼`に変更しました〜！

2022-11-28 09:35 UTC, samemaru approved these changes
LGTM〜

2022-11-28 09:39 UTC, 8chari approved these changes
:lgtm: 🎉

2022-11-28 09:40 UTC, merged

2022-11-28 09:41 UTC, omameoicy commented
おふたりともありがとうございます〜！🎉