ファシリテータの役割のドキュメントを追加
kufu/smarthr-design-system pull request #373
Opened 2022-11-16 08:16 UTC by oremega

## 課題・背景

ユーザビリティテストのファシリテータの役割のドキュメントを追加しました。

## やったこと

- `/products/design-process/usability-test/role_facilitator.mdx`を追加
- `/products/design-process/usability-test/index.mdx`にリンクを追加
- `/products/design-process/usability-test/design_perspective.mdx`の見出しのレベルを変更

## やらなかったこと
なし

## 動作確認

- 文章の内容をみて意味的に変なところがないかを確認してほしい
- 文章の誤字脱字を確認してほしい

## キャプチャ

- なし

2022-11-16 09:19 UTC, versionfive reviewed
nitsな部分でSuggestionしていますが、全体的によさそうです〜

2022-11-16 09:19 UTC, versionfive commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +アイスブレイクや事前質問などで、被験者の緊張を和らげる効果につながりあります。またテストに不備があっても、空気が悪くなるのを減らす効果もあります。
```suggestion
アイスブレイクや事前質問などで、被験者の緊張を和らげる効果につながります。またテストに不備があっても、空気が悪くなるのを減らす効果もあります。
```

2022-11-16 09:19 UTC, versionfive commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +一般的には、オープンクエスチョン（はい、いいえで答えられない質問）の質問をすることで発話量が増えます。また、あえてクローズドクエスチョン（はい、いいえで答えられる質問）の質問をすることで被験者との会話のリズムを掴み、スムーズな受け答えをしてもらえるようにします。
```suggestion
一般的には、オープンクエスチョン（はい、いいえで答えられない質問）の質問をすることで発話量が増えます。また、あえてクローズドクエスチョン（はい、いいえで答えられる質問）の質問をすることで、スムーズな受け答えができるように被験者との会話のリズムを掴むことも有効です。
```

2022-11-16 09:19 UTC, versionfive commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +zoomを使ったオンラインでテストを実施する場合、[イントロダクション](/products/design-process/usability-test/design_perspective/#h3-3)で録画と配信の許可を被験者からもらう必要があります。許可をもらったあとは録画ボタンの押し忘れがないように録画が開始したことを確認してから進行しましょう。
```suggestion
zoomを使ったオンラインでテストを実施する場合、[イントロダクション](/products/design-process/usability-test/design_perspective/#h3-3)で被験者から録画と配信の許可をもらう必要があります。許可をもらったあとは録画ボタンの押し忘れがないように録画が開始したことを確認してから進行しましょう。
```

2022-11-16 09:19 UTC, versionfive commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +**ポイント:**
```suggestion
被験者に過度に負荷をかけるのは検証したい目的を達成できなかったり、テスト自体に悪い印象を持つことがあります。以下のような場合には、テストの結果に影響を与えないように配慮しながらサポートします。

```
以下のような場合には、とあるので「ポイント」ではないかなと思いました。

2022-11-16 09:19 UTC, versionfive commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +テスト後の被験者の意見にはバイアスがかかります。テスト序盤よりも終盤の印象を元に話したり、無意識的に自分をよく見せる発言をすることがあります。また、テスト結果やプロダクトに満足していなくても、印象が良くみえる発言をしてしまうこともあるのを覚えておきましょう。
```suggestion
振り返りでは、被験者の行動と思考発話で気になったところを質問することで、被験者の「行動」と「思考」を一致させることが目的になります。

テスト後の被験者の意見にはバイアスがかかります。テスト序盤よりも終盤の印象を元に話したり、無意識的に自分をよく見せる発言をすることがあります。また、テスト結果やプロダクトに満足していなくても、印象が良くみえる発言をしてしまうこともあるのを覚えておきましょう。
```

2022-11-16 09:19 UTC, versionfive commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +被験者は答えを持っていません。具体的な改善案は開発チームで考えましょう。
```suggestion
被験者の意見はそのまま受け止めず、補足情報と考えましょう。被験者の「行動」を観察し、気になる行動に対して質問します。  
被験者は答えを持っていません。具体的な改善案は開発チームで考えましょう。
```

2022-11-16 09:19 UTC, versionfive commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +また、テストによって見つかった改善がリリースされたときに連絡することも大切です。
```suggestion
テスト終了後、被験者に参加してくれたことに対してお礼をしましょう。具体的にテストのどの部分が参考になったか、テストを実施したことによってどのような改善や対応に繋がったかを共有することは、被験者がプロダクトに貢献できたと感じられる、テスト実施側からの重要なフィードバックです。

また、テストによって見つかった改善がリリースされたときに連絡することも大切です。
```

2022-11-17 02:50 UTC, aguringo requested changes
@oremega @versionfive @wentzzz 
主に表現がアケスケなところに配慮してリライトをしています。

URLに関わってくる部分なのですが、ファイル名、どうしよう…

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +被験者とは初対面であることがほとんどなので、緊張をほぐす意味を込めて、普段よりも声のトーンを上げて明るい雰囲気で接して安心感を与えましょう。
```suggestion
多くの場合、被験者とは初対面です。意識的に普段よりも声のトーンを上げて会話して、明るい雰囲気で相手の緊張をほぐし、安心感を与えましょう。
```

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +被験者とは初対面であることがほとんどなので、緊張をほぐす意味を込めて、普段よりも声のトーンを上げて明るい雰囲気で接して安心感を与えましょう。
明るい雰囲気を作るの具体的なアクションが、普段よりも声のトーンをあげることなので、ファシリテーターを務める人がどうすればわかりやすい語順で書き直しています。

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +被験者について調べておくことで、テスト前の事前質問やアイスブレイクに活用し、信頼関係（ラポール）※1の構築に役立てます。
```suggestion
あらかじめ、被験者に関する情報を知っておくことで、テスト前の事前質問やアイスブレイクに活用し、信頼関係（ラポール）※1の構築に役立てます。  
```

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +被験者について調べておくことで、テスト前の事前質問やアイスブレイクに活用し、信頼関係（ラポール）※1の構築に役立てます。
「調べる」は場合によってはネガティブな印象を与えるので、表現を変更しています。

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +企業規模、業種、契約プランの把握や、要望や問い合わせからどのようなお客さまが使用しているかを把握しておく。
```suggestion
企業規模、業種、契約プランといった情報だけでなく、過去に要望や問い合わせをいただいている場合には、その内容からどのようにプロダクトを利用しているかを把握しておく。
```

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +直近に参加したリサーチがあれば把握しておき、アイスブレイクのネタに使う。
```suggestion
これまでに参加した他のリサーチがあれば、その記録も確認しておくと、アイスブレイクの話題として使いやすいです。
```

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +被験者の自己紹介を事前に確認しておき、アイスブレイクのネタに使う。
```suggestion
被験者の自己紹介記事を事前に確認しておきましょう。
```

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +被験者の自己紹介を事前に確認しておき、アイスブレイクのネタに使う。
社外の人が見たらよくわからない表現になっているのと、「アイスブレイクのネタ」という砕けた表現はさけたいので、シンプルに修正しました。

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +カスタマーサポートやカスタマーサクセスのメンバーの場合は、ユーザーが困っている機能の話や、頻繁に質問される項目をもとに事前質問で聞けるように準備する。
```suggestion
カスタマーサポートやカスタマーサクセスのメンバーの場合は、ユーザーの困りごとやわかりづらい機能、ユースケースなど、ユーザーに関して事前質問ができるよう、社内のドキュメントやSlackのデスクチャンネルなどを確認しておきましょう。
```

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +テストで目的を果たすことは大事ですが、被験者が気持ちよくテストを受けられることも意識しましょう。被験者が貴重な時間を割いてテストに参加してくれていることを忘れてはいけません。
```suggestion
被験者が貴重な時間を割いてテストに参加してくれていることを、忘れてはいけません。  
テストの目的を果たすことも大事ですが、被験者が気持ちよくテストを受けられることも意識しましょう。
```

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +被験者は慣れてないテストにとても緊張しています。テストが始まるまでの間に被験者と話して緊張を解していきましょう。
```suggestion
「テストを受ける」という状況で、被験者は緊張しています。テストが始めるまでに被験者と会話して、緊張をほぐしていきましょう。
```

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +被験者は慣れてないテストにとても緊張しています。テストが始まるまでの間に被験者と話して緊張を解していきましょう。
「慣れ・不慣れ」で語ってしまうのもなぁ…と思ったので、被験者の状況を書いてみました。

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +アイスブレイクや事前質問などで、被験者の緊張を和らげる効果につながります。またテストに不備があっても、空気が悪くなるのを減らす効果もあります。
```suggestion
アイスブレイクや事前質問などは、被験者の緊張を和らげる効果につながります。またテスト中のトラブルがあった場合に円滑にカバーする土壌にもつながります。
```

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +アイスブレイクや事前質問などで、被験者の緊張を和らげる効果につながります。またテストに不備があっても、空気が悪くなるのを減らす効果もあります。
表現が直接的だったので、少し直しました。

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +テスト中は被験者が自力でタスク完了できることを第一に考え、必要以上のサポートを行なわず、被験者の操作と発言を見守るようにしてください。
```suggestion
テスト中は被験者が自力でタスク完了できることを第一に考え、必要以上に誘導せず、被験者の操作と発言を見守るようにしてください。
```

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +テスト中は被験者が自力でタスク完了できることを第一に考え、必要以上のサポートを行なわず、被験者の操作と発言を見守るようにしてください。
このドキュメントでいう「サポート」は、雰囲気づくりとかも含めた行為を言うと思うので、誘導としました。

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +#### 被験者をサポートする場合
```suggestion
#### 被験者を誘導する場合
```

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +被験者に過度に負荷をかけるのは検証したい目的を達成できなかったり、テスト自体に悪い印象を持つことがあるので、以下のような場合には、テストの結果に影響を与えないように配慮しながらサポートします。
```suggestion
テスト中の被験者に過度にプレッシャーを与えると、検証したい目的を達成できなかったり、被験者が今後テストにネガティブな印象を抱いてしまうことがあります。  
以下のような場合には、テストの結果に影響を与えないように配慮しながら被験者が操作しやすいように誘導します。
```

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +ファシリテーターは、以下のような声がけで思考発話を促してください。
```suggestion
思考発話とは、操作しながらその時に考えていることを発話することです。  
被験者は、操作と発言を同時にすることに慣れていないことが多いため、無言になったり、途中で発話が止まることがあります。ファシリテーターは、以下のような声がけで思考発話を促してください。
```

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +ファシリテーターは、以下のような声がけで思考発話を促してください。
改行位置を変えたいです。

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +ファシリテーターの質問に対して、色々な答えが返ってきますが、必ずどの程度の意図なのかを確認します。「使いづらい」といっても全く使えないのか、苛つくが使えるのか、では大きな違いがあります。
```suggestion
被験者からはさまざまな感想や印象が得られますが、必ず意図を確認しましょう。  
「使いづらい」という一言でも、「全く使えない」のか、「面倒だけれど使える」のか、では大きな違いがあります。
```

2022-11-17 02:50 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +テスト後には、被験者の行動を分析してプロダクトの改善ポイントを決める「トリアージ」を実施します。かならず開発チームと一緒に行ない、被験者がどのように行動したのかの共通認識をつくってください。
```suggestion
テスト後には、被験者の行動を分析してプロダクトの改善ポイントを決める「トリアージ」を実施します。かならず開発チームと一緒に実施し、被験者がどのように行動したのかの共通認識をつくってください。
```

2022-11-17 03:03 UTC, wentzzz reviewed
aguri-sanのコメントに返しました。

2022-11-17 03:18 UTC, oremega commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +被験者について調べておくことで、テスト前の事前質問やアイスブレイクに活用し、信頼関係（ラポール）※1の構築に役立てます。
なるほど！意識したことなかったので勉強になる

2022-11-17 03:47 UTC, oremega commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +被験者は慣れてないテストにとても緊張しています。テストが始まるまでの間に被験者と話して緊張を解していきましょう。
ふむふむ、直接な表現にしなくても状況だけで伝わりますね。すごい。

2022-11-17 09:03 UTC, oremega commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +アイスブレイクや事前質問などで、被験者の緊張を和らげる効果につながります。またテストに不備があっても、空気が悪くなるのを減らす効果もあります。
マイルドな表現よい。あざます！

2022-11-17 09:20 UTC, oremega commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +テスト中は被験者が自力でタスク完了できることを第一に考え、必要以上のサポートを行なわず、被験者の操作と発言を見守るようにしてください。
@aguringo サポートと誘導は明確に違う意味で使ってました。
サポートは、被験者の操作が止まっているときの声がけや、ちょっとした質問をテストの進行に影響を与えずに答えるなどのヘルプ作業。
誘導は、明確に被験者を特定の行動に従わせるになるので、ここの意味としては良くないかなと思います。

下記の見出しの誘導は、被験者がテストから逸脱したりして自ら現状を打開できないときにテスト進行をするは良いのよいことだと考えています。

なので、ここで「誘導」を使うなら`基本的には誘導せず`のほうが適切かもと思いました。

2022-11-17 09:47 UTC, oremega commented on content/articles/products/design-process/usability-test/index.mdx
> +- [ファシリテーターのやり方](/products/design-process/usability-test/role_facilitator/)
🦀 なので、「ファシリテーションの心得」、facilitationにします。

2022-11-17 09:51 UTC, oremega commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +被験者に過度に負荷をかけるのは検証したい目的を達成できなかったり、テスト自体に悪い印象を持つことがあるので、以下のような場合には、テストの結果に影響を与えないように配慮しながらサポートします。
ファイル名直すので一緒に取り込みました

2022-11-17 10:12 UTC, aguringo commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +テスト中は被験者が自力でタスク完了できることを第一に考え、必要以上のサポートを行なわず、被験者の操作と発言を見守るようにしてください。
意図理解しました。

基本的に誘導せず

に賛成です！

2022-11-18 01:48 UTC, oremega commented on content/articles/products/design-process/usability-test/role_facilitator.mdx
> +テスト中は被験者が自力でタスク完了できることを第一に考え、必要以上のサポートを行なわず、被験者の操作と発言を見守るようにしてください。
取り込み済

2022-11-18 02:03 UTC, wentzzz reviewed
タイトルが変わっていなさそうだったのでサジェストしました。

2022-11-18 02:03 UTC, wentzzz commented on content/articles/products/design-process/usability-test/facilitation.mdx
> +ファシリテーターの役割は、テスト設計に沿ってユーザビリティテストを進行し、被験者の心情に配慮しながら気持ちよくテストを受けてもらえるようにサポートすることです。
```suggestion
ユーザビリティテストをテスト設計に沿って円滑に進行し、被験者の心情に配慮しながら気持ちよくテストを受けてもらえるようにサポートするための、ファシリテーションの心得をまとめています。
```

2022-11-18 06:50 UTC, aguringo approved these changes
:lgmt2::gogo:

2022-11-18 06:52 UTC, merged