デザインレビューを最新に更新
kufu/smarthr-design-system pull request #374
Opened 2022-11-17 01:33 UTC by kgsi

## 課題・背景

## やったこと

- ツール名を差し替え
- 一部記述を修正

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2022-11-17 04:54 UTC, aguringo requested changes
@kgsi 
108行目に　Abstract の記述が残っているので、こちらも修正をお願いしたいです 🙏

2022-11-17 05:43 UTC, uknmr commented
`レビュー中のポイント` に「レビュー観点から逸れそうな意見も拾うために、書き留める場所を用意しておく」みたいな Tips を追加してもよさそう。

2022-11-18 01:32 UTC, kgsi commented
@uknmr @aguringo それぞれ訂正、追記してみましたー

2022-11-18 01:55 UTC, uknmr approved these changes
良き!!!!!!1

2022-11-18 06:57 UTC, aguringo approved these changes
:lgtm2::gogo:

2022-11-18 06:57 UTC, merged