コンテンツ配下の構成を見直し（リリースノートをヘルプセンター配下に）
kufu/smarthr-design-system pull request #386
Opened 2022-11-22 06:10 UTC by aguringo

## 課題・背景
ヘルプページの書き方を追加するタイミングで、構成と各ページのDescriptionを見直し。
- リリースノートはヘルプセンターに含まれるので、移動。
- DesignSystemに掲載されているコンテンツは基本的にすべてガイドラインなので、ディレクトリやファイル名からguideを削除して統一したかった。

また、#design_system相談に寄せられた
> ヘルプセンターの概要と操作手順のガイドラインが「各セクションの役割」と「各セクションの書き方」が離れているので、実際に使うときに上下して見る必要があり見づらい
https://kufuinc.slack.com/archives/CJX59GJFR/p1668574183671809
という声を受けて、内容を微調整しました。

## やったこと
- リリースノートの書き方をヘルプセンター配下へ移動
- Page Descriptionを全体的に調整
- ヘルプセンターのindexを修正
- URLから「guide」を削除して、リダイレクトを設定

- 「ヘルプページの構成」と「ヘルプページの書き方」の内容を調整
　- 「ヘルプページの書き方」に含まれていたスクショの話をヘルプページの構成の「画像」の見出し配下へ移動
　- 「ヘルプページの構成」に含まれていたライティングに関する内容を「ヘルプページの書き方」へ移動

- 「概要の書き方」「操作手順の書き方」のセクションの役割と書き方をマージ

-「手引」を「手引き」などに修正

## やらなかったこと
- 

## 動作確認

- Previewでみてね。

2022-11-22 06:21 UTC, tomof commented
@aguringo リダイレクトの処理、問題ないことを確認しました🙆‍♂️

2022-11-24 00:46 UTC, SmartMDK commented on content/articles/products/contents/help-center/step-by-step.mdx
> +1〜2文を目安として「XXについて説明します。」という形で記載します。「このページでは〜」という導入は不要です。
```suggestion
1〜2文を目安として「**XXについて説明します。**」という形で記載します。「このページでは〜」という導入は不要です。
```
「概要の書き方」と統一して、リード文の文例も太字で良いかと思いました。

2022-11-24 00:53 UTC, SmartMDK commented on content/articles/products/contents/help-center/basic-rule.mdx
> +### [スクリーンショットの使用ルール](../help-page/#h4-0)に従いましょう
見た目上、ここがリンクになっていることが伝わりづらいかもと思いました。
見出しの後に「詳しくはヘルプページの構成を参照してください。」などと一文挿入して、リンクであることを気づきやすくしても良いかもしれません。

2022-11-24 00:54 UTC, SmartMDK reviewed
@aguringo クリティカルではないのですが、気になった点を2点コメントしました！

2022-11-24 09:54 UTC, aguringo commented on content/articles/products/contents/help-center/basic-rule.mdx
> +### [スクリーンショットの使用ルール](../help-page/#h4-0)に従いましょう
> @aguringo クリティカルではないのですが、気になった点を2点コメントしました！

修正しました〜 :arigatau:

2022-11-25 00:09 UTC, SmartMDK approved these changes
@aguringo 反映ありがとうございます!! LGTMでした！Approveします:smile:

2022-11-25 10:23 UTC, 8chari commented on content/articles/products/contents/writing-principles.mdx
>  「わかりやすい」の定義については、[UXライティンググループミッション 〜プロダクトを、もっとわかりやすく〜](https://smarthr-inc.docbase.io/posts/2138204)を参照してください。
最新のミッションに差し替えると良さそうです🙏
```suggestion
「わかりやすい」の定義については、[UXライティンググループミッション](https://smarthr-inc.docbase.io/posts/2438010)を参照してください。
```

2022-11-25 10:25 UTC, 8chari commented on content/articles/products/design-process/review.mdx
> +- この手引きはレビュー依頼時の必要事項を網羅的まとめ、指針として共有するものです。
助詞が抜けていたので追加しました🙏
```suggestion
- この手引きはレビュー依頼時の必要事項を網羅的にまとめ、指針として共有するものです。
```

2022-11-25 10:28 UTC, 8chari requested changes
@aguringo おまたせしました！
1件だけ脱字があったので、suggestしました。大盛更新ありがとうございます:pray:

2022-11-25 10:30 UTC, 8chari submitted a review, later dismissed
:lgtm: 🎉

2022-11-25 10:38 UTC, merged