ジングルムービーページの追加
kufu/smarthr-design-system pull request #46
Opened 2022-05-02 05:03 UTC by omameoicy

## 課題・背景
https://github.com/kufu/smarthr-design-system-issues/issues/695

## やったこと

- ジングルムービーページを追加

## やらなかったこと
- 

## 動作確認
- Previewでの確認お願いします〜！

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2022-05-09 07:35 UTC, yuw27b commented
@omameoicy こちらプレビューのビルドに失敗していたので確認したところ、 `/content/articles/communication/photography/jingle-movie.mdx`内の、引用符の種類が原因のようでした。
（とても紛らわしいのですが、「`"`」のところが「`”`」になっていました。エディタなどが勝手に変換してしまうケースもあるので、そういうものかもしれません。）

Netlifyプレビューにて、ビルド結果に問題ないかどうか確認いただければと思います🙏
https://deploy-preview-46--smarthr-design-system.netlify.app/communication/photography/jingle-movie/

2022-05-10 01:55 UTC, samemaru commented on content/articles/communication/photography/jingle-movie.mdx
> +SmartHRジングルムービーを本ガイドラインおよび[利用規約](/terms/)に違反する態様での複製・転用・変更することを禁止します。
```suggestion
（ <a href="https://www.youtube.com/watch?v=EKpYFkLSIjY" target="_blank">SmartHR ジングルムービー | YouTube</a> ）  
イベントやライブストリーミングで利用できるジングルムービーです。  
SmartHRジングルムービーを本ガイドラインおよび[利用規約](/terms/)に違反する態様での複製・転用・変更することを禁止します。
```
モーションロゴページに合わせて改行します

2022-05-10 01:55 UTC, samemaru commented on content/articles/communication/photography/jingle-movie.mdx
> +- 社内Slack `#design_comm_依頼`
```suggestion
ジングルムービーの掲載、使用の可否についての相談・お問い合わせ
- 株式会社SmartHR　pr@smarthr.co.jp
- 社内Slack `#pr`

ジングルムービーの利用方法に関する相談・お問い合わせ
- 株式会社SmartHR　pr@smarthr.co.jp
- 社内Slack `#design_comm_依頼`
```
モーションロゴページに合わせて改行します

2022-05-10 01:56 UTC, samemaru requested changes
モーションロゴページに合わせて提案しています。
ご確認お願いします！

2022-05-10 15:40 UTC, omameoicy commented
zipデータを追加しました！
ご確認お願いします！🙏

2022-05-13 05:48 UTC, samemaru approved these changes
LGTMです！

2022-05-13 07:19 UTC, merged