ステータスのガイドラインを追加
kufu/smarthr-design-system pull request #513
Opened 2023-02-02 09:20 UTC by SmartMDK

## 課題・背景

https://smarthr.atlassian.net/browse/UXW-121

## やったこと

-

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2023-02-06 06:52 UTC, versionfive reviewed
具体的な内容はレビュー会として、表面的なところをSuggestionしました🙏

2023-02-06 06:52 UTC, versionfive commented on content/articles/products/design-patterns/status.mdx
> +**タスクの開始前**
```suggestion
##### タスクの開始前
```

2023-02-06 06:52 UTC, versionfive commented on content/articles/products/design-patterns/status.mdx
> +**タスクの開始後〜未完了**
```suggestion
##### タスクの開始後〜未完了
```

2023-02-06 06:52 UTC, versionfive commented on content/articles/products/design-patterns/status.mdx
> +**タスクの完了後**
```suggestion
##### タスクの完了後
```

2023-02-06 06:52 UTC, versionfive commented on content/articles/products/design-patterns/status.mdx
> +**イレギュラーケース**
```suggestion
##### 問題発生時
```
これでいいかわからないけど、日本語にしたみがあります。

2023-02-06 06:52 UTC, versionfive commented on content/articles/products/design-patterns/status.mdx
> +あわせて[StatusLabel](/products/components/status-label/)のガイドラインを参照してください。
```suggestion
### 3. コンポーネント

ステータスラベルの使い方について説明します。  
あわせて[StatusLabel](/products/components/status-label/)のガイドラインを参照してください。  
```
- これは「ラベル」というよりコンポーネントの使い方に読めました。（ラベルについては上の推奨例で表現してある）
  - このドキュメント全体がStatusLabelの使い方のパターンなんですかね…？
- あるいは、StatusLabelの視覚的なパターンについては、StatusLabelのところに書きたいなと思いました。
  - 「ステータス」のパターン（）と、それをどんなコンポーネントとして表現するかを分けたい、という意図です。

2023-02-06 06:58 UTC, SmartMDK commented on content/articles/products/design-patterns/status.mdx
> +**イレギュラーケース**
🦀

2023-02-08 02:36 UTC, uknmr commented
文字文字していて読み込むの厳しそうなので、各セクションに画像があると理解しやすい気がしました!

2023-02-09 08:51 UTC, SmartMDK commented
:memo:プロデザレビュー会でいただいたフィードバック
- 色の選定ルールは運用可能性が低いので、代表的なものの紹介だけしよう
   - エラーや警告など
- コンポーネントの説明はこのページに入れるのはトゥーマッチかも
   - ステータスの表現で使われるコンポーネントはStatusLablだけでないので
- 現状テキストのルールだけになっているので、ページタイトルが「ステータス」だとデカすぎるかも

2023-02-14 06:05 UTC, SmartMDK commented
@versionfive @aguringo @8chari @ibulog @INABAshina @kuny25 
お手すきで以下2ページのレビューをお願いいたします:pray:

- [ステータスラベルのガイドライン（文言のルール）](https://deploy-preview-513--smarthr-design-system.netlify.app/products/design-patterns/status-label/)
- [StatusLabelのコンポーネントの使い方（色、強調等）](https://deploy-preview-513--smarthr-design-system.netlify.app/products/components/status-label/)

補足：
[プロデザレビュー会のフィードバック](https://github.com/kufu/smarthr-design-system/pull/513#issuecomment-1423834909)を参照し、コンポーネントのルールは既存ページに統合しました。また、色に関する記載は警告色の使い方のみにとどめ、その他は適宜判断としています。

2023-02-15 01:32 UTC, versionfive reviewed
デザインパターンのほうをみました

2023-02-15 01:32 UTC, versionfive commented on content/articles/products/design-patterns/status-label.mdx
> +1. コンポーネント
これは「構成」といえるのかな。
ステータスラベルの中にコンポーネントが要素としてあるのもちょっと違和感があります。

ここは無理に「構成」に押し込めなくてもいいかも。「ライティングパターン」という項目もテンプレートにはあります。

2023-02-15 01:32 UTC, versionfive commented on content/articles/products/design-patterns/status-label.mdx
> +- バックグラウンド処理の実行後、処理が成功したのか失敗したのかをユーザーに伝えたい場合
「基本的な考え方」としてまとめたいです。

参考：[デザインパターンのテンプレート](https://smarthr.design/operational-guideline/page-template/design-patterns-template/)

2023-02-15 01:32 UTC, versionfive commented on content/articles/products/design-patterns/status-label.mdx
> +例外として、同じテーブル上に表示されるオブジェクトが複数のステータスを持っていて、明確に呼び分ける必要がある場合は`〇〇状況`と表記します。（例：依頼状況、確認状況、送信状況）
例が説明（OKの理由）の前にあるので、前後を入れ替えると読む順番として理解しやすい気がします。

2023-02-15 01:32 UTC, versionfive commented on content/articles/products/design-patterns/status-label.mdx
> +#### タスクの進行状況
nitsですが、冒頭に書いているステータスラベルを使うケースの順番に合わせて書くとよいかもです

2023-02-15 08:59 UTC, aguringo commented on content/articles/products/design-patterns/status-label.mdx
> +1. コンポーネント
ですね。

@SmartMDK 
デザインパターンのテンプレートに適応させる作業をモブで一緒にやりませんか？

2023-02-15 10:21 UTC, 8chari commented on content/articles/products/design-patterns/status-label.mdx
> +order: 12
議論済みだったら、ごめんなさい🙏
orderはココでいいのかが気になりました:eyes:
![image](https://user-images.githubusercontent.com/85212123/219000542-f58ec2df-9b00-4735-898e-1b6ecbb5d7a4.png)

2023-02-15 10:23 UTC, 8chari commented on content/articles/products/components/status-label.mdx
> +ユーザーがアクションをしないと次に進めないなど、ユーザーの注意を喚起したい場合は、背景色と文字色を反転させた「強調あり」のラベルを使います。
好みのレベルかもですが🙏
```suggestion
ユーザーがアクションをしないと次に進めないなど、ユーザーに注意喚起を促したい場合は、背景色と文字色を反転させた「強調あり」のラベルを使います。
```

2023-02-21 01:52 UTC, SmartMDK commented on content/articles/products/design-patterns/status-label.mdx
> +例外として、同じテーブル上に表示されるオブジェクトが複数のステータスを持っていて、明確に呼び分ける必要がある場合は`〇〇状況`と表記します。（例：依頼状況、確認状況、送信状況）
反映しました:pray:

2023-02-21 01:55 UTC, SmartMDK commented on content/articles/products/design-patterns/status-label.mdx
> +#### タスクの進行状況
順番を入れ替えました

2023-02-28 06:36 UTC, SmartMDK commented
@aguringo 先日はモブでのサポートありがとうございました！
以下の方針で修正したので、ご確認をお願いいたします:pray:
- 「[よくあるテーブル](https://deploy-preview-513--smarthr-design-system.netlify.app/products/design-patterns/smarthr-table/)」＞「オブジェクトの情報」のセクションに、ステータスの用途を追記
- 「[StatusLabel](https://deploy-preview-513--smarthr-design-system.netlify.app/products/components/status-label/)」に色、強調、ライティングのルールを追記

2023-02-28 07:16 UTC, aguringo commented
@SmartMDK :lgtm:

@versionfive 先生にも一応もう一回見てもらおう！

2023-02-28 07:16 UTC, aguringo approved these changes
わかりやすく、使いやすい場所に情報を配置できたと思います！

2023-02-28 07:59 UTC, versionfive reviewed
構成はすごく見通しがよくなっていました！ありがとうございます。
何点かコメントしました〜

2023-02-28 07:59 UTC, versionfive commented on content/articles/products/components/status-label.mdx
> +### ラベル名のライティング
StatusLabelにおけるライティングはそのままラベル名になると思うので、このH3は不要で繰り上げてもいいかも、と思いました。

2023-02-28 07:59 UTC, versionfive commented on content/articles/products/components/status-label.mdx
> +ユーザーがアクションをしないと次に進めないなど、ユーザーに注意喚起を促したい場合は、背景色と文字色を反転させた「強調あり」のラベルを使います。
「注意喚起」と言ってしまうと、意味的には`type=warning | error`が該当すると思っています。（重要度や緊急度の高さを示し、HTMLでいうと、`strong`要素的な意味）

`bold=true`は、あくまで「視覚的なアテンションを高める目的だけ」だと理解しているのですがいかがでしょう？（HTMLでいうと、`b`要素や`em`要素的な意味）

@uknmr にも聴いてみたい。

2023-02-28 07:59 UTC, versionfive commented on content/articles/products/components/status-label.mdx
> +その他のステータスを表す場合は、プロダクトの状況に応じて適宜色を選択します。
（アクセシビリティ文脈で色は視覚情報のみなので、）色だけで区別せさず、ラベル名を適切につけよう、みたいなリード文がほしいです。

```suggestion
その他のステータスを表す場合は、プロダクトに応じて適宜色を選択します。ただし、色のみでステータスを伝えようとすることは避け（参考：[カラーユニバーサルデザイン](https://smarthr.design/accessibility/#h3-2)）、ステータスを示す適切な[ラベル名](#ライティング)と組み合わせて使用しましょう。
```

2023-02-28 07:59 UTC, versionfive commented on content/articles/products/design-patterns/smarthr-table.mdx
> +ステータスラベルのコンポーネントの使い方は、[StatusLabel](/products/components/status-label/)のガイドラインを参照してください。
```suggestion
ステータスラベルの使い方は、[StatusLabel](/products/components/status-label/)を参照してください。  
```

2023-02-28 09:06 UTC, SmartMDK commented on content/articles/products/components/status-label.mdx
> +### ラベル名のライティング
繰り上げました:pray:

2023-03-01 02:20 UTC, SmartMDK commented on content/articles/products/components/status-label.mdx
> +ユーザーがアクションをしないと次に進めないなど、ユーザーに注意喚起を促したい場合は、背景色と文字色を反転させた「強調あり」のラベルを使います。
@versionfive ありがとうございます！いったん以下のように修正してみました。
>ユーザーがアクションをしないと次に進めないなどの理由で、視覚的に目立たせたい場合は、背景色と文字色を反転させた「強調あり」のラベルを使います。

2023-03-01 02:58 UTC, uknmr commented on content/articles/products/components/status-label.mdx
> +
種類の下に「色」の見出しが適切でないように思えました。直で本文が来ても問題ないので取ってもよさそう。
```suggestion
```

2023-03-01 02:58 UTC, uknmr commented on content/articles/products/components/status-label.mdx
> +### 強調の有無
視覚的なプレビュー入れたいですね!
「＜ここにプレビュー入れる＞」みたいな一文入れておいてもらえたらあとで差し込みますよ!

2023-03-01 02:58 UTC, uknmr commented on content/articles/products/components/status-label.mdx
> +ユーザーがアクションをしないと次に進めないなど、ユーザーに注意喚起を促したい場合は、背景色と文字色を反転させた「強調あり」のラベルを使います。
同じ理解です!

2023-03-01 03:10 UTC, uknmr requested changes
文字文字していて読むつらさがあるので、各所にプレビューを入れたいと思いました!
見出しとプレビューで注意を惹きつけて本文を読ませたい。

SmartMDK さんの方で対応が難しそうであれば、「＜ここにプレビュー入れたい＞」みたいな一文を差し込んどてい貰えると対応しやすいです!

また、（個人的な気持ちですが）あくまでガイドラインなので、ルールを書くというよりは読んで理解したら次からは読みに来なくても自分で判断できるようにしていけるようなドキュメントになってると嬉しいです。
「なぜ」が全体的に薄く感じました。

2023-03-01 03:10 UTC, uknmr commented on content/articles/products/design-patterns/smarthr-table.mdx
> +<!-- textlint-disable -->
何で検知されたものかわからないですが、辞書の修正で済むのであれば textlint-rule-preset-smarthr に連絡するのが良いと思います!（もうやってたらごめんなさい）

2023-03-01 03:10 UTC, uknmr commented on content/articles/products/components/status-label.mdx
> +#### 推奨例
ok / ng のような非推奨例ってあったりしますか?
なぜ推奨されてるのかが全くわからないな、と思いました。

2023-03-01 04:23 UTC, SmartMDK commented on content/articles/products/components/status-label.mdx
> +### 強調の有無
どうもありがとうございます！お言葉に甘えてプレビュー入れたい部分にコメントしておきます:pray:

2023-03-01 04:27 UTC, SmartMDK commented on content/articles/products/components/status-label.mdx
> +#### 推奨例
確かにそうですね。OK例の一部という位置付けだったので、端的に「例」としておきます。

2023-03-01 04:31 UTC, SmartMDK commented on content/articles/products/design-patterns/smarthr-table.mdx
> +<!-- textlint-disable -->
「フィルタリング（×フィルタ ○フィルター）」が誤検知されていたので、別途ルールを修正します:pray:

2023-03-01 04:35 UTC, uknmr commented on content/articles/products/design-patterns/smarthr-table.mdx
> +<!-- textlint-disable -->
今 textlint って通ってないとマージできないんでしたっけ。
disabled をあとで外しにくくなるので、警告でたままマージしてしまうか、preset-smarthr 側の修正を待つかするといいかもと思いました!

2023-03-01 07:19 UTC, SmartMDK commented on content/articles/products/design-patterns/smarthr-table.mdx
> +<!-- textlint-disable -->
失礼しました すでにtextlintでルール化されていたものが、私のyarnの問題で反映されていなかっただけでした:pray:
textlint-disableは削除済みです！

2023-03-01 23:29 UTC, SmartMDK commented
@uknmr 丁寧に見てくださってありがとうございます！
-  確かにルールのような書き方になっていたので、背景となる考え方を補足しました（何を伝えれば良いのか、なぜXXしてはいけないのか）
- 「＜ここにプレビュー入れたい＞」のコメントを入れました
- textlintの件は解決済みです

お手数ですが、再度ご確認いただければ助かります。よろしくお願いします:pray:

2023-03-02 00:21 UTC, uknmr approved these changes
よさそう〜
コメント入れましたが無視でも問題ないやつです!

2023-03-02 00:21 UTC, uknmr commented on content/articles/products/components/status-label.mdx
> +このため、色のみでステータスを伝えることは避けましょう。（参考：[カラーユニバーサルデザイン](/accessibility/#h3-2)）
imo： 接続詞少ないほうが読みやすかったかも
（好みかもなので無視して問題ないです!）

2023-03-02 00:34 UTC, SmartMDK commented on content/articles/products/components/status-label.mdx
> +このため、色のみでステータスを伝えることは避けましょう。（参考：[カラーユニバーサルデザイン](/accessibility/#h3-2)）
早速ありがとうございます！修正してマージします:smile:

2023-03-02 02:08 UTC, aguringo approved these changes

2023-03-02 02:09 UTC, merged