端末モックに禁止事項を追加・階層を変更
kufu/smarthr-design-system pull request #695
Opened 2023-05-25 08:32 UTC by omameoicy

## 課題・背景
今書いている途中です〜

## やったこと

-

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2023-05-26 09:24 UTC, samemaru requested changes
ご確認ください！

2023-05-26 09:24 UTC, samemaru commented on content/articles/communication/images/mock/edit-mock_ng_transform.png
画面は変形させず、適当にトリミングする形にできますか？
あくまでモックの利用方法だけだめ、という見え方にしたいです

2023-05-26 09:24 UTC, samemaru commented on content/articles/communication/capture/kit.mdx
> +| キャプチャ中央部省略用 | ![省略線-center-image](./images/kit/break-axis_center_image.png)|![省略線-center-example](./images/kit/center_example_image.png)　| <a href="/downloads/personal-computer-size_center.png" dow
PCの方、ファイル名が違いそうです、ご確認ください！（ほかの2つも）

2023-05-29 02:12 UTC, omameoicy commented on content/articles/communication/capture/kit.mdx
> +| キャプチャ中央部省略用 | ![省略線-center-image](./images/kit/break-axis_center_image.png)|![省略線-center-example](./images/kit/center_example_image.png)　| <a href="/downloads/personal-computer-size_center.png" dow
ありがとうございます〜！こちら修正しました🙏

2023-05-29 06:01 UTC, samemaru approved these changes
LGTM〜

2023-05-29 06:01 UTC, samemaru approved these changes
LGTM〜

2023-05-29 10:55 UTC, merged