スクリーンショットの使用ガイドラインに、スクリーンショットを使う基準について追記
kufu/smarthr-design-system pull request #707
Opened 2023-05-31 04:46 UTC by keroyama-nao

## 課題・背景

スクリーンショットはできるだけ使わない、というガイドラインになっていたが、使う／使わないの基準が明確でなかったため追記しました。

UXW内での確認スレッド
https://kufuinc.slack.com/archives/C01L7GK9APK/p1684906045993129

## やったこと

- 「アクセシビリティの観点から、スクリーンショットはできるだけ使わず、テキストで説明する」配下の内容を追記
- 「画像を使うときのガイドライン」を作成したときにリンク先が変わってしまったページがあったので修正

## 動作確認

- 内容は確認済みなのでファイルでざっと確認いただければ！

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2023-05-31 04:56 UTC, keroyama-nao commented on content/articles/products/contents/help-center/basic-rule.mdx
> -### [スクリーンショットの使用ルール](../help-page/#h4-0)に従いましょう
見出しにリンクが仕込んでありましたが、見た目はリンクにならない＆同じリンクが本文中にあるので消しました。

2023-05-31 05:26 UTC, samemaru commented
コミュニケーション領域では「画面キャプチャ」と総称していましたが、名称は統一が必要でしょうかね？
https://smarthr.design/communication/capture/

厳密にいうと、
・スクリーンショットは撮って出しそのまま
・画面キャプチャはユースケース等を考慮して諸々の調整をしている
という差分はある気がしています！

2023-05-31 05:45 UTC, aguringo requested changes
@keroyama-nao 
Previewでコンテンツ全体との関係を見て結果、ページと見出しタイトルを変更したいと思います。

2023-05-31 05:45 UTC, aguringo commented on content/articles/products/contents/help-center/image.mdx
>  ## スクリーンショットの使用ガイドライン
```suggestion
## スクリーンショット掲載についての考え方
```

2023-05-31 05:45 UTC, aguringo commented on content/articles/products/contents/help-center/basic-rule.mdx
> +### スクリーンショットの使用ガイドラインに従いましょう
```suggestion
### スクリーンショット掲載についての考え方に従いましょう
```

2023-05-31 05:45 UTC, aguringo commented on content/articles/products/contents/help-center/basic-rule.mdx
> +詳細は「画像を使うときのガイドライン」の[スクリーンショットの使用ガイドライン](../image/#h2-0)を確認してください。
```suggestion
詳細は「ヘルプページ用の画像」の[スクリーンショット掲載についての考え方](../image/#h2-0)を確認してください。
```

2023-05-31 05:45 UTC, aguringo commented on content/articles/products/contents/help-center/basic-rule.mdx
> +詳細は「画像を使うときのガイドライン」の[スクリーンショットの使用ガイドライン](../image/#h2-0)を確認してください。
@keroyama-nao 
［MUST］
ガイドラインなのは、自明なので省略したいです。
ページとして見ると非常に冗長です。

ページタイトル、サジェストできないんで、Formatter直していただけると :pray:

2023-05-31 05:45 UTC, aguringo commented on content/articles/products/contents/help-center/image.mdx
> +アクセシビリティの観点、および情報量が増えて可読性が下がることを防ぐ観点から、スクリーンショットの使用は最小限にします。ユーザーがプロダクトの画面を表示したうえで、ヘルプページを閲覧している想定で、まずはテキストのみで説明できないか検討してください。
```suggestion
アクセシビリティの観点、および情報量が増えて可読性が下がることを防ぐ観点から、スクリーンショットの使用は最小限にします。ユーザーがプロダクトの画面を表示したうえでヘルプページを閲覧している想定で、まずはテキストのみで説明できないか検討してください。
```

2023-05-31 05:45 UTC, aguringo commented on content/articles/products/contents/help-center/image.mdx
> +#### 従業員向けのヘルプの場合
```suggestion
#### 従業員向けのヘルプページの場合
```

2023-05-31 05:45 UTC, aguringo commented on content/articles/products/contents/help-center/image.mdx
> +#### 従業員向けのヘルプの場合
［IMO］
きちんとヘルプページって書きたい

2023-05-31 05:45 UTC, aguringo commented on content/articles/products/contents/help-center/image.mdx
> +アクセシビリティの観点、および情報量が増えて可読性が下がることを防ぐ観点から、スクリーンショットの使用は最小限にします。ユーザーがプロダクトの画面を表示したうえで、ヘルプページを閲覧している想定で、まずはテキストのみで説明できないか検討してください。
［IMO］
意味のかたまりをわかりやすくするために読点を取りたいです。

2023-05-31 06:03 UTC, aguringo commented
> コミュニケーション領域では「画面キャプチャ」と総称していましたが、名称は統一が必要でしょうかね？ https://smarthr.design/communication/capture/
> 
> 厳密にいうと、 ・スクリーンショットは撮って出しそのまま ・画面キャプチャはユースケース等を考慮して諸々の調整をしている という差分はある気がしています！

コミュニケーション素材で提供しているものは、画面キャプチャでいいと思います。
商品画像みたいなものなので。

2023-05-31 06:11 UTC, samemaru commented
別物として扱うので統一は不要、ということで承知しました！

2023-06-01 02:16 UTC, aguringo approved these changes
:arigatau::gogo:

2023-06-01 06:16 UTC, merged