Feature:コンテンツにUIテキストを追加
kufu/smarthr-design-system pull request #72
Opened 2022-05-20 07:01 UTC by aguringo

## 課題・背景
Airtableの「基本的な考え方」のシートにアプリケーション上のライティングのみに限定されるルールなど粒度の異なるものが入っていたので、仕分けをしました。

切り分けたデータを掲載する、UIテキストというページを新規作成しました。

## やったこと
- Airtableのクエリを追加
- App-Writingページを追加
- Indexや影響のあるページを微調整

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2022-05-20 07:50 UTC, uknmr requested changes
細かい指摘のみです!!

2022-05-20 07:50 UTC, uknmr commented on src/components/contents/AppWriting/AppWriting.tsx
> +        })
imo: この `filter()` は38行目の `reverse()` に続けて書けばよさそう。
reverse の戻り値もまた配列なのでメソッドチェーンで書けます。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse

意味的には `.filter().reverse()` かしら。

2022-05-20 07:50 UTC, uknmr commented on src/components/contents/AppWriting/AppWriting.tsx
> +          }
recordId がない場合に、どの id にも空文字が入るのは問題がありそうな気がします。
recordId が false になる可能性がありますか?

```suggestion
          const fragmentId = (suffixId: string) => {
            return recordId ? `${recordId}-${suffixId}` : undefined
          }
```

あるいは

```ts
if (!recordId) {
  return
}

return `${recordId}-${suffixId}`
```

でもいいかも。

2022-05-20 08:10 UTC, aguringo commented
> 細かい指摘のみです!!

:arigatau: この辺、`src/components/contents/BasicConceptTable/BasicConceptTable.tsx` のコピペなのですよ。
なので、直すならまとめて修正を入れた方が良いかな？と思いました。

2022-05-20 08:47 UTC, aguringo commented
@uknmr 

回答漏れていましたが、

> recordId が false になる可能性がありますか?

ありません！

AppWritingだけで良いですか？　それともBasicConceptTableも？

2022-05-23 02:15 UTC, tomof commented
@aguringo 右ナビゲーションに何も表示されないのが気になりました。

![image](https://user-images.githubusercontent.com/1369376/169730529-8415a5d2-ab6d-4aab-bbfe-aab25c1092a7.png)

例えば、用字用語と同じような構成で作られていれば、右ナビゲーションが自動的に作られると思うのですが、構成が異なっていたりしますか？↓でナビゲーション用のデータを作っているはずなのですが。

https://github.com/kufu/smarthr-design-system/blob/5826b2c15162525d66f7a461565b4d02ef592244/src/templates/article.tsx#L211-L218

@uknmr @aguringo 

> AppWritingだけで良いですか？　それともBasicConceptTableも？

こちら、`IdiomaticUsageTable`なども対象のようですし他にもあるかもしれないので、こちらでissue化して引き取りますがどうでしょう？

2022-05-23 02:49 UTC, aguringo commented
@tomof 

最初、右の実装のことをきちんと把握せずにAirtable側の名前を変えちゃってたのですが、https://github.com/kufu/smarthr-design-system-issues/issues/933 を立てる時に気づいて、追加コミットでテーブル名を揃えたんですけど、うまくいってまっせんね…
→　[FragmentTitleを流用しやすいようテーブル名を既存に揃えた](https://github.com/kufu/smarthr-design-system/pull/72/commits/0238d90f9584e3f51d59c1aca03c663bb98bf680)

どうしたら良いんだろう…　何がダメなんだ…？

そして、

> IdiomaticUsageTableなども対象のようですし他にもあるかもしれないので、こちらでissue化して引き取ります

ぜひお願いしたいです 🙏 

実は、今回、BasicBasicConceptTableと新規追加したAppWritingに、このPRでは使用していないorderってテーブル名を追加しています。
これは、あとでIssue化しようと思っていた、並び順をairtable側でコントロールできるようにするためのものです。
本件も合わせて、Issueにてコミュニケーションさせてください。

2022-05-23 02:58 UTC, 8chari requested changes
表現まわりで気になった下記、Airtableを更新しています。確認お願いします🙏

**全体**

- OK例の前に「・」があったが、ない方が見ばえが良さそうと判断して削除（NGに「・」を付け忘れているように見える）

- `OK例：`と`OK：`が混在していたので、`OK：` に統一


**アクションに関する画面やダイアログのタイトルでは、助詞は「の」を使用する**

-  削除ダイアログへのリンク追加（`[削除ダイアログ](https://smarthr.design/products/design-patterns/delete-dialog/)`）


**ヘッダーの行も含めてエラーの発生した行数を表示する。**

- 末尾の「。」を削除
- 改行を追加
- 説明を「です・ます」調に変更


**作成を表す言葉（登録・追加・作成の考え方）**

- 説明に「。」を追加
- 出典の「-」を削除


**「デフォルト」と「プリセット」の使い分け**

- 説明の冒頭に「用途に合わせて使い分けましょう。」を追加

2022-05-23 03:20 UTC, uknmr commented
> AppWritingだけで良いですか？　それともBasicConceptTableも？

はっ! 両方やってしまうとよさそうです! @aguringo

2022-05-23 03:25 UTC, tomof commented
@aguringo 

> どうしたら良いんだろう…　何がダメなんだ…？

https://github.com/kufu/smarthr-design-system/blob/8ba2b7729594e9bc1441694fee572b17f10a8d18/src/constants/airtable.ts#L10-L29

/src/constants/airtable.ts の更新が必要でした。
これ何箇所も同じような定義が必要なのは、以前Netlifyのデプロイが原因不明で落ちてしまうため、古いバージョンに戻さなければいけないための影響です。#934で改善される予定ですので、ここでは面倒ですが両方に同じような定義の記述をお願いします🙏

2022-05-23 03:28 UTC, tomof commented
@aguringo ↓の件、承知しました！
@uknmr こちらで引き取ろうと思いますが、構わないでしょうか？

>>IdiomaticUsageTableなども対象のようですし他にもあるかもしれないので、こちらでissue化して引き取ります

> ぜひお願いしたいです 🙏

> 実は、今回、BasicBasicConceptTableと新規追加したAppWritingに、このPRでは使用していないorderってテーブル名を追加しています。
> これは、あとでIssue化しようと思っていた、並び順をairtable側でコントロールできるようにするためのものです。
本件も合わせて、Issueにてコミュニケーションさせてください。

2022-05-23 09:03 UTC, aguringo commented
@tomof 

> /src/constants/airtable.ts の更新

コミットできないエラー回避で、直近のコミットメッセージが空なのですが、こちら対応しています。
確認お願いします 🙏

2022-05-23 09:17 UTC, aguringo commented
> > 実は、今回、BasicBasicConceptTableと新規追加したAppWritingに、このPRでは使用していないorderってテーブル名を追加しています。
> > これは、あとでIssue化しようと思っていた、並び順をairtable側でコントロールできるようにするためのものです。
> > 本件も合わせて、Issueにてコミュニケーションさせてください。

こちらに書きました〜

https://github.com/kufu/smarthr-design-system-issues/issues/933#issue-1242737125

2022-05-23 09:46 UTC, 8chari approved these changes
:lgtm:

2022-05-23 10:02 UTC, merged