[WIP]従業員サーベイ サーベイ回答の検証結果ページを追加
kufu/smarthr-design-system pull request #755
Opened 2023-06-21 10:40 UTC by k-shirahama

## 課題・背景

## やったこと

-

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
|  |  |

2023-06-21 10:41 UTC, k-shirahama commented on content/articles/accessibility/status/survey/202306.mdx
> +該当する達成基準のうち、レベルA: 20個中19個、レベルAA: 3個中3個で、その基準を満たしていました。
📝 NG1件修正するので、リリースしたら更新する

2023-06-23 05:31 UTC, k-shirahama reviewed
内容が適切かレビューお願いしたいです！

2023-06-23 05:31 UTC, k-shirahama commented on content/articles/accessibility/status/index.mdx
> +        問題の改善と他のプロセスの検証を実施</td>
[Q]
meyasuは下期開発停止期間になるので、下期は具体的な改善予定がない（ユーザーからの要望があってかなりクリティカルな場合対応する可能性はあると思いますが、基本的にはなにもしないと思う）のですが、ここの記載どういう表現が良いでしょうか。

2023-06-23 05:32 UTC, k-shirahama commented on content/articles/accessibility/status/survey/202306.mdx
> +該当する達成基準のうち、レベルA: 20個中20個、レベルAA: 3個中3個で、その基準を満たしていました。
NG箇所が1件ありましたが、修正してリリースしたため更新しました！

2023-06-28 22:10 UTC, uknmr commented on content/articles/accessibility/status/survey/202306.mdx
> +
使ってなさそう!

```suggestion

import { DefinitionList } from 'smarthr-ui'
```

2023-06-29 00:13 UTC, maiha2 commented
@k-shirahama 私が渡した作業元のファイルに残ってたので申し訳ないんですが
`<!-- textlint-enable -->` と `<!-- textlint-disable -->` を一旦全部消しちゃいましょう。

この2つは、達成基準などの改変したくないテキストに対してlintがerrorを出すときに使うみたいです。
なので、一旦消した上で、lintにひっかかるところがあったら適宜　
`<!-- textlint-enable -->` と `<!-- textlint-disable -->` を使う感じにしてみてください〜。

2023-06-29 07:12 UTC, maiha2 requested changes

2023-06-29 07:12 UTC, maiha2 commented on content/articles/accessibility/status/survey/202306.mdx
> +<a href="https://docs.google.com/spreadsheets/d/1jfq99h68aT3iwuCSRwo9eJdgssb42pLnhoG3xIaF9v8/edit?usp=sharing">2023年6月 SmartHR 従業員サーベイ 達成基準チェックリスト</a>
@k-shirahama 
スプシの格納フォルダの設定でリンク共有できなかったので 😭 公開可能なフォルダにファイルを置き直しています。
スプシのURLを更新お願いします〜。
https://docs.google.com/spreadsheets/d/1qecIHsAdOHKbqhybs1sih3vjooc6fvk0FQA7hqWPg68/edit?usp=sharing

ファイルを移動できればURL変更必要なかったんですが権限の都合でファイル移動できなかった…

2023-06-29 07:31 UTC, k-shirahama commented on content/articles/accessibility/status/survey/202306.mdx
> +
修正しました 🙏 
https://github.com/kufu/smarthr-design-system/pull/755/commits/2ced596d37cbde13ca1617018f80c312defb10ed

2023-06-29 07:32 UTC, k-shirahama commented on content/articles/accessibility/status/survey/202306.mdx
> +<a href="https://docs.google.com/spreadsheets/d/1jfq99h68aT3iwuCSRwo9eJdgssb42pLnhoG3xIaF9v8/edit?usp=sharing">2023年6月 SmartHR 従業員サーベイ 達成基準チェックリスト</a>
@maiha2 
コメント頂いた点、修正しました〜！
https://github.com/kufu/smarthr-design-system/pull/755/commits/baf600ad25025301ebeb24ab7c7838e8bc4b47a7
https://github.com/kufu/smarthr-design-system/pull/755/commits/32d061dea5a24c651bb7ae730a20e02255b88013

2023-06-29 07:41 UTC, maiha2 approved these changes

2023-06-29 07:41 UTC, maiha2 commented
@k-shirahama ありがとうございます！おマージします！

2023-06-29 07:42 UTC, k-shirahama commented
マージしますっ！

2023-06-29 07:42 UTC, merged