左ナビゲーションに子ページの開閉機能を追加
kufu/smarthr-design-system pull request #86
Opened 2022-05-27 02:47 UTC by yuw27b

## 課題・背景
https://github.com/kufu/smarthr-design-system-issues/issues/898

## やったこと
コンテンツページ左カラムのナビゲーションメニューを更新しました。
- 表示中以外のページの子・孫ページのデータも取得しておき、ナビゲーションに追加しました。
- 子ページが存在する場合は、右端にキャレットを表示します。
- クリックすると、子ページのリストが開閉します。

実装としては、`aria-controls` `aria-expanded` `aria-hidden` 属性をJSで切り替え、さらにCSSで表示の制御をしています。

## 動作確認

## キャプチャ

|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/170618584-d9be6f00-d139-46cf-803d-7cf83abd05db.png" width="350" alt=""> | <img src="https://user-images.githubusercontent.com/7822534/170618645-0d453878-4e63-43b1-ad5d-ea1024ca5bb1.png" width="350" alt=""> |

2022-05-27 04:26 UTC, tomof requested changes
@yuw27b ありがとうございます！確認しましたが、概ね想定どおりに動いていてコードも問題無さそうです🙏 ちょっとした指摘だけコメントしたので確認をお願いしますー！

2022-05-27 04:26 UTC, tomof commented on src/components/article/Sidebar/Sidebar.tsx
> +  const onClickCaret = (e: React.MouseEvent<HTMLButtonElement>): void => {
`e`よりも`event`の名前使っている箇所が多いので`event`のほうが良いかも。

2022-05-27 04:26 UTC, tomof commented on src/components/article/Sidebar/Sidebar.tsx
> +  transform: translateY(-50%);
キャレットが項目の高さの中心に配置されていないように見えるので調整可能ですかね？
キャレットのアイコンが14pxなので、`transform: translateY(-7px);` を指定すると中心に配置されるように思います。

2022-05-27 04:28 UTC, tomof requested changes
@yuw27b ありがとうございます！確認しましたが、概ね想定どおりに動いていてコードも問題無さそうです🙏 ちょっとした指摘だけコメントしたので確認をお願いしますー！

2022-05-27 04:38 UTC, yuw27b commented
@tomof ありがとうございますー！他のフィードバックと合わせて諸々調整します。

2022-05-27 06:23 UTC, yuw27b commented
- ボタンの範囲を縦いっぱい・横32pxにしました
- `e`→`event`に
- ホバー時・フォーカス時にボタンに背景色（薄いグレー）を設定しました
- アイコンにラベルを追加しました
  - ボタン（アイコンの親要素）フォーカス時に、ラベル用の`span`にもフォーカスリングがつくのですが、`width: 1px; height: 1px; top: -1px;`のスタイルが適用されていてリングが左上に 1pxはみ出して見えるので、`top: 0;`で上書きしています。

2022-05-27 06:59 UTC, tomof approved these changes
@yuw27b ありがとうございます！LGTM👍

2022-05-30 04:24 UTC, uknmr approved these changes
LGTM!

2022-05-30 05:32 UTC, tomof approved these changes
LGTM〜

2022-05-30 05:33 UTC, merged