(WIP)ユーザビリティテストの手引と被験者になったらを載せる
kufu/smarthr-design-system pull request #98
Opened 2022-06-02 02:53 UTC by oremega

## 課題・背景
デザインシステムにユーザビリティテストのドキュメントを載せる活動の一環です。

## やったこと

手始めに、デザインシステムに領域を作るために以下を追加
- ユーザビリティテストの手引き
- 被験者になったらを

## やらなかったこと
- ユーザビリティテストの他ドキュメントは別でブランチにする

## 動作確認
- Previewでみてね。

## キャプチャ
- なし

2022-06-02 07:00 UTC, aguringo commented
@oremega 
見出しに使っている言葉を揃えたい「概要」とか「はじめに」とか。（他のページも含めて）

今日のMTG類が終わったら、方針決めるので、そしたらサジェスト加えます！

2022-06-02 08:41 UTC, versionfive reviewed
コメントしておりますー

2022-06-02 08:41 UTC, versionfive commented on content/articles/products/design-process/user-resaerch/index.mdx
> +## ユーザーリサーチ推進室について
問い合わせ先として記載してもよいかもと思いました！
https://smarthr.design/accessibility/policy/#h2-5

2022-06-02 08:41 UTC, versionfive commented on content/articles/products/design-process/user-resaerch/usability-test.mdx
> +4. [事前の予習は必要ありません](#h3-3)
h3のインデックスは右カラムで担保できているので、必然性がなければなくてもよいかもです

2022-06-02 08:41 UTC, versionfive commented on content/articles/products/design-process/user-resaerch/usability-test.mdx
> +<iframe width="100%" height="350" src="https://www.youtube.com/embed/xWePbJLHhHA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosc
```suggestion
#### ユーザビリティテストの思考発話をしている様子
<iframe width="100%" height="350" src="https://www.youtube.com/embed/xWePbJLHhHA" title="ユーザビリティテストの思考発話をしている様子" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```
iframeのtitleで担保できているなら見出しはなくてもいいかもです。

2022-06-02 08:41 UTC, versionfive commented on content/articles/products/design-process/user-resaerch/usability-test.mdx
> +マイクが周囲の音を拾わない静かな場所
```suggestion
例：会議室をとっていただく、自宅、などマイクが周囲の音を拾わない静かな場所
```

2022-06-02 08:41 UTC, versionfive commented on content/articles/products/design-process/index.mdx
> +[WIP] ユーザビリティテストを実施するうえで利用する資料をまとめています。
```suggestion
## [ユーザーリサーチの手引](/products/design-process/user-research)
[WIP] ユーザーリサーチを実施するうえで利用する資料をまとめています。
```

2022-06-02 08:41 UTC, versionfive commented on content/articles/products/design-process/user-resaerch/index.mdx
> +description: 'description'
書いたほうがよさそうです！

2022-06-02 08:41 UTC, versionfive commented on content/articles/products/design-process/user-resaerch/usability-test.mdx
> +description: 'レビュー依頼時の必要事項を網羅的にまとめ、指針として共有するものです。'
ほかのページの概要のママになってそうです。

2022-06-02 09:13 UTC, oremega commented on content/articles/products/design-process/user-resaerch/usability-test.mdx
> +4. [事前の予習は必要ありません](#h3-3)
カニすぎ。直そう

2022-06-02 09:14 UTC, oremega commented on content/articles/products/design-process/user-resaerch/index.mdx
> +## ユーザーリサーチ推進室について
特に強いお気持ちないのでGoGoかな。
メールアドレスもらわないと

2022-06-03 05:15 UTC, oremega commented on content/articles/products/design-process/user-resaerch/index.mdx
> +## ユーザーリサーチ推進室について
slackで意図を確認。変更していきます

2022-06-03 05:23 UTC, oremega commented on content/articles/products/design-process/user-resaerch/usability-test.mdx
> +<iframe width="100%" height="350" src="https://www.youtube.com/embed/xWePbJLHhHA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosc
んー、つけようかとも思ったけど、まー、文章流れ的にもわかるしtitle入るからアクセシビリティ的にも担保されるか。

2022-06-03 05:23 UTC, oremega commented on content/articles/products/design-process/user-resaerch/usability-test.mdx
> +マイクが周囲の音を拾わない静かな場所
修正します

2022-06-03 05:23 UTC, oremega commented on content/articles/products/design-process/index.mdx
> +[WIP] ユーザビリティテストを実施するうえで利用する資料をまとめています。
これもなお明日

2022-06-03 05:24 UTC, oremega commented on content/articles/products/design-process/user-resaerch/index.mdx
> +description: 'description'
直します

2022-06-03 05:24 UTC, oremega commented on content/articles/products/design-process/user-resaerch/usability-test.mdx
> +description: 'レビュー依頼時の必要事項を網羅的にまとめ、指針として共有するものです。'
直します

2022-06-06 02:36 UTC, aguringo reviewed
コメントしました！

2022-06-06 02:36 UTC, aguringo commented on content/articles/products/design-process/index.mdx
> +## [ユーザーリサーチの手引](/products/design-process/user-research)
```suggestion
## [ユーザビリティテスト](/products/design-process/user-research)
```
Indexにユーザーリサーチに関する方針みたいなのが書ければ、コンテンツが未作成でも（いずれ変更するよりも）この見出しのままで良いんですが、そこが書けないなら直しちゃってもいいかなぁ…

個人的な解釈としては、
- ユーザーリサーチの手引き
　- hogeインタビュー
　- fugaインタビュー
　- ユーザビリティテスト
　- piyo
ってネストされるんだと思っているので、一旦ユーザビリティテストが親でも良いのかも。

2022-06-06 02:36 UTC, aguringo commented on content/articles/products/design-process/user-resaerch/index.mdx
> +title: 'ユーザーリサーチの手引'
```suggestion
title: 'ユーザビリティテスト'
```

2022-06-06 02:46 UTC, oremega commented on content/articles/products/design-process/index.mdx
> +## [ユーザーリサーチの手引](/products/design-process/user-research)
どうなるかちょっと想像ついてない部分があるので、一旦変更しちゃうほうがいいかなっと。

2022-06-06 02:54 UTC, oremega commented
一旦ユーザビリティテストだけに特化していくので、あとで構成を変える方針にします。

2022-06-06 06:48 UTC, aguringo approved these changes
:lgtm:

2022-06-07 00:49 UTC, wentzzz reviewed
リンクが切れてるところがあったのでサジェスト入れました。

2022-06-07 00:49 UTC, wentzzz commented on content/articles/products/design-process/usability-test/index.mdx
> +- [ユーザビリティテストの被験者になったら](/products/design-process/user-resaerch/usability-test/)
```suggestion
- [ユーザビリティテストの被験者になったら](/products/design-process/usability-test/usability-test/)
```
このリンクが古いままでした。

2022-06-07 01:16 UTC, uknmr requested changes
いいね!

「ユーザビリティテストの被験者になったら」の中に「台本」があると、ユーザビリティテストをする側はよりイメージできそうだと思いました!

2022-06-07 01:16 UTC, uknmr commented on content/articles/products/design-process/usability-test/index.mdx
> +被験者の認知プロセスを観察、確認しながら、操作の失敗や不満の原因を理論的に分析して、開発チームにフィードバックします。
imo： 前文で「ユーザビリティテストは」と言ってるので言い回し変えるといいかも?

```suggestion
具体的には、被験者にタスク（作業課題）を提示して、その操作風景と認知プロセスを観察・確認します。そこで得た操作の失敗や不満の原因を理論的に分析して、開発チームに伝え改善に繋げます。
```

2022-06-07 01:16 UTC, uknmr commented on content/articles/products/design-process/usability-test/index.mdx
> +スクラム開発の文脈で行われるスプリントレビューは、スプリントの成果に対してステークホルダーから幅広い意見を求める機会です。
imo： 「スクラム開発の文脈で行われる〜」という前置きがあるなら、言葉は平易にしたい

```suggestion
スクラム開発の文脈で行われるスプリントレビューは、スプリントの成果に対して関係者から幅広い意見を求める機会です。  
```

2022-06-07 01:16 UTC, uknmr commented on content/articles/products/design-process/usability-test/index.mdx
> +スクラム開発の文脈で行われるスプリントレビューは、スプリントの成果に対してステークホルダーから幅広い意見を求める機会です。
これは正直よくわからないかも? スクラムやスプリントレビューで「これをやらないといけない」というのはない気がしてる。
誰が定義したんだ問題😇

`一般的に` とかつけるといいのかな。

2022-06-07 01:16 UTC, uknmr commented on content/articles/products/design-process/usability-test/index.mdx
> +スクラム開発の文脈で行われるスプリントレビューは、スプリントの成果に対してステークホルダーから幅広い意見を求める機会です。
実際弊社だと簡易的なユーザビリティテストをスプリントレビューでやることは多そうなので、線引きする必要もあまりない気がしました!

2022-06-07 01:16 UTC, uknmr commented on content/articles/products/design-process/usability-test/index.mdx
> +ユーザビリティテストは、ユーザーに実際に使用してもらい、観察やヒアリングを通して、フィードバックを得るもので、実施目的は異なります。
imo

```suggestion
前述の通り、ユーザビリティテストは、ユーザーに実際に使ってもらった結果やヒアリングを通して洞察を得るために行うため、実施目的が異なります。
```

2022-06-07 01:16 UTC, uknmr commented on content/articles/products/design-process/usability-test/index.mdx
> +### ユーザーリサーチ推進室 `#user_research_推進室`
imo

```suggestion
### ユーザーリサーチ推進室

Slack ID： `#user_research_推進室`
```

2022-06-07 01:16 UTC, uknmr commented on content/articles/products/design-process/usability-test/usability-test.mdx
> +タスク（作業課題）を実施する様子を観察し、ヒアリングを通して確認しながら、操作の失敗や不満の原因を見つけ出して、開発チームにフィードバックします。
項目ごとに必ず書く? 不要な気がしました!

2022-06-07 01:16 UTC, uknmr commented on content/articles/products/design-process/usability-test/usability-test.mdx
> +タスク（作業課題）を実施する様子を観察し、ヒアリングを通して確認しながら、操作の失敗や不満の原因を見つけ出して、開発チームにフィードバックします。
改めて伝えるのであれば、このページに即した内容にした方がよさそう。

2022-06-07 01:16 UTC, uknmr commented on content/articles/products/design-process/usability-test/usability-test.mdx
> +有意義なテストを実施するために、事前に理解していただきたい5つのポイントです。
「実施するために」と「事前に」がかぶってる

```suggestion
有意義なテストを実施するために抑えておきたい5つのポイントです。
```

2022-06-07 01:16 UTC, uknmr commented on content/articles/products/design-process/usability-test/usability-test.mdx
> +title: 'ユーザビリティテストの被験者になったら'
imo
```suggestion
title: '被験者に知っておいてほしい5つのこと'
```

2022-06-07 02:15 UTC, versionfive commented on content/articles/products/design-process/usability-test/index.mdx
> +### ユーザーリサーチ推進室 `#user_research_推進室`
こちらと表記あわせるとよさそうです。
https://smarthr.design/products/#h2-1

<img width="462" alt="image" src="https://user-images.githubusercontent.com/64398878/172281281-1419a749-72b5-4bb9-8c1a-601235541e94.png">

2022-06-07 02:18 UTC, versionfive commented on content/articles/products/design-process/usability-test/usability-test.mdx
> +- [ユーザーリサーチってご存知ですか？｜SmartHR オープン社内報](https://shanaiho.smarthr.co.jp/n/n426fd941cfcf)
この参考情報は「ユーザビリティテストの手引」の方にあってよいのではと思いました！

2022-06-07 02:18 UTC, versionfive commented on content/articles/products/design-process/usability-test/index.mdx
> +- [ユーザビリティテストの被験者になったら](/products/design-process/user-resaerch/usability-test/)
URLが`usability-test`の連続で気になりました

2022-06-07 02:38 UTC, oremega commented on content/articles/products/design-process/usability-test/index.mdx
> +- [ユーザビリティテストの被験者になったら](/products/design-process/user-resaerch/usability-test/)
リンクは直した気になっていた。
確かに、ユーザビリティテストの何？を入れたほうがいい。
こんな感じで変えれるといいかな？

```
~usability-test/usability-test-subjects/
~usability-test/tester/
```

2022-06-07 02:40 UTC, oremega commented on content/articles/products/design-process/usability-test/index.mdx
> +ユーザビリティテストは、ある機能を特定の状況で使うときに不具合がないかを検証するために実施します。
台本ってテスト資料のことだよね。
テスト設計とか実施とかも随時アップしていくからできたらそっちにリンクつける感じかな？

2022-06-07 07:59 UTC, aguringo commented on content/articles/products/design-process/usability-test/index.mdx
> +スクラム開発の文脈で行われるスプリントレビューは、スプリントの成果に対してステークホルダーから幅広い意見を求める機会です。
```suggestion
スクラム開発で行われるスプリントレビューは、スプリントの成果に対してステークホルダーから幅広い意見を求める機会です。  
```

2022-06-07 07:59 UTC, aguringo commented on content/articles/products/design-process/usability-test/usability-test.mdx
> +タスク（作業課題）を実施する様子を観察し、ヒアリングを通して確認しながら、操作の失敗や不満の原因を見つけ出して、開発チームにフィードバックします。
一応、被験者の人がここしか読まない（私は、senseiに事前にURLを送って読んでおいていただくことを想定）場合に必要かなと思って記載しました。

- タスクに関する説明が他になかったので、そのインプット
- 作業課題をやる様子を観察させてもらいますよ
- ヒアリングもしますよ
- （実施はユーザーリサーチ推進室のことがありますが）その内容は開発チームにフィードバックしますよ

ってことを暗に伝えようと思っていました。

だったら、「それを書いてよ」って言われそうな予感がしています… 😇

2022-06-07 10:15 UTC, oremega commented on content/articles/products/design-process/usability-test/usability-test.mdx
> +- [ユーザーリサーチってご存知ですか？｜SmartHR オープン社内報](https://shanaiho.smarthr.co.jp/n/n426fd941cfcf)
被験者向けということでここで入れてましたね。
読まないかなー？

2022-06-07 10:16 UTC, oremega commented on content/articles/products/design-process/usability-test/index.mdx
> +### ユーザーリサーチ推進室 `#user_research_推進室`
表記合わせまするー。

2022-06-07 10:26 UTC, oremega commented on content/articles/products/design-process/usability-test/index.mdx
> +- [ユーザビリティテストの被験者になったら](/products/design-process/user-resaerch/usability-test/)
~usability-test/tester/で調整した

2022-06-07 10:27 UTC, oremega commented on content/articles/products/design-process/user-resaerch/index.mdx
> +title: 'ユーザーリサーチの手引'
ユーザビリティテストの手引で更新

2022-06-07 10:36 UTC, oremega commented on content/articles/products/design-process/usability-test/usability-test.mdx
> +- [ユーザーリサーチってご存知ですか？｜SmartHR オープン社内報](https://shanaiho.smarthr.co.jp/n/n426fd941cfcf)
必要なときに案内すればいいので「ユーザビリティテストの手引」に持っていく

2022-06-07 20:03 UTC, uknmr commented on content/articles/products/design-process/usability-test/usability-test.mdx
> +タスク（作業課題）を実施する様子を観察し、ヒアリングを通して確認しながら、操作の失敗や不満の原因を見つけ出して、開発チームにフィードバックします。
> それを書いてよ

これは被験者向けに書き直しが必要なのかなと思ってました! @aguringo

2022-06-07 20:06 UTC, uknmr commented on content/articles/products/design-process/usability-test/index.mdx
> +スクラム開発の文脈で行われるスプリントレビューは、スプリントの成果に対してステークホルダーから幅広い意見を求める機会です。
> SmartHRで行われていると言わないと正しくないですね。しかもhanica

※ でもいいので書いておきたい!

2022-06-07 20:10 UTC, uknmr commented on content/articles/products/design-process/usability-test/tester.mdx
> +---
imo： ファイル名、`for-tester` かなぁ

2022-06-08 02:03 UTC, oremega commented on content/articles/products/design-process/usability-test/tester.mdx
> +---
ああああ、そうですね。

2022-06-08 02:06 UTC, oremega commented on content/articles/products/design-process/usability-test/index.mdx
> +スクラム開発の文脈で行われるスプリントレビューは、スプリントの成果に対してステークホルダーから幅広い意見を求める機会です。
この文脈は足す

2022-06-09 01:05 UTC, oremega commented on content/articles/products/design-process/usability-test/usability-test.mdx
> +タスク（作業課題）を実施する様子を観察し、ヒアリングを通して確認しながら、操作の失敗や不満の原因を見つけ出して、開発チームにフィードバックします。
@aguringo ここだけ意図の確認お願いします:pray:

2022-06-09 01:07 UTC, oremega commented on content/articles/products/design-process/usability-test/tester.mdx
> +---
対応済

2022-06-09 01:07 UTC, oremega commented on content/articles/products/design-process/usability-test/index.mdx
> +スクラム開発の文脈で行われるスプリントレビューは、スプリントの成果に対してステークホルダーから幅広い意見を求める機会です。
対応済

2022-06-09 08:20 UTC, aguringo commented on content/articles/products/design-process/usability-test/usability-test.mdx
> +タスク（作業課題）を実施する様子を観察し、ヒアリングを通して確認しながら、操作の失敗や不満の原因を見つけ出して、開発チームにフィードバックします。
@uknmr @oremega 

もう少しちゃんとリライトしますね…　ちょい待って

2022-06-09 08:59 UTC, aguringo commented on content/articles/products/design-process/usability-test/for-tester.mdx
> +タスク（作業課題）を実施する様子を観察し、ヒアリングを通して確認しながら、操作の失敗や不満の原因を見つけ出して、開発チームにフィードバックします。
```suggestion
特定の操作ごとの使い勝手（ユーザビリティ）を確認するテストです。

被験者の方にはシナリオに沿ってタスク（作業課題）に取り組んでもらい、その様子を観察させていただきます。  
ヒアリングを通してテスト中の行動について確認しながら、操作の失敗や不満の原因を見つけ出し、開発チームにフィードバックします。
```

2022-06-09 22:00 UTC, uknmr commented on content/articles/products/design-process/usability-test/index.mdx
> +- [被験者に知っておいてほしい5つのこと](/products/design-process/usability-test/tester/)
リンク切れてる〜

```suggestion
- [被験者に知っておいてほしい5つのこと](/products/design-process/usability-test/for-tester/)
```

2022-06-10 03:03 UTC, aguringo commented on content/articles/products/design-process/usability-test/for-tester.mdx
> +タスク（作業課題）を実施する様子を観察し、ヒアリングを通して確認しながら、操作の失敗や不満の原因を見つけ出して、開発チームにフィードバックします。
> 特定の操作ごとに かな

edited

2022-06-10 03:41 UTC, oremega commented on content/articles/products/design-process/usability-test/index.mdx
> +- [被験者に知っておいてほしい5つのこと](/products/design-process/usability-test/tester/)
変え忘れた:arigatau:

2022-06-10 03:43 UTC, oremega commented on content/articles/products/design-process/usability-test/for-tester.mdx
> +タスク（作業課題）を実施する様子を観察し、ヒアリングを通して確認しながら、操作の失敗や不満の原因を見つけ出して、開発チームにフィードバックします。
ありがとございます。良さそうです。

2022-06-10 05:05 UTC, uknmr approved these changes
LGTM!

再レビュー時、これ押してもらえると助かります!
![image](https://user-images.githubusercontent.com/19403400/172994099-79c6a586-5261-4497-807f-6b8234b2d468.png)

2022-06-10 09:44 UTC, oremega commented
@uknmr さんありがとうございます。
再レビューも理解しました:pray:

2022-06-13 02:38 UTC, versionfive commented on content/articles/products/design-process/usability-test/for-tester.mdx
> +## ユーザビリティテストとは
```suggestion
title: 'ユーザビリティテストの被験者になったら'
description: 'ユーザビリティテストの被験者に事前連絡するドキュメントです。被験者として参加する際に、事前に知っておいていただきたい5つのことをまとめました。'
order: 4
---
<!-- textlint-disable -->
ユーザビリティテストに被験者として参加する際に、**事前に知っておいていただきたい5つのこと**をまとめました。

## ユーザビリティテストとは
```
このページは直接URLを共有され読みに来る（前提知識がない）被験者の方がいることを想定すると、「知っておいてほしい5つのこと」だと少しかたい印象を持ちました。

タイトルはふわっとさせ、👇descriptionが表示されなくなったので、サマリにいいたいことを表記してみました。

2022-06-13 02:38 UTC, versionfive commented on content/articles/products/design-process/usability-test/index.mdx
> +前述の通り、ユーザビリティテストは、ユーザーに実際に使ってもらった結果やヒアリングを通して洞察を得るために行うため、実施目的が異なります。
```suggestion
### スプリントレビューとの違い

ユーザビリティテストと、スクラム開発で行われる「スプリントレビュー」とでは、実施目的が異なります。

スプリントレビューは、スプリントの成果に対して関係者から幅広い意見を求める機会です（SmartHRの開発チームが行っている手法の一例です）。
一方、ユーザビリティテストは、ユーザーに実際に使ってもらった結果やヒアリングを通して洞察を得るために実施します。
```

2022-06-13 02:38 UTC, versionfive commented on content/articles/products/design-process/usability-test/index.mdx
> +- [被験者に知っておいてほしい5つのこと](/products/design-process/usability-test/for-tester/)
```suggestion
- [被験者への事前連絡](/products/design-process/usability-test/for-tester/)
```
ここは「ガイド」としての目次だと思うので、タイトルからあえて外してみました。

2022-06-13 02:41 UTC, aguringo reviewed
少し読みやすくさせてもらいました :pray:

2022-06-13 02:41 UTC, aguringo commented on content/articles/products/design-process/usability-test/index.mdx
> +前述の通り、ユーザビリティテストは、ユーザーに実際に使ってもらった結果やヒアリングを通して洞察を得るために行うため、実施目的が異なります。
```suggestion
前述の通り、ユーザビリティテストはユーザーに実際に使ってもらった結果やヒアリングを通して洞察を得るもので、実施目的が異なります。
```

2022-06-13 02:41 UTC, aguringo commented on content/articles/products/design-process/usability-test/index.mdx
> +お客様を理解するための調査を専門とするチームです。
```suggestion
顧客理解のための調査を専門とするチームです。  
```

2022-06-13 03:03 UTC, oremega commented on content/articles/products/design-process/usability-test/for-tester.mdx
> +## ユーザビリティテストとは
思想が分かれそうだけど、ぼくもこっちで良い気がしている。

2022-06-13 03:04 UTC, oremega commented on content/articles/products/design-process/usability-test/index.mdx
> +- [被験者に知っておいてほしい5つのこと](/products/design-process/usability-test/for-tester/)
「ガイド」としての役割から考えて理解できたの良さそう！

2022-06-13 03:05 UTC, oremega commented on content/articles/products/design-process/usability-test/index.mdx
> +お客様を理解するための調査を専門とするチームです。
:AZMS:シュッとした

2022-06-13 03:13 UTC, oremega commented on content/articles/products/design-process/usability-test/index.mdx
> +前述の通り、ユーザビリティテストは、ユーザーに実際に使ってもらった結果やヒアリングを通して洞察を得るために行うため、実施目的が異なります。
ありがたう。このまま直します。

2022-06-13 07:53 UTC, aguringo submitted a review, later dismissed
:lgtm:

2022-06-14 02:04 UTC, versionfive reviewed
nitsですが、主語が他の違ってそうなところにコメントしましたmm

2022-06-14 02:04 UTC, versionfive commented on content/articles/products/design-process/index.mdx
> +[WIP] ユーザーリサーチを実施するうえで利用する資料をまとめています。
```suggestion
ユーザビリティテストを実施するうえで利用する資料をまとめています。
```

2022-06-14 02:04 UTC, versionfive commented on content/articles/products/design-process/usability-test/index.mdx
> +具体的には、被験者にタスク（作業課題）を提示して、その操作風景と認知プロセスを観察・確認します。そこで得た操作の失敗や不満の原因を理論的に分析して、開発チームに伝え改善に繋げます。
こちらも主語が推進室かもしれません

2022-06-14 02:04 UTC, versionfive commented on content/articles/products/design-process/usability-test/index.mdx
> +ユーザビリティテストは、ある機能を特定の状況で使うときに不具合がないか確かめるために行います。
```suggestion
ユーザビリティテストとは、ある機能を特定の状況で使うときに不具合がないか確かめるために行なう手法の一つです。
```
不具合、でいいのかな？

2022-06-14 02:38 UTC, oremega commented on content/articles/products/design-process/usability-test/for-tester.mdx
> +ヒアリングを通してテスト中の行動について確認しながら、操作の失敗や不満の原因を見つけ出し、開発チームにフィードバックします。
「開発チームにフィードバックします。」ここがあるからですね。
社内向けの文言のままなので、「インターフェイスの改善点を明らかにする」的な事に変更する

2022-06-14 02:39 UTC, oremega commented on content/articles/products/design-process/usability-test/index.mdx
> +具体的には、被験者にタスク（作業課題）を提示して、その操作風景と認知プロセスを観察・確認します。そこで得た操作の失敗や不満の原因を理論的に分析して、開発チームに伝え改善に繋げます。
こっちも一緒ですね。うち向けの文章のままなので上と同じように「インターフェイスの改善点を明らかにする」とむすびます。

2022-06-14 06:27 UTC, versionfive commented on content/articles/products/design-process/usability-test/index.mdx
> +order: 3
```suggestion
order: 4
```
「デザインレビューの手引」とorderかぶっていたので、他を変えるかしたほうがよさそう。

2022-06-14 06:27 UTC, versionfive commented on content/articles/products/design-process/usability-test/index.mdx
> +「特定の利用状況」において、「特定のユーザー」によって、ある製品が、「指定された目標」を達成するために用いられる際の、有効さ、効率、ユーザの満足度の度合い。
```suggestion
>「特定の利用状況」において、「特定のユーザー」によって、ある製品が、「指定された目標」を達成するために用いられる際の、有効さ、効率、ユーザの満足度の度合い。
```
引用にしました。

2022-06-14 06:36 UTC, oremega commented on content/articles/products/design-process/usability-test/index.mdx
> +「特定の利用状況」において、「特定のユーザー」によって、ある製品が、「指定された目標」を達成するために用いられる際の、有効さ、効率、ユーザの満足度の度合い。
ありがとです！
この引用ありだったのか、スタイルがマージンだけだったのでスタイル設定してないのかと思った！

2022-06-14 07:48 UTC, versionfive approved these changes
LGTM!! :arigatau:

2022-06-14 09:19 UTC, merged